### ISSUE TITLE
Add support for label-based filenames

### ISSUE THREAD

**Issue by ivanmayes** [garris/BackstopJS#101]
Would be great to have the filenames use the label property so thats its easy to clearly see what scenario the file is for.

**Comment by garris** [comment]
Would pull that.  Should be placed after the ordering indexes but before the selector string.  Maybe need to guard filename length.

**Comment by garris** [comment]
Done.

**Comment by ivanmayes** [comment]
Thanks!

**Comment by axe312ger** [comment]
@garris i would propose to use https://github.com/dodo/node-slug to ensure valid file names. We got some very good experiences with slug in a bigger project.

**Comment by garris** [comment]
yup. would pull that too.   "unicode ♥ is ☢"

**Comment by Primajin** [comment]
Hey guys, so I understand you put this functionality in? I can't find it documented nor generated by genConfig. How can I use the label for the filename?

**Comment by garris** [comment]
The Label was added to the CLI reports to make it clear what scenario a given selector is for.

example...
<img width="630" alt="screen shot 2016-01-14 at 8 06 59 am" src="https://cloud.githubusercontent.com/assets/447033/12329853/210d2f28-ba97-11e5-9f32-7e7c9ecdea1c.png">

**Comment by Primajin** [comment]
I see, I thought this issue was about using the label for the filenames generated for reference/test. But anyhow if there is no such function yet, I'm gonna do a PR soon :wink:

**Comment by garris** [comment]
@Primajin That would be a great addition -- happy to help in any way.   thanks!

**Comment by garris** [comment]
I think right after `scenarioIndex`here...
https://github.com/garris/BackstopJS/blob/master/capture/genBitmaps.js#L183

**Comment by Primajin** [comment]
#137 Might fix #101 :wink:
