### ISSUE TITLE
[DEBUGGING] How to console log the dom in keyPressSelectors? 

### ISSUE THREAD

**Issue by adamchenwei** [garris/BackstopJS#1022]
I am having issue seeing why selector seems not getting triggered with key press value. however, I dont even know if it gets selected at all. any good way for debugging in backstopjs beside guessing work?

**Comment by garris** [comment]
Check docs.  There is debugWindow option.

**Comment by adamchenwei** [comment]
@garris that does not indicate if selector works. any specific detail? I am not sure closing without properly confirming if the question is answered.

**Comment by garris** [comment]
FWIW I closed all your tickets after your snarky post.  This software is 100% free.  If it's useful go ahead and use it.  If you have good suggestions or useful criticism, great.  But don't come around here spreading your negativity and sarcasm.
