### ISSUE TITLE
is this project dead / dying?

### ISSUE THREAD

**Issue by adamchenwei** [garris/BackstopJS#1023]

**Comment by garris** [comment]
Everything in this world is temporary.  You're comment is not useful.

**Comment by adamchenwei** [comment]
I am glad this simple question can get answer so quickly, while my other very much valid question pretty much lingered for many days lol
Its certainly not dead (seems), but I understand it must be hard to support this lib by one person. maybe a good time to get some supporter or helper to maintain?

**Comment by garris** [comment]
Be the change you wish to see.   

Learn the package. Provide support for yourself and others.
