### ISSUE TITLE
Multiple onReadyScripts

### ISSUE THREAD

**Issue by kmjch** [garris/BackstopJS#1025]
Hi, is there a way to call multiple action js files with onReadyScript?

For example:
`{
            "label": "testcase1",
            "selectors": [
                "#element"
            ],
            "clickSelectors": [
                "#element"
            ],
            "hoverSelectors": [
                "#element"
            ],
            "onBeforeScript": [
                "click.js",
                "hover.js"
            ]
        }`

**Comment by garris** [comment]
@kmjch thanks for posting!   in short, no.  However, at work we have a library of behaviors which we import into our single onBeforeScript.  We use that to compose various more-complex behaviors.   So, that's kind of the same thing, just implemented in a different spot.   Hope that helps!

**Comment by kmjch** [comment]
@garris Thanks for ur response! That helps, I'll look into how my team can implement something similar for our project.
