### ISSUE TITLE
How to run failed test-cases automatically again, When Navigation Timeout Error

### ISSUE THREAD

**Issue by SanthoshRaghav** [garris/BackstopJS#1028]
Hi Garris, All

I am new to Backstop Js,  it is really cool!
i wrote 93 test-cases to test project UI. When i am running 93 test cases at a time, 5 to 10 test-cases are failed  randomly, may be because of **internet connection** drop or **system processing time**. but when i run few cases(not whole) manually, its working very smoothly.

So, i would like to split my test-cases in to, like this 30, 30, 33 =93. 
i mean,
1. I would like to run, first 30 test-cases,
2. again 2nd 30 test-cases,
3. again 3rd 33 test-cases.

I want run test-cases automatically, but how can i split whole test-cases in to multiple and run automatically(each and every time should run like a new instance) ? or How to run failed test-cases automatically again.

Could you please provide any solution to me.
Thanks.

`config.js`

```
const scenarios = require('./scenarios');
module.exports = {
   id: 'backstop_default',
   viewports: [
      {
         label: 'desktop-large',
         width: 1440,
         height: 1000,
      },
      {
         label: 'tablet',
         width: 1024,
         height: 768,
      },
      {
         label: 'mobile iphone-x',
         width: 375,
         height: 650,
      },
   ],
   onBeforeScript: 'puppet/onBefore.js',
   onReadyScript: 'puppet/onReady.js',
   scenarios,
   paths: {
      bitmaps_reference: 'server/backstop/data/bitmaps_reference',
      bitmaps_test: 'server/backstop/data/bitmaps_test',
      engine_scripts: 'server/backstop/data/engine_scripts',
      html_report: 'server/backstop/data/html_report',
      ci_report: 'server/backstop/data/ci_report',
   },
   report: ['browser'],
   engine: 'puppeteer',
   engineOptions: {
      args: ['--no-sandbox'],
   },
   asyncCaptureLimit: 5,
   asyncCompareLimit: 50,
   debug: false,
   debugWindow: false,
};

```

**Comment by garris** [comment]
Why not just create 3 scenarios files and switch them with CLI args?    Or create 3 config files?  Something like that?
