### ISSUE TITLE
Integrated backstopJS with VSTS but build report doesnt show reference and test images

### ISSUE THREAD

**Issue by Bhav1907** [garris/BackstopJS#1031]
@garris  I have added backstop test to my CI build. I could successfully see the tests results.
![image](https://user-images.githubusercontent.com/47148494/56137608-d4005e00-5f5a-11e9-9bea-1316b67ae26f.png)

But when i download "html_report" folder from CI agent . I cant see images. PFB image

![image](https://user-images.githubusercontent.com/47148494/56137576-c64ad880-5f5a-11e9-85c1-7bf0d6fdeabc.png)

Can you help me with what went wrong here ?

**Comment by Bhav1907** [comment]
Closing this as i have solved the issue.

**Comment by x1c0** [comment]
@Bhav1907 I have the same issue, the images are not there since they are not inside the `html_report` folder..

I was also curious to find what you did to solve this :)

**Comment by x1c0** [comment]
If someone is having the same issue, this happed because probably on CI server, downloading the `html_report` folder only is not enough, you need to download the `backstop_data` folder and then open the report inside `html_report`

**Comment by garris** [comment]
Thank you for posting the solution!
