### ISSUE TITLE
backstop v 4.0.3 problem to launch test Error: Chromium revision is not downloaded. 

### ISSUE THREAD

**Issue by patriciamarchand** [garris/BackstopJS#1033]
I try to launch test with the new unstable version 4.0.3

I lunch this command
`backstop test --configPath=backstop_data/backstopTests/composantes/bouton/backstop_bouton.js`

I got an error
`COMMAND | Executing core for "test"
createBitmaps | Selected 1 of 1 scenarios.
      COMMAND | Command "test" ended with an error after [0.018s]
      COMMAND | Error: Chromium revision is not downloaded.
Run "npm install" or "yarn install" at Launcher.launch (C:\Users\...AppData\Roaming\npm\node_modules\backstopjs\node_modules\puppeteer\lib\Launcher.js:119:15) at <anonymous>`

Do I have to add a path to chrome? Or install else?
Thanks

My config file :

var bouton_d = require("./bouton_d20").scenario1;
var allScenarios = [].concat(
  bouton_d
);
module.exports = {
  id: "abcd",
  viewports: [
    {
      name: "phone",
      width: 320,
      height: 10000
    }
  ],
  scenarios: allScenarios,
  onBeforeScript: "puppet/onBefore.js",
  onReadyScript: "puppet/onReady.js",
  paths: {
    bitmaps_reference: "backstop_data/bitmaps_reference/bouton",
    bitmaps_test: "backstop_data/bitmaps_test/bouton",
    compare_data: "backstop_data/bitmaps_test/compare.json",
    engine_scripts: "backstop_data/engine_scripts",
    html_report: "backstop_data/html_report/bouton",
    ci_report: "backstop_data/ci_report/bouton"
  },
  ci: {
    format: "junit",
    testSuiteName: "testBouton"
  },
  engine: "puppeteer",
  engineOptions: {
    waitTimeout: 120000,
    args: ["--no-sandbox", "--disable-setuid-sandbox"]
  },
  asyncCaptureLimit: 1,
  asyncCompareLimit: 10,
  report: ["CI", "browser"],
  debug: false,
  debugWindow: true,
  fileNameTemplate: "abc_{scenarioLabel}_{selectorLabel}_{viewportIndex}_{viewportLabel}"
};

**Comment by garris** [comment]
How did you install 4.0.3?  Did you...
`npn install backstopjs@canary`?

**Comment by patriciamarchand** [comment]
I try both 
`npm install -g  backstopjs@canary` and `npm install -g backstopjs@4.0.3`
same error when I launch test.

**Comment by patriciamarchand** [comment]
Problem with admin right on my laptop. It works on my coworkers laptop. Thanks.

**Comment by garris** [comment]
Thanks for following up!
