### ISSUE TITLE
backstop test not removing selectors on CI VSTS build 

### ISSUE THREAD

**Issue by Bhav1907** [garris/BackstopJS#1036]
I am running backstop in nightly build on Azure devops (VSTS) . It works smoothly on local but on azure devops test screenshots are not excluding 'removeSelectors' elements . 

**'removeSelectors': ['div.ui-sidebar-left', 'div[id=JBH360Platform] header', '.flexbox-container', '.content-section.documentation','footer[class="ui-g"]']**

Is it sync issue ? or any other setting required ?

**Comment by garris** [comment]
Maybe it is a rendering delay?

**Comment by Bhav1907** [comment]
Seems to be delay..Closing this.

**Comment by InoshikaFernando** [comment]
Hi Bhav1907,

I'm new to BackstopJS and new to Azure as well. Can you please explain how to use BackstopJS in azure release pipeline?

**Comment by garris** [comment]
@Bhav1907 ☝️
If you have documentation that you are able to share I would love to know what your implementation is like on Azure!

- how would you describe your web app?
- What does your stack and specific pipeline look like -- how is it triggered?  
- What other test frameworks do you run?  
- How do you roll up reporting?  
- How do you handle failures?
- what is your false-positive rate like?


If you have the time I would love to learn about how you approach these.

Cheers!
Garris
