### ISSUE TITLE
Is it possible to have mutliple clicks and interaction?

### ISSUE THREAD

**Issue by RachelSeale** [garris/BackstopJS#1042]
Is it possible to simulate multiple clicks in the same scenario with user input as well?

It would be something like:

1. Open page A (mysite.com)
2. Click to open page B - same url
3. Fill out a form - same page as B
4. Click to be taken page C - same url

Its a SPA form written in React so no direct URLs.

Example scenarios:
  {
    "label": "Page1",
    "url": "http://localhost:3000/",
    "referenceUrl": "",
    "readyEvent": "",
    "readySelector": "",
    "delay": 0,
    "hideSelectors": [],
    "removeSelectors": [],
    "hoverSelector": "",
    "clickSelector": "#next-button",
    "postInteractionWait": 1000,
    "selectors": [],
    "selectorExpansion": true,
    "expect": 0,
    "misMatchThreshold" : 0.1,
    "requireSameDimensions": true
  },
   {
    "label": "Page2",
    "url": "http://localhost:3000/",
    "referenceUrl": "",
    "readyEvent": "",
    "readySelector": "",
    "delay": 0,
    "hideSelectors": [],
    "removeSelectors": [],
    "hoverSelector": "",
    "clickSelectors": [
         "#next-button"
         ".radio-button",
         "#next-button"
    ],
    "postInteractionWait": 1000,
    "selectors": [],
    "selectorExpansion": true,
    "expect": 0,
    "misMatchThreshold" : 0.1,
    "requireSameDimensions": true
  }

If running this scenario - Page2 captures the same screenshot as scenario - Page1

Also how do I deal with user interaction to input if I have to click before and after?

**Comment by garris** [comment]
Hi @rachelseale.  It may help to think of backstopjs more from a unit-test mindset.   The scenario objects are there to make setting up state easier -- but depending on how your app is designed they may or may not be appropriate for what you need to test.  

So, however your app handles state, be it a url parameter, a cookie, some internal store or a _simple_ UI interaction the `scenario` node represents one state and one screenshot.   In your case, if you have four states and want 4 screenshots you'll need 4 scenarios.  Keep in mind that scenarios run in parallel-- so you'll need to stub your states for each one and not depend on other scenarios to persist those prior states.   

You will need to look into programmatically setting those conditions using the various scenario props (in your case you may need to use an onReadyScript). 

I hope this helps some.

**Comment by jric** [comment]
This seems like such a strange limitation to me.  Puppet has the ability to navigate the site and dump the screenshots.  Backstop has the ability to run the above and then compare the screenshots in a docker container.  The only thing that seems to be missing is a way to compute the same filepath that backstop uses, and then this should totally work?
