### ISSUE TITLE
How to run a script *once only* before any scenarios.

### ISSUE THREAD

**Issue by justlevine** [garris/BackstopJS#1046]
Hi,

How can you run a script _once_ before any of the scenarios start. The default `onBefore` behavior is to repeat onBefore before **each** scenario.

(Im trying to have a script log in to a WP site, and grab the cookies to write them to cookies.json used for all the scenarios. Wordpress is too overzealous with invalidating its login cookies for me to keep updating them manually, and having backstop go through the physical steps of logging in every single time before running each scenario seems like a waste of time and resources).

**Comment by garris** [comment]
Hi there.  There are lots of way to handle this.  Why not add a step to your onbefore -- try to fetch a page (or even just an image) with your last saved cookies, if the response returns with 200 then your cookies are still good so don't bother attempting to sign in.    This means you validate auth prior to all scenarios,  very little overhead, lots of confidence, so probably a good way to go.   You could alternatively create a config that does just this.  Create a runner script that runs config one, then runs config two.   Then you are only checking once per run.  But I like the first idea better.   ☮️

**Comment by justlevine** [comment]
Thanks for the response @Garris! Interesting ideas - I had just assumed this was built into backstopjs and I was missing it.

Sadly the first option isn't really practical in my case (with WP it's not that the cookies don't exist or there's an error response that can be picked up by puppeteer et al. Rather if the cookies are invalid, the site just shows the logged-out version of the page).
But the second approach should work: instead of running backstop directly from the console, using a task runner to run up puppeteer first, and after saving the cookies to the file have it call backstop. 

Guess I'll need to learn how to actually initialize puppeteer instead of relying on backstop to do the heavy lifting :)

Thanks!

**Comment by garris** [comment]
FWIW: if it helps you can still do that second approach using backstop as a harness e.g. this would atill work...
```
backstop reference --config=justAShimUsedForSettingTheCookiesOnce && backstop test --config=myRealTests
```

Good luck!

**Comment by awhisler** [comment]
@garris So are you saying backstop doesn't currently use the `onReady` script as the beginning state for each scenario?
Basically, I want it to log in then do all the scenarios below. 

Is there a way to accomplish this without cookies?
