### ISSUE TITLE
Using attribute selectors on Windows breaks things

### ISSUE THREAD

**Issue by CreativPixel** [garris/BackstopJS#105]
When i try to use attribute selectors like :hover, :nth-child(2) etc. files can't be saved to my disk, so the tests won't work.
I guess it can't generate files with names like subnav_level1_li:first-child_a:hover.png.
Any way to work around this? Maybe by providing a custom filename possibility or label?

**Comment by garris** [comment]
What OS are you on?  `:nth-child(n)` has workd pretty reliably in the past.  Please let me know.  Thanks!

**Comment by garris** [comment]
Sorry, I should say, which *version* are you on.  I haven't gotten this bug from other Windows in the past -- but it's never to late!   Do you know which character breaks the file write?  We can escape that internally.  Again, please let me know.

**Comment by CreativPixel** [comment]
I am using Windows 10 pro, 64 bit version.
Other than this issue the rest is working flawlessly.
Op 19 okt. 2015 16:51 schreef "Garris" <notifications@github.com>:

**Comment by garris** [comment]
One question. Can you try deleting your `backstop.json` file and running the default test?   Please let me know if that is also broken on your windows machine.

**Comment by CreativPixel** [comment]
The default config is also broken. This is my output in the console:
-----------------------------------------------------------------------------
D:\php\insyde\einstein\bower_components\BackstopJS>gulp reference

Could not find a valid config file.

To run your own tests create a config here...
 ==> D:\php\insyde\einstein\backstop.json

Run `$ gulp genConfig` to generate a config template file in this location.

[08:30:58] Using gulpfile D:\php\insyde\einstein\bower_components\BackstopJS\gulpfile.js
[08:30:58] Starting 'clean'...
bitmaps_reference was cleaned.
[08:30:58] Starting 'bless'...
[08:30:58] Finished 'clean' after 25 ms
[08:30:58] Finished 'bless' after 28 ms
[08:30:58] Starting 'reference'...
gulp.run() has been deprecated. Use task dependencies or gulp.watch task triggering instead.
[08:30:58] Starting 'init'...
[08:30:58] Finished 'init' after 7.82 μs
[08:30:58] Starting 'test'...

Generating reference files.

[08:30:58] Finished 'test' after 12 ms
reference has run.
[08:30:58] Finished 'reference' after 18 ms
CasperJS: CREATING NEW REFERENCE FILES
CasperJS: Ready event received.
CasperJS: Current location is http://getbootstrap.com
CasperJS: Screenshots for phone (320x480)
CasperJS: Ready event received.
CasperJS: Current location is http://getbootstrap.com
CasperJS: Screenshots for tablet_v (568x1024)
CasperJS: Ready event received.
CasperJS: Current location is http://getbootstrap.com
CasperJS: Screenshots for tablet_h (1024x768)
CasperJS: Comparison config file updated.

Bitmap file generation completed.

Run `$ gulp test` to generate diff report.
-----------------------------------------------------------------------------
After this I check the files to see if it could write the "body .bs-docs-featurette:nth-of-type(1)" test related images. But it couldn't write them correctly. The filenames are:
- 0_2_body.bs-docs-featurette (whithout extention)
- 0_3_body.bs-docs-featurette (whithout extention)

Also the report that opens in the browser hangs and stops checking after the second test.

**Comment by garris** [comment]
Perfect, thanks.  I will see if I can get a patch for this tomorrow.

**Comment by CreativPixel** [comment]
Superb, thanks for the quick reply!

**Comment by garris** [comment]
Yup...  https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx

```
...reserved characters:
< (less than)
> (greater than)
: (colon)
" (double quote)
/ (forward slash)
\ (backslash)
| (vertical bar or pipe)
? (question mark)
* (asterisk)

```

**Comment by CreativPixel** [comment]
Woohoo, that fixed it for me. Many thanks!

**Comment by garris** [comment]
Awesome.

**Comment by CreativPixel** [comment]
Sorry to bug you one more time. Though :nth-child and :first-child selectors are working beautifully, using the :hover selector returns a gray image with an arrow in it. Is this expected behaviour?

**Comment by axe312ger** [comment]
:hover is a pseudo class and no selector. You can not select by :hover, :focus and :active

**Comment by CreativPixel** [comment]
Thanks for clearing that up.

**Comment by axe312ger** [comment]
No worries. But i see what feature you are looking for, I hope I get some time in november to support garris with backstopjs 💪

**Comment by axe312ger** [comment]
Lol, seems like i missed a version. @CreativPixel you may create a custom casperjs script for testing the hover state -> https://github.com/garris/BackstopJS#version-080-beta-available-now

**Comment by garris** [comment]
^^^ I am so psyched for that feature!
