### ISSUE TITLE
Hidden element launch error 

### ISSUE THREAD

**Issue by patriciamarchand** [garris/BackstopJS#1054]
Hello,
I have a hidden element not displayed at some viewport with a Bootstrap class (hidden-lg). With previous version, the test generate an image with the animal lemur. To deal with this I add the same image in my reference and this work fine for me. 

With the version 4.0.6 the same test does not generate the placeholder image. It does not generate any image. So I have nothing to compare. 

The error log in the console is 
Error : Expected options.clip.width not to be 0.

The image "element not found" display only when the selector is not found in the page. Is it possible to have the same behaviour when Backstop hit the error "Expected options.clip.width not to be 0"

![SNAG-0102](https://user-images.githubusercontent.com/6225238/58828015-6a273b00-8612-11e9-81a8-12aa1c95938c.png)

**Comment by garris** [comment]
Can you post your config?

**Comment by patriciamarchand** [comment]
I fix this issue buy targeting another selector. I close this issue. thanks!

**Comment by garris** [comment]
This must have been caused by the puppeteer version change.  Thanks.
