### ISSUE TITLE
backstop:init template?

### ISSUE THREAD

**Issue by mstruensee** [garris/BackstopJS#1062]
Is there currently anyway to customize the init process?  Our team uses init but then we always make a few tweaks based on lint, etc.  Is there a way we can include a template file/config for the init to use?

**Comment by garris** [comment]
Sorry.  I don't think there is a way to modify this.  Do you have special scripts or something like that?

**Comment by mstruensee** [comment]
right now its just a good ol copy/paste of the config file.  Was debating what the best route would be to achieve this ...

**Comment by garris** [comment]
Nothing wrong with a little cut and paste.  😄

As you can see -- the backstop init command will not be winning any awards anytime soon so -- I think you'll be ok.  https://github.com/garris/BackstopJS/blob/master/core/command/init.js

Cheers!

**Comment by mstruensee** [comment]
lol yes, looking at that now, debating to fork or just make a script to do it all (npm add, update package.json, and init [aka copy file]) ... not sure yet

thanks for the info!
