### ISSUE TITLE
Is having an onReady script and importing the clickAndHoverHelper a requirement for click and hover selectors to work?

### ISSUE THREAD

**Issue by annaemu** [garris/BackstopJS#1065]
I have a very simple configuration where backstop is installed locally into the project. I'm not using any onBefore or onReady scripts. I am using backstop 4.1.9.

**I wanted to add a click selector to my test, however it didn't seem to do anything**. Eventually I added an onReady script and explicitly imported the clickAndHoverHelper from the library into the script. Suddenly, the clicks started to happening and I could see them in the test results.

What gives? Do you need to have an onReady script and import the helper for the various click/hover selectors to work?

My original configuration:

```
module.exports = {
  id: 'backstop_default',
  viewports: [
    {
      label: 'desktop',
      width: 1920,
      height: 1080,
    },
  ],
  scenarios: [
    {
      {
        label: 'Buttons - Button',
        url: 'http://localhost:6060/#/Buttons/Button',
        clickSelector: '.btn',
      },
    }
  ],
  paths: {
    bitmaps_reference: 'testing/ui/bitmaps-reference',
    bitmaps_test: 'testing/ui/bitmaps-test',
    engine_scripts: 'testing/ui/engine-scripts',
    html_report: 'testing/ui/html-report',
    ci_report: 'testing/ui/ci-report',
  },
  report: ['browser'],
  engine: 'puppeteer',
  engineOptions: {
    args: ['--no-sandbox'],
  },
  puppeteerOffscreenCaptureFix: true,
  asyncCaptureLimit: 5,
  asyncCompareLimit: 50,
  debug: false,
  debugWindow: false,
};
```

To make it work the only difference was my scenario changed to:
```
  scenarios: [
    {
      {
        label: 'Buttons - Button',
        url: 'http://localhost:6060/#/Buttons/Button',
        clickSelector: '.btn',
        onReadyScript: 'onReady.js',
      },
    }
  ],
```

Where the onReady script was:
```
module.exports = async (page, scenario) => {
  await require('backstopjs/capture/engine_scripts/puppet/clickAndHoverHelper')(page, scenario);
};
```

With these updates, clicks and hovers started working. Is having an onReady script and importing the helper a requirement?

**Comment by garris** [comment]
Here is the boilerplate file generated with `backstop init`.   This is probably a good starting point for you.  You don't need to remove anything.  Just add what you need.

**Comment by annaemu** [comment]
Thank you, but that's what I did and how I ended up with my configuration file in the first place.

**Comment by annaemu** [comment]
Ah I see, thank you. I had actually run this command, but subsequently moved the various paths and didn't copy the generated engine_scripts over.

**Comment by megclaypool** [comment]
This issue is closed, but I'm commenting to clarify for future people who (like myself) found this via a search engine.

**It turns out that _yes_, you do need an onReady that imports the helper script. The new boilerplate adds that to the default configuration.** 

I'm upgrading an older project, and didn't catch that so spent an embarrassing amount of time trying to figure out why the fancy new puppeteer interactions worked in a new init and not in my old project 😆
