### ISSUE TITLE
'backstop'  is not recognised as an internal or external command, operable program or batch file

### ISSUE THREAD

**Issue by Ashwajit** [garris/BackstopJS#1070]
While running the backstop test command- started getting - 'backstop'  is not recognised as an internal or external command, operable program or batch file

**Comment by garris** [comment]
Sounds like you need to install like this... `npm install backstopjs --global`

**Comment by Ashwajit** [comment]
Thanks for your reply.

I have re-installed nodejs and its started working. 

Regards,
Ashwajit Thukral

**Comment by ayeshahartley** [comment]
My colleagues and I are experiencing the same issue. Error "backstop: command not found". I have installed it globally as well and no change. Using Nodejs v12.19.0

**Comment by herrlitz** [comment]
@ayeshahartley Had the same problem, not sure exactly why it started working unfortunatly but might have been changing permission and re-install: https://github.com/garris/BackstopJS/issues/545

My directory was /usr/local/lib/node_modules/ instead of /usr/lib/node_modules/, Nodejs v15.3.0, using (oh my) zsh instead of bash.

**Comment by KonstanciaM** [comment]
im seeing the same issue: npm install backstopjs --global
ive tried installing globally and no help, can someone pls help resolving this issue?

**Comment by garris** [comment]
Most people are finding upgrading NPM or sorting out permissions is resolving the issue.  If it would help -- you can try the sanity check which will install and run a test in one command -- this is good to try to make sure your env is compatible...  https://github.com/garris/BackstopJS#sanity-test-does-backstop-work-in-my-environment

**Comment by KonstanciaM** [comment]
yeah everything was working few weeks ago, al of a sudden it didnt recognize it, I install puppeteer as it was missing.
I ran the sanity and it generated a report, not sure what to do next
