### ISSUE TITLE
Custom CasperJS scripts doesn't work with SlimerJS

### ISSUE THREAD

**Issue by paweltin** [garris/BackstopJS#108]

**Comment by garris** [comment]
Can you please provide your test case and console output.   Thank you for filing the bug!

**Comment by paweltin** [comment]
Sure, sorry. This is my Grunt config:
```
    backstop: {
      setup: {
        options: {
          backstop_path: './bower_components/backstopjs',
          test_path: './tests',
          setup: false,
          configure: true
        }
      },
      test: {
        options: {
          backstop_path: './bower_components/backstopjs',
          test_path: './tests',
          create_references: false,
          run_tests: true
        }
      },
      reference: {
        options: {
          backstop_path: './bower_components/backstopjs',
          test_path: './tests',
          create_references: true,
          run_tests: false
        }
      }
    },
```

This is `backstop.json`
```
{
  "viewports": [
    {
      "name": "phone",
      "width": 320,
      "height": 4000
    }
  ],
  "scenarios": [
    {
      "label": "Home page",
      "url": "http://www.google.com",
      "hideSelectors": [],
      "removeSelectors": [],
      "selectors": [
        "body"
      ],
      "readyEvent": null,
      "delay": 1000,
      "onReadyScript": "homepage.js",
      "misMatchThreshold" : 0.1
    }
  ],
  "paths": {
    "bitmaps_reference": "../../backstop_data/bitmaps_reference",
    "bitmaps_test": "../../backstop_data/bitmaps_test",
    "casper_scripts": "../../backstop_data/casper_scripts",
    "compare_data": "../../backstop_data/bitmaps_test/compare.json"
  },
  "engine": "slimerjs",
  "report": ["CLI", "browser"]
}
```

This is my custom script:
```
module.exports = function(casper, scenario) {
    casper.echo("Testing");
};
```

And this is console output for `grunt backstop:reference`:
```
Running "backstop:reference" (backstop) task
[15:24:18] Using gulpfile /var/www/przesylarka.local/bower_components/backstopjs/gulpfile.js
[15:24:18] Starting 'clean'...
bitmaps_reference was cleaned.
[15:24:18] Starting 'bless'...
[15:24:18] Finished 'clean' after 23 ms
[15:24:18] Finished 'bless' after 22 ms
[15:24:18] Starting 'reference'...
[15:24:18] Starting 'init'...
[15:24:18] Finished 'init' after 3.8 μs
[15:24:18] Starting 'test'...

Generating reference files.

[15:24:18] Finished 'test' after 3.94 ms
reference has run.
[15:24:18] Finished 'reference' after 4.99 ms
CasperJS: CREATING NEW REFERENCE FILES
CasperJS: Ready event received.
CasperJS: Current location is http://www.google.com
CasperJS: Running custom scripts.
CasperJS: Screenshots for phone (320x4000)
CasperJS: Comparison config file updated.

Bitmap file generation completed.

Run `$ gulp test` to generate diff report.


gulp.run() has been deprecated. Use task dependencies or gulp.watch task triggering instead.




Done, without errors.
```

If I switch engine for `phantomjs` I get an extra line in output:
```
CasperJS: Testing
```
After `CasperJS: Running custom scripts.`

**Comment by paweltin** [comment]
Do you have any clue what can be wrong? I would gladly try to fix it, as I prefer to use SlimerJS, but I don't know where to start.

**Comment by paweltin** [comment]
It seems that this `require()` goes wrong:
https://github.com/garris/BackstopJS/blob/master/capture/genBitmaps.js#L141

**Comment by paweltin** [comment]
It looks like SlimerJS issue. If I use absolute path for my custom scripts directory in `backstop.json` everything works fine. Issue probably can be closed.

**Comment by garris** [comment]
Thank you for tracking this down -- this is very helpful!   Before closing, we should probably do two things...

1)  Update readme documentation in the `onReadyScript` and `casper_scripts` notifying users that absolute paths are required when using the slimer engine.

2) maybe wrapping the require() in a `try` block.  On error we could notify the user to check the notes in the documentation -- or give some other useful next step.


Thank you.

**Comment by garris** [comment]
I have just pushed item 1 above to master.

**Comment by klausbayrhammer** [comment]
I just ran into the same issue. What about either:
* Add the module path to slimerjs' require.path `require.paths` see the [Docs](https://docs.slimerjs.org/current/api/require.html)
* When loading casper scripts we could check if engine is slimer and the path is absolute and stop the test if not.

**Comment by garris** [comment]
Looks good to me.

**Comment by Brykou** [comment]
Are seriously use absolute paths when you use SlimerJS ? This is a crazy process when your backstop.json file is versionned and used by différents peoples to run tests.
I have this problem and can't find a good workaround.

**Comment by garris** [comment]
Have you tried the suggestion above?

> Add the module path to slimerjs' require.path require.paths see the Docs

Another approach is to use a .js based config and make those paths a computed property.

**Comment by Brykou** [comment]
> Another approach is to use a .js based config and make those paths a computed property

I did this (jsx files used to generate backstop.json file)
