### ISSUE TITLE
Add viewport to custom script's context

### ISSUE THREAD

**Issue by paweltin** [garris/BackstopJS#109]
I think it's pretty useful for writing device specific scripts. If you agree I will be happy to push a PR

**Comment by garris** [comment]
What is a specific use case for this?

**Comment by paweltin** [comment]
You may want to do different actions for different devices (e.g. click different button on mobile than on desktop).

**Comment by garris** [comment]
Sure, that makes sense.  Would totally appreciate the pull request.   Please create a script that we could run to test the feature (at minimum it should just log viewport data to the console to prove that everything is in sync).  Also, please add a note in the documentation.

**Comment by EvanLovely** [comment]
+1

**Comment by paweltin** [comment]
I'm gonna push it as soon as i can. Please leave this open.

**Comment by EvanLovely** [comment]
@garris @paweltin I might of just taken care of this in #113 - did I?

**Comment by garris** [comment]
Yes, #113 did it.  It's merged to master.   Please review.  It would be great to see a test (switching on 2 vp cases) for it in the tests folder. If it's otherwise working the ticket can be closed.

**Comment by EvanLovely** [comment]
Got some tests up in #114

**Comment by garris** [comment]
Thanks everyone.
