### ISSUE TITLE
Improve code pattern consistency

### ISSUE THREAD

**Issue by felquis** [garris/BackstopJS#11]
Hi @garris 

Would you like a pull request with a .editorconfig and JSHint tests to improve JS code?

Things like, ensure I used single quotes, ensure I used 4 spaces tabs, remove trailing spaces, ensure I do not let unused variables in the code etc...

I think this repository will receive a lot of pull request and some tests with Travis CI can save a lot of your time.

Thanks.

**Comment by xavhan** [comment]
try [JSCS](http://jscs.info/) for consistency ;)
