### ISSUE TITLE
Can I use html_report source files from node_modules?

### ISSUE THREAD

**Issue by renatonouman** [garris/BackstopJS#1118]
Hey!
Is it possible to keep the html_report source files and assets inside the node_modules folder and use them from there, instead of adding them to the repo?
I could add them to the `.gitignore`, but the next person would need them as well, and running `backstop init` would bring back a bunch of files I don't need.
How could I clean up and make it easier for other people to run tests on my repo? Am I missing something here?

**Comment by renatonouman** [comment]
Oh! I see now. Everything inside the `html_report` folder is generated dynamically right?

**Comment by garris** [comment]
That directory is generated.  It's a self-contained html report.  You configure where this is generated -- no need to put it in Git unless you need it there.

**Comment by renatonouman** [comment]
Yes! I realised that short after opening the ticket. Thanks for the answer anyway. BackstopJS is awesome! 💎
