### ISSUE TITLE
Is it possible to save the diff image on a successful test?

### ISSUE THREAD

**Issue by pwtyler** [garris/BackstopJS#1121]
I'm looking to save the "diffImage" for cases where the difference is above 0.00%, but below the tolerable misMatchThreshold— the test passed, so I don't get the diff in the report, but is it possible to override the current behavior and view/store that diff image anyway?

**Comment by garris** [comment]
This is not easily possible.  You probably just need to run another pass outside of your testing flows.

**Comment by mirzazeyrek** [comment]
I think an easy way would be that you can set the threshold very low, so anything above 0.00% would be in the report. But then I suggest you to write a script to re-run failed tests separately to make sure it's not a temporary issue.

**Comment by pwtyler** [comment]
Thank you— I can run the test at 0.00% diff and check the misMatchPercentage separately if > 0.00% as suggested. Just wanted to make sure I wasn't missing the functionality elsewhere.
