### ISSUE TITLE
ERROR: content 0.00%, threshold 0.1%

### ISSUE THREAD

**Issue by lpeabody** [garris/BackstopJS#1133]
I'm receiving an error for one test where there is clearly nothing different, but it reports as an error anyways.

```
      compare | ERROR { requireSameDimensions: true, size: isDifferent, content: 0.00%, threshold: 0.1% }: Layout - T02 - Landing Page prototypes_base_Layout_-_T02_-_Landing_Page_0_document_0_large-desktop.png
```

What could cause this?

**Comment by garris** [comment]
Check the report for different image dimensions.

**Comment by lpeabody** [comment]
This is the contents of report.json:

```
{
  "testSuite": "BackstopJS",
  "tests": [
    {
      "pair": {
        "reference": "../bitmaps_reference/prototypes_base_Layout_-_T02_-_Landing_Page_0_document_0_large-desktop.png",
        "test": "../bitmaps_test/20191213-205700/prototypes_base_Layout_-_T02_-_Landing_Page_0_document_0_large-desktop.png",
        "selector": "document",
        "fileName": "prototypes_base_Layout_-_T02_-_Landing_Page_0_document_0_large-desktop.png",
        "label": "Layout - T02 - Landing Page",
        "requireSameDimensions": true,
        "misMatchThreshold": 0.1,
        "url": "http://baxter.docksal/profiles/custom/bax_base/themes/bax_base_theme/build/t02-landing.html",
        "referenceUrl": "",
        "expect": 0,
        "viewportLabel": "large-desktop",
        "diff": {
          "isSameDimensions": false,
          "dimensionDifference": {
            "width": 0,
            "height": -1
          },
          "misMatchPercentage": "0.00",
          "analysisTime": 235
        },
        "diffImage": "../bitmaps_test/20191213-205700/failed_diff_prototypes_base_Layout_-_T02_-_Landing_Page_0_document_0_large-desktop.png"
      },
      "status": "fail"
    }
  ],
  "id": "prototypes_base"
}
```

Looks like isSameDimensions is `false`. Why would that be though?

**Comment by garris** [comment]
Looks like the test screenshot is 1 pixel shorter than the reference.   There could be many reasons for this.  It is most likely an inconsistency in your app display.  Make sure you page is completely done rendering before taking the screenshot.

**Comment by lpeabody** [comment]
Apologies for my ignorance but I'm a total noob when it comes to JavaScript. I've been reading documentation and, I think for my purposes, I would consider a page "rendered" when there is no longer any network traffic occurring as I assume this means that all the images on the page are loaded. This is complicated by the fact we use lazy image loading. I have the following:

```
module.exports = async (page, scenario, vp) => {
  console.log('SCENARIO > ' + scenario.label);
  await require('./clickAndHoverHelper')(page, scenario);
  await page.evaluate(() => {
    // Activate all observers and preload all lazy images.
    let observers = document.querySelectorAll('[data-module=Observer]');
    for (let observer of observers) {
      observer.classList.add('reveal');
    }
    let lazies = document.querySelectorAll('.lazyload');
    for (let lazy of lazies) {
      lazy.classList.add('lazypreload');
    }
  });
};
```

That lazy loads all the images on the page and sets all fade-in effects. This works about 70% of the time. However, based on the intermittent failures I'm clearly capturing the screenshots at the wrong time.

I tried adding this after the `page.evaluate`:

```
  await page.waitForNavigation({
    waitUntil: 'networkidle0'
  });
```

But that just resulted in every test run timing out after 60 seconds. I realize you don't know anything about my application, but if you have any best-practice recommendations on how to check that a page is fully "rendered" I would be most appreciative. Thank you for your help so far!

**Comment by garris** [comment]
Unfortunately you will probably need to work with whoever is building your frontend -- too many variables.    I haven't used the networkidle0 idle method -- so not sure how to advise there either.  Sorry.

**Comment by lpeabody** [comment]
No problem. Thanks for your guidance and time. Appreciate all the effort put into this product, it's going to help us immensely.

**Comment by lpeabody** [comment]
Yeah I've got no clue, this makes no sense. I just turned off `requireSameDimensions` and now it passes every time. I guess not all scenarios are created equal! Thanks again for the insights.
