### ISSUE TITLE
Utilizing backstopJS against logged pages and no possibility to use cookies to login

### ISSUE THREAD

**Issue by Sven-WEBDESIGN** [garris/BackstopJS#1155]
Hello Garris and community,

**My need**
Reuse a successfully logged-in access to pages served after a login page through keyboard and click interactions without the possibility to use cookies

**My problem**
I fail to reuse such a successful logged-in session to make synchronous, successive (non atomic) browser session.
First page after the login page displays well. Second page after the login is just a copy of the first page after login, it don't go to the URL it targets.

**The technical problem as i see it**
It seems backstopJS, being asynchronous, opens a tab for every page, thus making any test of a URL a separate process. In my case it means i have to run every logged page against first the logged page.

**My 'backstop.json' config**

`{
    "id": "twimm_vnrtsuite",
    "viewports": [
        {
            "label": "phone",
            "width": 320,
            "height": 480
        },
        {
            "label": "tablet",
            "width": 1024,
            "height": 768
        },
        {
            "label": "desktop",
            "width": 1900,
            "height": 3800
        }
    ],
    "onBeforeScript": "puppet/onBefore.js",
    "onReadyScript": "puppet/onReady.js",
    "scenarios": [
        {
            "label": "login - Intranet",
            "cookiePath": "",
            "url": "{url1}",
            "referenceUrl": "{url1Ref}",
            "readyEvent": "",
            "readySelector": "",
            "delay": 0,
            "hideSelectors": [],
            "removeSelectors": [],
            "hoverSelector": "",

            "postInteractionWait": 0,
            "selectors": [],
            "selectorExpansion": true,
            "expect": 0,
            "misMatchThreshold": 0.1,
            "requireSameDimensions": true
        },
        {
            "label": "HP - Intranet",
            "cookiePath": "",
            "url": "{url2}",
            "referenceUrl": "{url2ref}",
            "readyEvent": "",
            "readySelector": "",
            "delay": 0,
            "hideSelectors": [],
            "removeSelectors": [],
            "hoverSelector": "",
            "keyPressSelectors": [
                {
                    "keyPress": "{username}",
                    "selector": "#username"
                },
                {
                    "keyPress": "{password}",
                    "selector": "#password"
                }
            ],
            "clickSelector": ".btn-info",
            "postInteractionWait": 8000,
            "selectors": [],
            "selectorExpansion": true,
            "expect": 0,
            "misMatchThreshold": 0.1,
            "requireSameDimensions": true
        },
        {
            "label": "Contrats et maintenance / Clients / les groupes - Intranet",
            "cookiePath": "",
            "url": "{url3}",
            "referenceUrl": "{url3Ref}",
            "readyEvent": "",
            "readySelector": "",
            "delay": 0,
            "hideSelectors": [],
            "removeSelectors": [],
            "hoverSelector": "",
            "keyPressSelectors": [
                {
                    "keyPress": "{username}",
                    "selector": "#username"
                },
                {
                    "keyPress": "{password}",
                    "selector": "#password"
                }
            ],
            "clickSelector": ".btn-info",
            "postInteractionWait": 2000,
            "selectors": [],
            "selectorExpansion": true,
            "expect": 0,
            "misMatchThreshold": 0.1,
            "requireSameDimensions": true
        }
    ],
    "paths": {
        "bitmaps_reference": "backstop_data/bitmaps_reference",
        "bitmaps_test": "backstop_data/bitmaps_test",
        "engine_scripts": "backstop_data/engine_scripts",
        "html_report": "backstop_data/html_report",
        "ci_report": "backstop_data/ci_report"
    },
    "report": [
        "browser"
    ],
    "engine": "puppeteer",
    "engineOptions": {
        "args": [
            "--no-sandbox"
        ]
    },
    "asyncCaptureLimit": 0,
    "asyncCompareLimit": 0,
    "debug": false,
    "debugWindow": false
}`

**Comment by Sven-WEBDESIGN** [comment]
Hello, found a solution, so i'll close the ticket.

**Comment by garris** [comment]
If possible, please share your solution so that others with a similar problem can benefit. 

Cheers.

**Comment by fede-green** [comment]
Hello... I think i have a similar need... would you mind telling me how you get it working, @Sven-WEBDESIGN ? 

Thanks in advance :)

**Comment by Sven-WEBDESIGN** [comment]
Hello @fede-green we used a PHP session token, like so in ***backstop.json****:
"scenarios": [
        {
            "url": "https://{myDomain}/?token={PHP session token value}",
            ...
        },
