### ISSUE TITLE
YouTube Iframe - Screenshot Comes Blank

### ISSUE THREAD

**Issue by superKalo** [garris/BackstopJS#116]
Hello,

I am trying to "catch" a screenshot of youtube video.
Here's my scenario:
```json
{
    "label": "A screen with youtube iframe",
    "url": "http://the-url-to-my-localhost.dev",
    "hideSelectors": [],
    "removeSelectors": [],
    "selectors": [
        "body"
    ],
    "readyEvent": "make-screenshot",
    "delay": 1000,
    "misMatchThreshold" : 0.1,
    "onReadyScript": "wait-iframe-to-load.js"
}
```
and here's my "wait-iframe-to-load.js" script:
```javascript
module.exports = function(casper, scenario) {
    casper.evaluate(function(){

        $(window).on('load', function(){
            $('iframe[src^="http://www.youtube.com"]').ready(function(){
                console.log('make-screenshot');
            });
        });

    });
    casper.wait(1000);
};
```

In the console, I am getting:
```bash
CasperJS: CREATING NEW REFERENCE FILES
CasperJS: ERROR: casper timeout.
```

The iframe on ready event works when I tested it on the page itself. I tried to increase both timeouts to 10000, doesn't do the trick :( The place in the 'body' where the youtube video is supposed to be, comes out empty in the comparison screenshots.

Am I doing something wrong?
Thanks in advance! :)

**Comment by garris** [comment]
@superKalo Sorry for the delay getting to this.  Seems there are some issues with loading YouTube iFrames in Phantom...
[](http://stackoverflow.com/questions/30146353/phantomjs-not-mimicking-browser-behavior-when-looking-at-youtube-videos)

Maybe it would work using the SlimerJS option?

Hope that helps!   Cheers.

**Comment by superKalo** [comment]
Thank you @garris ! Yes, changing the engine to SlimerJs did the trick even without my "wait-iframe-to-load.js" script. Great :+1:
