### ISSUE TITLE
Define config in JS instead of JSON

### ISSUE THREAD

**Issue by EvanLovely** [garris/BackstopJS#117]
Would be great if `backstop.json` could be `backstop.js` as it'd allow the use of variables & comments. Even better would be if Backstop got config by using `require('backstop')` as that would grab any of these:

- `backstop.json`
- `backstop.js`
- `backstop/index.js`

**Comment by garris** [comment]
Yes!

I just merged a configuration for setting the location of backstop.json.   I think there is plenty of room for this feature to live in harmony with that one. 

If *.js returns a promise you could easily hit an endpoint -- I think that might be the way to go.

Any case -- sounds great.  If you write it, I'll pull it.  Fine to do in small steps too.  Let me know how I can help.

Awesome.

**Comment by rimi-itk** [comment]
I would like this as well and I have created a pull request: https://github.com/garris/BackstopJS/pull/125

**Comment by garris** [comment]
Almost closed by PR #125 merged to master.  See documentation on how to specify config file via CLI argument.  

Would like to look at enabling backstop.js *or* backstop.json in it's default location by removing `.json` from the default config filename here https://github.com/garris/BackstopJS/blob/master/gulp/util/paths.js#L19

**Comment by garris** [comment]
just looked at removing `.json` from default file -- unfortunately too many dependencies on a file extension ATM.   

Anycase,  tweaked the documentation -- pretty nice feature as is.  closing issue.  Thanks.
