### ISSUE TITLE
Which browser

### ISSUE THREAD

**Issue by emmareardon1** [garris/BackstopJS#118]
Hi, are there any plans to be able to compare different browsers with this? Which does it currently do?

**Comment by axe312ger** [comment]
We use headless browser implementations. You currently can decide if you wanna test with phantomjs (webkit => Chrome) or slimerjs (Gecko => Firefox)

Other browser are currently not implemented, it might be possible to integrate with [Selenium](http://www.seleniumhq.org/) to support almost any browser but this is very complex and often very buggy. People who worked with Behat & Silenium know what I mean :see_no_evil:

**Comment by garris** [comment]
Thanks Benedikt!
