### ISSUE TITLE
readyEvent halts the process at random times

### ISSUE THREAD

**Issue by hkirsman** [garris/BackstopJS#1191]
I'm trying to solve issue where BackstoJS finds difference because Google fonts have not loaded yet. So instead of loading the fonts like this:
`<link href="//fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800,700italic,800italic,600italic,400italic,300italic" rel="stylesheet">`
I thought I'd go with js so I can have console.log after the fonts have loaded:
```
    <script src="//ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js"></script>
    <script>
      WebFont.load({
        google: {
          families: ['Open Sans:400,300,600,700,800,700italic,800italic,600italic,400italic,300italic']
        },
        active: function() {
          console.log('Fonts have been rendered')
        }
      });
    </script>
```

Sometimes this works, sometimes not. The issue happens only when I enable 'readyEvent'. My whole script looks something like this:
```

/* Quick guide to BackstopJS commands

  backstop reference --configPath=backstop.js --env=local
  backstop test --configPath=backstop.js --env=local

*/
var args = require('minimist')(process.argv.slice(2)); // grabs the process arguments
// List of paths to check on the site.
var environments = {
  'prod': 'https://example.com'
};
var default_environment = 'prod';

// Environments that are being compared
if (!args.env) {
  args.env = default_environment;
}
// if you pass in a bogus environment, it’ll still use the default environment
else if (!environments.hasOwnProperty(args.env)) {
  args.env = default_environment;
}

// Add default screenshot delay, because content and fonts don't always load the
// same way.
const default_delay = 50;

const default_hide_selectors = [
  // Hide videos.
  '.advanced-page-block-1__video',
];

scenarios = [
  {
    'label': '/',
    'url': environments[args.env] + '/',
    'hideSelectors': default_hide_selectors,
    'delay': default_delay,
  },
];

// Backstop default configuration.
module.exports = {
  'id':'backstop_default',
  'viewports':[
    {
      'label': 'phone',
      'width': 320,
      'height': 480
    },
    {
      'label': 'tablet',
      'width': 1024,
      'height': 768
    },
    {
      'label': 'desktop',
      'width': 1440,
      'height': 900
    }
  ],
  // 'onBeforeScript': 'puppet/onBefore.js',
  // 'onReadyScript': 'puppet/onReady.js',
  'scenarios': scenarios,
  'paths': {
    'bitmaps_reference': 'backstop_data/bitmaps_reference',
    'bitmaps_test': 'backstop_data/bitmaps_test',
    'engine_scripts': 'backstop_data/engine_scripts',
    'html_report': 'backstop_data/html_report',
    'ci_report': 'backstop_data/ci_report'
  },
  'report': ['browser'],
  'engine': 'puppeteer',
  'asyncCaptureLimit': 5,
  'asyncCompareLimit': 50,
  'debug': true,
  'readyEvent': 'Fonts have been rendered',
  'debugWindow': false,
  'engineOptions': {
    'ignoreHTTPSErrors': true,
    'args': ['--no-sandbox', '--disable-setuid-sandbox']
  }
}


// Put the report under public files when using Lando so we can get URL to report.
if (process.env.HOSTING_TECH === 'lando') {
  for (let key in module.exports.paths) {
    if (module.exports.paths.hasOwnProperty(key)) {
      module.exports.paths[key] = 'public/' + module.exports.paths[key] ;
    }
  }
}

```

I'm using version 4.5.0 It runs inside Docker container backstopjs/backstopjs:4.5.0

Somebody said that if console.log happens before BackstopJS puts it's scripts in, then it fails. Could it be? So there's no solution? Should I instead somehow remove google fonts during tests? Font would look ugly but then again it would maybe not show font diff.

**Comment by hkirsman** [comment]
This sounds like a good solution https://codurance.es/2020/01/16/backstopjs-tutorial/ "Custom Fonts"

Downloading a non-default font from some server somewhere will take an unpredictable amount of time, so it harms our repeatability. Rather than reaching for that unreliable delay setting, however, we can pre-install the fonts on the Docker image to get around this problem altogether. Simply create a Dockerfile inside your BackstopJS directory with an entry like the following:

    FROM backstopjs/backstopjs:4.4.2
    RUN apt-get update && apt-get install -y fonts-lato
    RUN apt-get update && apt-get install -y fonts-font-awesome

This is a very basic Dockerfile that extends the official BackstopJS image (remember to include the version!) and uses apt-get to install the requisite fonts. This way the browser emulator won't need to download the fonts as they're already installed. You should be able to find the package name of any font you need by searching Debian's package registry. Then you just need to change your docker-compose entry to build your BackstopJS directory, like so:

    visual_regression_tests:
      image: build: ./tests/visual
      volumes:
        - ./test/visual:/src

**Comment by garris** [comment]
@hkirsman Very creative solution.   One thing I would suggest is looking at this issue where they had the same font loading synchronization issue... https://github.com/garris/BackstopJS/issues/1144#issuecomment-625507875

**Comment by hkirsman** [comment]
Tx! I don't have the font issue any more. Although I did the above "add fonts to docker image", I think it might have also been caused by lot of duplicate URL's in the test.
