### ISSUE TITLE
HTML Report possible to just have failures

### ISSUE THREAD

**Issue by broksonic21** [garris/BackstopJS#1192]
Right now, it can take a long time to load the HTML report page as the images are large and need to be loaded. Is there a mode to just have it have failures, and not all images? That would help a lot.

Alternatively, can the images be optimized to be smaller in any way?

**Comment by matejkosiarcik** [comment]
I haven't look into the source, but sounds like something simple as `<img loading="lazy">` could help? <https://web.dev/native-lazy-loading>

**Comment by garris** [comment]
Also, you can filter the results to just show difference results.

**Comment by broksonic21** [comment]
I'm no longer actively needing this, so closing this out as it's 4+ years old and there are workarounds above
