### ISSUE TITLE
Distributed test run system

### ISSUE THREAD

**Issue by f0rzer** [garris/BackstopJS#1200]
thanks for the great product, it really helps :)

I have a problem.
many tests have been written and I need to run them multithreaded on different servers.
on one server, when browsers are packaged in docker everything is fine, but server capacity is not enough.

what approach to use in this case?
most likely you need some kind of balancer and report aggregator to build from different servers.
are there any best practices for this?

**Comment by garris** [comment]
How many tests?  What is your use case?

**Comment by f0rzer** [comment]
a couple of hundred


problem - I do not want to wait 10-15 minutes, I want to parallelize the execution on several servers

but some kind of balancing and reporting tool is needed

**Comment by f0rzer** [comment]
@garris y have idea?)

**Comment by garris** [comment]
I might try setting async limit to say 250 and create a pool of 250 containers running chrome.  Then for each scenario dynamically point puppeteer to connect to the next available Chrome container across the pool.  That might bring the total running time down to say 30 secs for say 500 tests.  This would be a very minimal change to backstop -- potentially only changing the config to dynamically point to a chrome container.

**Comment by f0rzer** [comment]
thanks for the idea!
I’ll close the current issue
