### ISSUE TITLE
Feature request: `postInteractionEvent`

### ISSUE THREAD

**Issue by DEfusion** [garris/BackstopJS#1212]
In some of my scenarios I need to wait until something is ready, setting an arbitrary `postInteractionWait` time does work but can also cause inconsistent behaviour between CI and local (both using docker) my thought is maybe this is because one is running faster than the other.

Rather than tweaking `postInteractionWait` up it'd be nice to have a `postInteractionEvent` similar to `readyEvent` so my test could log to console that it's ready to screenshot.

**Comment by garris** [comment]
The helper files are intended to be modified for your project.  It should be very easy for you to extend these yourself -- this is encouraged.

**Comment by DEfusion** [comment]
Thanks for that @garris, I didn't think of modifying the helpers will have a look.
