### ISSUE TITLE
Behat & Backstop

### ISSUE THREAD

**Issue by EgorSolonchenko** [garris/BackstopJS#1217]
Hello.
I try to run "Backstop" from "Behat" but the failure to achieve full compatibility "Behat" and "Backstop" since "Behat" uses its browser and "Backstop" also uses its browser. 
It would be perfect to get provide deeper integration between Behat and Backstop: the Behat and Backstop should use the same Chrome driver.

Can I somehow tell "Backstop" to use an already running browser?

**Comment by garris** [comment]
Hi-- I think if you want to use behat you probably want to do this differently.  You probably want to create a behat-backstop helper.   This lets you use behat as the rest framework and you can simply delegate screenshots to backstop.

See ember-backstop for an example of how this is done. Ember uses testem underneath so this I think will be very similar.

**Comment by EgorSolonchenko** [comment]
Thanks. You've saved me a lot of work with that.

**Comment by garris** [comment]
If you happen to publish your final project I would love to see it!   Cheers.
