### ISSUE TITLE
Failure due to missing library libXss.so.1 in Docker image

### ISSUE THREAD

**Issue by merelrietbergen** [garris/BackstopJS#1225]
Hi!

In the latest (5.0.4) Docker image (build September 5, 2020) the library `libXss.so.1` is not installed, resulting in a failure with the following error:
```
COMMAND | Error: Failed to launch the browser process!
                /usr/local/lib/node_modules/backstopjs/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory
```

Adding `libxss1` to the libraries being installed in the `Dockerfile` seems to resolve the issue, though there may be some other underlying cause.

Neither 5.0.1 nor 5.0.2 are affected, likely because the images for these were not built as recently.

**Comment by digitaldonkey** [comment]
Ran into same issue.

**Comment by jlnschfr** [comment]
same here, occured today.

`/usr/local/lib/node_modules/backstopjs/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory`

**Comment by AdamChrimes** [comment]
Having the same issue on Travis CI

```
COMMAND | Executing core for "test"
createBitmaps | Selected 89 of 89 scenarios.
      COMMAND | Command "test" ended with an error after [0.033s]
      COMMAND | Error: Failed to launch the browser process!
                /usr/local/lib/node_modules/backstopjs/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory
                
                
                TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md
                
                    at onClose (/usr/local/lib/node_modules/backstopjs/node_modules/puppeteer/lib/Launcher.js:750:14)
                    at Interface.helper.addEventListener (/usr/local/lib/node_modules/backstopjs/node_modules/puppeteer/lib/Launcher.js:739:50)
                    at Interface.emit (events.js:194:15)
                    at Interface.close (readline.js:379:8)
                    at Socket.onend (readline.js:157:10)
                    at Socket.emit (events.js:194:15)
                    at endReadableNT (_stream_readable.js:1125:12)
                    at process._tickCallback (internal/process/next_tick.js:63:19)
The command "docker run --rm -it --network="host" --mount type=bind,source="/home/travis/build/nhsuk/nhsuk-frontend",target=/src backstopjs/backstopjs:latest test --config=tests/backstop/backstop.js --moby --testhost=http://127.0.0.1:3000" exited with 1.
```

https://travis-ci.org/github/nhsuk/nhsuk-frontend/jobs/725519186

**Comment by garris** [comment]
Does anyone know the root cause?  Does the problem go away if we bump puppeteer?

**Comment by garris** [comment]
Or is there maybe a problem with the base docker image -- maybe a change there?

**Comment by garris** [comment]
If someone can post a patch I will approve it ASAP.

**Comment by digitaldonkey** [comment]
apt-get install libxss1

**Comment by digitaldonkey** [comment]
I did this PR kind of blind. I cant get the latest image. Maybe a tag missing? 

`ᐅ docker pull  backstopjs/backstopjs
docker pull backstopjs/backstopjs:latest

Using default tag: latest
latest: Pulling from backstopjs/backstopjs
Digest: sha256:57015a3c7545b05d361d346f826c63eb809e84a29aefb6c127febd1f88660955
Status: Image is up to date for backstopjs/backstopjs:latest
docker.io/backstopjs/backstopjs:latest
latest: Pulling from backstopjs/backstopjs
Digest: sha256:57015a3c7545b05d361d346f826c63eb809e84a29aefb6c127febd1f88660955
Status: Image is up to date for backstopjs/backstopjs:latest
docker.io/backstopjs/backstopjs:latest


ᐅ docker run -it --add-host="host.docker.internal:$(ipconfig getifaddr en0)"  -v $(pwd)/backstopjs:/src -v $(pwd)/lfs_data:/lfs_data  backstopjs/backstopjs -v
BackstopJS v5.0.4`

Shouldn't  `backstopjs -v` be v5.0.5 ?

**Comment by garris** [comment]
@digitaldonkey Thank you for this PR -- ITS FIXED!

```
npm notice === Tarball Details ===
npm notice name:          backstopjs
npm notice version:       5.0.6
npm notice package size:  22.9 MB
npm notice unpacked size: 28.9 MB
npm notice shasum:        c2ef7f1e6466ad515d757c77da70314113cc430c
npm notice integrity:     sha512-YNBiWDzgBqxW8[...]GgJtwGhQOTEpA==
npm notice total files:   520
npm notice
+ backstopjs@5.0.6
```

**Comment by tobiasbaehr** [comment]
I am not sure if we really need this. I use puppeteer v3 (backstopjs v2) to generate pdf and in case you have an own chrome etc. you can say puppeteer please do not download your own chrome use my chrome. (PUPPETEER_SKIP_DOWNLOAD)
