### ISSUE TITLE
Basic HTTP Auth

### ISSUE THREAD

**Issue by kateivamarmalade** [garris/BackstopJS#123]
Hey, is there a way that it would be possible to make basic HTTP auth before each scenario?

**Comment by garris** [comment]
@kateivamarmalade I haven't tested this use case myself -- but you should be able to add a simple CasperJS script to do that for you.  See these two links...

example of CasperJS script with httpAuth...
http://stackoverflow.com/questions/24842762/casperjs-http-auth

running CasperJS scripts in BackstopJS...
https://github.com/garris/BackstopJS#running-custom-casperjs-scripts-version-080

Hope that helps!

**Comment by ay13** [comment]
@kateivamarmalade @garris When you add the URL to the scenerios you can include the http basic auth username and password in the URL and it will log you in.

example: ```http://username:password@www.website.com```

**Comment by garris** [comment]
@ay13  Nice!  :+1:

**Comment by garris** [comment]
I think that should do it -- closing.   @kateivamarmalade Please reopen if for some reason @ay13's answer doesn't solve the issue.  Cheers

**Comment by torounit** [comment]
Chromy sample.

https://gist.github.com/torounit/33cdc09cbb698f4b4287085da23c7fe5
