### ISSUE TITLE
Is it possible to take the reference of only the newly added scenario?

### ISSUE THREAD

**Issue by zehra89** [garris/BackstopJS#1230]
Hi, I am new to the backstop js. The issue I am facing is that in my backstop.json file I have multiple scenarios and when I want to capture a reference screenshot for the newly added scenario then the references for the old scenarios are re-taken. Is there any way with which I can run the command backstop reference for a particular scenario only and not for all the scenarios present in the JSON file.

Moreover, it is possible to run a **backstop test** command for a specific test case?

**Comment by zehra89** [comment]
Found the answer

**Comment by ArunWakekar** [comment]
what is the answer?

**Comment by garris** [comment]
See the docs about filtering `reference` and `test` commands by scenario name.
