### ISSUE TITLE
Specify location of compareConfigFileName

### ISSUE THREAD

**Issue by klausbayrhammer** [garris/BackstopJS#124]
Currently we are running our backstop-tests on a CI-server which operates on a fresh checkout. Since `npm install` is so painfully slow use a prepackaged node_modules directory and use `npm purge` and `npm install` to update dependencies, quite similar to [this approach](https://lincolnloop.com/blog/speeding-npm-installs/). Something we stumbled upon was that we sometimes we got the error `It looks like the reference configuration has been changed since last reference batch` although the config didn't change. In the end our problem was, that the `.config.json.cache` is stored under `node_modules/backstopjs/capture` and distributed in our packaged `node_modules.tgz` and may not match the original backstop.json. Furthermore backstop stops (with response code 0) and backstop doesn't execute the tests - which makes our CI believe that all backstop tests succeeded (but in fact they haven't been executed at all).

There are two issues we are having with the current implementation:
* If a changed config is detected the test stops without notifying the caller (like calling the gulp callback with an error or something like that)
* The cached config is placed under node_modules and the location of this cached config cannot be modified.

The easy solution for the second problem would probably be to specify the `captureConfigFileNameCache` in the `backstop.json` just like the other paths. But maybe we could come up with a more elegant solution, like computing a hash of the configuration and storing it somewhere? 

We are currently working around this by calling `bless` before we execute the tests, but with that we are loosing the config change detection (which is an awesome feature btw).
This may be quite an edge-case but I think trying to avoid storing data in the node_modules would support the implementation of #32 as well.

**Comment by garris** [comment]
I understand.  I guess the two options would be 1) move the location of the cache file to the bitmaps_reference path (or an explicitly specified path in the config)
OR
2) just add a config `disableConfigCheck`  which turns off saving/checking etc..  (This is probably easiest and maybe more useful for your case)

**Comment by garris** [comment]
I totally take back my last response.  Reading this on my phone on the train, I didn't see the text after the bullets.  So sorry about that!

I like your current workaround calling `bless` like that.  Totally what I would have done.

I think your first solution is the way to go.  Super straight forward.

That said,  the other suggestion, hash or checksum idea is very cool.  I guess that could actually be saved in the `compare_data` file in it's own top level node along-side the test data.   It makes sense to keep that data together.   Bless would need to be changed to simply update that top level node (if it existed) and not clobber the test data node.  And the compareConfig data would need to be made into a branch here...  https://github.com/garris/BackstopJS/blob/master/capture/genBitmaps.js#L248
```
compareConfigDecorated: {
    compareConfig: compareConfig,
    lastConfigHash: turnIntoSomeKindOfHashOrChechsum(config)
}
var configData = JSON.stringify(compareConfigDecorated, null, 2);
```
And the other scripts that read `compareConfigFileName` would need to look for `compareConfigFileName.compareConfig` to get the data they need.   

And here... https://github.com/garris/BackstopJS/blob/master/gulp/tasks/test.js#L31
You'd want to get the `cache` from `compareConfigFileName.lastConfigHash`.  If none existed you would not throw.  If one did exist, you'd want to do a compare or deepEquals of `turnIntoSomeKindOfHashOrChechsum(config)` against whatever is appropriate for `cache` -- and return `false` if false.

I hope that helps -- its probably 80% of what you'd need to implement your "computed hash" idea.   I am happy to support you if you want to implement this. And again,  so sorry for missing your thoughtful suggestions the first time around.   My day job is great but I do get pretty frantic managing everything and sometimes miss the good stuff.

ok.  Awesome!

**Comment by garris** [comment]
Ok.  The PR looks great.  Merged.  

Notes:  
- After merging I cleaned up `echoFiles.js` so no other tasks are needed there.
- I have not tested anything yet -- but all the code changes look really good.  Will test either tonight or tomorrow AM.  

:+1:

**Comment by garris** [comment]
Ok.   Just tested this -- works great --  Thanks for the contribution!

**Comment by klausbayrhammer** [comment]
Ah nice you removed the copying of the compareConfig entirely - I was wondering why that was needed :+1:
