### ISSUE TITLE
npm vulnerability with url-regex

### ISSUE THREAD

**Issue by alexpradap** [garris/BackstopJS#1243]
Message came out after running `npm install --save-dev backstopjs`

On `npm audit`got this:
High - Regular Expression
Package: url-regex
Patched in: No patch available
Dependency of: backstopjs
Path: backstopjs > merge-img > jimp > url-regex

On `backstop init`got: command not found

Did I installed correctly?

**Comment by ledenis** [comment]
Your "command not found" error has nothing to do with vulnerability issues.

If running from your terminal, try `npx backstop init`. Because you did not install it globally (with `-g`) but only locally.

**Comment by alexpradap** [comment]
You are right. Found this solution searching over the Internet:

$./node_modules/.bin/backstop init

Seems like that is the way of executing backstop when it is not installed globally.
