### ISSUE TITLE
Recommendations for Interacting with Cloudflare Polish or other image CDNs

### ISSUE THREAD

**Issue by broksonic21** [garris/BackstopJS#1244]
We are using backstopjs during our CI to do a "before deploy" (reference) vs "after deploy" (test) comparison when deploying to our dev cloud environment.

It works great in general.

We recently turned on Polish though (which does some image compression), so it looks different and fails sometime. Any one have a way to tell Polish or other systems not to compress when backstop is running?

**Comment by garris** [comment]
I don't know about polish -- but you could try telling backstop to ignore all images.

**Comment by broksonic21** [comment]
I'm no longer actively needing this, so closing this out as it's 4+ years old and work around above
