### ISSUE TITLE
Change URL/Port for 'Remote'

### ISSUE THREAD

**Issue by mspi** [garris/BackstopJS#1253]
Currently `backstop remote` will start a server on  `http://127.0.0.1:3000`

Is it possible to change this url and port in the config? I could not find this in the documentation. 

Thank you for making BackstopJS, we really like to use it!

**Comment by garris** [comment]
Sorry for the delay getting back.  I thought someone had added an environment var for this.  Please take a look at the code -- if no one has added this I would gladly pull this in.  E.g. --backstop-remote-port=\<nnnn>

If it _was_ already added -- I would gladly pull in a documentation update.

**Comment by fuhlig** [comment]
@mspi any update on this?

**Comment by domibarton** [comment]
@garris I think this issue can be closed, since it's already documented (via ENV var).

**Comment by mmunz** [comment]
As of now it is only possible to change the port but not the host.

Use case: Running backstop in a ddev (docker) environment, where the backstop container is reachable via an http reverse proxy, so the remote url is not 127.0.0.1:3000 but something like mysite.ddev.site:3000
