### ISSUE TITLE
Allow additional YML config file

### ISSUE THREAD

**Issue by digitaldonkey** [garris/BackstopJS#1254]
Maintaining a distribution the backstop.json file is limited as JSON does not allow comments. 

To explain to my users (and develop more easily) it would be great if I could provide a backstop.yml file as alternative.

**Comment by garris** [comment]
You can easily use a .JS file instead. You can use comments in there.  check the docs for more info.

**Comment by digitaldonkey** [comment]
Thank you for clarification.
