### ISSUE TITLE
diff%: 0.00 diff-x: 0 diff-y: -1 reporting as failure without any visual difference

### ISSUE THREAD

**Issue by broksonic21** [garris/BackstopJS#1259]
We have automation that keeps failing on one, and only one, comparison with these text results:

diff%: 0.00 diff-x: 0 diff-y: -1

The diff and scrubber aren't showing any pink or other visual difference.

Is this a known issue or a different way to diagnose what the actual issue is?

**Comment by broksonic21** [comment]
Note: these are running in the same environment

**Comment by broksonic21** [comment]
The logs say

 compare | ERROR { requireSameDimensions: true, size: isDifferent, content: 0.00%, threshold: 0.35% }

**Comment by garris** [comment]
Sounds like a situation where the bounding element (maybe body or some div or whatever?) is overflowing.  this can happen if a font loads, or an image loads or some change happens somewhere which affects the size of the element very very subtly.

Maybe try isolating potential sources for this.  Maybe force-set the H & W of your container, maybe change the timing of your screen capture (ideally waiting for some kind of event), or maybe set all the inner content to display:none.  I don't suggest this as a solution -- the goal is to discover what operation is changing the size of your container and then ensuring your screenshot is always taken after this operation happens so screen shots become consistent.

FWIW:  whenever something like this happens -- I have found there is ALWAYS a cause.  Something happening to cause a reflow.  Chrome inspector can help find these too.   Keep at it, you will likely find the reason.   And if you
