### ISSUE TITLE
Error in custom script

### ISSUE THREAD

**Issue by Grafs** [garris/BackstopJS#126]
Use:
````
module.exports = function(casper, scenario, vp) { 
    if (vp.name === 'phone' || vp.name === 'tablet') {
	  casper.echo( 'Clicking menu button in vievport: ' + vp.name);
	  casper.click( '#menu-mobsdb' );
  }
}
````
Error: vp is undefined
Please correct in backstopjs/capture/genBitmaps.js 
`require(require_script_path)(casper, scenario);`
to 
`require(require_script_path)(casper, scenario, vp);`

**Comment by garris** [comment]
Hi, thanks for reporting this.   The `vp` argument was actually added after the 0.8.0 release and I have just pushed release 1.0.0 to NPM.   I expect everything will work if you update to the latest version.  Please let me know if that fixes it.  Thanks.  GS
