### ISSUE TITLE
selectorExpansion takes screenshots in arbitrary order...

### ISSUE THREAD

**Issue by deap82** [garris/BackstopJS#1269]
I have a number of pages testing multiple UI components. Basically they look like this when backstop accesses them and each  surface within the gray borders are to be screenshot using the `selectorExpansion` feature.

![image](https://user-images.githubusercontent.com/1295067/105191405-527a2e80-5b37-11eb-9d2d-55282e4a84f2.png)

Now I've stumbled upon an issue where I get failing tests because all of a sudden the ordering of these tests (n1, n2, n3 etc in the test file name) seems to be arbitrary on each test run. Sometimes the last area is screen shot as if it was the first etc, making the screenshot compared with the wrong reference image...

Example of failing test (here you can see that the last area has been screenshot as if it was the first in the test run):
![image](https://user-images.githubusercontent.com/1295067/105190069-eb0faf00-5b35-11eb-81c4-cee3c6f7c189.png)

What is the exact logic for the `selectorExpansion` feature? Shouldn't it be document html order (🙏) or is it pixel order (😬), meaning that multiple elements on the same Y point, matching the `selector`, might be scrambled like this on each test run?

**Comment by deap82** [comment]
I have no rearranged my test pages so that each area selected is rendered top to bottom, instead of in columns. I still get problems with screenshots not being taken in the same order as each area appears in the page...

**Comment by garris** [comment]
Hmm -- this is the first time I am hearing about this issue.   This feature is tested in the backstop smoke test.  Can you see if that is working?

`npm run smoke-test-docker`

**Comment by deap82** [comment]
Yes, the smoke-test is working, I get a few text-antialising diffs but no diffs where images seems to have swapped place... Hmm indeed... 🤔

**Comment by garris** [comment]
Oh,  I think you may have a rendering timing issue.  Like one of the elements isn't rendered yet when the test is executing -- and the selection is off because the count is different.

Can you await until you have the correct number of elements?

**Comment by deap82** [comment]
I apologize. After reiterating and testing again locally vs in our CI environment the cause of the error was found in how I "generate" the test pages.

(The details; When testing locally, the system under test runs on Windows. In our CI environment the system under test runs on Linux. The test pages are generated at runtime from a set of files in a set of folders, using C# `Directory.GetFiles`, it turns out that the return from that method does not guarantee any specific order but it has been consistent on Windows. Apparently in Linux it is not, resulting in the different test areas actually being RENDERED in different order on each run (which I could not visualize, as it was in the CI job...) :-|.)

Backstop is not to blame, closing this issue! Again, I apologize.
