### ISSUE TITLE
Override defaults for misMatchThreshold/readyEvent

### ISSUE THREAD

**Issue by klausbayrhammer** [garris/BackstopJS#127]
We are currently building up more and more backstop-scenarios, but since we use the same "test-setup" we are duplicating the readyEvent and misMatchThreshold in every scenario. The scenario part of our backstop config kind of  look like this:

```json
...
"scenarios": [
    {
      "label": "label1",
      "url": "url1",
      "selectors": ["selector"],
      "readyEvent": "backstop_ready",
      "misMatchThreshold" : 0.1
    },
    {
      "label": "label2",
      "url": "url2",
      "selectors": ["selector"],
      "readyEvent": "backstop_ready",
      "misMatchThreshold" : 0.1
    },
    {
      "label": "label3",
      "url": "url3",
      "selectors": ["selector"],
      "readyEvent": "backstop_ready",
      "misMatchThreshold" : 0.1
    },
]
...
```

As you can see we are duplicating the readyEvent and misMatchThreshold properties heavily and reduce the readability of our scenarios. Would it be possible to somehow specify defaults (override the defaults) for those properties. Probably the config could look like this:

```json
...
// probably this should go somewhere else or should have a different name
"defaultProperties": {  
     "readyEvent": "backstop_ready",
      "misMatchThreshold" : 0.1
}
"scenarios": [
    {
      "label": "label1",
      "url": "url1",
      "selectors": ["selector"]
    },
    {
      "label": "label2",
      "url": "url2",
      "selectors": ["selector"]
    },
    {
      "label": "label3",
      "url": "url3",
      "selectors": ["selector"]
    },
]
...
```

Probably its already possible (maybe #24) but I haven't found out how to configure it.

**Comment by garris** [comment]
Yes, this should not be difficult to add.

I would not add the `defaultProperties` branch. Instead I would probably just keep the parameters (e.g. `misMatchThreshold` etc...) at the config root.   (It's ok with me if it makes more sense for your use case to group them together.)

_first, add the variables internally_

after this line...
https://github.com/garris/BackstopJS/blob/master/gulp/util/paths.js#L71
add...
```
paths.misMatchThreshold = config.misMatchThreshold || null;
paths.readyEvent = config.readyEvent || null;
```

_then, add these parameters in the app in the capture flow_

replace this line...
https://github.com/garris/BackstopJS/blob/master/capture/genBitmaps.js#L208
with...
```
misMatchThreshold: scenario.misMatchThreshold || config.misMatchThreshold
```

replace these lines...
https://github.com/garris/BackstopJS/blob/master/capture/genBitmaps.js#L88-L89
with...
```
var readyEvent = scenario.readyEvent || config.readyEvent;
if (!readyEvent) return true;
var regExReadyFlag = new RegExp(readyEvent,'i');
```

Hopefully this is everything you'd need.  I don't think you'll need to make any modifications in the compare flow.  Please let me know if this works for you.  Cheers!

**Comment by garris** [comment]
Merged.  This should work now.  Please test for your use case and close if all good.  Cheers!

**Comment by joaoffalcao** [comment]
Hi, 
I want to set my misMatchThreshold to 0% in all scenarios, how can I do it?
I've set it on each scenario with ```"misMatchThreshold" : 0.0,``` but when the report opens, the setted value of misMatchThreshold is 1. 

My backstop.json is something like 
```javascript 
    {
      "label": "List Component",
      "url": "http://localhost:5000/#/component/list",
      "hideSelectors": [],
      "removeSelectors": [],
      "selectors": [
        "html"
      ],
      "readyEvent": null,
      "delay": 1000,
      "misMatchThreshold" : 0.0,
      "onBeforeScript": null,
      "onReadyScript": "onReadytoPhone.js"
    },
    {
      "label": "EMS Footer",
      "url": "http://localhost:5000/#/home/highlights",
      "hideSelectors": [],
      "removeSelectors": [],
      "selectors": [
        ".mod-footer"
      ],
      "readyEvent": null,
      "delay": 500,
      "misMatchThreshold" : 0.0,
      "onBeforeScript": null,
      "onReadyScript": "onReadytoPhone.js"
    }
```
What am I doing wrong?

Regards, 
João Falcão

**Comment by garris** [comment]
0 is considered invalid -- you can try a very small fraction but I don't know if that would work.  .00000001

**Comment by joaoffalcao** [comment]
Hi @garris, I tried the "misMatchThreshold" : 0.0000000001, and it worked. 

Many thanks!
João Falcão

**Comment by garris** [comment]
Great!   Cheers.
