### ISSUE TITLE
BackstopJS producing weird diff pattern

### ISSUE THREAD

**Issue by valoricDe** [garris/BackstopJS#1274]
Hello there,
I'm using backstopjs in a project and it worked fine for months but since the new year there are multiple tests failing with a strange pattern
![failed_diff_breadcrumb-navigationhtml_data-qa-regressionbreadcrumb-navigation_usage_desktop](https://user-images.githubusercontent.com/22564188/106170521-d748f600-6190-11eb-92d3-b433d95191cf.png)
or
![failed_diff_absolute-positioninghtml_data-qa-regressionabsolute-positioning_state-specific_desktop](https://user-images.githubusercontent.com/22564188/106170560-dfa13100-6190-11eb-8e9c-359ce3c2f894.png)

I checked the build output with the reference and they seem to be pixel perfect the same. Happened with backstopjs 4.4.2 and 5.1.0

**Comment by garris** [comment]
@valoricDe  Looks like the elements are different sizes.  Take a look at the report -- it tells you what size each image is.  I bet they 1 or 2 pixels off from each other.

**Comment by valoricDe** [comment]
Wow 1px width off. Thank you
