### ISSUE TITLE
Syntax Error: Unexpected token

### ISSUE THREAD

**Issue by mdiasfernandes** [garris/BackstopJS#1278]
When the installation it's made with `npm install -g backstopjs`

And the command `backstop init` it's triggered the following message error it's printed on terminal:
![image](https://user-images.githubusercontent.com/22181846/107577724-85ad5c00-6bd1-11eb-94c9-b7a5bce7442c.png)

Node version: `9.11.2`
NPM version: `6.14.4`

Appreciate any help with this issue. 

Thanks!

**Comment by garris** [comment]
I think you might have to bump your node version.  Try using latest.

**Comment by mdiasfernandes** [comment]
Unfortunately, we're working on this bump and we're not ready yet. I've tried some old versions of backstop but doesn't worked. Do you know what version it's compatible with node `9.11.2`?
