### ISSUE TITLE
When a selector is not available, error " scenario.selectors.join is not a function " is displayed and run aborted.

### ISSUE THREAD

**Issue by sreeram1985** [garris/BackstopJS#1285]
There are multiple scenarios in the script I run and if some selector is not found, then execution abruptly ends with the following error. 

      COMMAND | Command "reference" ended with an error after [40.276s]
      COMMAND | TypeError: scenario.selectors.join is not a function
                    at processScenarioView (c:\Users\..\AppData\Roaming\npm\node_modules\backstopjs\core\util\runPuppet.js:253:151)

Can you help me with this.

**Comment by garris** [comment]
Hi @sreeram1985 -- I have never heard of an issue in this part of the flow -- and I don't think this has changed for a long time.   What versions of backstop and node are you using?

Also,  if it's not too much trouble -- could you put in a breakpoint and tell me what the value of `scenario.selectors` is at...

`backstopjs\core\util\runPuppet.js` line 253

I am guessing it is NULL.   I guess you could set this to an empty array if it fails an array type check.   But I was pretty sure there should already be a check for this in the flow.  

Can you also post a gist of your config?

**Comment by sreeram1985** [comment]
Hi @garris thanks for responding, below are the details:

Backstop v5.1.0
Node v14.15.5

backstopjs\core\util\runPuppet.js line 253: const testPair = engineTools.generateTestPair(config, scenario, viewport, variantOrScenarioLabelSafe, scenarioLabelSafe, 0, `${scenario.selectors.join('__')}`);

My config file is below:
Note that I am intentionally passing the wrong selector here  ( "clickSelector":"#contac-link", ) just to show the error occurred.
{
  "id": "backstop_default",
  "viewports": [
    {
      "label": "Dell",
      "width": 1536,
      "height": 754
    }
  ],
  "onBeforeScript": "puppet/onBefore.js",
  "onReadyScript": "puppet/onReady.js",
  "scenarios": [
    {
      "label": "demo",
      "url": "http://automationpractice.com/index.php",
      "referenceUrl": "http://automationpractice.com/index.php",
	  "delay": 1000,
	  "clickSelector":"#contac-link",
	  "postInteractionWait": 1000,
	  "selectors":"viewport",
    "misMatchThreshold" : 0.0
    }	
  ],
  "paths": {
    "bitmaps_reference": "backstop_data/bitmaps_reference",
    "bitmaps_test": "backstop_data/bitmaps_test",
    "engine_scripts": "backstop_data/engine_scripts",
    "html_report": "backstop_data/html_report",
    "ci_report": "backstop_data/ci_report"
  },
  "report": ["browser"],
  "engine": "puppeteer",
  "engineOptions": {
    "args": ["--no-sandbox"]
  },
  "asyncCaptureLimit": 5,
  "asyncCompareLimit": 50,
  "debug": false,
  "debugWindow": false
}

**Comment by garris** [comment]
Does behavior stay the same if you remove selectors prop?

**Comment by sreeram1985** [comment]
Yes, when the selectors property is removed, scenario.selectors error is not displayed. 

    {
      "label": "demo1",
      "url": "http://automationpractice.com/index.php",
      "referenceUrl": "http://automationpractice.com/index.php",
	  "delay": 1000,
	  **"clickSelector":"#contac-link",
	  "postInteractionWait": 1000,**
	  "misMatchThreshold" : 0.0
    },
    {
      "label": "demo2",
      "url": "http://automationpractice.com/index.php",
      "referenceUrl": "http://automationpractice.com/index.php",
	  "delay": 1000,
	  **"clickSelector":"#contac-link",
	  "selectors":"viewport",
	  "postInteractionWait": 1000,**
	  "misMatchThreshold" : 0.0
    }

____________________________________________________________________
PS S:\Automation\BackstopJS> backstop reference --filter=demo1
BackstopJS v5.1.0
Loading config:  S:\Automation\BackstopJS\backstop.json 

COMMAND | Executing core for "reference"
createBitmaps | Selected 1 of 2 scenarios.
CREATING NEW REFERENCE FILE
Browser Console Log 0: JSHandle:BackstopTools have been installed.
waitFor is deprecated and will be removed in a future release. See https://github.com/puppeteer/puppeteer/issues/6214 for details and how to migrate your code.      
**SCENARIO > demo1**
waitFor is deprecated and will be removed in a future release. See https://github.com/puppeteer/puppeteer/issues/6214 for details and how to migrate your code.      
**Puppeteer encountered an error while running scenario "demo1"
TimeoutError: waiting for selector `#contac-link` failed: timeout 30000ms exceeded**

Run `$ backstop test` to generate diff report.

      COMMAND | Command "reference" ended with an error after [41.904s]
      COMMAND | [object Object]
PS S:\Automation\BackstopJS> backstop reference --filter=demo2
BackstopJS v5.1.0
Loading config:  S:\Automation\BackstopJS\backstop.json 

COMMAND | Executing core for "reference"
createBitmaps | Selected 1 of 2 scenarios.
CREATING NEW REFERENCE FILE
Cookie state restored with: []
Browser Console Log 0: JSHandle:BackstopTools have been installed.
waitFor is deprecated and will be removed in a future release. See https://github.com/puppeteer/puppeteer/issues/6214 for details and how to migrate your code.
**SCENARIO > demo2**
waitFor is deprecated and will be removed in a future release. See https://github.com/puppeteer/puppeteer/issues/6214 for details and how to migrate your code.
**Puppeteer encountered an error while running scenario "demo2"
TimeoutError: waiting for selector `#contac-link` failed: timeout 30000ms exceeded
      COMMAND | Command "reference" ended with an error after [40.907s]
      COMMAND | TypeError: scenario.selectors.join is not a function
                    at processScenarioView (c:\Users\Sreeramachandra\AppData\Roaming\npm\node_modules\backstopjs\core\util\runPuppet.js:253:151)
PS S:\Automation\BackstopJS>**

**Comment by sreeram1985** [comment]
Updated the selectors prop as below:

"selectors":["viewport"] 

And that resolved the problem.

**Comment by sreeram1985** [comment]
Closing this
