### ISSUE TITLE
Possibility to modify initial server-side rendered HTML response

### ISSUE THREAD

**Issue by wattux** [garris/BackstopJS#1292]
The pages I'm testing get delivered by the backend with feature flags information injected. They look something like this:

```html
<body>
....
<script>window.featureflags = {...}</script>
</body>
```

They are set randomly and do have an impact on the design, causing a visual test to fail every now and then (everytime a specific flag value occurs).

I fiddled around a bit with `page.evaluate` calls in `onBefore` / `onReady` scripts to alter the values behind `window.featureflags`, but they seem to run either too early (original `window.featureflags` is not there yet) or too late (app already initialized with backends feature flag values).

Another attempt was to intercept the initial request and modify its response, so that only a deterministic set of flag values appear. But I fail to find a way to modify an intercepted response with `page.on('request', cb)`.

  Any ideas or hints are more than welcomed :)

**Comment by wattux** [comment]
As always, once you wrote / talked about it, you start to make more progress than you have made the last couple of days ^^ 

For reference (and for people that may run into the same issue), here's what worked for me, though this feels very verbose.. Also the Chrome DevTools Protocol docs say, that `Network.setRequestInterception` is [deprecated](https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-setRequestInterception). Got it from a [blog post by Jarrod Overson](https://jarrodoverson.com/post/using-chrome-devtools-protocol-with-puppeteer-737a1300bac0/)

```js
let client = page._client;

await client.send('Network.enable');
await client.send('Network.setRequestInterception', {
    patterns: [
        {
            urlPattern: '*',
            interceptionStage: 'HeadersReceived'
        }
    ]
});

client.on('Network.requestIntercepted', async ({interceptionId, request, responseHeaders, resourceType}) => {
    // We only want the initial HTML request (job-1.0)
    if (interceptionId !== "interception-job-1.0") {
        client.send('Network.continueInterceptedRequest', {interceptionId});
        return;
    }

    const response = await client.send('Network.getResponseBodyForInterception', {interceptionId}),
        contentTypeHeader = Object.keys(responseHeaders).find(k => k.toLowerCase() === 'content-type'),
        bodyData = response.base64Encoded ? atob(response.body) : response.body;

    let contentType = responseHeaders[contentTypeHeader];

    let newBody = bodyData.replace("backend-string", "whatever-I-want-to-be-fixed");
    const newHeaders = [
        'Date: ' + (new Date()).toUTCString(),
        'Connection: closed',
        'Content-Length: ' + newBody.length,
        'Content-Type: ' + contentType
    ];

    client.send('Network.continueInterceptedRequest', {
        interceptionId,
        rawResponse: btoa('HTTP/1.1 200 OK' + '\r\n' + newHeaders.join('\r\n') + '\r\n\r\n' + newBody)
    });
});
```

**Comment by garris** [comment]
This is very nice.  Do you set this up in an onBefore script?   For a while this interception method was buggy in puppeteer -- glad to see its working now and that you were able to bend this content to your will!  Cheers.

**Comment by garris** [comment]
@wattux ^

**Comment by wattux** [comment]
@garris Yes exactly, living in `onBefore`. I hope it keeps working for a while, watching on the deprecation notice.. 

Since my problems are solved, I'd close the issue. Also: Thanks garris for your work on BackstopJS :)
