### ISSUE TITLE
Where do you store your reference binary?

### ISSUE THREAD

**Issue by dodozhang21** [garris/BackstopJS#1322]
It seems git is not the right tool to store tons of binary. It slows down the check out dramatically. 

Has anyone tried to store the reference binary not the same repo as the tests?

**Comment by garris** [comment]
This is a solution that may help -- https://docs.gitlab.com/ee/topics/git/lfs/

Depending on your use case git can work fine.  But for a a lot of large tests you could simply exclude or host in a separate repo or just save to a file server.

**Comment by dodozhang21** [comment]
@garris is there any type of a hook to the lib to store files in s3 bucket? Or what's your recommendation if I want to store them in s3 bucket. What do I need to do to get there?

**Comment by dodozhang21** [comment]
actually, my system friends say GIT LFS is a better fit also. maybe I will look into that more.

**Comment by garris** [comment]
Also, you can change the directory where assets are stored in your config file -- any mounted directory/resource should work.   Hope that helps.

**Comment by dodozhang21** [comment]
@garris i got git LFS to work  thanks
