### ISSUE TITLE
Capture hover state for all buttons display in a page with selectorExpansion and hoverSelector

### ISSUE THREAD

**Issue by patriciamarchand** [garris/BackstopJS#1324]
Hello,
I have a page with several variation of buttons. I want to capture the "hover" state for each of these buttons. My configaration uses the "selectorExpansion" to target all buttons. But only the first one is hover.

Is there a way to capture all buttons in a hover state in the same scenario using the "selectorExpension"? I tried to use an "onready" script but this one only rolls at the beginning.

Thanks!

```
"label": "btn-focus",
 "url": "/pages/button.html",
 "selectors": ["button"],
"selectorExpansion": true,
"hoverSelector": "button",
```

![image](https://user-images.githubusercontent.com/6225238/120236225-c802b380-c229-11eb-8ecd-205b33d2f108.png)

**Comment by garris** [comment]
Unfortunately no.  

selectorExpansion takes multiple snapshots of a single page state and there can only be one active hover state at a time. 

IOW: hoverSelector runs first and then selectorExpansion runs.

**Comment by patriciamarchand** [comment]
thanks!
