### ISSUE TITLE
fileNameTemplate - reason to have viewportIndex in the filename?

### ISSUE THREAD

**Issue by klodoma** [garris/BackstopJS#1345]
Just questioning the reason to have the `viewportIndex` in the filename by **default**. 

The Problem I have is that if the viewports changing(order is changed or something new added in-between) then the whole references are invalid due to the `viewportIndex`. 

https://github.com/garris/BackstopJS#changing-screenshot-filename-formats
```
  fileNameTemplate: '{scenarioIndex}_{scenarioLabel}_{selectorIndex}_{selectorLabel}_{viewportIndex}_{viewportLabel}',
```

![image](https://user-images.githubusercontent.com/944350/127633642-31165057-0842-4565-90a7-625b356d8e84.png)

**Comment by garris** [comment]
This is just an old convention to ensure that reports ordered results related to their positioning the config.  With simple implementations (for most new users) this helps keep behavior predictable.  More advanced users like yourself can simply remove that tag from the template to order things by viewport name.

**Comment by klodoma** [comment]
Thanks for the info. 
Kind of makes sense. 

It's a matter of preference and it's configurable, so all good.
