### ISSUE TITLE
[QUESTION] Workflow with CI

### ISSUE THREAD

**Issue by renanvalentin** [garris/BackstopJS#135]
Hey thanks for the awesome tool!

I would like to know the best way to integrate it with a CI workflow, right now I'm using Travis, so I don't know in which step to put the reference and the test task from backstopjs.

Thanks in advance!

**Comment by garris** [comment]
This sounds like a great article idea!   Unfortunately I have very little experience with Travis so I'd have to dig into it more myself.   Please let me know if you come up with something good.  Maybe someone else will have some ideas...   GS

**Comment by frob** [comment]
Right now the tool is geared around a manual review of the diff results. What would be needed for this is a threshold of failure. I wraith/imagemagick terms this is the fuzz and/or some type of CL only way to checking this. 

The best way to do this would be to give this tool a CL command that can be able to report back a json object with the results.

A quick and dirty way to do this is to have a CL command report back with a return -1 for fail and return 0 for success.

**Comment by klausbayrhammer** [comment]
We are using Backstop heavily with Jenkins and so far it works out really well. Currently we commit the reference images into our VCS and use backstop's CLI reporter to verify our pull requests. To guarantee reproducible results we also use a separat jenkins job to create the reference images because the different rendering processes on different operating systems and rendering engines are quite hard to deal with. In fact the ```{"report": "CLI"}``` was created to address exactly the issue of running backstop in a CI-environment. This would probably be the best hint for you.

HTH Klaus

**Comment by lmakarov** [comment]
> In fact the {"report": "CLI"} was created to address exactly the issue of running backstop in a CI-environment.

The current CLI report is human and not machine oriented.
It is useful for a high level manual review of test results in a terminal, but not so much for CI.

In a CI environment scripts are expected to return a correct status code at the very minimum (0 - pass, 1- something failed).
Ideally, a machine-readable report should be generated, which the CI server can parse and analyze (e.g. a junit XML report).

**Comment by klausbayrhammer** [comment]
@lmakarov you should try the option `cliExitOnFail:true` which returns 0 if a cli-test succeeded and 1 if it failed. @garris we should probably think about making this the default for the CLI-Reporter.

We could also think about adding the actual test-run (like dimensions or misMatchPercentage) to the `compare.json` so it would be machine-readable

**Comment by frob** [comment]
++ making this the default

**Comment by garris** [comment]
:+1: on both.  Seems there is some interest in CI -- we could make this use case more workable out of the box.

We should probably just eliminate the `cliExitOnFail` property (always throw on error) and clean up the error trace that's logged to the console when there is a fail.

**Comment by levithomason** [comment]
>We should probably just eliminate the cliExitOnFail property (always throw on error)

Yes please!

**Comment by levithomason** [comment]
See PR #215 for the fix.
