### ISSUE TITLE
Idea: no-cache meta tag

### ISSUE THREAD

**Issue by conradkirschner** [garris/BackstopJS#1352]
Why? 

I am using github pages to access the report and was wondering why it isn't reloading. 

After I disabled the cache, page got reloaded. 

To avoid such things it might be a idea to disable cache completly? (really not sure) 

``` html
<meta http-equiv="cache-control" content="no-cache"/>
```

@klodoma What do you think?

**Comment by klodoma** [comment]
@conradkirschner yes, it would make sense to use `no-cache` for the report files. 

I think you should use something like this for more browser compatibility:
```
<meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate">
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Expires" content="0">
```

We could make a PR and push it in the master.
