### ISSUE TITLE
Run BackstopJs with : casperFlags: "--ignore-ssl-errors=true"

### ISSUE THREAD

**Issue by fixfoxi3** [garris/BackstopJS#136]
Hallo together, 

for our local https testing we need to add:

 "casperFlags": [
    "--ignore-ssl-errors=true",
    "--ssl-protocol=any"
  ],

to our backstop.json.

But it seems that it`s not working correct. All we get is an empty screenshot in our Result (like it is know from invalid https on phantomJs).

In node_modules/backstopjs/gulp/tasks/test.js:
var casperArgs = tests.concat(args);  
console.log(casperArgs) gives me ["capture/genBitmaps.js"]

When i manuelle change this to: 
casperArgs = ["--ignore-ssl-errors=true", "--ssl-protocol=any", "capture/genBitmaps.js"]
everything works fine for me.

So it seems that casperJs Arguments never will be executed in: 
var casperChild = spawn(casperProcess, casperArgs);

**Comment by fixfoxi3** [comment]
Ps: our Version
"name": "backstopjs",
  "version": "1.0.2",

**Comment by garris** [comment]
ok -- thank you for filing the issue!  

The casper docs specify the script path as the first argument (which is different from your example).  But then perhaps something "interesting" is happening in that spawn call?   I would like to see what is in that casperArgs and compare that with what casper.js is seeing.   The docs also demonstrate how to echo the CLI params when inside of casper.  see here...  http://docs.casperjs.org/en/latest/cli.html

This feature was developed without any tests so it would be nice to get some confidence around it.

I will try to test it out -- please let me know if you find anything in the meantime.

**Comment by garris** [comment]
Ok, found the bug and pushed a fix. 

You were correct -- there was a missing assignment that dropped paths.casperFlags. 

Could you verify that it is working for you now? 

Please pull from master to install... `npm install --save-dev backstopjs`

If it's working for you I will push a patch asap.

Thank you!

**Comment by fixfoxi3** [comment]
i pulled your latest changes:

It`s working now fine ! 
Thank you very much !

**Comment by garris** [comment]
Great!

**Comment by garris** [comment]
Closed by patch 1.0.3
