### ISSUE TITLE
Update puppeteer to v11?

### ISSUE THREAD

**Issue by mayank99** [garris/BackstopJS#1373]
Puppeteer v11 was released a few days ago: https://github.com/puppeteer/puppeteer/releases/tag/v11.0.0

The latest version of BackstopJS (5.4.3) limits puppeteer to v10.

https://github.com/garris/BackstopJS/blob/6a30f1fc0972b2ed020ead256ca2ee1c3ea203c0/package.json#L103

**Comment by garris** [comment]
Thanks for the heads up!    If the tests all work with docker then feel free to bump in a PR.   Cheers!

**Comment by mayank99** [comment]
I am waiting for https://github.com/puppeteer/puppeteer/pull/7764 to be merged before I try to mess with this, as new chromium versions are currently blocked (stuck on chromium v93).
