### ISSUE TITLE
Force device mode

### ISSUE THREAD

**Issue by markanthonyuy** [garris/BackstopJS#138]
Is it possible to force device mode while taking a screenshot?

Here is the scenario, we load different header and footer for mobile and desktop devices. We use a library called "Mobile Detect" https://github.com/serbanghita/Mobile-Detect to conditionally loads the right header and footer for the right type of devices.

Btw Great Tool!

Many Thanks.

**Comment by garris** [comment]
Thanks for posting but unfortunately the short answer is: I don't know...   You may be able to use a custom casper script to set this and then re-open the URL -- but that is just a guess.  

Info on adding custom scripts is here...
https://github.com/garris/BackstopJS#running-custom-casperjs-scripts-version-080

Please post back if you solve this -- there may be others with this issue.   Cheers!

**Comment by markanthonyuy** [comment]
Alright, no problem. I'll post it here once I figure it out. Thanks!

**Comment by vaidotas-adf** [comment]
MobileDetect uses user agent to detect if device is mobile or not. CasperJS has function to set user agent (e.g. https://gist.github.com/iwek/3124720), but it has to be executed before opening URL.
I'd like to suggest adding optional user agent parameter to viewport options. That way we could set mobile UA for small viewports.

**Comment by garris** [comment]
I think you should be able to do this using a custom script.  @timperry used this technique for a similar case...

Create a setUA.js file in the /scripts directory:

```
module.exports = function(casper, scenario, vp) {
  casper.echo("Setting UA");
  casper.then(function(){
    casper.userAgent('Mozilla/5.0 (Macintosh; Intel Mac OS X)');
  });
  casper.thenOpen(scenario.url);
}
```
Then in the scenario add this:
```
    "onReadyScript": "setUA.js"
```

Hope this helps...

**Comment by markanthonyuy** [comment]
@garris @vaidotas-adf Awesome! Works like a charm. 

Thanks you for helping guys.
