### ISSUE TITLE
Report: diff showing fragmented 

### ISSUE THREAD

**Issue by koritzaki** [garris/BackstopJS#1383]
Lately we noticed in our reports that the diff report for a failed test is displayed fragmented like in the below screenshot.
Did anyone see something similar? Is this a new way of displaying the diff or is this an issue?

<img width="349" alt="Screenshot 2022-01-03 at 16 30 23" src="https://user-images.githubusercontent.com/3287262/147949222-d1ec01f1-3186-4379-a374-05472bc65743.png">

**Comment by garris** [comment]
Hi there.  Diffs will look this way if the test image is a different h and/or w dimension from the reference image (even if it is just 1px difference).

**Comment by koritzaki** [comment]
Hi! Thank you for you answer. 
Is there anything we can do to ignore the 1-2px difference? The misMatchThreshold will not help on this.

**Comment by garris** [comment]
To avoid the error you could simply update your reference file so that backstop knows your change is approved.   

If there is a difference between reference and test renderings backstop will report an error.  This is how the app is supposed to work.

**Comment by koritzaki** [comment]
Thank you, we are using backstop in a bit more complex way by comparing lots of pages on various environments so this might not work in our specific case but I understand we will try to find a workaround for our specific case. 
I will close this issue, thanks.
