### ISSUE TITLE
Comparing / Diff a Production URL and a Development URL

### ISSUE THREAD

**Issue by chipcullen** [garris/BackstopJS#140]
First off - great project!

I'm wondering if I'm missing something obvious: what I'm trying to do is do a comparison / diff between two different URLs - a 'production' url (http://www.example.com) and a local 'development' url (http://dev.example.com:8000).

Is there a way to make one scenario your 'reference' and one your 'test'? Or is there a different way to do this?

Thank you for any help!

**Comment by garris** [comment]
@chipcullen hi, thanks for posting!  I have not considered that use case before --  it sounds like something that should be added.   Currently, BackstopJS is built around a single developer on a single URL model.   

That said, the workaround would be pretty easy.   Just set up your scenarios pointing the URLs to your reference and then run  `$ gulp reference`     Then when you want to test, just copy your config file and transform your URLs as needed (in your case, adding `:8000`) and run `$ gulp bless`  then `$ gulp test`  

( `$ gulp bless`  is to let BackstopJS know that you you've deliberately changed your config)

There are more integrated options as well.  You could make your config a node module and enable a dynamic URL based on some enviornment var.  see the docs for more info...

Hope that helps!

**Comment by chipcullen** [comment]
@garris wow - thank you for the *very* fast response! 

Your work around works for now - I'll see if I can make it more dynamic.

As for the use case - I originally had seen it on Wraith - http://bbc-news.github.io/wraith/index.html#Capturemode

BUT, I'm digging an npm based project, which is why I'm trying out backstop. So far it's working great!

Is there anything I could do to help? Would a different, more "feature request" type ticket help?

**Comment by garris** [comment]
Sure, I am trying to be disciplined about adding properties to the config at this point -- keep the complexity low while the project is still manageable.  That said,  I think it's a legitimate feature request.   If you wanted to do a PR I'd support it.  Should be pretty easy to add a `referenceUrl` property to a config scenario and then switch on if we are running a reference or test pass.

Replace this line...
https://github.com/garris/BackstopJS/blob/master/capture/genBitmaps.js#L84

with...
```
var url = scenario.url;
if (isReference && scenario.referenceUrl) {
  url = scenario.referenceUrl;
}
this.thenOpen(url, function() {
```
...

**Comment by garris** [comment]
this is merged to master.  Would appreciate if someone could verify that the feature is working.   Thanks!

**Comment by laubsauger** [comment]
Seems to work (only tested 1 case). Noticed that the scenario.url is used for a few echo calls, e.g. https://github.com/laubsauger/BackstopJS/commit/4b263009ece76eed5a0e17fe357aa668afec9439

**Comment by garris** [comment]
@laubsauger Great catches -- thanks for testing!

@frob Looks like the change is also needed in `capture/echoFiles.js`.  And also here... https://github.com/laubsauger/BackstopJS/commit/4b263009ece76eed5a0e17fe357aa668afec9439

**Comment by chipcullen** [comment]
@garris sorry for radio silence for a few days. Still digging out from under the snow on the east coast. 

The reference/test scheme worked very well for me as well. I had a similar experience as @laubsauger in terms of the echos spouting out the scenario.url.

Thanks for adding this feature so quickly! It's a great enhancement!

**Comment by garris** [comment]
@chipcullen No problem at all -- thanks for the PR.  Cheers

**Comment by michael-tung** [comment]
could you share an scenario example of how to setup the referenceURL vs staging URL in the JSON file with this new feature? (sorry for noob question) 

What are the steps involved?
- setup referenceURL in backstop.json file
- run gulp reference
- run gulp test

obj: compare a page on prod vs staging and find the diff 

I tired setting it up like this but it does not seem to work.

Please help.

"scenarios": [  
      "label": "Reference Page",
      "referenceUrl": "https://referenceurlhere/",
      "hideSelectors": [],
      "removeSelectors": [],
      "selectors": [
        "header",
        "main",
        "footer",
        "body"
      ],
      "readyEvent": null,
      "delay": 1000,
      "misMatchThreshold" : 0.1,
      "onBeforeScript": "onBefore.js",
      "onReadyScript": "onReady.js"
    },
      "label": "Test Page",
      "referenceUrl": "https://testurlhere/",
      "hideSelectors": [],
      "removeSelectors": [],
      "selectors": [
        "header",
        "main",
        "footer",
        "body"
      ],
      "readyEvent": null,
      "delay": 1000,
      "misMatchThreshold" : 0.1,
      "onBeforeScript": "onBefore.js",
      "onReadyScript": "onReady.js"
    }
]....

**Comment by chipcullen** [comment]
@michael-tung _each scenario_ needs a reference and a test url. So, mine look like this:

```
  "scenarios": [
    {
      "label": "Home",
      "url": "https://testurlhere/",
      "referenceUrl": "http://referenceurlhere/",
      "selectors": [
        "body"
      ],
      "readyEvent": null,
      "delay": 1000,
      "misMatchThreshold" : 0.1,
      "onReadyScript": "onReady.js"
    },
    {
      "label": "Foo Page",
      "url": "https://testurlhere/foo",
      "referenceUrl": "http://referenceurlhere/foo",
      "removeSelectors": [],
      "selectors": [
        "body"
      ],
      "readyEvent": null,
      "delay": 3000,
      "misMatchThreshold" : 0.1,
      "onReadyScript": "onReady.js"
    },
   ...
```

Does that make sense?

**Comment by michael-tung** [comment]
Absolutely!! Thanks a bunch!

**Comment by cilefen** [comment]
This is a great feature. Sorry for the noise.
