### ISSUE TITLE
Backstop Test is not run if Backstop Reference fails

### ISSUE THREAD

**Issue by sreeram1985** [garris/BackstopJS#1435]
If I run both Backstop Reference and Backstop Test together, and while executing reference if an error occur for any of the scenarios then Backstop test is not started automatically after reference command is completed.

Ex - **npx backstop reference && npx backstop test**

Is there a way to overcome this?

**Comment by rynodivino** [comment]
Also running into this issue

**Comment by garris** [comment]
I am sure if I understand the question,  but the following should run regardless of any scenario errors...

```
npx backstop reference ; npx backstop test
```

**Comment by sreeram1985** [comment]
Hi @garris 
This resolved the issue that I reported. Thanks a lot :)
