### ISSUE TITLE
BackstopJS Docker Image 6.1.1 uses backstopJS 6.0.4

### ISSUE THREAD

**Issue by HanMas123** [garris/BackstopJS#1437]
Hey guys,

When I run the following command:
```
docker run backstopjs/backstopjs:6.1.1 --version
```
I get `BackstopJS v6.0.4`. Shouldn't this be version `6.1.1` or am I wrong here?

**Comment by garris** [comment]
You should get 6.1.1.  

Might be a deploy issue on the backstop side.

**Comment by edvardsniedre** [comment]
Also getting v6.0.4.

**Comment by garris** [comment]
Yup.  Was a docker file issue.   

fixed by e6cb1f1dd9be271846d6af9d46251a659cc28c6f

<img width="283" alt="image" src="https://user-images.githubusercontent.com/447033/193486451-656f7e93-714c-4f6a-a619-8a666f76f8a9.png">

Apologies for the hassle.
