### ISSUE TITLE
Remote Service

### ISSUE THREAD

**Issue by Merynek** [garris/BackstopJS#1446]
I tried Remote service but immediately after this command: `backstop remote` it display 
![image](https://user-images.githubusercontent.com/6883795/199967802-b367a05c-c698-4228-a4eb-4dc562922cc6.png)
and on http://127.0.0.1:1234/ i cant see anything naturally.

Any idea?

**Comment by martiniert** [comment]
Same problem here using `BACKSTOP_REMOTE_HTTP_PORT=3001 backstop remote` or `backstop remote`

**Comment by Merynek** [comment]
> Same problem here using `BACKSTOP_REMOTE_HTTP_PORT=3001 backstop remote` or `backstop remote`

Totally same :-) I run `backstop remote`

**Comment by martiniert** [comment]
@Merynek it seems to be working with `6.1.3`, fyi

**Comment by garris** [comment]
Uh oh.  Looks like this is broken in 6.1.4.  I will roll this back.

**Comment by dgrebb** [comment]
Was this fixed? I haven't been able to get `remote` working with Node 16, 18, on any port I can think of.

## What's happening

```bash
❯ BACKSTOP_REMOTE_HTTP_PORT=1338 backstop remote --config="backstop.production.json"
BackstopJS v6.2.2
Loading config:  /Users/dgrebb/Projects/backstop/_ci/backstop/backstop.production.json

COMMAND | Executing core for "remote"
 remote | Starting remote with: node /Users/dgrebb/.nvm/versions/node/v16.18.1/lib/node_modules/backstopjs/node_modules/super-simple-web-server/index.js /Users/dgrebb/Projects/backstop/_ci/backstop /Users/dgrebb/.nvm/versions/node/v16.18.1/lib/node_modules/backstopjs/remote --config=/Users/dgrebb/Projects/backstop/_ci/backstop/backstop.production.json with env {"SSWS_HTTP_PORT":"1338"}
 remote | Backstop remote connection closed.
COMMAND | Command "remote" successfully executed in [0.006s]
```

## What I've Tried

- `nvm use 16`
- `sudo BACKSTOP_REMOTE_HTTP_PORT=3001 backstop remote --config="backstop.production.json"`
- `BACKSTOP_REMOTE_HTTP_PORT=1338 backstop remote --config="backstop.production.json"`
- a dozen other ports
- `npm i -g backstopjs`
- downgrading to `backstopjs@6.1.3`
- upgrading to `super-simple-web-server@1.1.4`
- `lsof -i :3001` and other attempted ports — all open

## Side Notes

- I've been using `backstop` for at least five years now — thank you!
- Please consider [turning on the "sponsor" button](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository) for this repo :)

**Comment by dgrebb** [comment]
@garris @Merynek @martiniert submitted a PR for the fix: https://github.com/garris/BackstopJS/pull/1488

**Comment by yuany2036** [comment]
Hey guys, this problems seems to have persisted to some degree, have tried using the remote command with no success, running on version `6.2.2` on macOS Sonoma.
Running it with the command `BACKSTOP_REMOTE_HTTP_PORT=8080 backstop remote --config="backstop.config.js"` results in the same error message:
> I tried Remote service but immediately after this command: `backstop remote` it display ![image](https://user-images.githubusercontent.com/6883795/199967802-b367a05c-c698-4228-a4eb-4dc562922cc6.png) and on http://127.0.0.1:1234/ i cant see anything naturally.
> 
> Any idea?

Was able to get it running when switching over to version `6.1.3`, though no button appears for approving in the web interface. It also runs on my colleagues Windows system, though had to remove the port definition for it to work.
Please let me know if there is any other information I could provide to help troubleshoot this, thanks!
