### ISSUE TITLE
Issues running on 6.2.1 - docker run .. unknown shorthand flag: 'g' in -g)

### ISSUE THREAD

**Issue by klodoma** [garris/BackstopJS#1481]
I wanted to upgrade, but I hit quite some issues. 

Here is the repo I use for testing:
https://github.com/klodoma/backstopjs-debug

OS is windows 11. 

```
yarn install
backstop test --docker
```

```
PS D:\Projects.support\backstop\backstopjs-debug> yarn install
yarn install v1.22.19
warning package.json: No license field
warning backstopjs@1.0.0: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 3.21s.
PS D:\Projects.support\backstop\backstopjs-debug> backstop test --docker
BackstopJS v6.2.1
Loading config:  D:\Projects.support\backstop\backstopjs-debug\backstop.json 

COMMAND | Executing core for "test"
Delegating command to Docker... docker run --rm -it --user $(id -u):$(id -g) --mount type=bind,source="D:\Projects.support\backstop\backstopjs-debug",target=/src backstopjs/backstopjs:6.2.1 test "--moby"
unknown shorthand flag: 'g' in -g)
See 'docker run --help'.
COMMAND | Executing core for "openReport"
openReport | Attempting to ping 
   COMMAND | Command "test" ended with an error after [0.233s]
   COMMAND | Error: docker run --rm -it --user $(id -u):$(id -g) --mount type=bind,source="D:\Projects.support\backstop\backstopjs-debug",target=/src backstopjs/backstopjs:6.2.1 test "--moby" returned 125
                 at ChildProcess.<anonymous> (D:\Projects.support\backstop\backstopjs-debug\node_modules\backstopjs\core\util\runDocker.js:68:18)
                 at ChildProcess.emit (node:events:513:28)
                 at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
openReport | Remote not found. Opening backstop_data\html_report\index.html
```

![image](https://github.com/garris/BackstopJS/assets/944350/a99404e7-e3fc-4f06-84f5-431ee1b5c0d1)

**Comment by garris** [comment]
The default docker command was updated -- you can try using the more generic one...


```
"dockerCommandTemplate": "docker run --rm -it --mount type=bind,source=\"{cwd}\",target=/src backstopjs/backstopjs:{version} {backstopCommand} {args}"
```

**Comment by klodoma** [comment]
> The default docker command was updated -- you can try using the more generic one...
> 
> ```
> "dockerCommandTemplate": "docker run --rm -it --mount type=bind,source=\"{cwd}\",target=/src backstopjs/backstopjs:{version} {backstopCommand} {args}"
> ```

Oh great. This works. 
Thank you for the quick answer! 

I leave this open, maybe will be fixed. If I find some time I'll have a look at the issue myself. 

PS: don't feel sorry :)

**Comment by tkrah** [comment]
@garris People really don't read docs. Btw 6.2.2 @klodoma rolled back the change (because people don't read the docs ... ) and we updated the docs how to use a better template than the default one which is used again now.

**Comment by klodoma** [comment]
> @garris People really don't read docs (like you said ;-) )

If all fails then rtfm or hit it with a bigger hammer :) At least my approach. 

Fun aside, I guess one would just expect to work "out of the box". 

Thanks for the updates, I'll give it a try.

**Comment by tkrah** [comment]
> > @garris People really don't read docs (like you said ;-) )
> 
> If all fails then rtfm or hit it with a bigger hammer :) At least my approach.
> 
> Fun aside, I guess one would just expect to work "out of the box".
> 
> Thanks for the updates, I'll give it a try.

I did work out-of-the-box for mac + linux, you just use(d) the wrong OS ;-)
