### ISSUE TITLE
Remote HTTP service fails on MacOs 13

### ISSUE THREAD

**Issue by KieArm** [garris/BackstopJS#1498]
Creating a demo repo with "backstop init" on Mac and using the command:

BACKSTOP_REMOTE_HTTP_PORT=3000 backstop remote --config=<your config>

On a windows 10/11 machine the server starts and allows the approve function from within the test results.

On Mac OS 13 (Possibly others?) the server starts and then closes.
I tried with and without the --config for the demo test, this did not change the result.

![Screenshot 2023-09-19 at 3 45 18 pm](https://github.com/garris/BackstopJS/assets/87212808/5e9036fd-56af-4d10-b95e-20070ee0e0f4)

**Comment by yuany2036** [comment]
Were you able to resolve this issue? I am having the same problem on my Mac as well.

**Comment by KieArm** [comment]
No sorry I have not resolved this, I was using the latest at the time so that fix would have been included on my side.
I created a minimal demo repo and was able to consistently reproduce the problem.
