### ISSUE TITLE
Show details by default

### ISSUE THREAD

**Issue by mikestreety** [garris/BackstopJS#1519]
Hey, thanks for a great tool :)

I was wondering if you would consider showing all the information by default rather than having it hidden? I appreciate the clean interface, but I didn't notice that the information was hidden until I went to click to copy the file name.

I'm not so confident in getting this spun up to make an MR, but I think the changes would be:

Change [this styling](https://github.com/garris/BackstopJS/blob/b67c169177b303f0621c1998297559adc1e62205/compare/src/components/atoms/TextDetails.js#L32-L39) to

```
display: flex;
flex-wrap: wrap;
```

And then remove [these lines](https://github.com/garris/BackstopJS/blob/b67c169177b303f0621c1998297559adc1e62205/compare/src/components/atoms/TextDetails.js#L91C9-L94) and everything pertaining to `settings.textInfo`

**Comment by dgrebb** [comment]
@mikestreety are you looking for this?

![2024-01-11 08 25 32](https://github.com/garris/BackstopJS/assets/445891/fb4d7288-6183-482e-87ab-c57470686059)

**Comment by mikestreety** [comment]
🤦 Yes. Apparently so. Is there anyway of having this on by default?

**Comment by dgrebb** [comment]
I'm not sure, but it's a great idea for a feature!

**Comment by dgrebb** [comment]
@mikestreety PR #1538 is open for this. If you'd like, have a peek by installing the branch: 

```shell
npm install dgrebb/BackstopJS#feat/1519-suiteInfo-localStorage-hydration
```

Thanks again for the feedback!
