### ISSUE TITLE
Can Backstop be used with a Jekyll site?

### ISSUE THREAD

**Issue by tyleryoungblood** [garris/BackstopJS#152]
I'm trying to get Backstop to work with a Jekyll site I'm building. The gh-pages version can be [found here](http://tyleryoungblood.github.io/resimplifi-site-jekyll/).

If I update my label so that it points to that url (`"label": "http://tyleryoungblood.github.io/resimplifi-site-jekyll/"`) my screenshots show the site without CSS being applied.

I've also tried using `"label": "http://localhost:3000/"` and `"label": "/_site"` and I get the same results (no CSS being applied). 

Any ideas?

**Comment by garris** [comment]
hi,  first, `label` is just for display purposes in your reports so the value would probably be something like "homepage".   The `url` property is where you'd add the actual URL.

Second,  try increasing the delay parameter.  Your CSS may not be loaded when the snapshot is taken.  See testing-spas-and-ajax-content in the readme.
