### ISSUE TITLE
Headless mode: deprecation warning after upgrading 

### ISSUE THREAD

**Issue by fuhlig** [garris/BackstopJS#1525]
After the upgraded Puppeteer dependency with the latest `6.3.1` release, Puppeteer/Chrome throws the following deprecation warning:
![image](https://github.com/garris/BackstopJS/assets/1364116/cc10e616-5682-47f8-80a8-11afc25786ca)

docs:
https://developer.chrome.com/docs/chromium/new-headless?hl=en

While this is documented in the [Backstop docs](https://github.com/garris/BackstopJS?tab=readme-ov-file#setting-puppeteer-and-playwright-option-flags), it might be a better option is setting the headless mode to `new` by default to avoid deprecation warnings (and potential failures in future versions).

**Comment by dgrebb** [comment]
@fuhlig I agree, and know this is planned for a future release. "new" is not new so much anymore ¯\_(ツ)_/¯

I'll look into submitting a PR for the change today.

**Comment by fuhlig** [comment]
Cheers mate

**Comment by dgrebb** [comment]
@fuhlig I just remembered to follow up! This can probably be closed — check out #1535 and `backstop@latest` ([6.3.3](https://www.npmjs.com/package/backstopjs)).

There are some notes in [the PR](https://github.com/garris/BackstopJS/pull/1535) about Playwright to be aware of. We didn't think it was a good idea to default _that_ runner to `'new'` just yet.

Happy new year!

**Comment by fuhlig** [comment]
Awesome, thanks @dgrebb!
Will check it out next week

Have a happy new year!
