### ISSUE TITLE
UI style regression with 6.3.2

### ISSUE THREAD

**Issue by garris** [garris/BackstopJS#1529]
Hey @dgrebb -- any hunches where this issue may have crept in?

<img width="920" alt="image" src="https://github.com/garris/BackstopJS/assets/447033/349f0672-ef14-4526-9f38-7b097207ec4e">

_And FWIW -- it's not lost on me that backstop UI doesn't have any UI Regression tests.  Proof that Irony is not dead.  😄_

**Comment by dgrebb** [comment]
I'll dig into this now.
