### ISSUE TITLE
Multiple Screenshots in a Single Script

### ISSUE THREAD

**Issue by annasesb01** [garris/BackstopJS#1545]
Currently, I am only able to capture one screenshot per engine script and JSON configuration. Is there a way to capture multiple screenshots using a single script?

**Comment by garris** [comment]
Each scenario takes only 1 screenshot at a time.  Most users who ask about this question are looking to test a complex UI flow.  The recommended way to do this is to directly stub the data side of the app (including cookie states) in a scenario so you are not actually testing your application end-to-end, the goal is to test that the UI displays the right thing given the right data.   

Hopefully this makes sense.  Good luck!
