### ISSUE TITLE
Looks like fonts or chrome is breaking the docker build

### ISSUE THREAD

**Issue by garris** [garris/BackstopJS#1546]
Hey @dgrebb  -- if you have a minute -- I tried to publish backstop today but the builds kept hanging on what looked like a failure to install fonts or chrome.  Was wondering if you might have some insight?   Here is the output of that section...

```
> [linux/arm64 2/4] RUN apt-get -qq update >/dev/null && apt-get install -qq   fonts-liberation   xfonts-cyrillic   xfonts-wqy fonts-wqy-zenhei fonts-arphic-ukai fonts-arphic-uming   fonts-ipafont-mincho fonts-ipafont-gothic fonts-ipafont fonts-vlgothic   fonts-unfonts-core fonts-unfonts-extra   fonts-noto-cjk fonts-noto-color-emoji   chromium >/dev/null && apt-get -qq clean >/dev/null && rm -rf /var/lib/apt/lists/*:
38.80 debconf: delaying package configuration, since apt-utils is not installed
267.1 E: Sub-process /usr/bin/dpkg returned an error code (1)
------
Dockerfile:10
--------------------
   9 |     # install chromium and its deps
  10 | >>> RUN apt-get -qq update >/dev/null && apt-get install -qq \
  11 | >>>   fonts-liberation \
  12 | >>>   # cyrillic
  13 | >>>   xfonts-cyrillic \
  14 | >>>   # chinese
  15 | >>>   xfonts-wqy fonts-wqy-zenhei fonts-arphic-ukai fonts-arphic-uming \
  16 | >>>   # japanese
  17 | >>>   fonts-ipafont-mincho fonts-ipafont-gothic fonts-ipafont fonts-vlgothic \
  18 | >>>   # korean
  19 | >>>   fonts-unfonts-core fonts-unfonts-extra \
  20 | >>>   # cjk + emoji font
  21 | >>>   fonts-noto-cjk fonts-noto-color-emoji \
  22 | >>>   # chromium
  23 | >>>   chromium >/dev/null && apt-get -qq clean >/dev/null && rm -rf /var/lib/apt/lists/*
  24 |
--------------------
ERROR: failed to solve: process "/bin/sh -c apt-get -qq update >/dev/null && apt-get install -qq   fonts-liberation   xfonts-cyrillic   xfonts-wqy fonts-wqy-zenhei fonts-arphic-ukai fonts-arphic-uming   fonts-ipafont-mincho fonts-ipafont-gothic fonts-ipafont fonts-vlgothic   fonts-unfonts-core fonts-unfonts-extra   fonts-noto-cjk fonts-noto-color-emoji   chromium >/dev/null && apt-get -qq clean >/dev/null && rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 100

```

**Comment by dgrebb** [comment]
@garris is this in the GitHub Action ([backstop-sanity-docker.yml](https://github.com/garris/BackstopJS/actions/workflows/backstop-sanity-docker.yml)) you mean? Local builds work for me. What does the Action look like that you're running in [these runs](https://github.com/garris/BackstopJS/actions/workflows/backstop-sanity-docker.yml)?

**Comment by dgrebb** [comment]
I'll take a closer look tomorrow, but may be missing context. 

Some observations in the meantime:

In [this run](https://github.com/garris/BackstopJS/actions/runs/7968085240) and [this run](https://github.com/garris/BackstopJS/actions/runs/7967382866), there's an error indicating lines [38](https://github.com/garris/BackstopJS/blob/master/.github/workflows/backstop-sanity-docker.yml#L38) and [41](https://github.com/garris/BackstopJS/blob/master/.github/workflows/backstop-sanity-docker.yml#L41) of `backstop-sanity-docker.yml` can't both exist on the same step. I think we may want the "`with`", as opposed to the "`run`", in this case.

In the downstream `[docker-build.yml](https://github.com/garris/BackstopJS/blob/master/.github/workflows/docker-build.yml)` action, [builds are working](https://github.com/dgrebb/BackstopJS/actions/runs/7968174550/job/21752020436), but [publishing to GHCR](https://github.com/dgrebb/BackstopJS/pkgs/container/backstopjs/180956620?tag=bugfix-1546-chrome-docker-build-broken). Perhaps there's something in [that workflow](https://github.com/garris/BackstopJS/blob/master/.github/workflows/docker-build.yml) which could help?

We'll get to the bottom of this!

**Comment by garris** [comment]
Thanks @dgrebb for taking a look!  This happens locally in the terminal when I `npm run build-and-publish`.    Even when commenting out the apt-get install stuff staring on line 10 -- the docker build still fails later on when trying to install backstop.

<img width="779" alt="image" src="https://github.com/garris/BackstopJS/assets/447033/53ffcf9c-b59d-4389-b670-e949b86f2e45">
 

So unfortunately -- publishing to dockerhub is broken 😭

**Comment by dgrebb** [comment]
@garris it definitely looks like something is up with `backstopbuilder`.

Did you already give something like this a go?

1. `docker buildx create --name newbackstopbuilder --platform linux/amd64,linux/arm64`
2. `docker buildx use newbackstopbuilder`
3. `npm run build-and-publish`

And see that `buildx` is reflecting a newly created builder?

```shell
6.3.6           
[+] Building 9.8s (6/14)              docker-container:newbackstopbuilder
```

I've successfully published from a `master` branch [on npm](https://www.npmjs.com/package/downstream_dgrebb_backstopjs/v/6.3.6) and [Docker Hub](https://hub.docker.com/repository/docker/dgrebb/downstream_backstopjs/tags?page=1&ordering=last_updated). 

Here's the branch [diffed with `master`](https://github.com/garris/BackstopJS/compare/master...dgrebb:BackstopJS:bugfix/1546-chrome-docker-build-broken?expand=1), which yielded the above, after changing the package and image names.

**Comment by garris** [comment]
Wow -- that is a great idea!   Will totally do that!   I will try when I get home or tomorrow AM before the chaos ensues!  Will LYK soon.   Cheers!

**Comment by dgrebb** [comment]
@garris I wrote a new workflow to build and push to Docker Hub via GitHub Actions as well, in [`dockerhub-build-push.yml`](https://github.com/dgrebb/BackstopJS/blob/bugfix/1546-chrome-docker-build-broken/.github/workflows/dockerhub-build-push.yml), downstream. 

If the host machine issues continue, maybe that will help get 6.3.6 out the door. It requires setting up a Docker Hub PAT and some GitHub Actions secrets, which we could work through. The tag is also set to the current branch name right now, for illustration.

GitHub's docker build runners are _fast_! [~8 minutes](https://github.com/dgrebb/BackstopJS/actions/runs/7983183800) for a [multi-architecture build](https://hub.docker.com/layers/dgrebb/downstream_backstopjs/bugfix-1546-chrome-docker-build-broken/images/sha256-f49157a9ce48cf577b2921568ddca51cce2797fded4daa4e289a858be7ea3ab9?context=explore).

**Comment by garris** [comment]
That's awesome would be nice to automate this. Hopefully, minting a new builder will get us over the immediate issue.  Will follow up as soon as I can.

**Comment by garris** [comment]
@dgrebb  Ok quick follow up.  No dice on the new builder.

<img width="777" alt="image" src="https://github.com/garris/BackstopJS/assets/447033/450d59d3-cf06-4cde-9a4c-40a886181754">

New builder -- same fail...
<img width="778" alt="image" src="https://github.com/garris/BackstopJS/assets/447033/e3eaacb3-4958-4e96-b77f-86227924529c">

But this error is closer to the real problem...
<img width="781" alt="image" src="https://github.com/garris/BackstopJS/assets/447033/b24c5d47-75a3-44d4-a42d-6d419a23e21a">

I guess I should install in debug mode to see what is really going on.  Will try that tomorrow.   Cheers.

**Comment by garris** [comment]
I am wondering if docker is caching anything locally -- maybe something to do with chrome?

**Comment by dgrebb** [comment]
What version of Docker is running? Does it need to be updated? For me:

```shell
❯ docker --version
Docker version 25.0.3, build 4debf41
```

Maybe try this first from project root directory, eliminating cache from the equation:

- `docker buildx build --no-cache --platform linux/amd64,linux/arm64 -t dgrebb/downstream_backstopjs:6.3.6 docker`

No? Why don't we go ahead and [burn Docker to the ground](https://gist.github.com/dgrebb/3d4063ed75e6cbbb3fa72fae1381a687).

Then try `npm run build-docker`, or the first command?

**Comment by garris** [comment]
@dgrebb    Thanks for the support man!  I have the same exact version.   I am going to try to spit out the build transcript to the terminal to see if I can learn anything.  When that doesn't work -- I am totally burning docker to the ground 🔥     Wish me luck!   🕳️

**Comment by garris** [comment]
Well.  just for the record -- I saw this error.  But now I am going to burn this thing down.

```
179.4 qemu: uncaught target signal 11 (Segmentation fault) - core dumped
179.4 Segmentation fault
179.4 qemu: uncaught target signal 11 (Segmentation fault) - core dumped
179.4 Segmentation fault
179.4 dpkg: error processing package libc-bin (--configure):
179.4  installed libc-bin package post-installation script subprocess returned error exit status 139
...
185.5 Errors were encountered while processing:
185.5  libc-bin
185.6 E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by garris** [comment]
uh oh. it's the linux/arm64 build that causes the issue. 😭 

@dgrebb -- what hardware are you using?   Apple Silicon or Intel Mac?

**Comment by dgrebb** [comment]
@garris I'm on an M1. I'll put in a proper PR for that docker build / push to hub action.

**Comment by dgrebb** [comment]
@garris FYA the latest changes to `Dockerfile` in `master` fail to build regardless of previous issues.

**Comment by dgrebb** [comment]
@garris as mentioned over in #1550, puppeteer needs to be bumped, and a new version of backstopjs needs to be published to npm, before we can continue...

Now that puppeteer can't find Chrome, this is a hard-stop in any additional testing. Both backstop itself as well as Docker are impacted.

**Comment by garris** [comment]
@dgrebb puppeteer is bumped and a new version is pushed to npm.

So, we're back to -- building for `linux/amd64` works.  building for `linux/arm64` barfs.  I have a sinking feeling I need to run this on my kid's mac mini to test out if buildx no longer builds multiplatform on intel macs.  

That is where I am.  Will follow up.   Thanks!

**Comment by dgrebb** [comment]
@garris GitHub Workflow is ready in #1551.

[AMD](https://github.com/dgrebb/BackstopJS/actions/runs/8012164310/job/21886901809#step:8:1198) and [ARM](https://github.com/dgrebb/BackstopJS/actions/runs/8012164310/job/21886901809#step:8:2232) are succeeding, prior to the action failing to push to Docker Hub (account permission).

Instructions in the PR for setting up secrets to auth with Docker Hub.

Good luck!

**Comment by garris** [comment]
@dgrebb The new Github Workflow is amazing!  6.3.14 is pushed out to npm & dockerhub!   Cheers!!  🚀
