### ISSUE TITLE
Will there be a tagged version on Dockerhub for version 6.3.6?

### ISSUE THREAD

**Issue by davidcmoulton** [garris/BackstopJS#1549]
Looking on Dockerhub, the latest image seems to be for version 6.3.3 from 2 months ago.

**Comment by garris** [comment]
Yes, as soon as possible.  Ran into an issue last night, https://github.com/garris/BackstopJS/issues/1546 -- docker builds are broken and didn't have enough time to troubleshoot it.  

If anyone is able to repo and fix a patch would greatly be appreciated!

**Comment by garris** [comment]
fixed w/ backstopjs@6.3.14
