### ISSUE TITLE
`scenario.misMatchThreshold` is ignored

### ISSUE THREAD

**Issue by gruberro** [garris/BackstopJS#1555]
Since using BackstopJS `>=6.3.19` all scenarios using a custom `misMatchThreshold` are ignoring this configuration value. I may be wrong @dgrebb, but IMHO https://github.com/garris/BackstopJS/pull/1539/files#diff-60b20548efe794ef5ed3fb10ae1b2d2fbf9ad3786e7c69d86da083c1b9cd9782R9 introduced this problem by looking for `misMatchThresholdconfig` instead of `misMatchThreshold` 😄.

**Comment by dgrebb** [comment]
Thank you @gruberro for finding this — submitted  #1556 to fix.

**Comment by gruberro** [comment]
> Thank you @gruberro for finding this — submitted #1556 to fix.

Thank you for the immediate fix!
