### ISSUE TITLE
Failed to launch the browser process when running inside of docker container

### ISSUE THREAD

**Issue by erkannt** [garris/BackstopJS#1560]
We are currently stuck on version 6.2.2 of BackstopJS.

In versions since 6.3.3 it fails with the following error.

```
COMMAND | Executing core for "test"
createBitmaps | Selected 27 of 27 scenarios.
      COMMAND | Command "test" ended with an error after [1.623s]
      COMMAND | Error: Failed to launch the browser process!
                chrome_crashpad_handler: --database is required
                Try 'chrome_crashpad_handler --help' for more information.
                [23:23:0307/073746.668667:ERROR:socket.cc(120)] recvmsg: Connection reset by peer (104)
                
                
                TROUBLESHOOTING: https://pptr.dev/troubleshooting
                
                    at Interface.onClose (/usr/local/lib/node_modules/backstopjs/node_modules/@puppeteer/browsers/lib/cjs/launch.js:267:24)
                    at Interface.emit (node:events:530:35)
                    at Interface.close (node:internal/readline/interface:527:10)
                    at Socket.onend (node:internal/readline/interface:253:10)
                    at Socket.emit (node:events:530:35)
                    at endReadableNT (node:internal/streams/readable:1696:12)
                    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
COMMAND | Executing core for "openReport"
openReport | Attempting to ping 
   COMMAND | Command "test" ended with an error after [42.454s]
   COMMAND | Error: docker run --rm -i --user $(id -u):$(id -g) --network sciety-test_default --mount type=bind,source="/home/runner/work/sciety/sciety",target=/src backstopjs/backstopjs:6.3.23 test "--moby" "--filter=" returned 1
```

[Our config](https://github.com/sciety/sciety/blob/main/backstop.json)
[How we run it in Github Actions](https://github.com/sciety/sciety/blob/main/.github/workflows/ci.yml)

**Comment by garris** [comment]
Hey @erkannt I'm sorry this isn't working for you.   The 6.3.23 docker sanity test is working for me locally.   Could you maybe try to isolate this a bit?   

There were a few changes to the docker file since 6.2.2...
<img width="1793" alt="image" src="https://github.com/garris/BackstopJS/assets/447033/693e67b2-c8db-4deb-9cbb-9afd6f5f04bb">

And also puppeteer was bumped (among others)
<img width="1188" alt="image" src="https://github.com/garris/BackstopJS/assets/447033/68bea91b-6202-430c-b9fa-109b5dadc1cb">

Does reverting either of these provide any insight?

**Comment by erkannt** [comment]
Thanks for the pointer to the docker sanity test. We'll do our best to narrow this down. What we have done so far:

- can't reproduce the issue on our local machines (Void Linux and Mac OS)
- bumping our GH Actions runner image from ubuntu-20.04 to ubuntu-22.04 to match the backstopjs CI does not fix the issue

We have noticed that the [docker sanity test runs backstopjs fully inside the container](https://github.com/garris/BackstopJS/blob/6d0e5fe42e15f6fe8468dced56087bf6d29cbbba/.github/workflows/docker-sanity-test.yml#L67), however [we run backstopjs outside of docker](https://github.com/sciety/sciety/blob/3752ee0caa0b280a396dd0d7ebd2347d2d74238d/Makefile#L102) using the `--docker` flag and a [custom](https://github.com/sciety/sciety/blob/3752ee0caa0b280a396dd0d7ebd2347d2d74238d/backstop.json#L223) `dockerCommandTemplate`.

We will continue investigating as we find time. If you have any other pointers they are much appreciated.

**Comment by erkannt** [comment]
Looks like it was a change to the Docker container. We had copied and adjusted the default `dockerCommandTemplate` prior to https://github.com/garris/BackstopJS/commit/629a8ab373614c13a938416c203cc37ddcd14769. Removing `--user $(id -u):$(id -g)` from our `dockerCommandTemplate` seems to fix the issue.
