### ISSUE TITLE
How to get full page screen shot ?

### ISSUE THREAD

**Issue by mirzazeyrek** [garris/BackstopJS#157]
Is there a way to get full page screen shots with the specified resolution ?  

I'm looking for something like this:

http://postimg.org/image/5wyfcho1b/

**Comment by mirzazeyrek** [comment]
It was because of the pages it self. Issue is solved now.

**Comment by ryami333** [comment]
Hey @mirzazeyrek I'm interested in hearing how you achieved this?

**Comment by mirzazeyrek** [comment]
@ryami333 as far as I remember it was adding body tag to the selectors.
