### ISSUE TITLE
Thank you ! What a nice tools this is.

### ISSUE THREAD

**Issue by megane9988** [garris/BackstopJS#1570]
When I update CMS on the website, I always use it for testing.
This is not an issue. But I want to say thank you for maintaining it.

I posted the article today. 

How can we capture sites that use scrolling animations?
https://snippet.m-g-n.me/2024/05/20/928

**Comment by garris** [comment]
Thank you very much for your kind words! 💜 

Also, thank you for sharing your technique for scroll testing -- I am sure this will be helpful for others.   Cheers!
