### ISSUE TITLE
Backstop running on GH – the tests are not passing, because of difference on text rendering

### ISSUE THREAD

**Issue by paschalidi** [garris/BackstopJS#1572]
Hey, thank you for working on this very helpful project, once again 🙇 

I am running my tests on gh actions with a simple setup.
Upon failure I am deploying the html_report on surge, to help the developer see what is wrong.

At the moment everything works but the tests wont pass due to some difference in text rendering, see this surge deployment: https://ever-visual-regression-refs-pull-190-merge.surge.sh/

I didnt find any good way to avoid that, and the tests would never fail when I run them locally 🤔 

Anyone who faced this before perhaps?

**Comment by garris** [comment]
Different OS+Hardware combinations render text differently.   The usual solution for this is to use the Docker option.

**Comment by paschalidi** [comment]
Right thank you garris for all the good work on this project 🙇

**Comment by paschalidi** [comment]
2
