### ISSUE TITLE
Puppeteer 21.3.2 brings breaking change

### ISSUE THREAD

**Issue by r-oldenburg** [garris/BackstopJS#1577]
Hi there,

first of all: 
BackstopJS is a GREAT Tool! Great project. Love it.

Now on to my problem: 
After several rounds of try-and-error I found that beginning with BackstopJS 6.3.7 and its dependency puppeteer >=21.3.2 there is a breaking change on the `page/element.screenshot(...)` method. 

Several of our test cases started failing, because elements could not be screenshotted (error message "Error capturing Element") or even worse the screenshot call would be stuck until its timeout (i.e. 45 seconds). It would then list an untyped error and proceed with the next scenario. (Using debug logging I could find the original message, saying that making a screenshot with the width 0 is not allowed/possible).

Admittedly all these failing cases were selectors referring to slider elements that often have negative offsets (slided out of the viewport) which may not be the originally intended usage. But it worked for years now. 

The new code in puppeteer introduces a method `getIntersectionRect` which cuts off negative offsets. (See https://github.com/puppeteer/puppeteer/pull/10992/files#diff-53eb4c597328f5c5190375bec9e69b10c37a36c699d186b5cef48cfb610e4f8aR1061) 

You can also see in the MR that setting `captureBeyondViewport` to `true` would solve the issue, but that does not (yet) happen in BS ([BackstopJS/core/util/runPuppet.js, line 426ff](https://github.com/garris/BackstopJS/blob/944884bcd785a3cd0715a90371eb39a62855ec58/core/util/runPuppet.js#L428), sets `captureBeyondViewport` to `false`). Unfortunately even setting it to `true` does not solve all the failures and that is because in the puppeteer code `screenshot()` on ElementHandle (as opposed to Page) it does explicitly set `captureBeyondViewport: false` again (see https://github.com/puppeteer/puppeteer/blob/01c33e81777f173b1d5b51abad216bbdde24e0a4/packages/puppeteer-core/src/api/ElementHandle.ts#L1375). 

So pinning the dependency back to 21.3.0 does solve that issue for now (obviously). The latest puppeteer code again does it all completely different, so my next test will be to pin to that version.

Any ideas? Are we using BS incorrectly? I will report on my tries with latest puppeteer.

**Comment by r-oldenburg** [comment]
Latest puppeteer version (22.13.1) also makes BS fail with "Error capturing Element"

**Comment by garris** [comment]
Hi there @r-oldenburg -- thank you so much for this thoughtful root cause analysis.   So, just to make sure I am understanding the problem -- there are 2 blockers when trying to capture offscreen elements (or is this just sliders?)
Blocker 1)  happens when BS invokes puppeteer, setting offscreen to false 
Blocker 2) something similar in puppeteer code

Am I grasping this right?

**Comment by r-oldenburg** [comment]
@garris Thank you so much for responding that quickly!

I have to apologize. Actually by now I was able to get it all running again. Mostly by fixing our test cases. I was even able to get our (meanwhile) 1444 tests working again with BS 6.3.7 and the latest(!) puppeteer Version 22.13.1.

Just shortly: `headless: "shell"` was an important necessary change. Also using the write selectors and setting correct viewport sizes. And it all works again.
YAY. Will write the details later.

**Comment by garris** [comment]
Ok great to hear.  Would love to merge the solution since it would probably be helpful to other users. Please post if you can.

Cheers!

**Comment by r-oldenburg** [comment]
> Would love to merge the solution
Well... actually there is nothing that needs to be changed in your code. 

I did the following in our client code:
-  replace `page.waitForTimeout` (see https://github.com/puppeteer/puppeteer/pull/11780) with this:
`await new Promise(r => setTimeout(r, clickSelectorInterval))`
- not use "delay" (as it is discouraged anyway)
- patch the selectors for the slider element (selecting the *active* slide -> no negative offsets any more)
- Add this to the `engineOptions` in the configuration:
`"headless": "shell",`

With all that in place the current referenced puppeteer 21.11.0 as well as the latest 22.13.1 are working fine for us.

**Comment by r-oldenburg** [comment]
Sorry again for the noise
