### ISSUE TITLE
Node 22 support

### ISSUE THREAD

**Issue by atomicrobokid** [garris/BackstopJS#1581]
Engine is restricted to 
`"node": ">=16.0.0 <=20.x.x",`

Any reason why this can't be bumped to include Node 22? I have a project that is node 22 based, and this package throws a warning

**Comment by dgrebb** [comment]
If I remember correctly something in `21` brought a breaking error, but I'll take another look.

**Comment by dgrebb** [comment]
Raised #1582 for this @atomicrobokid @garris.

I have no idea what I was thinking with `<=20.x.x`. All tests, minus one which I've commented on elsewhere, are passing.

Docker intact as well.

**Comment by garris** [comment]
Awesome!  Happy to pull in the bump.  I'll follow up on the file extension warning in the other thread.  I don't mind reverting that if it's causing a stir.
