### ISSUE TITLE
update gulpfile.js

### ISSUE THREAD

**Issue by fvena** [garris/BackstopJS#16]
gulp.run() has been deprecated. Use task dependencies or gulp.watch task triggering instead.

...

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)

**Comment by garris** [comment]
Hi fvena,   This error is usually caused by a dependency issue.   Can you verify that Phantom and Casper are installed correctly?

    $ phantomjs -v
    > 1.9.8

and

    $ casperjs --version
    > 1.1.0-beta3

**Comment by fvena** [comment]
Yes, I have those versions, but get the following message:

$ phantomjs -v
> 1.9.8

$ casperjs --version
>1.1.0-beta3
> Unsafe JavaScript attempt to access frame with URL about:blank from frame with URL file:///Users/fvena/.node/lib/node_modules/casperjs/bin/bootstrap.js. Domains, protocols and ports must match.

**Comment by garris** [comment]
Ok.  3 requests...

Can you try running `gulp genConfig` and post the full output.

Can you post the <root>/backstop.json file as well.

And also, please post the full output for `gulp reference`.

**Comment by fvena** [comment]
$ gulp genConfig

> Using gulpfile ~/Sites/temp/myCoolProject/bower_components/backstopjs/gulpfile.js
> Starting 'genConfig'...
> Finished 'genConfig' after 16 ms

backstop.json

```
{
	"viewports" : [
		{
		 "name": "phone",
		 "viewport": {"width": 320, "height": 480}
		}
		,{
		 "name": "tablet_v",
		 "viewport": {"width": 568, "height": 1024}
		}
		,{
		 "name": "tablet_h",
		 "viewport": {"width": 1024, "height": 768}
		}
	]
	,"grabConfigs" : [
		{
			"testName":"http://getbootstrap.com"
			,"url":"http://getbootstrap.com"
			,"hideSelectors": [
			]
			,"removeSelectors": [
				"#carbonads-container"
			]
			,"selectors":[
				"header"
				,"main"
				,"body .bs-docs-featurette:nth-of-type(1)"
				,"body .bs-docs-featurette:nth-of-type(2)"
				,"footer"
				,"body"
			]
		}
	]
}

$ gulp reference

```
Using gulpfile ~/Sites/temp/myCoolProject/bower_components/backstopjs/gulpfile.js
Starting 'clean'...
bitmaps_reference was cleaned.
Starting 'bless'...
Finished 'clean' after 12 ms
Finished 'bless' after 17 ms
Starting 'reference'...
gulp.run() has been deprecated. Use task dependencies or gulp.watch task triggering instead.
Starting 'init'...

BackstopJS needs to update bower_components, please hang on...

Finished 'init' after 4.56 ms
Starting 'test'...

Generating reference files.

Finished 'test' after 2.24 ms
reference has run.
Finished 'reference' after 8.12 ms

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)

**Comment by garris** [comment]
Thanks for that.  It looks like node is not able to spawn out Casper or Phantom.  What OS are you on?   

Just to test this, you could add this log stmt at line 199 of gulpfile.js...

    console.log( 'Ready to run ' + tests + ' with ' + casperProcess + '.' )

![image](https://cloud.githubusercontent.com/assets/447033/5621758/12c244c8-94ee-11e4-9b30-0ea6b2dd4d0d.png)

**Comment by fvena** [comment]
Thank you very much for your help, my OS is OSX Yosemite 10.10.1, this is what I get:

```
Ready to run capture/genBitmaps.js with casperjs.
