### ISSUE TITLE
Folders, Images and compare.json are getting duplicated

### ISSUE THREAD

**Issue by laubsauger** [garris/BackstopJS#160]
I just noticed that the folders `bitmap_reference` and `bitmaps_test` (and the contained images) are getting duplicated while `gulp test` is running.

At first they are created at the location specified in backstop.json. But as soon as the `compare` step starts they'll get copied or created again right next to the `gulp` folder. 

Of course this is more of a cosmetic issue.

Somebody saw this? Any ideas what's causing this?

See:
![image](https://cloud.githubusercontent.com/assets/1301310/13001528/2ebcd5b0-d167-11e5-8483-670563bea298.png)

**Comment by garris** [comment]
This is by design.  File resources are cached locally so that the report host has guranteed access to the files when tests are run.

**Comment by laubsauger** [comment]
Uh, guess that makes sense. Thanks for clearing it up.
