### ISSUE TITLE
Several actions in one viewport?

### ISSUE THREAD

**Issue by Grafs** [garris/BackstopJS#167]
Example:
1. Load url in viewport 360x480
1.1. Run scenario 1 for this viewport:
1.1.1. Click element > show element > create selector screenshot > click hide element
1.1.2. Click 2 element > show 2 element > create selector screenshot > click hide 2 element
1.1.3. Click 3 element > show 3 element > create selector screenshot > click hide 3 element
1.1.4. ...
2. Load url in viewport 768x1024
2.1. Run scenario 2 for this viewport:
2.1.1. Click element > show element > create selector screenshot > click hide element
2.1.2. Click 2 element > show 2 element > create selector screenshot > click hide 2 element
2.1.3. Click 3 element > show 3 element > create selector screenshot > click hide 3 element
2.1.4. ...
How for the one URL a few events and screenshots?

**Comment by garris** [comment]
I'd suggest doing something like:

Set up your viewports with each of your window sizes and then, create 1.1.1, 1.1.2 &  1.1.3 as separate scenarios.   for each scenario, use a custom script to click your element.  You can even use the same script for all scenarios and just trigger different button click behavior based on the scenario names.  There is probably then no need to hide your elements since the next scenario will reload and start fresh.

Please let me know if that works for you.  I am curious to see how you solve this.

Thanks

**Comment by Grafs** [comment]
I understand, but it is not convenient.
For every action you need to reload the page.
I have tried to do so:
```
module.exports = function(casper, scenario, vp) {
	  casper.click('#elem1_show');
          casper.wait(2000);
          casper.captureSelector('../../backstop_data/bitmaps_reference/elem1.png', '#elem1_show');
         casper.click('#elem1_hide');
	  casper.click('#elem2_show');
          casper.wait(2000);
          casper.captureSelector('../../backstop_data/bitmaps_reference/elem2.png', '#elem2_show');
         casper.click('#elem2_hide');
}
```
But the result is not written in the compare.json
You can make a recording function in compare.json from the casper scenario?

**Comment by garris** [comment]
I am curious why a page refresh is an issue for your use case?  Are there side-effects from your element clicks that you are trying to capture?

**Comment by Grafs** [comment]
For example:
viewport w-320
    click>show and captur hidden element 1 only
viewport w-768
    click>show and captur hidden element 2 only
viewport w-1024
    click>show and captur hidden element 3 only

---------------------
```
  "viewports": [
    {
      "name": "phone",
      "width": 320,
      "height": 12000
    },
    {
      "name": "tablet",
      "width": 768,
      "height": 8000
    },
    {
      "name": "desctop",
      "width": 1280,
      "height": 6000
    }
  ],
  "scenarios": [
    {
      "label": "http://example.com",
      "url": "http://example.com",
      "selectors": ["#element1","#element2","#element3"],
      "readyEvent": null,
      "delay": 1000,
      "misMatchThreshold" : 0.001,
      "onReadyScript": "elementTest.js"
    },
---------------------------------------------------
elementTest.js:
module.exports = function(casper, scenario, vp) {
  if (vp.name === 'phone') {
	  casper.click( '#element1' );
  }else if(vp.name === 'tablet'){
	  casper.click( '#element2' );
  }else if(vp.name === 'desctop'){
	  casper.click( '#element3' );
  }
}
```
---------------------
How many images? = 9, of these 6 empty end 9 page refresh
It is better to make a function in scenario for module.exports to capture intermediate images

**Comment by garris** [comment]
It appears your use case has changed.  From your initial example to your last example.  Is this deliberate or is this a typo?  Changing the scenario on me will make it difficult to help you.   If you only want 3 comparisons which all use different viewports then you must use 3 different config files.
