### ISSUE TITLE
refactor

### ISSUE THREAD

**Issue by peter-mouland** [garris/BackstopJS#17]
hey,

I've found your repo and it looks very interesting... almost what i need :)

I know at the moment there are no test, probably because testing gulp tasks is hard, but if i propose a refactor how likely is a pull-request going to accepted?  I ask because the last pull request is sitting still.

I think it makes sense to pull out as much code as possible into an index.js to allow people require this like a node module and exposing an API.  the gulp file would then also require this file keeping it backward compatible.  

A second pull request would be to make the configuration to be slightly more flexible and I propose a change to allow the user to choose where to save the screenshots i.e. not within bower_components.  

The final thing would be to enhance the tasks to respond with exit code depending on if there was an error or not.  Hopefully this could also be applied to the comparison tool too.

We need these things are about to start the work anyway i was just wondering how likely you are to accept these changes considering there are no tests yet?

thanks!

**Comment by garris** [comment]
I can tell from your wish list that we are on the same page.  All this stuff makes total sense. Even without tests I am really happy to pull this stuff in -- it's worth the short term regression risk.   I would also add that I've gotten a lot of feedback on adding a ready event listener to the config -- e.g. a developer could emit a 'myAppIsReady' event on the body or in the console and BackstopJS would wait to test until that event is fired.  This would really be easy to implement in Casper.

From the feedback I am getting I know the changes you're proposing, in addition to the ready event would create a lot of happiness.   


Please do it and request the pull -- let me know if you need any support!

**Comment by garris** [comment]
if you do go ahead with the changes -- I would just suggest you set the *default* reference directory location to be in parallel with the backstop.json file.  It would simplify the on-boarding process for new users.

**Comment by garris** [comment]
Hey Peter,  I just wanted to check in with you.  There has been considerable work done on BackstopJS: updating to an all-NPM install, simplifying the config files, adding custom screenshot events and cleaning up some of the underlying Gulp code.   One of the next items would be the customizable screenshot location -- this is one of the items you had proposed above.   

I wanted to see if you had gotten anywhere with that or if you still had any intentions of doing so.   Please let me know.   Best regards.  GS

**Comment by peter-mouland** [comment]
I went a slightly different direction and built this: https://github.com/skyglobal/Sheut

relies on node-canvas and is pain having to install cario...

**Comment by garris** [comment]
Looks like it's all server side -- that's cool.  Alright then, best of luck with it.    Take care.   GS
