### ISSUE TITLE
Windows: Testing script failure with "the system can not find the path specified" console error.

### ISSUE THREAD

**Issue by benjaminfisher** [garris/BackstopJS#171]
I'm following the steps laid out in https://css-tricks.com/automating-css-regression-testing/

Attempting to run this on a Windows 7 Enterprise SP1 box. Both the reference gulp task (which is generating reference image files) and the test gulp task are throwing `Testing script failed with code: 1` and the test page is not launching in the browser.

Here is the output from `gulp test`
```
C:\Users\bfisher1\Documents\development\myCoolProject\bower_components\BackstopJS>gulp test

BackstopJS Config loaded at location C:\Users\bfisher1\Documents\development\myCoolProject\backstop.json
[15:27:31] Using gulpfile ~\Documents\development\myCoolProject\bower_components\BackstopJS\gulpfile.js
[15:27:31] Starting 'init'...
[15:27:31] Finished 'init' after 82 μs
[15:27:31] Starting 'test'...

Running CasperJS with:  [ 'capture/genBitmaps.js' ]
The system cannot find the path specified.
The system cannot find the path specified.
[15:27:31] Finished 'test' after 233 ms
Ready event received.
CasperJS: Ready event received.
Current location is ../../index.html
CasperJS: Current location is ../../index.html
Screenshots for phone (320x480)
CasperJS: Screenshots for phone (320x480)
Ready event received.
CasperJS: Ready event received.
Current location is ../../index.html
CasperJS: Current location is ../../index.html
Screenshots for tablet_v (568x1024)
CasperJS: Screenshots for tablet_v (568x1024)
Ready event received.
CasperJS: Ready event received.
Current location is ../../index.html
CasperJS: Current location is ../../index.html
Screenshots for tablet_h (1024x768)
CasperJS: Screenshots for tablet_h (1024x768)
Comparison config file updated.
CasperJS: Comparison config file updated.

Testing script failed with code: 1

Looks like an error occured. You may want to try running `$ gulp echo`. This will echo the requested test URL output to the console. You can check this output to verify that the file requested is indeed being received in the expected format.
```

**Comment by garris** [comment]
@benjaminfisher thanks for posting.  Just earlier today I resubmitted a long-overdue update to that article -- which is woefully out-of-date.  My guess is that the new article will be live in a week or so.  

In any case, if you want to run this down I would suggest just running this...

```
$ gulp genConfig
$ gulp reference
$ gulp test
```

Just to make sure that your install is working.  If that doesn't work you could try to reinstall using the newer method here https://github.com/garris/BackstopJS#installation.

Then run the above lines to make sure the install worked.

If all that is working then there may be an issue that just affects windows -- which I'd be happy to look at.

Cheers.

**Comment by benjaminfisher** [comment]
npm install of BackstopJS results in the same error with both gulp reference, and gulp test.

**Comment by garris** [comment]
What version of BackstopJS are you using?

**Comment by benjaminfisher** [comment]
I've updated to the latest version of Backstop (1.2.1). `npm run genConfig` runs with no errors. Both `npm run reference` and `npm run test` give the same error previously mentioned.

`npm run test` doesn't automatically open the browser, but `npm run openReport` does.

**Comment by benjaminfisher** [comment]
Closed accidentally. Sorry.

**Comment by garris** [comment]
Thanks for updating the issue and thanks for pulling down the most recent version.

The most suspicious line in your log is the one that says:  `the system can not find the path specified`.   Seeing as you're on windows and paths are specified differently across platforms, I'm suspecting there is something internal _or even in the config_ which is confounding the write to disk operation. 

I will review that flow and see if I can find anything obvious.   Will follow up soon.

**Comment by benjaminfisher** [comment]
That error seems to be specific to my machine, and I get it no matter what I try to run in the command line. I don't think it's related, since it hasn't actually stopped me from doing anything else. I really should track that down, and fix it :)

**Comment by gerbilsinspace** [comment]
@benjaminfisher are you using the default command prompt, or something else? I've noticed this issue when using git bash. I can't test any more until I get back in the office tomorrow, but I'll try to do my part debugging this.

**Comment by benjaminfisher** [comment]
@gerbilsinspace I have been using git bash for the unix support, but I've seen the `system can not find the path specified` error when using the vanilla Windows cmd prompt.

**Comment by garris** [comment]
Are you able to create a file in node?  Could permissions be an issue?

**Comment by benjaminfisher** [comment]
1. Yes
2. Doesn't seem to be.

```
$ node
> fs.appendFile('aNewFile.txt', '1234')
undefined
>
/c/Rhythm/rhythm-testing (master)
$ ls
aNewFile.txt   backstop_data/  package.json
```

**Comment by benjaminfisher** [comment]
Resolved issues with `the system can not find the path specified.` error, and that does seem to have resolved this particular issue. I'm not getting the `Testing script failed with code: 1` error anymore, and the `npm run test` is auto-opening the browser now. However changing the engine to SlimerJS is still not generating reference screen shots.

**Comment by benjaminfisher** [comment]
@gerbilsinspace By the way I resolved the path issue in cmd by following the steps in the first answer on http://superuser.com/questions/727316/error-in-command-line-the-system-cannot-find-the-path-specified

**Comment by garris** [comment]
Wow. Thanks for sharing this.  I have updated the title with  `the system can not find the path specified` to hopefully help other windows users who have this issue.   I will reopen your other bug.

**Comment by robertmazzo** [comment]
@benjaminfisher - i understand you resolved the path issue, but what about your original post regarding the gulp process not completing and also not opening the browser ?
From the OP:
            "the test gulp task are throwing Testing script failed with code: 1 and the test page is not launching in the browser."

**Comment by christianhaller** [comment]
I had the same problem.
With slimerjs, the reference image was not saved.
If you run backstopjs with debug: true, you can see the casperjs error:

> Failed to save screenshot to ...;
>  please check permissions...

I changed my selector body to the <div> with the id page (luckily I have this on every page).
After that, it references for all urls are generated.
ps: selector 'html' was also failing for some urls.

It's not happend with phantomjs.
