### ISSUE TITLE
Check if selected port is free

### ISSUE THREAD

**Issue by LukasLt** [garris/BackstopJS#176]
Is it possible to add check before starting to know if selected port is taken, and if so - give any error message?

I know you can set port manually (https://github.com/garris/BackstopJS/issues/130), but for new users its easy to miss.

I just had the same issue with browser sync (I totally forgot it was running form yesterday), and despite doing it on fresh install I got no success. For me it was was pure luck to notice that the issue is taken port and not some broken dependency causing this.

Since browser sync is quite popular, quicker solution could be to simply change default port to 3002

Thanks!

**Comment by garris** [comment]
Thanks for the post.  Feel free to put up a PR for this.  I am happy to pull that in.  Cheers.

**Comment by garris** [comment]
Closed by #259
