### ISSUE TITLE
Any plans on moving image comparison logic out of browser?

### ISSUE THREAD

**Issue by peteraverianov** [garris/BackstopJS#177]
I noticed that all the logic for image comparison happens on browser side using resemble.js
Screenshots and scenarios could be pretty big. 
Do you have any plans on moving this logic outside of browser (maybe using this package or something similar) https://www.npmjs.com/package/node-resemble-js?

**Comment by garris** [comment]
We're already using node-resemble for the CLI reporting option.   No plans for changes in the browser version -- but feel free to send a PR if you have a good optimization.

**Comment by klausbayrhammer** [comment]
@peteraverianov @garris  I'm not sure if I understand you correctly. You could either use the browser reporter (with resemble.js) or the CLI-Reporter (which uses node-resemble.js). But neither wouldn't change the size of the screenshots.
