### ISSUE TITLE
Run multiple CasperJS files for scenario

### ISSUE THREAD

**Issue by rapidfixer** [garris/BackstopJS#178]
Hello.! 
Say i've got application consisting of some components. I want to use separate **CasperJS** tests (separate files, to be more exact) for every component, but to run them all in certain scenario (maybe in all)
How can i do it? As far as i understand, **backstop.json**`s _'onReadyScript'_ contains module that already receives _'casper'_ instance.
Only solution that i see is using some bundler (**Webpack** or **Gulp**, for example) to make one test file from modules and then start backstopJS.

**Comment by garris** [comment]
Yes, you will need to compile your app components together first -- then test.

**Comment by rapidfixer** [comment]
No, not app components. of course my app is already bundled at the moment of testing :)
I mean separated casper test script files. And all i've found was _--includes_ option in CasperJS CLI, but that is unuseable in our case.
Will try to bundle tests together.

**Comment by garris** [comment]
Oh, I understand now.  Maybe you could just create an "index_casperScripts.js" and in that file just `import` your various scripts that way?   I think this would eliminate the need to concat them together -- perhaps it would let you use logic to import the correct scripts based on the scenario.   Hope that helps!

**Comment by rapidfixer** [comment]
Combining tests via webpack with _'commonjs2'_ libraryTarget setting. Works as expected.

**Comment by garris** [comment]
Glad it worked out.  Thanks for posting!
