### ISSUE TITLE
Using JS config and Gulp

### ISSUE THREAD

**Issue by bogatyrjov** [garris/BackstopJS#182]
Using JS module for config instead of JSON ( npm run test -- --configPath=config.js ) is very handy but apparently it can't be used with built in Gulp tasks? 

Any ideas how to use Gulp and JS config at the same time? If not possible, then that could be a great feature to add to backlog.

**Comment by garris** [comment]
I think you probably need to import gulp into the config file.   Have you tried that?

**Comment by bogatyrjov** [comment]
What do you mean and how would that work? I don't get it.
My goal is to just use 'gulp test' but make it load config from js, not the default json.

**Comment by garris** [comment]
Sorry, I don't quite understand your issue. Please post an example of what you're trying to do.

**Comment by bogatyrjov** [comment]
`npm run test` takes conf from backstop.json
`npm run test -- --configPath=config.js` takes conf from config.js
`gulp test` takes conf from backstop.json

Question is how to run `gulp test` with conf from config.js ?

**Comment by garris** [comment]
Ok. I see what you want to do.

Unfortunately, that approach is not really supported at this point.  It's probably possible to do this tho -- but you'd need to troubleshoot it.  You could also try the `gulp-chug` plugin, maybe it will help...
https://www.npmjs.com/package/gulp-chug

Hope that helps.  Please post back if you figure it out.  Thanks.

**Comment by bogatyrjov** [comment]
Ok, gulp-chug actually has an option to include arguments, so this task in my project's gulpfile solved my case:

```
gulp.task( 'test', function () {
    gulp.src( './node_modules/backstopjs/gulpfile.js' )
        .pipe( chug({
            tasks:  [ 'test' ],
            args: [ '--configPath=../../config.js' ]
        }));
});
```

**Comment by garris** [comment]
Thank you for posting the resolution. 👍 Cheers.
