### ISSUE TITLE
Reporting a better error message in test.js

### ISSUE THREAD

**Issue by racer2207** [garris/BackstopJS#185]
I was getting the error _Testing script failed with code: 1._ when attempting to create the reference images with _npm run reference_. I'm on a win32 platform and finally figured out the real issue by adding the following code to the test.js file.

`casperChild.stderr.on('data', function (data){ 
	  console.log("CasperJS:" + data.toString());
  });`

Turns out that CasperJS requires Python.exe to be on the machine. Once I loaded that dependency everything worked great.

**Comment by garris** [comment]
Thank you for posting the solution to this!  I'd like to add this note to the documentation.  Would you mind telling me what resource you used to install python? _e.g. the command, version, repo, etc._

**Comment by racer2207** [comment]
I installed the latest version of Python from [www.python.org](https://www.python.org/downloads). The direct link is [Download Python 3.5.1](https://www.python.org/ftp/python/3.5.1/python-3.5.1.exe)

From there I just installed their software suite and made sure my PATH variable included python.exe. Someone could do a custom install and only add python.exe.

**Comment by garris** [comment]
Thanks!
