### ISSUE TITLE
React and BackstopJS

### ISSUE THREAD

**Issue by cehter** [garris/BackstopJS#187]
I want to use BackstopJS for our new react application, but I just got the following errors after I run
 `npm run reference`

If I use phantomJS as an engine: 
```
CasperJS: Debug is enabled!
CasperJS: CREATING NEW REFERENCE FILES
CasperJS: Remote Error >    ReferenceError: Can't find variable: Symbol
CasperJS: file:     file:///Users/ceh/Projekte/Berlitz/src/pattenlab/_dev/styleguide/build/bundle.js

CasperJS: line:     101
CasperJS: function:
CasperJS: Ready event received.
CasperJS: Current location is ../../_dev/styleguide/index.html
CasperJS: <body>
                <div id="app"></div>
        <script src="build/bundle.js"></script>

</body>
CasperJS: Screenshots for phone (320x480)
```

If I use slimerjs as an engine: 
```
CasperJS: Debug is enabled!
CasperJS: CREATING NEW REFERENCE FILES
CasperJS: Remote Error >    [JavaScript Error: "ReferenceError: Symbol is not defined" {file: "file:///Users/ceh/Projekte/Berlitz/src/pattenlab/_dev/styleguide/build/bundle.js" line: 101}]
CasperJS: file:     file:///Users/ceh/Projekte/Berlitz/src/pattenlab/_dev/styleguide/build/bundle.js
CasperJS: line:     101
CasperJS: function: null
CasperJS: Ready event received.
CasperJS: Current location is ../../_dev/styleguide/index.html

CasperJS: <body>
                <div id="app"></div>
        <script src="build/bundle.js"></script>

</body>
CasperJS: Screenshots for phone (320x480)
```
After some research I found a [bug report at phantomjs ](https://github.com/ariya/phantomjs/issues/13304). But this problem should not be there if I use slimerjs or?

**Comment by garris** [comment]
It's hard to figure out what's going on by looking at your output.   Looks like there is an error in your app -- you might look there.   BackstopJS works with react just the same as any other app.  Here is a simple react app example (follow the readme to install) https://github.com/garris/BackstopJS/blob/master/test/simpleReactApp.zip

Hope this helps.

**Comment by JayGray** [comment]
If I look at `JavaScript Error: "ReferenceError: Symbol is not defined"` I would guess the `bundle.js` has ES6 syntax. AFAIK neither slimerjs nor PhantomJS supports ES6. You might need to transpile it down to ES5.
[Symbol](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol)

**Comment by cehter** [comment]
Thank you @garris and @JayGray. I didn't think about the ES6 support, we use the ES6 syntax. Will test it with ES5.
