### ISSUE TITLE
If bower directory is different from bower_components, angular APP has wrong JS paths

### ISSUE THREAD

**Issue by sergesemashko** [garris/BackstopJS#19]
I have following folder structure:
- .bowerrc - contains: 
```json
{
  "directory": "patternlab-source/bower_components"
}
```
- patternlab-source/bower_components/backstopjs/compare/patternlab-source/bower_components/angular
- patternlab-source/bower_components/backstopjs/compare/patternlab-source/bower_components/angular-route
- ...

Paths in Angular App do not match folder structure - [screenshot](http://take.ms/caAxN) . To fix the issue path should contain custom folder defined in ```.bowerrc``` file. The path to angular JS will look like:
```
http://localhost:3001/compare/patternlab-source/bower_components/...
```

**Comment by garris** [comment]
Hi @sergesemashko, Thanks for posting.  Not sure what the use case would be for changing the bower_components path *inside* the BackstopJS directory.  Could you let me know?  Thanks -GS

**Comment by sergesemashko** [comment]
Yeah, I don't know either :) That structure is automatically generated after, I guess, ```npm install```. I was running commands in order according to [CSS-tricks manual](http://css-tricks.com/automating-css-regression-testing/).

**Comment by garris** [comment]
oh... Got it!   Looks like Bower is behaving just as Bower should.  I just added a local `.bowerrc` to `backstopjs/` root and all is well.   I will push this update out momentarily.   Thank you very much for reporting this bug!

Cheers,
Garris

**Comment by garris** [comment]
@sergesemashko -- new release pushed out.  It would be great if you had a minute to validate the fix.

https://github.com/garris/BackstopJS/releases/tag/0.2.6

Regards!

Garris

**Comment by sergesemashko** [comment]
@garris it works, 
thanks for quick reply and fix
