### ISSUE TITLE
Test report in both XUnit and LCov?

### ISSUE THREAD

**Issue by nobso** [garris/BackstopJS#192]
I'm using Jenkins in my CI and that accepts test report in JUnit  XML format. Is there a way that i can create that using any commands at the moment?

**Comment by nobso** [comment]
@garris do you have any comment on this requirement?

**Comment by garris** [comment]
@nobso apologies for the delay!  

So, here is the loop where server side comparison reports are generated... 
https://github.com/garris/BackstopJS/blob/master/gulp/tasks/compare.js#L37

 I think you could potentially build up the kind of report you'd want inside this loop.   You could potentially add that as an option flag or as a configurable plugin.  It sounds like the kind of thing that others may also find useful -- so, if you do go ahead and create something, please create a PR.

**Comment by nobso** [comment]
@garris Cool, i'll raise a PR for the same.

**Comment by nobso** [comment]
@garris I've raised a https://github.com/garris/BackstopJS/pull/194 for the same, please review and let me know if you have any comments
