### ISSUE TITLE
ENOENT error 

### ISSUE THREAD

**Issue by coljung** [garris/BackstopJS#2]
When i try to run this i get an error, i followed the steps and im not sure what im missing.

To get the error I went to the specified folder and ran gulp echo, this is the message received:

[11:51:14] Using gulpfile ~\Projects\git\myCoolProject\bower_components\backstopjs\gulpfile.js
[11:51:14] Starting 'echo'...
[11:51:14] Finished 'echo' after 2.22 ms

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)

Thanks!

**Comment by matt-newman** [comment]
I know this is a closed issue, but I had this problem and the above steps didn't quite work for me, I had everything installed and running independently, but as I'd installed casperjs a long time ago independently it existed elsewhere on my PATH:

You can work out if you're having the same problem by using:
On windows cmd:
>where phantomjs
>where casperjs

On windows 'bash' (mysys, gitbash, etc):
>which phantomjs
>which casperjs

It's easiest if they're all in the same location, for me I made that npm global installs, e.g: /c/Users/{USERNAME}/AppData/Roaming/npm/

casperjs was in a different location so I had to remove that reference (environment variables) and install it via:
npm install -g casperjs

hope that helps someone

**Comment by garris** [comment]
@matt-newman, thanks for posting this.
