### ISSUE TITLE
validation of new features: readyEvent and delay

### ISSUE THREAD

**Issue by garris** [garris/BackstopJS#20]
I implemented loadEvent and delay features.  Documentation is in the readme.  

If anyone happens to get a minute I'd love to get some feedback on those. 

Thanks!  GS

**Comment by lewisnyman** [comment]
I needed to use this feature today as it happens. I needed to add the delay setting to every page, which was a little tiresome. Maybe allowing a global configuration that can be overridden per page might be better? I guess you could do the same for the event option

**Comment by garris** [comment]
Yes, great suggestion, I will work on that and also add a global sensitivity setting.

BTW: Thank you very much for validating the release!  I really appreciate the help. :)

**Comment by lewisnyman** [comment]
No problem! This is how open source works :) Thanks for working on it

**Comment by garris** [comment]
moving to feature request.

Closed by #24
