### ISSUE TITLE
Casper Scripts Causing Skipped Scenarios

### ISSUE THREAD

**Issue by angelariggs** [garris/BackstopJS#200]
I added a CasperJS login script for 3 (of about 60) scenarios. 
```
module.exports = function(casper, scenario, vp) {
  casper.wait(100);
  casper.echo('logging in');
  casper.start('<website>', function() {
    this.fill('form#user-login', {
      'name': '<name>',
      'pass': '<password>'
    }, true);
  });
  casper.echo('it worked');
};
```
I ran the commands for reference and test for each of the 3 scenarios separately, just to verify that the script logged in and then took the screenshots, and it works as expected. However, when I run the reference on my whole config file (I'm using a JS config, instead of the default JSON config), the reference starts at the scenario with the first Casper script and goes to the end; but skips all scenarios prior to that first one with a Casper script. 
Additionally, testing the individual scenarios with the Casper script initially produced some very wonky, very inconsistent errors - like only desktop OR mobile screenshots, but not both. Commenting out the "onBeforeScript: filename.js" portion of the scenario caused it to run as expected.

**Comment by garris** [comment]
Hmm,  could you maybe provide a gist of your setup.  That sounds like something to look into...

**Comment by angelariggs** [comment]
@garris Yes! Can you clarify what you'd like me to provide? E.g., my config file, or the process I used to set up, or...?

**Comment by garris** [comment]
The config would be a good start.  Please add any other relevant files e.g. the onBeforeScript.

**Comment by angelariggs** [comment]
I've added .txt versions of my config file (backstopJsConfig.txt) and my Casper file (userLogin.txt). In the config file, I use the userLogin.js in 3 scenarios, as `"onBeforeScript": "userLogin.js"`. 
[backstopJsConfig.txt](https://github.com/garris/BackstopJS/files/314753/backstopJsConfig.txt)
[userLogin.txt](https://github.com/garris/BackstopJS/files/314754/userLogin.txt)

**Comment by garris** [comment]
So, Are you saying that when you run the 3 login scenarios on their own they complete without any errors?

**Comment by angelariggs** [comment]
When my config file includes scenarios with custom Casper scripts, and I run the reference or test commands, Backstop starts the screenshots at the second scenario with the Casper script (line 710, `"label": "Schrod Downloads Landing Page (TODO: CASPER: LOGIN)"`), and proceeds through the rest of the scenarios to the end of the config file. It skips all of the tests above line 710. When I comment out all of the lines for the Casper script (`"onBeforeScript" : "userLogin.js"`), all scenarios run as expected.

When I comment out all scenarios _except_ those with a Casper script (e.g., run references for only the 3 scenarios that use the `userLogin.js` file), and then run the reference command, Backstop creates only a desktop reference for the 3rd scenario; it doesn't do a mobile reference for that scenario, and it ignores the other two active scenarios.

When I comment out all scenarios except just one scenario with a Casper script, and then run the reference command, Backstop takes only a desktop reference screenshot of that scenario; it does not take the mobile reference screenshot.

**Comment by garris** [comment]
Can you please make a new simple config file *just for troubleshooting* with 3 scenarios?   Please keep it to a bare minimum and exclude onBeforeScript.  Then run that.

Then duplicate that file and add the onBeforeScript.  Do you have any issues in this case?

**Comment by angelariggs** [comment]
Ack, yes! Sorry I didn't do that sooner :) New config / comments coming in just a minute!

**Comment by garris** [comment]
Yup. Just want to rule out a missing comma etc. 😉

**Comment by angelariggs** [comment]
Here's the pared-down, Casper-only version of the config file :) I'm seeing the same issue. When the Casper files are commented out for the scenarios, Backstop works as expected. When the Casper file is included for each scenario, the only reference screenshot is a desktop screenshot for the last scenario. 
I've included a screenshot of my Terminal window, after running the reference command with the Casper files included. The `casper.echo` code ran 6 times, which is what I would expect for 3 scenarios with 2 viewports each, but that is at odds with the single reference screenshot that actually happened. (I also added a screenshot of my Terminal after running the reference without the Casper script, for comparison.)

![angela-terminal-no-casper](https://cloud.githubusercontent.com/assets/10238548/16060013/8454981c-323a-11e6-8b0e-a0969c1003af.png)
![angela-terminal-with-casper](https://cloud.githubusercontent.com/assets/10238548/16060014/84555b6c-323a-11e6-838a-97d2a61023f5.png)
[backstop_beta.txt](https://github.com/garris/BackstopJS/files/314965/backstop_beta.txt)

**Comment by garris** [comment]
@angelariggs So, I am concerned there is a bug in here somewhere.  I need to leave for the day.  If it's possible you could maybe try experimenting with your login script.   Perhaps try to confirm that the login is really successful before the rest of the test executes.

**Comment by angelariggs** [comment]
(I'm replying now, but I definitely understand it's the end of your day, and won't expect an answer back tonight 😄  ) The login interaction is successful with the userLogin.js. When I run each scenario separately to test that, the reference screenshot does show the logged-in screen.

**Comment by garris** [comment]
If you commented all the before scripts except in the first scenario, what happens?

**Comment by angelariggs** [comment]
When I comment out all `before` scripts except the first scenario, the reference command results in 5 screenshots (not 6 as expected - it skipped the phone viewport for the first scenario). The test command was 'successful' - it also skipped the first scenario's phone viewport screenshot. 
None of the `before` scripts worked - all of the screenshots, both reference and test, were of the various page's login screens. I've attached the report summary here. 

![angela-firstbeforescenario](https://cloud.githubusercontent.com/assets/10238548/16087177/f5986336-32d6-11e6-8077-ef1c89638a6f.png)

**Comment by garris** [comment]
Ok.  So IOW any scenario running the before script dies?  What if you simplify the before script?  Can you track down which command is hosing execution?

**Comment by angelariggs** [comment]
(Assuming IOW = in other words) Yes. For instance, when I comment out all `before` scripts except in the _second_ scenario: the reference command skips both screenshots in the first scenario, does a desktop-only screenshot in the second scenario, and does both screenshots in the last scenario. Also without logging in any of them. 
I'll work with the lines of code in the before script to see if I can track it down.

**Comment by angelariggs** [comment]
It's definitely something in the `casper.start` or `casper.fill` code. If I just have an echo or a wait, all six scenarios are referenced and tested as expected. If I comment out the `casper.wait` and `casper.echo`'s, and just have
```
casper.start('https://schrodinger-staging.metaltoad-sites.com/knownissues', function() {
    this.fill('form#user-login', {
      'name': 'angela',
      'pass': 'Kraft423'
    }, true);
  });
```
the issues are still happening. I don't think I can really pare it down further than that.

**Comment by angelariggs** [comment]
Actually, I did a bit more paring down, to remove the login portion and just have the `casper.start`, and got the same errors as previously.
```
module.exports = function(casper, scenario, vp) {
  casper.start('https://schrodinger-staging.metaltoad-sites.com/knownissues', function() {
    this.echo('bananas');
  });
};
```

**Comment by garris** [comment]
Could you try changing your script a little bit -- pattern it this way...

```
casper.start();
this.thenOpen('https://schrodinger-staging.metaltoad-sites.com/knownissues', function() {
  this.echo('thenOpen succeeded.');
}
```

**Comment by angelariggs** [comment]
I tried that script, and got in Terminal `Testing script failed with code: 1`. I tried adding a `casper.echo` before the `casper.start`, and it didn't get even to that point - just exited with the same Terminal message.
```
module.exports = function(casper, scenario, vp) {
  casper.start();
  casper.thenOpen('https://schrodinger-staging.metaltoad-sites.com/knownissues', function() {
    this.echo('thenOpen succeeded.');
  }
};
```
I've attached a screenshot of the Terminal output after running the reference command, in case that helps shed any light. 

![angela-garris-refactored-before-script](https://cloud.githubusercontent.com/assets/10238548/16092081/3407125c-32eb-11e6-86bf-a0a23b71d14b.png)

**Comment by garris** [comment]
can you run `npm run echo` instead of `npm run reference`.   `echo` outputs debug info.  Please see if that sheds any light.  At this point I am not sure it is a Backstop issue -- but if possible, I'd still like to know what the issue is...   Thanks for your help troubleshooting!

**Comment by vflirt** [comment]
I have very similar issue with pretty much the same casper script for logged in user. My use case is as follows:
1) I have 2 scenarios 
 - Homepage : testing 5 different elements 
 - Search box: testing search form only visible for logged in users
2) I have 3 different viewports

If I have only search box scenario with 1 viewport and run the reference I can see the screenshot of the search box.
If I have only search box scenario with 3 viewports and run the reference then I get only 1 screenshot for the last viewport instead of all 3.

If I have Homepage only scenario and run reference then I get 15 screenshots as expected.

If I have Homepage and Search box (in that order) scenarios with 3 viewports and run the reference then I get only 1 screenshot for the search box for the last viewport.

If I have Search box and Homepage (in that order) scenarios with 3 viewports and run the reference then I get 16 screenshots : 15 for Homepage and only 1 for Search box for last viewport

If I set onBeforeScript for the Searchbox to null then I get 18 screenshots as expected but the screenshots that require login are empty files cause no search box is available for anonymous users.

If you want I can send over the config file and the casper script though its code is already posted in the thread above.

From what I can tell it using casper.start kills it but I cannot find any other way to login.

**Comment by vflirt** [comment]
I think I found the issue:
- using phantomjs
- for every viewport the same onbefore javascript is executed but it keeps the  info form the previous one so for the 2nd viewport it is already logged in which leads to casper failing to fill and submit the form and breaking the whole process.

As per my understanding onBeforeScript should run only once no matter the amount of viewports and onReadyScript should run for each viewport but I might have got it wrong.

**Comment by garris** [comment]
@vflirt -- thank you very much for troubleshooting the issue!   

`onBeforeScript` runs before page request for every viewport.  

Would something like only running on the first viewport this fix your issue? 
```
module.exports = function(casper, scenario, vp) {
  if (vp.name === 'phone') {
    console.log('logging in only on the first breakpoint');
    casper.start('<website>', function() {
      this.fill('form#user-login', {
        'name': '<name>',
        'pass': '<password>'
      }, true);
    });
  }
};
```

Another approach might be to only log in if there is a form present...
```
module.exports = function(casper, scenario, vp) {
  casper.start('<website>', function() {
    if (casper.exists('form#user-login')) {
      console.log('logging in if the form exists');
      this.fill('form#user-login', {
        'name': '<name>',
        'pass': '<password>'
      }, true);
    }  
  });
};
```

I think the second version is probably more solid (but maybe less efficient).

Please let me know if either or both of these work!  Thank you.

**Comment by vflirt** [comment]
Hi, thank you for the fast response. Running onBeforeScript on every page for every viewport totally makes sense. If we use slimerjs then we have no issues and for every page request for every viewport we have the login form but if we use phantomjs then after the first request we are still logged in on the second viewport so for a workaround we used the casper.exists to check for the form and that made it. 
I don't have the knowledge to say if the session should get passed after the login in the first viewport to the second because that is not the case with slimerjs so might be a bug when dealing with phantomjs or might be how phantomjs is working.
Again thanks for the fast response and for finding workaround.

**Comment by garris** [comment]
Would you mind posting your workaround code so I can update the example?

**Comment by vflirt** [comment]
Yep, here is my code:

module.exports = function(casper, scenario, vp) {
  casper.thenOpen(scenario.url, function() {
    if (this.exists('form#user-login-form')) {
      casper.fill('form#loginForm', {
        'name': "",
        'pass': ""
      }, true);
    }
  });
};

**Comment by garris** [comment]
@vflirt Thank you for sharing!   Cheers,  Garris

**Comment by shihao92** [comment]
@garris Hi garris. i found that this is not really because of the case of session still login. I did a small experiment which utilize the casper.start on the onBefore.js and the scripts are running fine. (but viewports are required to be defined well at the script) 
its just that at the end after the test session, the report module seems to not able to find the image to be compared and it will generate error.
