### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by dummdidumm** [garris/BackstopJS#204]
The latest release and therefore last publish to npm ( https://www.npmjs.com/package/backstopjs ) was three months ago. Is there a reason for this? Some cool new features are missing for users who want a quick "npm install".

**Comment by garris** [comment]
Which feature(s) are you interested in?

**Comment by dummdidumm** [comment]
Mainly the test report integration through "CI" .

**Comment by garris** [comment]
Ahh yes, I really like this group of features-- but before publishing that I wanted to give plenty of time for others to test out the various features.   I would love to hear how you have integrated BackstopJS into your CI.   How easy or hard it was and how you manage workflow/validation of UI changes.

**Comment by garris** [comment]
Sorry, accidentally hit close button...

**Comment by dummdidumm** [comment]
We use backstopJS as a regression / integration test tool for our angular web application. 
- Build showcase for a component
- Write backstopJS test for that showcase
- Periodically run tests
The last part is integrated with a jenkins-job that is run after a new build of the project. The job is already up and running using the CLI function, but the feedback loop is a bit cumbersome without the CI option: If the job failed, look into the console, identify failures, get failing screenshots, run "openReport" on own computer, see diff. The CI option would greatly improve this feedback flow. We also would use the github version of backstopJS but due to limitations we cannot integrate git into our jenkins and therefore have to rely on the npm installation.
As for the rest of the workflow: Easy and intuitive, no errors experienced so far.

**Comment by garris** [comment]
Thank you for the feedback.  That is very helpful!

Also, some good news -- we shipped version 1.3.1 today.  I very much appreciate your patience -- this is a labor of love so sometimes it takes longer than we'd like to ship.   

Cheers.
