### ISSUE TITLE
Old diffs in report

### ISSUE THREAD

**Issue by OleVik** [garris/BackstopJS#205]
Having some trouble understanding the tasks and their operability, I seem to be getting the incorrect images for diffs in the report after running `gulp reference` and then `gulp test`. For example, the source on the report reveals that images from `bitmaps_test/20160616-191947` are shown when `bitmaps_test/20160616-201429` are newer. Is there some caching mechanism in the generation of the report?

It seems to only use the newest images when I delete the old ones, and run `reference`and `test` again.

From what I understand, running with `"report": ["CLI"]` it should store the diff images alongside the test images, and with `"report": ["browser"]` it will display them in browser. However, with `"CLI"` the diff images are not present there, though they are generated in-browser with `"browser"`. What task should be run to generate the report for the browser and run the server, without opening the browser itself?

A simplified version of my `backstop.js`-file:

```
{
"viewports" : [
    {
     "name": "phone_portrait",
     "viewport": {"width": 320, "height": 480}
    }
],
"scenarios": [
	{
		"label": "Front",
		"url": "http://test.fremmed.dev:80",
		"referenceUrl": "http://fremmed.no",
		"hideSelectors": [],
		"removeSelectors": [],
		"selectors": [
			"body"
		],
		"readyEvent": "",
		"delay": 0
	}
],
"paths": {
	"bitmaps_reference": "../../backstop_data/bitmaps_reference",
	"bitmaps_test": "../../backstop_data/bitmaps_test",
	"compare_data": "../../backstop_data/bitmaps_test/compare.json",
	"casper_scripts": "../../backstop_data/casper_scripts"
},
"engine": "phantomjs",
"report": [""],
"debug": false,
"port": 3001
}
```

**Comment by garris** [comment]
Closed by #259
