### ISSUE TITLE
Possibility to capture viewport

### ISSUE THREAD

**Issue by rjokelai** [garris/BackstopJS#207]
I have a `position:fixed` element that overlaps a scroll container. Is there an easy way to capture a screenshot of the whole viewport instead of a selector?

**Comment by kamlesh-astech** [comment]
in such case u can use body to capture screen

**Comment by Steven-Pingel** [comment]
At least in my case selecting body does not capture the entire page, it cuts off the bottom of the page.

**Comment by garris** [comment]
@Steven-Pingel there is a commit of BackstopJS which allows you to specify "viewport" as a selector.  I haven't been able to test it yet -- but I will merge it to master and you can give it a try.  I will let you know when it's up -- pls give me 15 mins...

**Comment by garris** [comment]
ok.  the update is in master.
 install with `npm install garris/backstopjs#master`

for instructions, please see...
 https://github.com/garris/BackstopJS#capturing-the-entire-viewport

Please let me know if it works -- I haven't had time to test it myself!

Thanks!

**Comment by garris** [comment]
@rjokelai @Steven-Pingel @kamlesh-astech Document capture feature is ready to test.  Thank you.

**Comment by rjokelai** [comment]
Thanks! The `document` selector indeed works better

**Comment by rjokelai** [comment]
Oops, accidental close. Probably want to do this in a commit...

**Comment by garris** [comment]
Thanks for verifying!   This is in the latest release 1.3.2.   Cheers.

**Comment by kamlesh-astech** [comment]
Hello @garris, You mean to say we just have the call document within selectors and no need of any other elements..
Am I right ?

**Comment by garris** [comment]
You can use as many selectors as you like.

**Comment by kamlesh-astech** [comment]
ok thanks
