### ISSUE TITLE
Uncaught fails?

### ISSUE THREAD

**Issue by lewisnyman** [garris/BackstopJS#21]
Hey,

I was testing v0.3.0 today and I noticed that some tests that were caught by resemble.js weren't being marked as fails by the app? Screenshots attached:

![screenshot 2015-01-23 12 03 45](https://cloud.githubusercontent.com/assets/632390/5874219/2a642276-a2ff-11e4-9821-943a541ba344.jpg)
![screenshot 2015-01-23 12 04 11](https://cloud.githubusercontent.com/assets/632390/5874221/2f746276-a2ff-11e4-8194-2ea41dc0a7e7.jpg)
![screenshot 2015-01-23 12 06 26](https://cloud.githubusercontent.com/assets/632390/5874224/40ccfc90-a2ff-11e4-80ee-794508d0ddcd.jpg)

**Comment by garris** [comment]
Yes, I started seeing this recently also.  See line 34 of `compare/index.html`.   

    		var misMatchThresh = 1;

This setting allows you to give some range of acceptable deviation.  In your examples it is a very small difference -- in the 0.17 range.   I set the threshold high, to avoid false positives on rounding errors.

This really should be able to be a user setting -- and also, probably set much lower.

I think your suggestion to move delay & readyEvent to a global block makes sense also.  I will work on that.

**Comment by garris** [comment]
Tracking this in issue #20

**Comment by garris** [comment]
I will move this feature to an enhancement request.

**Comment by garris** [comment]
Closed by #24
