### ISSUE TITLE
Xunit report file is not generating correctly

### ISSUE THREAD

**Issue by vflirt** [garris/BackstopJS#214]
When running tests the xunit report file is not generating correctly.
I have tracked down the issue to the comapre.js file.
It generated the report file after comparison and only if the key equals testPairsLength + 1 however the comparisons are not run in the same order so the last pair will not always be the last one to run which leads to incorrect data written in the file.
If I move that block for writing the file in function updateProgress just bellow the "Test completed" messages then the data of the xunit file is correct and has all tests data.
If you want I can make PR with that code change.

**Comment by garris** [comment]
@vflirt thank you for posting this issue -- Suresh worked on that feature so I'd like to have him comment on the PR.

@nobso Could you please comment on this -- thanks!

**Comment by nobso** [comment]
@vflirt Thanks for raising this issue 😃.  I got your point. Please raise the PR if you can or let me know i can do that right away.
