### ISSUE TITLE
Add more contributors

### ISSUE THREAD

**Issue by levithomason** [garris/BackstopJS#217]
I'd love to help move project along.  I'm most interested in helping with the CLI work noted in #164 and #165. I've also submitted #215 to fix #135 issue with exit codes.

Would you consider adding me as a contributor to help trudge some of the issues and PRs?  I'm trusted as a [Semantic UI Org](https://github.com/Semantic-Org) member, [ShellJS](https://github.com/shelljs) member, [watch](https://www.npmjs.com/package/watch) contributor, and I'm the author of [Stardust](https://github.com/TechnologyAdvice/stardust).

**Comment by garris** [comment]
Hi @levithomason!  Thank you for PR #215 -- I've just merged that in. 

I am very happy to have you contributing anything else you're interested in. 

I'll be out of town for a week -- but lets follow up after that.

Again, thanks for your contributions!

**Comment by levithomason** [comment]
Awesome.  Could you add me to the repo as a collaborator so I can contribute directly?

**Comment by levithomason** [comment]
I should clarify, nothing will get merged without your sign off of course.

**Comment by garris** [comment]
To date all contributors are just posting PR's.  Seems to work pretty good that way.

**Comment by levithomason** [comment]
Sounds good.  Let's start it that way.

**Comment by garris** [comment]
@levithomason Just wanted to check in with you.  There is another contributor who wanted to take a look at the CLI-related effort.  I am assuming you aren't actively working on this at the moment -- is that correct.   I just wanted to make sure not to step on any of your effort.   Please let me know.   Thanks!

**Comment by levithomason** [comment]
Thanks, I replied on the other issue for now.
