### ISSUE TITLE
Having trouble install npm backstopjs

### ISSUE THREAD

**Issue by hamzazaidi** [garris/BackstopJS#218]
getting 

npm ERR! fetch failed https://registry.npmjs.org/backstopjs/-/backstopjs-1.3.5.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502

**Comment by garris** [comment]
@hamzazaidi -- are you still having this issue?  This is working for me.   Please LMK.  Thank you.

**Comment by J-Gea** [comment]
@garris  --i have a project. when i install backstopjs in my project . i got this 
npm ERR! Darwin 14.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save-dev" "backstopjs"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE

npm ERR! phantomjs-prebuilt@2.1.7 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs-prebuilt@2.1.7 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
i dont want to update my nodejs 
what should i do ?

**Comment by J-Gea** [comment]
@garris i install backstopjs  in my project  when i  use npm run genConfig 
i got  this 
npm ERR! Darwin 14.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "genConfig"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0

npm ERR! missing script: genConfig
what should i do ?
thank you
