### ISSUE TITLE
Running Multiple Phantom/Slimer Instances with more than one scenarios

### ISSUE THREAD

**Issue by IoT-master** [garris/BackstopJS#224]
Hi,
Is it possible to run multiple PhantomJS instances instead of just one? I'm looking to speed up my backstop tasks.

**Comment by garris** [comment]
@IoT-master This is a great question.  Unfortunately, it is not implemented yet.   This could be done by explicitly pointing to different phantom installs in each [node.span() closure here](https://github.com/garris/BackstopJS/blob/master/gulp/tasks/test.js#L66). Then you would write some logic around firing off different scenarios with each assigned an available phantom instance.   It's a bit complicated but I'd be happy to help anyone who has interest working on it.

Cheers.
