### ISSUE TITLE
Multiple screenshots per selector possible?

### ISSUE THREAD

**Issue by frescoraja** [garris/BackstopJS#229]
It seems in genBitmaps.js that casper.capture or casper.captureSelector are called only once per selector per scenario.. the beforeScripts and readyScripts are just for setup or preparation. But this seems to lead to a lot of code duplication if you are testing multiple phases of a single component.. say i have a custom dropdown menu, and i want to screenshot the menu before any actions, after a click, after some input, and then after highlighting an item in subsequent menu.. I have to create a new scenario for each? the first one without any script, then one with a click event, then one with the click event followed by input, then one with the click event, followed by input, followed by mouse movement to menu item.. I know i can call casper.captureSelector from within the before/ready scripts but then the screenshot doesn't seem to be detected by comparison tests.. any help would be appreciated.

**Comment by garris** [comment]
BackstopJS is for testing lots of pages.  If you want to test lots of interactions than you may be better off using phantomCSS or just CasperJS on its own.
