### ISSUE TITLE
CasperJS and PhantomJS are BackstopJS Dependencies.

### ISSUE THREAD

**Issue by jehoshua02** [garris/BackstopJS#23]
CasperJS and PhantomJS are BackstopJS dependencies. Please consider adding them to `package.json` and/or `bower.json`.

**Comment by jehoshua02** [comment]
Maybe looking at how I've done things here will help: https://github.com/jehoshua02/backstopjs-example

**Comment by garris** [comment]
This is a very popular enhancement.  Do you care to make a pull request?

Also, is it possible to implement this install without breaking the old install option.  There may be users who don't necessarily want their existing phantomjs & casperjs versions bumped.

What do you think?

**Comment by jehoshua02** [comment]
You would bump your version number and they could stay on an older version of backstop.

**Comment by jehoshua02** [comment]
I've forked it and will submit a pull request sometime.

**Comment by garris** [comment]
Done.  Closed with release https://github.com/garris/BackstopJS/releases/tag/1.2.0
