### ISSUE TITLE
Running it in your own project's gulp file

### ISSUE THREAD

**Issue by melissamcewen** [garris/BackstopJS#233]
Thanks for the great project, I was hoping to integrate it into my own project's gulp file that does all our other front end tasks, but I am having trouble getting it to run from anywhere but the BackstopJS directory. What's the best way to integrate it? I tried require-dir, but an obstacle seems to be it relies on the node_modules in the actual BackstopJS directory rather than the node_modules directory in my own project.

**Comment by nobso** [comment]
@melissamcewen You may try to use https://www.npmjs.com/package/gulp-shell with CWD option. I've used grunt-shell that is similar to this package.

**Comment by garris** [comment]
I like gulp-shell too.

Optionally, There is a nice tutorial for this exact use case using gulp-chug -- you might want to look at that as well...

http://blog.bartos.me/css-regression-testing/
> If you want to control backstop's gulp within your own project's gulpfile.js, there is an easy way out using gulp-chug package.

Hope that helps!

**Comment by melissamcewen** [comment]
Gulp chug worked great! Thanks everyone!
