### ISSUE TITLE
Is it possible to not automatically start the server?

### ISSUE THREAD

**Issue by svwu** [garris/BackstopJS#237]
Hello there,
I don't want to have an server started, when the test task is done.
As I want to use BackstopJS in a cronjob, I don't need the report in any browser.

Greets,
Sven

**Comment by patriciamarchand** [comment]
I think you can modify in the backstop.json file, line "report": ["browser", "CLI"]  to  "report": ["CLI"]

**Comment by garris** [comment]
+1

**Comment by svwu** [comment]
I changed my config file to "CLI" only and still get this message:

Server launched in background with PID: 22030
Listening on port: 3001
NOTE: Sever will auto-shutdown in 15 mins.

**Comment by garris** [comment]
This sounds like a big.  I don't think the server should start if only CLI is selected.

**Comment by garris** [comment]
This of course is not ideal and should be fixed -- but the server will auto shut down and should not impact your CI.  Is that true for your use case?

**Comment by svwu** [comment]
Well it's not a big impact, but it's unnecessary to start a process, when it's not needed...

**Comment by garris** [comment]
Marked as bug.

**Comment by garris** [comment]
Closed by #259
