### ISSUE TITLE
Issue on wpengine running backstopjs

### ISSUE THREAD

**Issue by jairusnativecommerce** [garris/BackstopJS#239]
Hello,

Just want to ask about our issue in running backstopjs in our sites housed in wpengine(wp hosting). it runs but it just gathers screenshot that says 403 forbidden so i assume this has something to do with wpengine. We contacted wpengine and they are saying that they could set rules for it to work but then they don't know what to set. Maybe you can us give idea on what causes this maybe because of nodejs also they ask if it uses particular user-agent to hit the site prior to the screenshot process?

I find backstopjs really useful and easy to use, i also used this on some of my site but not using wpengine. 

Thank you
![0_0_body_0_a](https://cloud.githubusercontent.com/assets/20844406/17412120/abe2fda6-5aad-11e6-9784-07432bc97b2e.png)

**Comment by garris** [comment]
Maybe they have a user-agent rule?   PhantomJS looks like this...
```
Mozilla/5.0 (Macintosh; Intel Mac OS X) AppleWebKit/534.34 (KHTML, like Gecko) PhantomJS/1.9.8 Safari/534.34
```

I just quickly googled this article -- wpengine may be using some of these techniques...
http://engineering.shapesecurity.com/2015/01/detecting-phantomjs-based-visitors.html

Please post back if you resolve the issue.  I am curious to see how it works out. 

Cheers.

**Comment by jairusnativecommerce** [comment]
Hey garris,

Thanks for the fast response, yes they are using user-agent rule i think.
they said they just added " if code" on their end to make the tool work.

if ($http_user_agent ~* "PhantomJS" ) {
break;
}

Thank you very much
