### ISSUE TITLE
No reference directory and no screenshots being created.

### ISSUE THREAD

**Issue by jon64digital** [garris/BackstopJS#251]
Hi,

I followed your css-tricks article today and really wanted to get BackstopJS running but came across lots of problems doing a vanilla install.

1) Failed with error code 1 - I found another issue on here tha suggested it was because of python. I tried running phantomjs and it said python wasn't installed, but your article/docs make no mention of installing python, so I installed python.

2) Needed to globally install phantomjs and casperjs to quash another error.

3) Finally got it running with no errors and it says it's completed successfully but it hasn't opened any browsers or generated any screenshots. Here is the output using a vanilla install and yout default backstop.json file from genConfig.

C:\Dropbox\Git\portal-test\node_modules\backstopjs (master) (garris@1.3.5)
λ npm run reference

> backstopjs@1.3.5 reference C:\Dropbox\Git\portal-test\node_modules\backstopjs
> gulp reference

BackstopJS Config loaded at location C:\Dropbox\Git\portal-test\backstop.json
[16:01:15] Using gulpfile C:\Dropbox\Git\portal-test\node_modules\backstopjs\gulpfile.js
[16:01:15] Starting 'clean'...
bitmaps_reference was cleaned.
[16:01:15] Starting 'bless'...
[16:01:15] Finished 'bless' after 4.08 ms
[16:01:15] Finished 'clean' after 13 ms
[16:01:15] Starting 'reference'...
gulp.run() has been deprecated. Use task dependencies or gulp.watch task triggering instead.
[16:01:15] Starting 'init'...
[16:01:15] Finished 'init' after 3.84 μs
[16:01:15] Starting 'test'...

Generating reference files.

Running CasperJS with:  [ 'capture/genBitmaps.js' ]
[16:01:15] Finished 'test' after 12 ms
reference has run.
[16:01:15] Finished 'reference' after 27 ms
CasperJS:
C:\Dropbox\Git\portal-test\node_modules\backstopjs {git}{hg}
{lamb}   "C:\Dropbox\Git\portal-test\node_modules\backstopjs\node_modules\.bin\\node.exe"  "C:\Dropbox\Git\portal-test\node_modules\backstopjs\node_modules\.bin\\..\phantomjs\bin\phantomjs" C:\Dropbox\Git\portal-test\node_modules\casperjs\bin\bootstrap.js --casper-path=C:\Dropbox\Git\portal-test\node_modules\casperjs --cli capture/genBitmaps.js

Bitmap file generation completed.

Run `$ npm run test` to generate diff report.

------------------------------------------------------------------

I've never used phantom or casper before so debugging this on my own is going to be really hard and I'd still like to get this working as it looks like a great tool. Any idea what's going on?

**Comment by svwu** [comment]
Did you check the paths in your config file?
They're relative and may used dirs?

**Comment by jon64digital** [comment]
They are generated for me by genConfig. They both start with "../../" which is surely correct becaue we're starting in /node_modules/baskstopJS which is two levels down from the root folder.

**Comment by svwu** [comment]
There is some output missing like:
CasperJS: Ready event received.
CasperJS: Current location is http://google.de
CasperJS: Screenshots for phone (480x480)
CasperJS: Ready event received.
CasperJS: Current location is http://google.de
CasperJS: Screenshots for tablet_v (768x1024)
CasperJS: Ready event received.
CasperJS: Current location is http://google.de
CasperJS: Screenshots for tablet_h (1024x768)
CasperJS: Ready event received.
CasperJS: Current location is http://google.de
CasperJS: Screenshots for desktop (1280x768)
CasperJS: Comparison config file updated.

**Comment by svwu** [comment]
Can you try to use the gulp task and check if there is any difference in behaviour?
Just use gulp reference instead of npm run reference

**Comment by svwu** [comment]
I used your config and test it on my own.
It works fine...

So it's the baddest answer I can give is "It works for me!"

I would like to debug with you, as I did it many times to find errors.

**Comment by jon64digital** [comment]
I would be happy to skype with you or something similar.

**Comment by svwu** [comment]
Do you have gitter?

**Comment by jon64digital** [comment]
No, but I just had a look and it looks a bit like Slack I'm guessing. 

Happy to get an account if you tell me how I can connect to you on it. You can email me at jon(@)64digital.co.uk and let me know a good time if you want.

**Comment by Serhansolo** [comment]
Hi guys ... just picked up your convo ... I am having exactly the same problem as @jon64digital is having. I am losing it! I don't know what is wrong with it. could you guys please post a solution after you have finished your debugging session ?

PS. I am not going to bother you guys with screenshots and code excerpts as it is exactly the same info jon gets.

**Comment by svwu** [comment]
It seems to be a general problem...
I'll try with a vanilla install at home to reproduce the error.
When I get it reproduced, I can find my own way to debug it. 

I guess I will recall on you when it's not reproduced at my vanilla install.
I'll let you know when I found out something!

**Comment by jon64digital** [comment]
OK cool. Just so you know, it's a windows 10 machine without any of this previous stuff installed except node/npm/gulp. My process was...

*npm install backstopJS - didn't work
* npm install -g phantomjs (which actually installed as phantomjs-prebuilt) - didn't work
* npm install -g casperjs - didn't work
* Ran phantomJS on it's own - got python not found error
* Installed python which added itself to PATH environment variable
* Ran it and got no errors but no output, then created this issue.

**Comment by mreall** [comment]
I had the exact same issue on Windows 10.  Based on what @jon64digital posted above I got the idea to add the full path to phantomjs.exe ("C:\...\node_modules\phantomjs-prebuilt\lib\phantom\bin") to the PATH environment variable.  I did that, relaunched the command prompt, and finally it worked!  My process was:

- Install python (make sure its folder is added to the PATH)
- npm install backstopjs
- Add the folder with phantomjs.exe to the PATH

I hope this works for you.

**Comment by Serhansolo** [comment]
Okay you guys! I seem to have found the problem on windows! 

I noticed that I was running with SlimerJS where you guys were running PhantonJS. When I changed my engine to PhantomJS everything worked just fine on my vanilla installation. BUT now I wondered why my SlimerJS was not working!.... 

Apparently it had something to do with my relative paths ... in the default backstop.js file there are some paths defined to some folders where backstop puts test output after it has run. 

`"paths": {
    "bitmaps_reference": "../../backstop_data/bitmaps_reference",
    "bitmaps_test": "../../backstop_data/bitmaps_test",
    "compare_data": "../../backstop_data/bitmaps_test/compare.json",
    "casper_scripts": "../../backstop_data/casper_scripts"
  }`

notice the relative way of referencing paths. Once I removed the '../../' part it all worked! Strange... I think this is a SlimerJS bug. Anyway ... This worked for me, I hope I can help anyone with this information!

**Comment by jon64digital** [comment]
Two possible solutions but unfortunately neither of them worked for me.

@mreall - I tried adding my global phantomjs location to the PATH but it made no difference.

@Serhansolo - I tried removing the ../../ from the directory paths but that also didn't work. It's strange bacause if the script is being run from 2 directories down and needs to travers up 2 before going into the screenshots folder then it definitely needs the ../../ so I have no idea how that worked for you.

Interestingly, when I tried switching to slimerjs I got basically the same CLI output but also no screenshots so that's telling me that it's not a phantomjs problem.

**Comment by Serhansolo** [comment]
@jon64digital  after I posted I went on from my vanilla setup to my working project setup and guess what ... removing the ../../ did not work there! :cry: ...

Here is what I discovered after countless hours of Googe'in without any result. I moved my whole project to the root of my directory. I figured could it be .... just ... could it be that my relative path might be affected by the root dir it is in (which had a space in it, my complete project folder was D:/AZ Projects/platform-templates/node_modules/backstopjs/)... AND IT WORKED!.... The problem I found now was that backstop converts your relative paths to absolute paths ... and if there is even 1 space in that whole path name .... it won't work! ...

Do you have a space in the complete path of you folders? This might help! I hope :laughing:  ...

**Comment by jon64digital** [comment]
There is indeed a space in one of my folder names but it's my Dropbox folder so I can't easily change it :(

I'll see if I can and report back.

**Comment by Serhansolo** [comment]
I am definitely having a party if you will fix it! because it was the most stupid bugfix of mu life .. I have spent so many precious hours together with some other developers @ work...

**Comment by jon64digital** [comment]
It's time to party @serhansolo because guess what? It worked!

I moved my project to the root of the c:\ drive and Yep, it produced the screenshots. I also need to work out how to remove spaces from a Dropbox folder (when you have work and business accounts it puts a space in automatically)

I also have a problem with slimerJS now that it is running because it seems incompatible with my Firefox version.

![capture](https://cloud.githubusercontent.com/assets/2878796/17775350/c2a17692-654f-11e6-9cd6-7a6065adc97a.PNG)

But that seems like a Slimer problem, not a Backstop problem. 

I cna't thank everybody enough for helping me sort this out. If Backstop is as useful as I think it's going to be then I'm going to save myself hours of torturous CSS debugging.

**Comment by Serhansolo** [comment]
@jon64digital YAAAY! :tada: 

Backstop is very awesome! We use it olmost daily within out development team. When you make changes you just run the regression and it will show you if it broke something else besides what you fixed!

About you slimer porblem, I know this is not the right thread but if you go to your slimer installation folder (for me it is in /node_modules/slimerjs/lib/slimer/ ) there is a file called application.ini you can change the maxversion value there to an higher version so it will run with your version. so for you I would set it to 50. 

**OR**

You can just go to [https://ftp.mozilla.org/pub/firefox/releases/](url) and doenload version 38 or somthing, that is what I did. Because SlimerJS only support until version 39.* at the moment. I wish you good luck in your life! Live prosper and may the force be with you and such and so on and what have you! :+1:  you can mark the issue as fixed I think we are done here! 

_\*drops mic, and walks out with an attitude*_
