### ISSUE TITLE
Why is the comparison re-run in the browser ?

### ISSUE THREAD

**Issue by onigoetz** [garris/BackstopJS#254]
Hello,

Thanks for your project, it's very useful for a component library I'm working on, but I have a question.

Why does the comparison run in the browser directly ?
If we have the CLI and the browser report, the report information could be reused from one to the other.

For example, always run the comparison in the CLI, and write the result either in the console, xunit report or create a `compare` folder that doesn't need to be run in a server to consult the report.

In my project, I have more than 1'000 Scenarios and needless to say ... the browser dies with that many comparisons to make.

**Comment by machowski** [comment]
same issue here - generating report in the browser takes ages. Would it be possible to make report generation in CLI/Browser configuration option?

**Comment by garris** [comment]
I totally agree with this.  It would be much better to spawn a paged, filterable browser report from an existing CLI result.   If you'd like to contribute this I'm sure there would be lots of happy developers as a result!

Cheers.

**Comment by onigoetz** [comment]
Well, this is great because I opened a pull request that does this : #259 An offline report and some other improvements.

This is currently work in Progress, but works well already.

**Comment by garris** [comment]
😮 Holy crap!  Sounds incredible.  I'll give this a review today.

**Comment by onigoetz** [comment]
Closed as the pull request will be merged soon :D
