### ISSUE TITLE
Generate screenshots for just one scenario

### ISSUE THREAD

**Issue by danwellman** [garris/BackstopJS#255]
Is it possible to generate new reference screenshots for just a single scenario?

I have 150 reference screenshots for a project, which is a set of UX components. When updating the CSS for a single component, it would be nice to be able to generate new reference screenshots for just the component I worked on, rather than for all components.

**Comment by garris** [comment]
There is an enhancement request for this.  see #95    I would really like to see that one implemented.

**Comment by garris** [comment]
You might also consider breaking your config file up into a few smaller ones and selecting the scenario group you want on the CLI.

**Comment by danwellman** [comment]
I did consider breaking up the config, we do have clear lines of division between the components so it would be relatively easy to do. Thanks

**Comment by garris** [comment]
Closed by #259
