### ISSUE TITLE
404s in the report

### ISSUE THREAD

**Issue by danwellman** [garris/BackstopJS#256]
I've got 50 scenarios and 3 viewports, resulting in 150 reference images.

Running the `npm run test` command completes the test run successfully, but when the report page loads up in the browser, it never actually completes.

Either I get 404s for images that I can see in the bitmaps_test/[timestamp]/ folder, or the page gets between 1/4 and 1/2 way through loading all of the images, then crashes (e.g. the 'aw snap' page in Chrome).

I've not seen a successful report yet and have tried numerous times. 

During testing, when I was working with 1 or 2 scenarios, the report page worked perfectly

**Comment by garris** [comment]
Hmm. 404?  I don't think you would see that if it was just a matter of having too many test cases -- but I don't have much context here.   Have you tried the CLI option?  Does that work?

Also, would it work if you were to just run one of the scenarios?

**Comment by danwellman** [comment]
Hello, yes, I'm using the CLI option now, it's working very well with no issues at all. Also, yes, if I run a small selection of scenarios, up to about 20 or so, the HTML page loads fine without any issues

**Comment by garris** [comment]
Ok.  Good to hear.  Our next step is to refactor the web report to handle very large sets.

**Comment by garris** [comment]
Closed by #259
