### ISSUE TITLE
Replace some references and leave the others

### ISSUE THREAD

**Issue by SKOLZ** [garris/BackstopJS#257]
Hello @garris! First of all, thank you for this awesome tool! I want to start using it in the near future so I was checking out how it works. Although everything is working fine, I would like to know if there's a way to say that a test failure is because of an error on my part or otherwise because I intentionally modified those files, in which case I would want to update the reference images of those specific files.

**Comment by garris** [comment]
@SKOLZ There is a feature enhancement request for this... See #95

**Comment by SKOLZ** [comment]
@garris thank you! I'll check it out

**Comment by garris** [comment]
Closed by #259
