### ISSUE TITLE
errors running backstop commands

### ISSUE THREAD

**Issue by danwellman** [garris/BackstopJS#268]
I've got a backstopjs (version 1.3.5)) running perfectly on my own machine, I can run the `npm run reference` command to generate the reference screenshots, and I can run the `npm run test` command without any issues, and it passes or fails when expected (e.g. fails successfully when I modify the CSS for a page)

So I've committed the backstop.json file, the bitmaps_reference folder, the bitmaps_test folder, (but only the compare.json file in here, not the test screenshots) and the capser_scripts directories in the backstop_data folder, to Git.

However, my colleagues are not able to run backstop. My colleague has pulled, and has the files/folders specified above. They have run `npm install` and have Backstop installed. When they try to run the `npm run test` command, they see this output:

>npm run test

> backstopjs@1.3.5 test fakepath\node_modules\backstopjs
> gulp test

>BackstopJS Config loaded at location fakepath\backstop.json
>[11:14:55] Using gulpfile fakepath\node_modules\backstopjs\gulpfile.js
>[11:14:55] Starting 'init'...
>[11:14:55] Finished 'init' after 82 μs
>[11:14:55] Starting 'test'...
>gulp.run() has been deprecated. Use task dependencies or gulp.watch task triggering instead.
>[11:14:55] Starting 'bless'...
>[11:14:55] Finished 'bless' after 5.05 ms

>Running CasperJS with:  [ 'capture/genBitmaps.js' ]
>[11:14:55] Finished 'test' after 16 ms

>Testing script failed with code: 1

>Looks like an error occured. You may want to try running `$ npm run echo`. This will echo the requested >test URL output to the console. You can check this output to verify that the file requested is indeed being received in the expected format.

They also see similar out if trying the `npm run reference` command.

Any ideas why this would work on my machine, but not work on an identical colleague's machine?

**Comment by garris** [comment]
The setup sounds correct.   What are the OS, node, npm versions?

**Comment by danwellman** [comment]
I'm going to have to get back to you with more information in a couple of weeks as I'll be away from the office (and my colleague) for a short while. I'll get this info back to you as soon as I can, thanks.

**Comment by DigitalKrony** [comment]
I'm haveing the exact same issue. 

OS: Win10(ent)
Node: v4.4.3
NPM -list:
└── backstopjs@1.3.5

Backstop -list:
├── casperjs@1.1.3
├── checksum@0.1.1
├── del@0.1.3
├── express@3.21.2
├── fs-extra@0.12.0
├── gulp@3.9.1
├── gulp-jscs@1.6.0
├── gulp-jscs-stylish@1.4.0
├── gulp-jshint@1.12.0
├── gulp-json-editor@2.2.1
├── gulp-open@0.3.2
├── gulp-rename@1.2.2
├── http-proxy@1.1.6
├── is-running@1.0.5
├── junitwriter@0.3.1
├── node-resemble-js@0.0.4
├── phantomjs-prebuilt@2.1.12
├── require-dir@0.1.0
├── underscore@1.6.0
└── yargs@3.9.1

**Comment by garris** [comment]
Are the npm and node versions in sync on all machines.

**Comment by DigitalKrony** [comment]
As of right now, I'm just trying to get this to run on one machine. But I've attempted it on three machines and have and the same result on all three. Versions are kept up-to-date from machine to machine.

**Comment by garris** [comment]
i am suspecting it is an issue with either phantom (or slimmer -- if you're using that).   Have you tried a simple install on your other machine?  Just install the app.  Do genConfig then reference then test.  Does that work?

**Comment by DigitalKrony** [comment]
So far I've been just trying to get just the basic NPM install working. So that comes with PhantomJS.

genConfig: Works
reference: fails
test: fails

**Comment by danwellman** [comment]
I'm suspecting Phantom also, we aren't using slimer. I'm out of the country at present, will confirm in a week or so.

Get Outlook for iOS




On Fri, Sep 2, 2016 at 9:16 PM +0200, "Garris" <notifications@github.com> wrote:





i am suspecting it is an issue with either phantom (or slimmer -- if you're using that).   Have you tried a simple install on your other machine?  Just install the app.  Do genConfig then reference then test.  Does that work?

**Comment by garris** [comment]
If you are on Windows then this might help...  https://github.com/garris/BackstopJS/issues/185

**Comment by danwellman** [comment]
We are on Windows, but I'm not sure this is the answer - we have Phython 2.x for Karma

Get Outlook for iOS




On Fri, Sep 2, 2016 at 10:13 PM +0200, "Garris" <notifications@github.com> wrote:





If you are on Windows then this might help...  https://github.com/garris/BackstopJS/issues/185

**Comment by DigitalKrony** [comment]
No dice with the Python install.

**Comment by garris** [comment]
@danwellman thanks for the update!  Cheers.  Garris
