### ISSUE TITLE
Update of reference

### ISSUE THREAD

**Issue by ipeshev** [garris/BackstopJS#271]
It would be great to have some possibility to update just part of reference , for example when new scenarios are added and we need reference snapshots for them.

**Comment by garris** [comment]
Yup.  It's on the list.   I could really use help on the feature if you have any free cycles.

**Comment by garris** [comment]
📢 This was included in 2.0 released yesterday.

See... https://github.com/garris/BackstopJS#updating-or-testing-just-one-scenario-filtering

Cheers!
