### ISSUE TITLE
Error when running 'npm run reference': bitmaps_reference folder not created.

### ISSUE THREAD

**Issue by robertmazzo** [garris/BackstopJS#278]
I'm also following along at https://css-tricks.com/automating-css-regression-testing/ , but I am getting errors when running `npm run reference`.

I have downloaded the `myCoolProject` zip file. My project dir structure is:
- myCoolProject
   - backstop_data
   - dist
   - node_modules
  
      .DS_Store
     backstop.json
     index.html

Details:
Node version 6.5.0
I have installed backstopjs --> npm install backstopjs 

And btw, I am troubleshooting based on your previous suggestion on March 10th (#171 ):
$ npm run genConfig
$ npm run reference
$ npm run test

Is there an issue with my gulp version, as per this error ?

 gulp.run() has been deprecated. Use task dependencies or gulp.watch task triggering instead.

Here is my command line execution from Win 7 :

     ..\myCoolProject\node_modules\backstopjs>npm run reference

Here is the output:

backstopjs@1.3.5 reference C:\Bob\dev\pluralsight\backstopjs-test\myCoolProjec
t\node_modules\backstopjs
gulp reference

BackstopJS Config loaded at location C:\Bob\dev\pluralsight\backstopjs-test\myCo
olProject\backstop.json
[09:38:40] Using gulpfile C:\Bob\dev\pluralsight\backstopjs-test\myCoolProject\n
ode_modules\backstopjs\gulpfile.js
[09:38:40] Starting 'clean'...
bitmaps_reference was cleaned.
[09:38:40] Starting 'bless'...
[09:38:40] Finished 'bless' after 7.98 ms
[09:38:40] Finished 'clean' after 20 ms
[09:38:40] Starting 'reference'...
gulp.run() has been deprecated. Use task dependencies or gulp.watch task trigger
ing instead.
[09:38:40] Starting 'init'...
[09:38:40] Finished 'init' after 8.08 µs
[09:38:40] Starting 'test'...

Generating reference files.

Running CasperJS with: [ 'capture/genBitmaps.js' ]
[09:38:40] Finished 'test' after 12 ms
reference has run.
[09:38:40] Finished 'reference' after 18 ms

Testing script failed with code: 1

Looks like an error occured. You may want to try running $ npm run echo. This
will echo the requested test URL output to the console. You can check this outpu
t to verify that the file requested is indeed being received in the expected for
mat.

C:\Bob\dev\pluralsight\backstopjs-test\myCoolProject\node_modules\backstopjs>

**Comment by garris** [comment]
@robertmazzo Just checking in here.  Did you test PhantomJS on your machine?  I suspect that is the issue.   Also,  We're about to release version 2.0.  You could try that -- check the documentation here https://github.com/garris/BackstopJS/blob/version_2_0/README.md for install and config changes.

**Comment by agentdylan** [comment]
Hey I was getting the same error, I fixed it by installing Python - as recommended here https://github.com/garris/BackstopJS/issues/185

**Comment by robertmazzo** [comment]
@garris thank you for following up. I wasn't able to spend time on this, so I'll def try to get back on version 2.0 on my home machine pretty soon. 
@agentdylan thank you for your feedback on install Python.

**Comment by robertmazzo** [comment]
@garris should I'll this until I resolve my issues ? I don't want to clutter up your github issues section. regards...Bob.
