### ISSUE TITLE
Some tests fail when mismatched % is less than the threshold

### ISSUE THREAD

**Issue by zcchew1202** [garris/BackstopJS#282]
Has anyone had this issue before?

**Comment by garris** [comment]
it can also fail if the image size is different.   Please post example.

**Comment by zcchew1202** [comment]
![screenshot_21](https://cloud.githubusercontent.com/assets/7612989/18598432/b868e39e-7c20-11e6-8d4b-94bb43ebfe46.png)
Here I changed the padding of the jumbotron from 0px to 2px and set the threshold to 15. I used the example on csstricks.

**Comment by garris** [comment]
Thank you for posting the example.   Yes, this is behaving correctly.   If the size of the element changes it will trigger a "fail".  In your example the height shows a 4px difference -- that is what is causing the condition.  The threshold setting does not apply to height or width differences.
