### ISSUE TITLE
Use semantic versioning & publishing to support regular NPM installs of v2

### ISSUE THREAD

**Issue by uglow** [garris/BackstopJS#284]
Would it be possible for you to publish version 2 on either the @latest or @beta distribution channels in NPM?  E.g.: `npm i backstopjs@beta` or `npm i backstopjs@2.0.0-beta`?

The current "published" URL is not recognised in my tooling setup, and doesn't follow the normal semantic publishing conventions for beta packages.

**Comment by garris** [comment]
Thanks for the post.  Will try to get to this.

**Comment by abangser** [comment]
Just a :+1: to this. Would love to upgrade since we are finding flaky failures on the older version that we thing are fixed in the new one! Thanks!

**Comment by garris** [comment]
Done!   Use `npm install backstopjs@beta`
