### ISSUE TITLE
The CI report is illegible

### ISSUE THREAD

**Issue by Miriloth** [garris/BackstopJS#288]
The CI report generated by BackstopJS is illegible due to lack of new lines or whitespaces. 

``<?xml version="1.0" encoding="UTF-8"?>
<testsuites errors="1" failures="1"><testsuite name="BackstopJS" tests="1" errors="1" failures="1"><testcase name=" ›› BackstopJS Homepage" classname="body"><error message="Design deviation ›› BackstopJS Homepage (body) component" type="CSS component"/><failure message="Design deviation ›› BackstopJS Homepage (body) component" type="CSS component"/></testcase></testsuite></testsuites>``

**Comment by garris** [comment]
Please provide screenshot and any other examples.
