### ISSUE TITLE
npm run test failing for specific test scenario involving login

### ISSUE THREAD

**Issue by rajesh825** [garris/BackstopJS#290]
Hello,

I'm seeing following failure on running "npm run reference; npm run test"  

Server launched in background with PID: 52684
Listening on port: 3001
NOTE: Sever will auto-shutdown in 15 mins.

[13:39:27] Finished 'start' after 1.01 s
[13:39:27] Starting 'report'...
[13:39:27] Finished 'report' after 610 μs
[13:39:28] Starting 'compare'...
 ERROR: Test Page 0_0_document_0_tablet_h.png
   See: /Users/testuser/TestProjects/perceptualTesting/backstop_data/bitmaps_test/20160923-133916/failed_diff_0_0_document_0_tablet_h.png

Test completed...
 0 Passed
 1 Failed

 *** Mismatch errors found ***
For a detailed report run `npm run openReport`

[13:39:28] 'compare' errored after 544 ms
[13:39:28] Error: Mismatch errors found.
    at updateProgress (/Users/testuser/TestProjects/perceptualTesting/node_modules/backstopjs/gulp/tasks/compare.js:37:22)
    at Array.<anonymous> (/Users/testuser/TestProjects/perceptualTesting/node_modules/backstopjs/gulp/tasks/compare.js:77:13)
    at triggerDataUpdate (/Users/testuser/TestProjects/perceptualTesting/node_modules/backstopjs/node_modules/node-resemble-js/resemble.js:69:28)
    at onceWeHaveBoth (/Users/testuser/TestProjects/perceptualTesting/node_modules/backstopjs/node_modules/node-resemble-js/resemble.js:447:6)
    at null.<anonymous> (/Users/testuser/TestProjects/perceptualTesting/node_modules/backstopjs/node_modules/node-resemble-js/resemble.js:125:13)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at null.<anonymous> (/Users/testuser/TestProjects/perceptualTesting/node_modules/backstopjs/node_modules/node-resemble-js/node_modules/pngjs/lib/png.js:52:14)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
[13:39:28] Starting 'openReport'...

Testing with  ../../backstop_data/bitmaps_test/compare.json
Opening report ->  http://localhost:3001/compare/

[13:39:28] Finished 'openReport' after 11 ms
 Regression test report file (xunit.xml) is successfully created.

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "test"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE
npm ERR! backstopjs@1.3.5 test: `gulp test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the backstopjs@1.3.5 test script 'gulp test'.
npm ERR! This is most likely a problem with the backstopjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp test
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs backstopjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls backstopjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/testuser/TestProjects/perceptualTesting/node_modules/backstopjs/npm-debug.log

Please refer to content of npm-debug.log

 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'test' ]
2 info using npm@2.14.20
3 info using node@v4.4.0
4 verbose run-script [ 'pretest', 'test', 'posttest' ]
5 info pretest backstopjs@1.3.5
6 info test backstopjs@1.3.5
7 verbose unsafe-perm in lifecycle true
8 info backstopjs@1.3.5 Failed to exec test script
9 verbose stack Error: backstopjs@1.3.5 test: `gulp test`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid backstopjs@1.3.5
11 verbose cwd /Users/testuser/TestProjects/perceptualTesting/node_modules/backstopjs
12 error Darwin 15.6.0
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "test"
14 error node v4.4.0
15 error npm  v2.14.20
16 error code ELIFECYCLE
17 error backstopjs@1.3.5 test: `gulp test`
17 error Exit status 1
18 error Failed at the backstopjs@1.3.5 test script 'gulp test'.
18 error This is most likely a problem with the backstopjs package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     gulp test
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs backstopjs
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls backstopjs
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

# I'm using following file for backstop.json
`{
  "viewports": [
    {
      "name": "tablet_h",
      "width": 1280,
      "height": 1024
    }
  ],
  "scenarios": [

    {
      "label": "Content List Page",
      "referenceUrl": "https://prodpublishing.gov.uk/#/",
      "url": "https://test.publishing.gov.uk/#/",
       "hideSelectors": [],
      "removeSelectors": [
        "#carbonads"
      ],
      "selectors": [
        "document"

      ],
      "readyEvent": null,
      "delay": 500,
      "misMatchThreshold" : 0.1,
      "onBeforeScript": "onBefore_Login.js",
      "onReadyScript": "onReady.js"
    }

  ],
  "paths": {
    "bitmaps_reference": "../../backstop_data/bitmaps_reference",
    "bitmaps_test": "../../backstop_data/bitmaps_test",
    "compare_data": "../../backstop_data/bitmaps_test/compare.json",
    "casper_scripts": "../../backstop_data/casper_scripts",
    "ci_report" :  "../../backstop_data/ci_report"
  },
  "ci": {
      "format" :  "junit" ,
      "testReportFileName": "gov-rubric-xunit",
      "testSuiteName" :  "backstopJS"
},
  "engine": "phantomjs",
  "report": ["CLI", "browser", "CI"],
  "casperFlags": [],
  "debug": true,
  "port": 3001
}
`

## Following onBefore_Login.js script used to login to form

`module.exports = function(casper, scenario, vp) {

  var url = scenario.url;
  if (isReference && scenario.referenceUrl) {
    url = scenario.referenceUrl;
  }

  var newUrl = url.split('/#')[0] + "/#/login";
    
  casper.wait(4000);
  casper.echo( 'waited for  400 ms' );
 
  casper.start(newUrl, function() {
      this.fillSelectors('form', {
        'input[id="username"]' : 'username@email',
        'input[id="password"]' : 'password'
      }, true);
  });

  casper.then(function() {
      this.click('button[ng-click="submitLogin()"]');
  });

 casper.wait(8000);

});
`

**Comment by garris** [comment]
BackstopJS 2.0 was soft launched yesterday.  It is a complete rewrite and will probably address your issue.   

The difference for your existing scripts is that BackstopJS is now a global install and paths are relative to your current working directory.  E.G. you just run `backstop <command>` from your project directory. And config paths would look like **`backstop_data/casper_scripts`** *not `../../backstop_data/casper_scripts`*.

**Comment by rajesh825** [comment]
Issue resolved after using BackstopJS 2.0

**Comment by garris** [comment]
Thanks for following up!
