### ISSUE TITLE
Is it possible to batch test multiple config files at once

### ISSUE THREAD

**Issue by stephenbe** [garris/BackstopJS#294]
Hello,

Congratulations on the 2.0 soft release yesterday! I was wondering if it is possible to test batch multiple config files at once.

Let's say I have 
buttons.json
forms.json
etc

Imagine I have 20 json files, is there a way to test all of them at once or are you obliged to test them one after another in the command line by hand? 

What would be cool is being able to create scenarios in different json files and calling them to the main json file. Like being able to create gulp task in their own file.

Thanks!

**Comment by garris** [comment]
If the performance and other options are ok you could write a node script to `require()` all of your configs and just concatenate scenarios...

you could create a file called `allMyBackstopTests.js` ...
```
var myButtonScenarios = require('buttons').scenarios;
var myFormScenarios = require('buttons').scenarios;

var allScenarios = [].concat(myButtonScenarios, myFormScenarios);

module.exports = {
  scenarios: allScenarios
  ... all other backstopjs required props here ... 
};
```

You of course could jazz this up in a lot of ways -- but that's one way to do it.

Is this kind of what you mean?

**Comment by garris** [comment]
Oh and thanks for the kind 2.0 words.   It was a huge effort  but I am really happy with it.   😊

**Comment by stephenbe** [comment]
Okay great, I'll look into it and tell you if it works! 😀

**Comment by stephenbe** [comment]
Hey @garris ,

So I figured it out, it seems to be working correctly, but once it goes on the second js file, it doesn't switch the url correctly, it stays on the same page.


Here is my setup : 
Main backstopjs file :
```
var myButtonScenarios = require('./buttons').scenarios;
var myFormScenarios = require('./headings').scenarios;
var allScenarios = [].concat(myButtonScenarios, myFormScenarios);
//console.log(allScenarios);
module.exports = {
  "viewports": [
    {
      "name": "tablet_h",
      "width": 1024,
      "height": 768
    }
  ],
  scenarios: allScenarios,
  "paths": {
    "bitmaps_reference": "backstop_data/bitmaps_reference",
    "bitmaps_test": "backstop_data/bitmaps_test",
    "compare_data": "backstop_data/bitmaps_test/compare.json",
    "casper_scripts": "backstop_data/casper_scripts"
  },
  "engine": "phantomjs",
  "report": ["browser", "CLI"],
  "debug": false,
  "port": 3001
};
```
Buttons :
```
exports.scenarios  = {
  "label": "Tous les boutons",
  "url": "http://localhost:4000/documentation/3.3/composantes.html#boutons",
  "referenceUrl": "http://localhost:4000/documentation/3.3/composantes.html#boutons",
  "selectors": [
    "#n3-doc-btn-a .btn-default",
    "#n3-doc-btn-a .btn-primary",
    "#n3-doc-btn-a .btn-primary.btn-block",
    "#n3-doc-btn-a .btn-danger",
    "#n3-doc-btn-a .btn-primary.crochet",
    "#n3-doc-btn-a .btn-primary.cadenas",
    "#n3-doc-btn-a .btn-default.precedent",
    "#n3-doc-btn-a .btn-default.suivant"
  ],
  "misMatchThreshold" : 1,

}

```
Headings
```
exports.scenarios  = {
  "label": "Tous les headings",
  "url": "http://localhost:4000/documentation/3.3/composantes.html#typographie",
  "referenceUrl": "http://localhost:4000/documentation/3.3/composantes.html#typographie",
  "selectors": [
    "#n3-doc-heading"
  ],
  "misMatchThreshold" : 1,
}
```

So buttons work correctly, but once it switches to headings it stays on the buttons url...

Would you know why this is happening?

**Comment by garris** [comment]
Is this an SPA?    Please include a screenshot of `body` so we can confirm pages state.

**Comment by stephenbe** [comment]
Yes this is a handbuilt SPA with jQuery, I will take the screenshots won't be long

**Comment by stephenbe** [comment]
![0313431307_tous_les_headings_0_body_0_tablet_h](https://cloud.githubusercontent.com/assets/3018441/19000141/f9035eb8-870e-11e6-8cf8-74890140db6b.png)
![0313431307_tous_les_boutons_0_body_0_tablet_h](https://cloud.githubusercontent.com/assets/3018441/19000142/f90d056c-870e-11e6-96b0-73e991ef1ad4.png)

Both are exactly the same even though I have two different urls. So when I try to get #n3-doc-heading, it doesn't find it and generates the gray picture.

**Comment by garris** [comment]
I don't think this is related to the script your wrote.   The part you are talking about is called a `fragment` -- its the part after the `#` symbol.  

To test this, please create a new single config with two scenarios.  Make sure the scenarios are the same ones from your previous example.   Take two full screen captures of your SPA with different fragments and I expect it will behave the same.  This should take 2 mins.   Can you try that and let me know how it goes?   The issue is likely with phantom -- I don't think your app router is getting the hashchange event that it expects.

**Comment by stephenbe** [comment]
To make sure we are on the same page : 
```
exports.scenarios1  = {
  "label": "Tous les boutons",
  "url": "http://localhost:4000/documentation/3.3/composantes.html#boutons",
  "referenceUrl": "http://localhost:4000/documentation/3.3/composantes.html#boutons",
  "selectors": [
    "body"
  ],
  "misMatchThreshold" : 1,
}
exports.scenarios2  = {
  "label": "Tous les headings",
  "url": "http://localhost:4000/documentation/3.3/composantes.html#typographie",
  "referenceUrl": "http://localhost:4000/documentation/3.3/composantes.html#typographie",
  "selectors": [
    "body"
  ],
  "misMatchThreshold" : 1,

}

```

The result is the same

**Comment by stephenbe** [comment]
Do you mean a single json config file without the requires?

**Comment by garris** [comment]
yes.   Just to confirm it is not your fine concat script.

**Comment by stephenbe** [comment]
Okay something interesting happened...In the one json config I had two more viewports and on the first one for typographie I got the gray icone and on the second and third it worked. I don't know what this means though.

I applied the two other viewports to my original backstop.js and it had the exact same behavior. So it seems that it doesn't change at first, but the second and third viewport it works.

**Comment by garris** [comment]
PROGRESS!  🏇

**Comment by stephenbe** [comment]
hahaha yes I agree! so what is the next steps that we need to take? 👊

**Comment by garris** [comment]
ok. So actually, this closes your original issue.   would you mind opening another issue -- we can work on this fagment thing over there.   Please just state the behaivior and I will follow up when I can -- gotta do real work now.    (In the meantime, you can probably fix it with an onReady script -- by adding an initial (throwaway) viewport for all scenarios)

**Comment by stephenbe** [comment]
Alright sounds good, hey by the way I was thinking of writing up a quick medium post to sum up what I learned on working with multiple config files. I think this could benefit a lot of people that aren't familiar with scripting with node

**Comment by garris** [comment]
That's wonderful!   Yes, this is a really powerful feature that I think a lot of users probably don't know about -- so it would be great to do an article on the topic!  Please let me know if you want any assistance -- I'd be happy to help.  😊

**Comment by aboutandre** [comment]
Hey @stephenbe did you come around writing that article?
I have the same question now and would love to take a look at how you fixed this. If no article, a gist or some commit should be fine to set me on the right track ;-)

Cheers!

**Comment by alucardu** [comment]
Any updates on the batch feature? I can't find any documentation beyond this thread.

**Comment by andrewJbenson** [comment]
@stevenbriscoeca  - to dredge this one up again, did you ever document/publish the multiple config process?
cheers
