### ISSUE TITLE
Loading fragment does not work on first viewport

### ISSUE THREAD

**Issue by stephenbe** [garris/BackstopJS#297]
Hello,

If you have two scenarios with two different urls, and multiple viewports, the first viewport with return a gray icon. I am using a handbuilt spa with jQuery.
```
    {
      "label": "Tous les boutons",
      "url": "http://localhost:4000/documentation/3.3/composantes.html#boutons",
      "referenceUrl": "http://localhost:4000/documentation/3.3/composantes.html#boutons",
      "selectors": [
        "body"
      ],
      "misMatchThreshold" : 1
    },
    {
      "label": "Tous les headings",
      "url": "http://localhost:4000/documentation/3.3/composantes.html#typographie",
      "referenceUrl": "http://localhost:4000/documentation/3.3/composantes.html#typographie",
      "selectors": [
       "body"
      ],
      "misMatchThreshold" : 1
    }
```
This issue has been opened following this conversation : 
https://github.com/garris/BackstopJS/issues/294

**Comment by stephenbe** [comment]
Additionally, I added further tests before switching pages to typographie with a parameter

http://localhost:4000/documentation/3.3/composantes.html?wl=bleh#boutons

Then typographie first screencapture works for some reason.

**Comment by garris** [comment]
My guess is that phantomjs does not issue the hashchange event your app is looking for.   Does your app rely on that event to do route switching?   Here is someone else with that issue...  https://github.com/Medium/phantomjs/issues/621   It makes sense because by adding a query param you force a window reload and therefore you get the result you expect.

**Comment by stephenbe** [comment]
For my project, now that I use parameters, it works. Anyone that reads this issue could put some ?foobar=true in the url to force the change...I think no further testing is needed...hopefully phantomjs will resolve the problem in the future!

Thanks @garris !
