### ISSUE TITLE
Different bitmaps_reference folder for each scenario

### ISSUE THREAD

**Issue by stephenbe** [garris/BackstopJS#298]
Hello,

Would it be possible to have a different bitmaps_reference folder for each scenario instead of having it globally?

This way, I could store each scenario in different folders ex (buttons/, forms/)

I see each scenario like a gulp task, you set what ever option you want there specific to that scenario. I think that makes more sens! Every option should be in the scenario.

Thanks!

**Comment by garris** [comment]
If this is what you want you'll need to run multiple configs. 

You can try this with node...

e.g.  create a script `backstop_batch.js` at the root of your project...   Then run.   The scrips will be run sequentially and output will be put to the console after each has run.
```
var execSync = require('child_process').execSync;

var currentProcessStdout = '';

currentProcessStdout = execSync('backstop test --config=<pathToYourFile>', {encoding: 'utf8'});

console.log('currentProcessStdout >', currentProcessStdout);

currentProcessStdout = execSync('backstop test --config=<pathToYourOtherFile>', {encoding: 'utf8'});

console.log('currentProcessStdout >', currentProcessStdout);
```

There are lots of examples for doing this and handling errors (which the above example doesn't do).   You should google around for some ideas.   Please let me know if you put together a nice multiple script runner -- I'd be happy to post that to the examples directory.

Hope this helps.

**Comment by stephenbe** [comment]
I didn't know you could do that with node, thank you I will check it out!

**Comment by stephenbe** [comment]
For now our team wont explore this option. I will close, but anyone with the same idea could test this out and re-open the issue
