### ISSUE TITLE
show Mismatch in CI output

### ISSUE THREAD

**Issue by Primajin** [garris/BackstopJS#306]
So back then I added some (I think) useful information to the CI output: when a mismatch error occurs, the output should show how high it is - so I know it's a _real_ regression or its just off by 0.1% and I need to increase threshold ;)

https://github.com/Primajin/BackstopJS/commit/6284fdb5e74b6d71669bc159e37d1da61bc70fff

So it would be great if you guys would add something like this again.

**Comment by garris** [comment]
Sorry about that.   We were trying to make as few changes as possible while migrating to 2.0.   Will put this in the backlog.   Thanks.

**Comment by Primajin** [comment]
Great! :tada:
