### ISSUE TITLE
HTTP Server Configuration

### ISSUE THREAD

**Issue by angelariggs** [garris/BackstopJS#308]
The README in the html_report folder says 
```
./compare/*
====

`config.js` is generated by `$ backstop test`.

`index.html` is opened by `$ backstop test` after screenshots are generated and the local http server is started.

The HTTP server will auto-shutdown after a 15 minute timeout to save you the trouble of cleaning it up yourself. You can configure this in `./server.js`
```
But I don't see a `server.js` file. Is this something that should be generated by one of the backstop commands?

**Comment by garris** [comment]
If you are using BackstopJS 2.x that should be deleted.   Was only applicable for 1.x.   The new reports just open from your file system.

**Comment by angelariggs** [comment]
Oh okay! Thank you :) I'll close this out.
