### ISSUE TITLE
Components failing tests when mismatch percent is near zero.

### ISSUE THREAD

**Issue by code-mattclaffey** [garris/BackstopJS#313]
Our mismatchThreshold is set as follows: `"misMatchThreshold": 5,` however when the tests run certain tests fail and say `"isSameDimensions": false,`.

Here's an example of some screenshots where the tests _should_ pass but don't seem to.

![prod_test_hillarys_styleguide_30_introbanner_2_desktop](https://cloud.githubusercontent.com/assets/10598938/19303001/bb36ea42-905e-11e6-9fe1-af55ab096095.png)

![prod_test_hillarys_styleguide_30_introbanner_2_desktop 1](https://cloud.githubusercontent.com/assets/10598938/19303013/c434beda-905e-11e6-8fd3-fdaf7936d83b.png)

Here's the output result from the report:

```
Report: {
  "isSameDimensions": false,
  "dimensionDifference": {
    "width": 0,
    "height": -1
  },
  "misMatchPercentage": "0.48"
}
Threshold: 1
```

This happens on around 8-10 tests, intermittently. Are we missing something, or is there a way to turn off the `isSameDimensions` property? Is this expected?

Thanks in advance for your advice.

**Comment by garris** [comment]
I think maybe you should see which element is causing your issue.   Other things to consider: Are you sharing with different machines?  Are there any animations?   Is your CSS math producing half pixel values?   Is content changing from test to test?

There are plans to incorporate a control for this:  but you want to be sure this error isn't exposing a performance issue.  This behavior usually means there is some unknown thing moving your CSS around.

**Comment by code-mattclaffey** [comment]
Thanks ill try that but if my misMatchThreshold is set to 5 shouldn't the test be ignored then because the misMatchPercentage was under that. Is it the isSameDimensions thats throwing it off?

**Comment by garris** [comment]
Currently -- if `isSameDimentions === false` then tests will fail.

**Comment by Primajin** [comment]
I'll try to PR my stuff from #306 soon, then you can at least see in the output that it fails because of different dimensions and not because of missmatch errors.

**Comment by code-mattclaffey** [comment]
Awesome! Please update the issue when you have made the PR.

Thank you :)

**Comment by Primajin** [comment]
See #314 :)

**Comment by YoungElPaso** [comment]
Seems odd that dimensions should be required to be exactly the same.  I guess its fine, but it might be better if there was a fuzziness applied to that no?  A height/width dimension threshold maybe?  I suppose this might just be a matter of opinion.

**Comment by garris** [comment]
Considering the existing config options, how would you specify the ranges?  What seems intuitive?

**Comment by YoungElPaso** [comment]
I dunno. That's a tough one.  I guess it'd be a differential that you could plug in per viewport?  This is a tough subject :)

**Comment by garris** [comment]
That is why there hasn't been anything implemented yet.  Please post here if you come up with something good.   👍

**Comment by jtuds** [comment]
Why does isSameDimensions need to be true when you can set a mismatch threshold? A mismatch can cause a change in dimensions, so they naturally don't go together. I have a scenario where my font rendering is slightly off which causes the height of my test to be slightly different to my reference, as the font renders slightly larger, this is an acceptable mismatch but because it changes the height, the test fails.

Why is isSameDimensions a thing alongside the mismatch?

**Comment by Primajin** [comment]
I could only imagine it was faster to test for dimension mismatch before going in deep with resembleJS. But @jtuds has a valid point, I think.

**Comment by garris** [comment]
I agree with this.  Do we just want to add a binary switch to disable testing for size.

**Comment by Primajin** [comment]
Yes I think this would be good. But it should be on the same level as the `misMatchThreshold`, so I can set it to true for one test, and false for another.

**Comment by jtuds** [comment]
Yep I agree with @Primajin.

**Comment by garris** [comment]
👍

**Comment by cheapaschips** [comment]
Great program by the way @garris, I too agree with @Primajin this functionality would be perfect. I'm guessing this functionality might take some time to put into a build?

**Comment by cdaringe** [comment]
im not sure i'm following this thread full well, but i have a similar problem.

the phantomjs on my ci server behaves differently than on my MBP.

![screen shot 2017-03-08 at 3 25 31 pm](https://cloud.githubusercontent.com/assets/1003261/23728800/7d68b168-0413-11e7-9222-c9eaad6a2275.png)

```
Report: {
  "isSameDimensions": false,
  "dimensionDifference": {
    "width": 0,
    "height": 1
  },
  "misMatchPercentage": "0.00",
  "getDiffImage": null
}
Threshold: 1
```

even w/ a mistmatch of `50`, this still tanks.  im going for a rough pass here, so im willing to be a little sloppy.  does someone see what im missing?

Thx!

**Comment by Primajin** [comment]
Do you see the output in the CI Server? Just search for 'ERROR', can you post the line where it fails here?

**Comment by jtuds** [comment]
This is most probably because of the mismatch in height. If there is a height mismatch the tests fail. This is fixed in my pull request number #331

**Comment by cdaringe** [comment]
@Primajin, thx!

> compare | ERROR { size: isDifferent, content: 0.00%, threshold: 50% }: Octagon \<huge-filename>.png
   See: /\<ci-root>/\<huge-filename>.png

@jtuds, looks cool, and close to being merged :)

**Comment by Primajin** [comment]
`size: isDifferent` ;)
