### ISSUE TITLE
Incremental Reference Screenshot Updates Isn't Working

### ISSUE THREAD

**Issue by angelariggs** [garris/BackstopJS#318]
The docs say
"If you need to update references (or test) for just one app-state you can do so by invoking BackstopJS with the following argument: `$ backstop reference --filter=<scenario.label>`"

The scenario that I want to update is the 10th item (0-index) in my list of scenarios, so I tried running:
`$ backstop reference --configPath=prod_backstop.json --filter=scenario[10].label`. And I'm getting `zsh` errors as a result: `zsh: no matches found: --filter=scenarios[10].label`. Note: I initially used `scenarios.label` (plural) instead of the singular version in the docs, because the config file has the plural; but I also tried the singular `scenario.label` with the same result.

**Comment by garris** [comment]
If your config looks something like:   `{ ... scenario: "landing-page", ... }`  then you would want to invoke that like this  `backstop reference --filter=landing-page`

**Comment by angelariggs** [comment]
My config file is this (with just a couple of scenarios for a shorter example): 
```
{
  "id": "meyer_prod_config",
  "viewports": [
    {
      "name": "desktop",
      "width": 1200,
      "height": 3000
    },
  ],
  "scenarios": [
    {
      "label": "Item 0: Meyer > Homepage",
      "url": "https://mmt.pantheonsite.io/",
      "hideSelectors": [],
      "removeSelectors": [],
      "selectors": [
        "body"
      ],
      "readyEvent": null,
      "delay": 500,
      "misMatchThreshold" : 0.1
    },
    {
      "label": "Item 1: Meyer > Trustee Landing Page",
      "url": "https://mmt.pantheonsite.io/about/trustees",
      "hideSelectors": [],
      "removeSelectors": [],
      "selectors": [
        "body"
      ],
      "readyEvent": null,
      "delay": 500,
      "misMatchThreshold" : 0.1
    },
    {
      "label": "Item 2: Meyer > Trustee: Toya Fick",
      "url": "https://mmt.pantheonsite.io/about/trustees/toya-fick",
      "hideSelectors": [],
      "removeSelectors": [],
      "selectors": [
        "body"
      ],
      "readyEvent": null,
      "delay": 500,
      "misMatchThreshold" : 0.1
    }
  ],
  "paths": {
    "bitmaps_reference": "backstop_data/prod_reference",
    "bitmaps_test": "backstop_data/prod_test",
    "casper_scripts": "backstop_data/casper_scripts",
    "html_report": "backstop_data/prod_html_report",
    "ci_report": "backstop_data/prod_ci_report"
  },
  "casperFlags": [
    "--ignore-ssl-errors=true",
    "--ssl-protocol=any"
  ],
  "engine": "phantomjs",
  "report": ["browser"],
  "debug": false
}
```
So if I wanted to re-do the references for Item 1, would I technically run `backstop reference --configPath=prod_backstop.json --filter=Item 1: Meyer > Trustee Landing Page`? (Which would mean I picked terrible labels :) )

**Comment by angelariggs** [comment]
(Also, I realize that I titled this issue "... Isn't Working", but it should really say "... Isn't Working For Me Yet" 😄

**Comment by garris** [comment]
A for effort!

**Comment by angelariggs** [comment]
Success! Thank you 😄  Also, I LOVE the 2.x updates to BackstopJS! It's really helpful for our projects.

**Comment by garris** [comment]
🐥  Hey great!   Thanks for the feedback -- so glad it's useful for you!

Cheers.
