### ISSUE TITLE
ERROR: "TypeError: Path must be a string. Received undefined"

### ISSUE THREAD

**Issue by tyler36** [garris/BackstopJS#323]
First, thank you for providing this package. I find it very useful for comparing CSS changes and grabbing screen shots for other documentation.

I had it all working with v2.0.3 but recently updated while i was playing with yarn.
I get the following error on v2.0.4, v2.0.5 & 2.0.6.

```
Running CasperJS with:  [ '[[ PATH ]]\\node_modules\\backstopjs\\capture\\genBitmaps.js' ]
COMMAND | Command `reference` ended with an error
COMMAND | TypeError: Path must be a string. Received undefined
              at assertPath (path.js:8:11)
              at Object.win32.join (path.js:221:5)
              at module.exports ([[ PATH ]]\node_modules\backstopjs\core\util\findExecutable.js:16:15)
              at module.exports ([[ PATH ]]\node_modules\backstopjs\core\util\runCasper.js:30:23)
              at [[ PATH ]]\node_modules\backstopjs\core\util\createBitmaps.js:51:23

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\ProgramFiles\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "bjs:question:ref"
npm ERR! node v5.5.0
npm ERR! npm  v3.3.12
```

I've removed the path from the output ([[ PATH]]) to keep it simple. 

SETUP:
OS: Win10
NODE: 5.5.0
NPM: 3.3.12

**Comment by garris** [comment]
Does this still happen if you just cd into a test directory and run `backstop genConfig`  then run the reference and test commands?

**Comment by tyler36** [comment]
OK ... did some more testing. Seems there an issue if I install via YARN.
On top of a fresh copy of Laravel, it works via NPM.
On top of a fresh copy of Lavavel, it fails via YARN.

**Comment by tyler36** [comment]
Seems there are issue with YARN and phantomJS that may be related:
[987](https://github.com/yarnpkg/yarn/issues/987)
[1015](https://github.com/yarnpkg/yarn/issues/1015)
[1016](https://github.com/yarnpkg/yarn/issues/1016),

**Comment by Ruskyj** [comment]
@tyler36 I can confirm, having the same issue (with the same error output) when installed via Yarn. Works fine with regular NPM install. 

OSX 10.11.6
NODE: 4.2.1
NPM: 2.14.7

**Comment by klausbayrhammer** [comment]
I can see the same issue - I'll dig into it when I have time

**Comment by klausbayrhammer** [comment]
It seems like yarn and npm store a dependencies package.json-file quite differently.
While npm uses the following structure for the bin section (which is the relevant part for this issue)
```json
{
  "bin": {
    "casperjs": "./bin/casperjs"
  },
}
```
Yarn uses the another structure
```json
{
  "bin": "./bin/casperjs"
}
```

**Comment by joaocunha** [comment]
FYI this fix already hit `backstop@beta`.
