### ISSUE TITLE
Backstop Workflow Uses Bless

### ISSUE THREAD

**Issue by angelariggs** [garris/BackstopJS#324]
https://www.npmjs.com/package/backstopjs#the-backstopjs-workflow

Hello! I noticed that in the new docs, the BackstopJS Workflow section says:

* **Configure:** Specify URLs, screen sizes, DOM selectors, ready events, interactions etc. (see examples directory)
* **Bless:** Create a set of reference screenshots. BackstopJS will consider this your source of truth. (Update this whenever you want).
* **Test:** BackstopJS creates a set of test screenshots and compares them with your reference screenshots. Any unwanted/unforeseen changes show up in a nice report.

But should 'Bless' be 'Reference' instead?

**Comment by garris** [comment]
Yes.  You are totally right.   For a while I was considering changing the command name because it's shorter and more poetic.   What do you think?

**Comment by angelariggs** [comment]
I like reference over bless; it's more self-explanatory in the context of what the user is doing - running tests, or running references :)

**Comment by garris** [comment]
Alright then.  Let's fix it.
