### ISSUE TITLE
Docker image?

### ISSUE THREAD

**Issue by dendril** [garris/BackstopJS#33]
Hey! 

I'm going to setup this as a docker image for simplicity, if you want I can contrib the basic configuration and documentation.

Just let me know,
Thanks!

**Comment by garris** [comment]
Hey Awesome!  What's a docker image?

**Comment by dendril** [comment]
I can't describe it in only one paragraph, please check https://www.docker.com/whatisdocker/

I'll let you know when I finish with the documentation so you can try this by yourself and give me your feedback :smile:

**Comment by dendril** [comment]
Hey @garris,

I finally get it working with an small example, please check https://github.com/dendril/docker

Comments are welcome!
