### ISSUE TITLE
Option to ignore/disable selector for a given viewport?

### ISSUE THREAD

**Issue by tk8817** [garris/BackstopJS#332]
Hi folks,

Love the tool but have not been able to find any info on how to stop a given selector from being picked up for a given viewport. Our mobile & desktop web-pages diverge at certain junctions and it would be great if we could avoid having the 'missing image' show up in the report for selectors we know will not be there.

**Comment by garris** [comment]
One way to think of it is that you actually *do* want to test that element.  You want to ensure that it's not there when it's supposed to not be there.     But if you are absolutely sure you don't want to test it when it's not supposed to be there, then, you should create a multiple config files with the exact viewport scenarios you want.

**Comment by tk8817** [comment]
@garris appreciate the viewpoint - I can get behind that :)

**Comment by DiegoMow** [comment]
@garris sorry for re-opening this, but i'm having the same problem.
In my case, the biggest issue is that having multiple config files cause our tests execution and reports to be separated (specially when manually running it).
Also, the complexity to maintain several config files are not ideal for us (adds complexity and unnecessary addition of code duplication).
In case there is no way. I want to propose my idea (as a feature request):
Add a key "viewports" at "scenarios". It accepts an array that, if filled, will consider testing only added environments.

**Comment by garris** [comment]
@DiegoMow thanks for posting -- this exact feature was added last year.  Give it a try!  Let me know if it's not working.  Cheers.
