### ISSUE TITLE
Introduce separate runner which can be used when running backstop locally

### ISSUE THREAD

**Issue by klausbayrhammer** [garris/BackstopJS#336]
With all the changes done in the 2.0 release it would be really easy to provide a comfortable way to include a locally installed backstop into your build.

Currently you have to duplicate some parts of the `cli/index.js` to your project (which looks more or less like this)
```js
const makeConfig = require('backstopjs/core/util/makeConfig');
const executeCommand = require('backstopjs/core/command');

function executeBackstopCommand(commandName, backstopJsonLocation = 'backstop.json') => {
    const config = makeConfig({
        _: [commandName],
        config: backstopJsonLocation
    });
    return executeCommand(commandName, config);
};

executeBackstopCommand('test')
```

It would be really easy to provide a runner which can then be integrated without using Backstop internals (probably like this if you would use gulp)
```js
const backstop = require('backstop');
gulp.task('backstop_test', () => backstop('test', config))
gulp.task('backstop_test_with_default_config', () => backstop('test'))
```

What do you think about that?

**Comment by garris** [comment]
👋🏼 Hi @klausbayrhammer -- Great to hear from you!   I have booked some time this Friday to look at PR's   -- will review then.   Hope all is going well for you.  I'll be in touch soon!

**Comment by klausbayrhammer** [comment]
Closed with #342

**Comment by obecker** [comment]
This is a great enhancement. Thanks! It would be great if the latest backstopjs version is also available via npm. Currently I get only 2.0.6 and it took me a while to figure out why `require('backstopjs')` didn't work.

**Comment by garris** [comment]
@obecker   It's available via...

`NPM install backstopjs@alpha`
