### ISSUE TITLE
`selectorExpansion` or `enableSelectorExpansion`?

### ISSUE THREAD

**Issue by maban** [garris/BackstopJS#338]
Hi, I'm trying to get BackstopJS to take screenshots of a bunch of selectors on the same page, all with the same classname.

Looking at [the documentation](https://github.com/garris/BackstopJS#selectorexpansion), I should use `"selectorExpansion": true`, and then the selectors. But when this didn't work for me, I checked for issues related to this and found [this PR where the feature is added](https://github.com/garris/BackstopJS/pull/287). The code for that is `"enableSelectorExpansion": true`.

Which is the correct one to use? I've tried both but neither of them seem to work for me. I'm using version `2.1.3`, so I wanted to check – is this feature still in progress?

For reference, I'm expecting this:

```
"selectorExpansion": true,
"selectors": [
  ".styleguide .pattern"
]
```

to give me individual screenshots of _all_ the elements with a class of `.pattern`. Let me know if I've misunderstood this feature.

Thanks for all your work on this 😄

**Comment by garris** [comment]
@maban Thanks for posting.  I just tested v2.1.3 -- it worked with this test config... 

https://gist.github.com/garris/4bcb529433f16aa89681ecb559929b66

**Comment by maban** [comment]
Hmmm, I must be doing something wrong then. Thanks so much for the quick response!

Just to check I'm not misunderstanding the feature though, if I had multiple elements with a class of `jumbotron` on the page, should it capture a screenshot and do a comparison for each?

**Comment by garris** [comment]
^^^ yes.

**Comment by maban** [comment]
Ok, I'm definitely doing something wrong then. Thanks again!

**Comment by nobso** [comment]
@maban Yes, that was the idea. I also could not get this working as of now.

**Comment by garris** [comment]
@nobso  It works with this config... https://gist.github.com/garris/4bcb529433f16aa89681ecb559929b66

**Comment by maban** [comment]
ahhhhh that's why it's not working! I would _love_ this feature, could you let me know when it's released, or if there's anything I can do to help, such as testing?

**Comment by garris** [comment]
@maban the version you're using should be working.   Yes, please *do* test it with the config above.  The config above should expand all three `".firstPanel .col-sm-4"` selectors.   If that DOES work for you there may be a bug we should look at or there may be a bug in your test file.  Please let me know how it goes.

To be sure:  `"selctorExpansion": true`  is the correct syntax.  (it was shortened after the PR was created.)

Thanks!

**Comment by maban** [comment]
@garris I know what it is now! It's a typo in your code – `selctorExpansion` instead of `selectorExpansion`. I'm not sure if that was an intentional shortening or not.

**Comment by maban** [comment]
I'm guessing this is an unintentional typo because the documentation spells it correctly.

**Comment by garris** [comment]
Wow -- great find!!! I will patch this as soon as I can -- hopefully today!   Thanks for doing that detective work!

**Comment by garris** [comment]
Please let me know if you find any other issues -- I'd like to push this feature soon!

**Comment by maban** [comment]
I've been having quite a bit of fun with this feature today, haven't come across any issues. Works really well, and I've been trying it out with 300+ selectors in total. I'm using it to do comparisons of all the components in a style guide locally vs production.

The only problem with this is that when I add a new component, Backstop compares it with what was previously that number. But that's a limitation with what I'm doing, not a bug with the feature. So I'm trying to think of a way to compare things with the same id that I've given it without typing all 300 ids in the JSON file!

Still, being able to automatically take screenshots of all selectors is great. 👍

**Comment by garris** [comment]
Really glad it's working out for you!   

I'd like to try to understand your use case a little bit to see if it's  something that could be addressed in the scope of this feature.   I'm not sure I grasp fully what it is from your brief description tho -- so please feel free to expand on that.   And if not, that's ok too.   I very much appreciate your feedback to this point!  💡

**Comment by maban** [comment]
It's very kind of you to look into it, as it probably is a little out of scope.

I'm using BackstopJS to take a screenshot of each component (pattern/module/design) in this styleguide: https://snyk.io/styleguide/section-base and I'm comparing it with a local version of the styleguide. This is so that, when I'm making changes to a component's CSS, I can run a test to see if any other components have unintentionally changed (leaking CSS styles).

My styleguide is a list of components generated using KSS, and when I add a new component, that gets inserted into the styleguide in alphabetical order.

What that means is, on the production environment, and my local environment, my list looks like this:

```
apple
banana
orange
pear
```

and running a comparison does this:

```
1. apple = 1. apple 👍
2. banana = 2. banana 👍
3. orange = 3. orange 👍
4. pear = 4. pear 👍
```

but when I add a component, my local environment looks like this:

```
1. apple
2. banana
3. pineapple < let's say this is the one I've just added
4. orange
5. pear
```

but the list of components in my production environment hasn't changed, so this is how Backstop compares it:

```
1. apple = 1. apple 👍
2. banana = 2. banana 👍
3. orange = 3. pineapple 👎
4. pear = 4. orange 👎
```

Here's how I'm writing the scenarios (shortened for brevity):

```
"scenarios": [
  {
    "label": "Base styles",
    "url": "https://snyk.io/styleguide/",
    "referenceUrl": "http://localhost:8000/styleguide/",
    "selctorExpansion": true,
    "selectors": [
      ".kss-modifier__example"
    ],
  },
  …
]
```

And I get lovely reports like this:

![screen shot 2016-11-02 at 13 21 50](https://cloud.githubusercontent.com/assets/237149/19938497/06149c66-a11d-11e6-9744-52469c8a2b1b.png)

_But_, If I add another component to my styleguide, that'll fail all the components in the list that come after it, because it's now comparing 2 completely _different_ components, like this:

![screen shot 2016-11-02 at 11 21 30](https://cloud.githubusercontent.com/assets/237149/19939125/9acad40e-a11f-11e6-9a74-eec6e418737c.png)

All my components have unique `id` attributes. The way I'd love this to work is for Backstop to compare ids (or even `data-` attributes) across 2 environments, but in a way where I don't have to explicitly say what those `id`s are. But it feels like a big ask.

Does this make sense? I can probably elaborate more, but it does feel out of scope for this feature.

**Comment by garris** [comment]
I see.  So, if you add a new component -- you don't want to test the new component per se, just if the new component's css is having unintended side effects?  Yes?

So then I assume there is a development period where your test and reference cache are out of sync.   During that period you'd want to run one or more BackstopJS tests but ignore that one component.   Depending on how long that period is you could do this...

```
"scenarios": [
  {
    "label": "Base styles",
    "url": "https://snyk.io/styleguide/",
    "referenceUrl": "http://localhost:8000/styleguide/",
    "selctorExpansion": true,
    "selectors": [
      ".kss-modifier__example"
    ],
    "removeSelectors": [
      "#myNewComponentUniqueId"
    ]
  },
  …
]
```

Does that make sense for your usecase?  You could probably automate the value inserted into `removeSelectors` somewhat too.

**Comment by maban** [comment]
Hah! Yes, that would definitely work! I hadn't thought of using `removeSelectors`, such a simple solution. Thank you so much for considering my use case. 😀

**Comment by garris** [comment]
Nice!   Thanks for beta-using -- really helps to get that insight.   Cheers.

_Closing ticket -- feel free to reopen if needed._
