### ISSUE TITLE
Test fail on browser native elements (select, radio, scroll bar)

### ISSUE THREAD

**Issue by patriciamarchand** [garris/BackstopJS#339]
Hello,
I ran a Backstop test on my environnement and the test are failling beacause the browser scroll bar, select, radio is different between my collegue environnement and I. The references have been created on his computer and the test are done on mine. 
![snag-0036](https://cloud.githubusercontent.com/assets/6225238/19905161/f255442c-a04b-11e6-843b-ad8c74a44003.png)

Thanks

**Comment by garris** [comment]
What are the os differences?

**Comment by patriciamarchand** [comment]
Him : windows 7 6.1, 
Me : windows server 2008 R2 6.1, primary 

I dont know if it could have an impact but my primary browser is Firefox and his primary browser is Chrome...

**Comment by garris** [comment]
Those elements are being generated by the OS.  So in a sense -- the test is working!   That bit will always display differently based on the OS.  One thing you could try is to style those elements with specific sizes and colors etc.  That will make it display more uniformly.   Otherwise you can use remove or hide selectors to duck the test.    Please let me know how you resolve the issue!

**Comment by PhilippeVay** [comment]
Hi,
[relevant comment in PhantomCSS readme](https://github.com/Huddle/PhantomCSS#scaling-visual-regression-testing-within-a-large-team).
You could replace (via `onBeforeScript`) each `select` (and file input) by a text input of the same width, maybe with a `value="fake select"` ^_^ , that'd keep the layout of your components.
Same with radio, a ~16-20px text input?
As for scrollbar, you want to know if one is present or not so modifying `overflow` property to avoid it would be a bad idea...

**Comment by patriciamarchand** [comment]
Ok, I was thinking the native element were generated by the browser and with phantomJs it will be agnostic.

**Comment by maban** [comment]
@patriciamarchand I got round this by using Slimer as the rendering engine instead of the default Phantom. You'll need to install Slimer and then add this to the JSON file:

`"engine": "slimerjs"`

**Comment by patriciamarchand** [comment]
We will definitively try that, but at short term we add a specific css add only when I run Backstop Test to "hide" and colorize these native component.

**Comment by Primajin** [comment]
other workaround could be adding `input`, `textarea` and `select` to hidden selectors - but that might let errors slip through
