### ISSUE TITLE
Version 0.4.0 stop working

### ISSUE THREAD

**Issue by dendril** [garris/BackstopJS#34]
Hey,

I did not review all the changes between 0.3.0 and 0.4.0, but seems the basic command `gulp reference` is throwing:

>
> [15:21:09] Finished 'reference' after 5.04 ms
> CasperJS: CREATING NEW REFERENCE FILES
> CasperJS: CasperError: No steps defined, aborting
> CasperJS:   /usr/lib/node_modules/casperjs/modules/casper.js:1505 in run
>  /home/user/projects/myCoolProject/node_modules/backstopjs/capture/genBitmaps.js:187
>
> Testing script failed with code: 1
>

Does anyone know which could be the problem? 

In the meantime, I'm going to continue working with 0.3.0 till I get time to debug this issue. 

Thanks!

**Comment by garris** [comment]
Hi @dendril, thanks for filing this.  The config files are slightly different from version 0.3.0 & 0.4.0 and this could cause the issue.

If you run `gulp genConfig` the app will write a default configuration file at the root of your project.  (Please be careful,  this will overwrite any config existing at that location.)

Then you can try running `gulp reference` and `gulp test`.  It should work then.  Please let me know if that fixes the issue.   

Thanks!   GS

**Comment by lewisnyman** [comment]
Maybe we could add more useful error messages for people who are caught by
the upgrade?

On Monday, 9 February 2015, Garris <notifications@github.com> wrote:

> Hi @dendril <https://github.com/dendril>, thanks for filing this. The
> config files are slightly different from version 0.3.0 & 0.4.0 and this
> could cause the issue.
>
> If you run gulp genConfig the app will write a default configuration file
> at the root of your project. (Please be careful, this will overwrite any
> config existing at that location.)
>
> Then you can try running gulp reference and gulp test. It should work
> then. Please let me know if that fixes the issue.
>
> Thanks! GS
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/garris/BackstopJS/issues/34#issuecomment-73567676>.
>


-- 
Lewis Nyman
+447753103690
lewisnyman.co.uk <http://www.lewisnyman.co.uk>
@lewisnyman <http://twitter.com/lewisnyman>

**Comment by garris** [comment]
Yes.  Messaging would be the right way to go.  Just a *'No <paramName> value found.'*  should do it.

**Comment by garris** [comment]
I just patched this in 0.4.1.  Old config parameters are now mapped to the new ones internally.   This is lowest friction for users.  The old format is deprecated, but on reflection, I think we should go a few releases before breaking everyones tests.

Extra credit is to still add the warning on the console by detecting old configs.

Cheers GS

**Comment by garris** [comment]
@dendril   Please verify the fix if you get a minute.   Regards.  GS

**Comment by dendril** [comment]
@garris I was having 2 problems:

1- I'm building a docker image with this project, this means I'm installing everything in a minimal box, and phantomjs depends on libraries which must be present in the system before start using it.
2- The configuration file was slightly different because of the version change.

Thanks for you help!
