### ISSUE TITLE
npm ERR! uid must be an unsigned int

### ISSUE THREAD

**Issue by Primajin** [garris/BackstopJS#341]
while working fine in my linux vm, `sudo npm install -g backstopjs` fails on my MBP 10.12.1(Sierra) with a lot of `npm ERR! uid must be an unsigned int`
[npm-debug.log.zip](https://github.com/garris/BackstopJS/files/569495/npm-debug.log.zip)

Any Idea?

**Comment by garris** [comment]
It's your node install &/or your MBP permissions...

https://github.com/npm/npm/issues/13918

**Comment by Primajin** [comment]
I see thanks I'll try that out - but I'm afraid I'm limited using the same node version as my collegues...
