### ISSUE TITLE
Regenerate references causing problem between environment

### ISSUE THREAD

**Issue by patriciamarchand** [garris/BackstopJS#344]
My colleague is generating the references, but when I generate the references on a different environment, all the references need to be recommitted even though it’s exactly the same image visually. I think the differences lies in the metas of the PNG itself because when I compare both PNGs that have been decompiled with imagik, I can see differences in the dates metas and I think GIT  is picking up on those changes.
 
Do you have an idea for a best workflow to have with a large team? I would like to avoid recreate ALL the references every time we changes something in our component.

**Comment by garris** [comment]
If I am understanding your question -- yes, if two people run `backstop reference` the ACTUAL FILES will have different metadata even if the image data itself is the same.

There _is_ an incremental feature which may help you.   It allows you to update a single scenario in case someone adds or updates a single component.   That way you don't have to update ALL references if only one component changes.

see here... https://github.com/garris/BackstopJS#incremental-scenario-referencetesting-filtering

Please let me know if that solves your issue.

**Comment by patriciamarchand** [comment]
I try `backstop reference --configPath=backstop_data/backstopTests/backstop-light.js --filter=Boutons `. The filter allows me to run only the scenario Buttons (primary, defalut, disabled, danger, etc...). But all the references of this scenario changes even if only one component button change.

I try also `backstop reference --configPath=backstop_data/backstopTests/backstop-light.js --i` and all the references are recreated. It just doesn't empty the folder first. Is it supposed to keep all the references and add an increment at the end of the file name?

**Comment by garris** [comment]
Yes, you are correct on the first.  Currently we only can only select by scenario.    Currently @ahoopen has developed a way to promote test images on a per-image basis here... https://github.com/ahoopen/BackstopJS/tree/feature/approve-test-as-new-reference

I have not yet had a chance to merge and test the changes.    That is the very next feature I will be trying to review -- but I still have no timetable on when it will be finished.

**Comment by klausbayrhammer** [comment]
@patriciamarchand you could also try to use a virtual machine (or some kind of container) which you  distribute within your team to generate the screenshots. That's something we do with docker containers (at least more or less). It solves the metadata-problem as well as the every-OS-and-Browser-does-font-rendering-differently problem

**Comment by patriciamarchand** [comment]
Thanks for the suggestion@klausbayrhamme, I will try with a shared virtual machine.
