### ISSUE TITLE
a test command without automatic openReport

### ISSUE THREAD

**Issue by gael-boyenval** [garris/BackstopJS#347]
i'm trying to integrate backstop into a node workflow by dynamically building a report with jenkins. 
The test command lunch a openReport subcommand. 

Is there a way to generate the html report without opening it ?

**Comment by michalkvasnicak** [comment]
Try to add `"openReport": false` to `backstop.json`.

**Comment by garris** [comment]
@michalkvasnicak    I think this is what you need...

See: workflow tips on the readme

> Use the report property in backstop.json enable or disable browser (opening)

**Comment by garris** [comment]
@gael-boyenval   ^^^

**Comment by gael-boyenval** [comment]
@garris @michalkvasnicak thanks ! didn't see that one… sorry
