### ISSUE TITLE
missing "selectors" property breaks image capture.

### ISSUE THREAD

**Issue by jedybeavis** [garris/BackstopJS#349]
![2016-11-15 16 29 44](https://cloud.githubusercontent.com/assets/736017/20309518/e64e3836-ab50-11e6-8cc0-0ae60423f28f.png)

run = backstop reference and nothing

**Comment by garris** [comment]
@jedybeavis thank you for posting -- looks like you found a bug!   As a workaround, adding back the `selectors` property inside `scenarios`.   e.g. `selectors: ["body"]`    

Also,  It looks like that web page is sometimes crashing PhantomJS.  That is a separate issue.

**Comment by garris** [comment]
This is fixed in backstopjs@2.3.2.

`npm install backstopjs@2.3.2`

**Comment by jedybeavis** [comment]
**thanks = backstop reference is working**
Now **backstop test** not working
