### ISSUE TITLE
On Jenkins: "An unexpected error occured."

### ISSUE THREAD

**Issue by obecker** [garris/BackstopJS#351]
I'm using BackstopJS 2.3.0 and have built my own Grunt integration:

```javascript
    var backstopjs = require('backstopjs');
    grunt.registerTask('backstop', 'BackstopJS integration', function(cmd) {
        var done = this.async();
        backstopjs(cmd).then(function() {
            done(true);
        }).catch(function() {
            done(false);
        });
    });
```

The resulting tasks `backstop:reference` and `backstop:test` are working pretty well on my local machine.

This is the outline of my `backstop.json` file:

```
{
  "id": "test",
  "viewports": [
    {
      "name": "desktop",
      "width": 1280,
      "height": 1024
    }
  ],
  "scenarios": [ ... ],
  "paths": {
    "bitmaps_reference": "backstop_data/bitmaps_reference",
    "bitmaps_test": "backstop_data/bitmaps_test",
    "compare_data": "backstop_data/bitmaps_test/compare.json",
    "casper_scripts": "backstop_data/casper_scripts"
  },
  "engine": "slimerjs",
  "report": ["browser", "CLI"],
  "casperFlags": [],
  "debug": true,
  "port": 3001
}
```

Now I want to use the `backstop:test` task on our CI environment on Jenkins. The Jenkins jobs simply runs  first `npm install` and after that `grunt backstop:test`.

Unfortunately I'm getting an error message that doesn't really tells me what's wrong. I have set already `"debug": true` in backstop.json and started grunt with `--verbose --debug`. The engine `slimerjs` is available on Jenkins.

This is the output (note: the project/job part has been replaced by DIR)
```
08:26:28 Running "backstop:test" (backstop) task
08:26:28 [D] Task source: /opt/progs/autobuild/workspace/DIR/Gruntfile.js
08:26:28 
08:26:28 BackstopJS CWD:  /opt/progs/autobuild/workspace/DIR
08:26:28 BackstopJS loading config:  /opt/progs/autobuild/workspace/DIR/backstop.json 
08:26:28 
08:26:28 COMMAND | Executing core for `test`
08:26:28 
08:26:28 Running CasperJS with:  [ '/opt/progs/autobuild/workspace/DIR/node_modules/backstopjs/capture/genBitmaps.js',
08:26:28   '--engine=slimerjs' ]
08:26:29 
08:26:29 Testing script failed with code: 1
08:26:29 
08:26:29 An unexpected error occured. You may want to try setting the debug option to `true` in your config file.
08:26:29 COMMAND | Command `test` ended with an error
08:26:29 COMMAND | Error: An unexpected error occured. You may want to try setting the debug option to `true` in your config file.
08:26:29               at ChildProcess.<anonymous> (/opt/progs/autobuild/workspace/DIR/node_modules/backstopjs/core/util/createBitmaps.js:63:18)
08:26:29               at emitTwo (events.js:100:13)
08:26:29               at ChildProcess.emit (events.js:185:7)
08:26:29               at maybeClose (internal/child_process.js:850:16)
08:26:29               at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
```

As you can see, the only error message is `An unexpected error occured. You may want to try setting the debug option to `true` in your config file.` Any idea what to do to find the cause of the problem?

**Comment by klausbayrhammer** [comment]
Can it be an x-server problem? Are you able to start firefox on your server?

**Comment by mirzazeyrek** [comment]
can you try it with phantomjs ?

**Comment by obecker** [comment]
Thanks for your input.
I just figured out how to get more information about problems with casper and/or slimer:
add the following casper flags:
```
  "casperFlags": [
    "--verbose",
    "--debug=true"
  ]
```

It turned out that it is indeed a display problem.

I will close this issue - perhaps a note in the documentation about these flags might be useful for other users with similar problems.
