### ISSUE TITLE
Make configurations more flexible

### ISSUE THREAD

**Issue by dendril** [garris/BackstopJS#36]
Hey @garris 

I have found 2 problems in my progress of make this project more easy to install using docker:
1. The location of the file `backstop.json` should be configurable using **ENV variables or JSON file**.
2. From my perspective, the server auto-shutdown should be removed completely from the code, we could handle that using a bash script or anything external, no need to force that by default.

What do you think?

**Comment by garris** [comment]
Hi @dendril, sorry for the delay.  

The first item has already been discussed and may happen at some point -- but this is not something currently planned.

The second item could be added as a property in any active config file at some point – again, this is something that is not currently planned.

You are more than welcome to add these enhancements and make a pull request.

Regards,

GS
