### ISSUE TITLE
How to specify the expected number of screenshots? 

### ISSUE THREAD

**Issue by n1313** [garris/BackstopJS#360]
I would like to be able to specify the number of screenshot comparisons that I am expecting before running the test. My use case: I have a working backstop setup, reference screenshots, reports, all that good stuff. Unfortunately, from time to time my code breaks in a way that makes my selectors return 0 results. In this case, running `backstop test` does nothing: there is zero comparisons made and zero comparisons failed, so, success.

I would like to have some help on handling this issue. I would like to set the number of expected screenshots for every scenario so that doing less comparisons than expected would result in test failure, but I don't know how to implement it. Another possible solution would be to decouple screenshot taking from screenshot comparison (possibly related to #293) so that I could compare externally with other test runners.

Thanks!

**Comment by garris** [comment]
@n1313 Yup, I totally get it.  That feature is not in BackstopJS yet -- but it probably should be.  It would be straightforward for you to implement.

The main switch would be here...
https://github.com/garris/BackstopJS/blob/master/core/command/report.js#L105

You'd change the above line to something like this...
```
if (failed || (report.failed() + report.passed() != config.expect)) {
```

And also insert passing of the `expect` parameter to the config here...
https://github.com/garris/BackstopJS/blob/master/core/util/extendConfig.js#L12
```
config.expect = userConfig.expect;
```

Expect would be an integer representing how many tests you required to run.  Then your test would fail if your total count of passed & failed tests was not equal to your `expect` value in your scenario. 

You'd have to guard against `undefined` `expect` values.  And you'd want to document the feature. And write a test for it.   

So, there you go.  If you post a PR I'd gladly pull it in.  

Cheers.

**Comment by n1313** [comment]
I finally sat down to implement this, but the initial setup is... confusing. I've forked the repo and cloned it to my local machine, but the app complains about running in "legacy mode" and insists on writing stuff to `~/` for some reason. Am I missing something? Is there a contributing guide? If I comment [this bit](https://github.com/garris/BackstopJS/blob/master/core/util/makeConfig.js#L5) out then things work but I'm not sure if this is a correct approach :) Please advise.

P.S. Some of the tests are failing because the badge now says "BETA available now". Is this intentional?

**Comment by n1313** [comment]
I have made an attempt at fixing this, please see the PR. I am not familiar with the codebase so I didn't try to do grouping tests by scenario, and so there is a requirement to have `expect` in every scenario block if you decide to use it. There are some lint errors and failing tests in the repo, they are there _before_ my PR, I could fix them but I don't think it should be done in this PR.

**Comment by garris** [comment]
@n1313 Thank you so much for the PR.  I will be hosting visitors till the end of the year and I may not be able to give this a proper review till next month.   Many apologies.  Will review as soon as I can.  Best regards.

**Comment by n1313** [comment]
Any updates?

**Comment by SBeator** [comment]
@garris Does this issue still valuable? 
I am interested with this issue and want to make some contribution on this. 
Is it OK for me to pick this issue?

**Comment by garris** [comment]
@sbeator yes, ok to pick this up.  However the app architecture has changed significantly since the last PR.  The heavy lifting would need to be addressed somewhere in `core/command` or `core/utils`.

**Comment by SBeator** [comment]
OK, thanks for your information, I will send my PR when my change is ready.

**Comment by SBeator** [comment]
PR is #783 is sent for this issue.
@garris please help review it. Thanks
