### ISSUE TITLE
Headless Chrome Support

### ISSUE THREAD

**Issue by jakub300** [garris/BackstopJS#370]
Google is working on [Headless](https://chromium.googlesource.com/chromium/src/+/lkgr/headless/README.md) support in Chrome. Current Linux builds from [download-chromium.appspot.com](https://download-chromium.appspot.com/?platform=Linux_x64&type=snapshots) are already working and it is possible to connect to it via [Chrome Debugging Protocol](https://developer.chrome.com/devtools/docs/debugger-protocol). I'm wondering whether you are planning to add support for it in BackstopJS?

**Comment by garris** [comment]
No plans ATM.  If CasperJS decides to implement this then BackstopJS will inherit the feature.

**Comment by bpatram** [comment]
For those finding this thread in the future, here are the related issues for implementing this: 
https://github.com/casperjs/casperjs/issues/1813
https://github.com/ariya/phantomjs/issues/14954

As many of you may already know, the maintainer of PhantomJS has stepped down which may affect continued development for that project: https://groups.google.com/forum/#!msg/phantomjs/9aI5d-LDuNE/5Z3SMZrqAQAJ

**Comment by Primajin** [comment]
Just to keep track: https://github.com/casperjs/casperjs/issues/1825

**Comment by garris** [comment]
Closing. Both Chromy and puppeteer chrome headless options are available.
