### ISSUE TITLE
onBeforeScript for Multiple Scenarios

### ISSUE THREAD

**Issue by ToreyStapleton** [garris/BackstopJS#376]
I'm having issues using different `onBeforeScript`'s within multiple scenarios.  I have 3 different onBefore scripts, which really is just logging in as different users, and then the onReady is the same for all 3.   Consider the following config:

    "scenarios": [
    {
      "label": "Customer",
      ....
      "onBeforeScript": "customer/onBefore.js",
      "onReadyScript": "onReady.js"
     },
     {
      "label": "Account Manager",
      ....
      "onBeforeScript": "manager/onBefore.js",
      "onReadyScript": "onReady.js"
    },
    {
      "label": "Admin",
      ....
      "onBeforeScript": "admin/onBefore.js",
      "onReadyScript": "onReady.js"
     }
    ]

If I run them individually, it's fine.  If I run them together, I get timeout errors because actions cannot be completed.  It seems like it's sharing the session, so the last 2 scenarios are actually logged in as the first user.

Am I misunderstanding the `onBeforeScript` flow and how scenarios should be organized?

**Comment by garris** [comment]
You are understanding the intended functionality correctly.  However, I have seen behavior like this before.  As far as I know, tests are async but it is possible that multiple instances of Phantom or Casper share the same session (which would be consistent with multiple browser windows sharing the same session).

A lot of assumptions here.  This is definitely worth understanding better.

**Comment by ToreyStapleton** [comment]
Thanks for the quick response, that's good to know.  I'm also not used to headless browsers, so I find it a little difficult to debug cause I usually have no idea where I am 😆 

I'll just have to read up some more on the docs!  Thanks again, awesome tool by the way.
