### ISSUE TITLE
Empty markup returned when testing HTTPS pages.

### ISSUE THREAD

**Issue by Chapabu** [garris/BackstopJS#38]
If your configuration is set up to hit a page over HTTPS, then you get the following markup:

``` bash
CasperJS: CREATING NEW REFERENCE FILES
CasperJS: LOG> CASPER IS RUNNING
CasperJS: LOG> PHANTOM IS RUNNING
CasperJS: 
==================
Current location is https://www.twitter.com
==================

CasperJS: 

<html><head></head><body></body></html>
CasperJS: 
======================
echoFiles has completed 
=======================


Echo files completed.
```

This isn't an issue with BackstopJS exactly, but how PhantomJS handles pages running under HTTPS. Following advice on StackOverflow [here](https://stackoverflow.com/questions/26415188/casperjs-phantomjs-doesnt-load-https-page/26419531#26419531), it can be fixed by passing `--ssl-protocol=tlsv1` in with the `tests` array prior to spawning the CasperJS process (e.g. [echo.js](https://github.com/garris/BackstopJS/blob/master/gulp/tasks/echo.js#L8-L13)).

Obviously this doesn't make sense to add this in globally, but perhaps we could add an option for which SSL protocol to use (if any) in the `backstop.json` config file? I guess it'd be most suitable in the scenarios section?

I.e.

``` json
...
 "scenarios": [
    {
      "label": "Twitter",
      "url": "https://www.twitter.com",
      "ssl-protocol": "tlsv1",
      "hideSelectors": []
    }
 ]

```

I'm happy to work on a pull request for this, but does the suggested approach make sense?

**Comment by garris** [comment]
Hi @Chapabu  thank you for filing this and researching the issue!   This suggestion makes sense.  Question tho --  is there any case where we'd need to set ssl-protocol if the url didn't contian `"https://"`?  My guess is no -- and if that guess is correct then my instinct is to handle this internally with a switch on `if (/^https:\/\//.test(url)) {...}`  just prior to the spawn block.   Maybe this is a nice convienience for nearly every (if not all) use cases?   What do you think?

**Comment by Chapabu** [comment]
Good call. My only concern with that would be that PhantomJS defaults to SSLv3 (which POODLE kinda borked), so we'd need to allow people to pass in the protocol that should be used. PhantomJS can take one of four arguments for `ssl-protocol` (namely `sslv3`, `sslv2`, `tlsv1`, `any` - [source](http://phantomjs.org/api/command-line.html)), so if we were to guess then there's a 75% chance we'd be wrong (I've not had success with `any` when using CasperJS for tests, but it my be OK in this case). So I think either way we'd need to add a configuration option somewhere.

**Comment by Chapabu** [comment]
Actually, I've just checked against Twitter and Facebook, and it appears that passing `any` works fine. So yeah, perhaps checking for `https://` in the url to be tested and just pushing `--ssl-protocol=any` onto the Casper arguments would work fine. That kinda makes things a LOT easier.

**Comment by Chapabu** [comment]
One last thing (sorry, I keep thinking just after posting my comments - this'll be the last one, I promise). If a site doesn't use HTTPS, then it doesn't even matter what option we pass to Casper/Phantom. We should just be able to _always_ pass `ssl-protocol=any`, and it should work across the board.

**Comment by garris** [comment]
That sounds great.  Go ahead and add that parameter if you get a chance.  I'm happy to pull that in.  Thanks.

**Comment by garris** [comment]
This was resolved.  Issue only effects older phantom installs.
