### ISSUE TITLE
Any plans to es6-ify it? :)

### ISSUE THREAD

**Issue by skip405** [garris/BackstopJS#388]
Hey guys,

Any plans to bump up the NodeJS version and have some ES6 fancies?
We could divide the work among several contributors (after coming to an agreement what ES6 features to use, if any). I'm speaking more of some cosmetic changes, not actual refactoring. Like `const, let`, arrow functions, etc.

What do you think?

**Comment by garris** [comment]
Wouldn't that stuff break in older versions of Node?   We currently test these versions...
  - "0.12"
  - "4"
  - "5"
  - "6"

**Comment by skip405** [comment]
Hey @garris . Sure, it will break. That's why I'm asking if there are plans to drop the support of older versions of Node. As when I look at the [official NodeJS LTS Schedule](https://github.com/nodejs/LTS/#lts-schedule) I see that even _they_ stopped maintaining node v. 0.12, so should BackstopJS, don't you think?

When I look at the [ES6 compatibility table for NodeJS v. 4](https://kangax.github.io/compat-table/es6/#node4), it's more or less ok, especially in `strict mode`. Anyways, my `nodeIntegration` example (#386) would definitely break in `0.12` =) I didn't know I should have done it with version `0.12` in mind...

**Comment by garris** [comment]
@skip405 sure -- no worries.    My only concern is there may potentially be users using older versions of node and I don't want to harsh their mellow.   And now, we interrupt this thread for a pie chart...
![nodejs-versions-commercial-projects-started-in-2016-5112d4d4](https://cloud.githubusercontent.com/assets/447033/22488386/96d2802a-e7c6-11e6-83f3-252ea855e883.png)

**Comment by klausbayrhammer** [comment]
If we want to keep the support for 0.12 we could transpile everything with babel (like yarn does it) - but since it's adding more complexity I'm not sure if it's worth it.

**Comment by garris** [comment]
Totally not worth it.

**Comment by klausbayrhammer** [comment]
Should we close the issue then?

**Comment by garris** [comment]
I really don't have a strong opinion here.  I think it's perfectly fine to drop anything below v4.

My bigger concern is support for headless chrome or webdriver -- I would like to know what the casperjs guys are planning to do -- but phantomjs, as awesome as it's been, is running out of useful life.  I would be happy to see backstop in node v6 implementation with support for headless chrome or webdriver.  Would totally trade that any day.   So yes -- let's close the ticket.   All devs should go ahead with es6 style.
