### ISSUE TITLE
What's the number of the latest package version?

### ISSUE THREAD

**Issue by n1313** [garris/BackstopJS#393]
Package.json says "[2.3.8](https://github.com/garris/BackstopJS/blob/master/package.json)", npm says "[2.3.7 is the latest of 47 releases](https://www.npmjs.com/package/backstopjs)", and if I run `npm show backstopjs versions` I get numbers up to version 2.5.0. I'm confused. Which one is the latest?

**Comment by garris** [comment]
```
$ npm view backstopjs
 
{ name: 'backstopjs',
  description: 'BackstopJS: Catch CSS curveballs.',
  'dist-tags': { latest: '2.5.1', beta: '2.5.0', canary: '2.3.8' },
...
```

**Comment by n1313** [comment]
I did that, `npm show` is an alias of `npm view`.
