### ISSUE TITLE
Missing file after global install

### ISSUE THREAD

**Issue by mheesters** [garris/BackstopJS#396]
Hi,

After installing backstopjs globally it seems to be missing a file, or i'm probably overlooking something.

```
npm install -g backstopjs
cd /home/xxx/public_html/projectname
backstop genConfig
backstop reference

BackstopJS loading config:  /home/xxx/public_html/projectname/backstop.json

COMMAND | Executing core for `reference`
  clean | backstop_data/bitmaps_reference was cleaned.
COMMAND | Command `reference` ended with an error
COMMAND | Error: EACCES: permission denied, open '/usr/local/lib/node_modules/backstopjs/capture/config.json'
              at Error (native)
```

When i install backstopjs locally and execute it, it works fine. For example:
node_modules/backstopjs/cli/index.js reference
.. it works ..

Help with getting the global install to work would be great,

**Comment by garris** [comment]
Looks like you have a permissions issue.  see the last line of your console output.

We released a new version today.   2.5.1, which happens to address issues like this.  It may resolve your issue.  Would you mind doing a new install `npm install -g backstopjs` and please let me know if that resolves your issue?

**Comment by mheesters** [comment]
We've installed the 2.5.1 version and it's running without any problems now. [Thank you](https://i.redd.it/fnpzw13moagy.jpg)!
