### ISSUE TITLE
Сomparison does not run if a new scenario is added to the configuration.

### ISSUE THREAD

**Issue by sashamorozov** [garris/BackstopJS#399]
Hi,

I compare HTML prototypes. And common styles may change during the development of new prototypes. So I create a reference screenshots before work, after work I do the test. And if I have added a new file, I include it in the configuration. But the comparison does not work.

I run `backstop test` and after the test is completed I do not get any errors. The test ends with the lines: 
```
CasperJS:  [info] [phantom] Step anonymous 700/700: done in 58500ms.
CasperJS:  [info] [phantom] Done 700 steps in 58500ms
CasperJS:  Comparison config file updated.
CasperJS:  [debug] [phantom] Navigation requested: url=about:blank, type=Other, willNavigate=true, isMainFrame=true
CasperJS:  [debug] [phantom] url changed to "about:blank"

Bitmap file generation completed. 
COMMAND | Executing core for `report`
```

Comparison does not start.

If I delete the new file from the configuration, then everything works as expected.

Please, help.

**Comment by garris** [comment]
What version of BackstopJS are you running?

**Comment by garris** [comment]
We released an update yesterday which may address this.  Could you make sure you're on the latest version?  `npm install backstopjs -g`

**Comment by sashamorozov** [comment]
Yeah, I'm on the latest version 2.5.1 and I use backstop locally.

Unfortunately, it does not work :(

**Comment by garris** [comment]
Ok. could you post some examples of what you're trying to do?

**Comment by sashamorozov** [comment]
I test about 35 html files. the configuration is almost the same for everyone, so I reduced the sample. I use this configuration before work and run `backstop reference` command. 

```
{
  "id": "test",
  "asyncCompareLimit": 200,
  "viewports": [
    {
      "name": "1280",
      "width": 1280,
      "height": 2000
    },
    {
      "name": "1920",
      "width": 1920,
      "height": 2000
    }
  ],
  "scenarios": [
    {
      "label": "Examples: Scaffolding",
      "url": "build/prototypes/examples-scaffolding.html",
      "selectorExpansion": true,
      "selectors": [
        "section"
      ],
      "delay": 100
    },
    {
      "label": "Examples: Popovers",
      "url": "build/prototypes/examples-popovers.html",
      "selectorExpansion": true,
      "selectors": [
        "section"
      ],
      "delay": 100
    },
    {
      "label": "Examples: Modals",
      "url": "build/prototypes/examples-modals.html",
      "selectorExpansion": true,
      "selectors": [
        ".modal"
      ],
      "delay": 100
    }
  ],
  "paths": {
    "bitmaps_reference": "backstop_data/bitmaps_reference",
    "bitmaps_test": "backstop_data/bitmaps_test",
    "casper_scripts": "backstop_data/casper_scripts",
    "html_report": "backstop_data/html_report",
    "ci_report": "backstop_data/ci_report"
  },
  "casperFlags": [],
  "engine": "phantomjs",
  "report": ["browser"],
  "debug": false
}
```

After work and if I created a new prototype, I add it to the configuration, then I run `backstop test`.

```
{
  "id": "test",
  "asyncCompareLimit": 200,
  "viewports": [
    {
      "name": "1280",
      "width": 1280,
      "height": 2000
    },
    {
      "name": "1920",
      "width": 1920,
      "height": 2000
    }
  ],
  "scenarios": [
    {
      "label": "Examples: Scaffolding",
      "url": "build/prototypes/examples-scaffolding.html",
      "selectorExpansion": true,
      "selectors": [
        "section"
      ],
      "delay": 100
    },
    {
      "label": "Examples: Popovers",
      "url": "build/prototypes/examples-popovers.html",
      "selectorExpansion": true,
      "selectors": [
        "section"
      ],
      "delay": 100
    },
    {
      "label": "Examples: Modals",
      "url": "build/prototypes/examples-modals.html",
      "selectorExpansion": true,
      "selectors": [
        ".modal"
      ],
      "delay": 100
    },
    {
      "label": "Dashboard",
      "url": "build/prototypes/dashboard.html",
      "selectorExpansion": true,
      "selectors": [
        ".main-container"
      ],
      "delay": 100
    }
  ],
  "paths": {
    "bitmaps_reference": "backstop_data/bitmaps_reference",
    "bitmaps_test": "backstop_data/bitmaps_test",
    "casper_scripts": "backstop_data/casper_scripts",
    "html_report": "backstop_data/html_report",
    "ci_report": "backstop_data/ci_report"
  },
  "casperFlags": [],
  "engine": "phantomjs",
  "report": ["browser"],
  "debug": false
}
```

Test screenshots are created, but the comparison does not start. And if I remove the new file from the configuration, the comparison starts and shows that I had changed.

**Comment by sashamorozov** [comment]
I came up with a small workaround: before testing I create a blank page with which I will work, and add it to the test. After that everything is working as expected.

But I want a normal way, if possible... :)

**Comment by garris** [comment]
You need to run `backstop reference --filter=Dashboard` to initialize the new Dashboard scenario prior to comparison. Otherwise the comparison function will fail.

**Comment by sashamorozov** [comment]
I apologize for responding so long.

So, my steps:
1. Before I start creating a new prototype, I run the command `backstop reference --filter=scenarioLabel
2. After I finish creating the prototype, I run the command `backstop test`.

Сorrectly?

But I need to test all the prototypes, because the changes can affect them. And the filter does not check the prototypes that do not fall under the conditions.

My work steps:
1. I run the command `backstop reference`
2. I change styles and sometimes I create new prototypes
3. If I create a new prototype I add it to the configuration.
3. I run the command `backstop test`

Expected Result: The test will check the existing prototypes. The new prototype does not compare with anything and the test will miss it.
Actual Result: Test screenshots are created, but the comparison does not start = Test failed

**Comment by sashamorozov** [comment]
Apparently the problem was fixed in the latest versions. Now when I add new scripts for new files, the comparison starts correctly.

THANK YOU!

**Comment by garris** [comment]
Thanks for letting me know!  Cheers.
