### ISSUE TITLE
Is there a way to make multiple screenshots per scenario?

### ISSUE THREAD

**Issue by gurianov-p** [garris/BackstopJS#406]

**Comment by garris** [comment]
Yes.   A scenario represents a single state for your app.  Given that state, a screenshot will be generated for each DOM selector you specify.  So, if you tell BackstopJS to capture all <li> elements and you have a list of say, 100 items in your layout, you will get 100 screenshots.

**Comment by rasenplanscher** [comment]
Close this?

**Comment by garris** [comment]
Sure. close away.

**Comment by garris** [comment]
Closed due to inactivity.  Feel free to reopen.
