### ISSUE TITLE
Work outside /node_modules possible?

### ISSUE THREAD

**Issue by joe-watkins** [garris/BackstopJS#41]
Hello,

I am enjoying backstop.js but would enjoy it even more if we didn't have to work inside the /node_modules/ folder. This folder I do not check into the repository generally. 

In a team setting I'd like to be able to simply npm install the module and work with it from the root of the project.. much like most other node modules. This would help for team based development. Is this possible and if so can I see examples?

I'm thinking this kind of scenario:
/node_modules/backstopjs/
/bitmaps_reference/ (configurable)
/bitmaps_test/ (configurable)
/backstop.json
Gulpfile.js

It looks like I could maybe hack the /node_modules/gulp/utils/paths.js file's paths but that's too hairy for me and I'd be manipulating the module and again,..I'd rather not checkin the node_modules folder.

Any ideas?

**Comment by garris** [comment]
Yup,  totally totally agree with you.  This is probably number #1 on my wish list at the moment!

Currently screenshots are saved to node_modules -- but it would be way way better to not write anything there at all (obviously).  The reason for that is really about how the tool evolved.  This project wants a proper CLI and assignable resource locations for sure.

But hey, it's completely free -- and I have a day job.   So there's that.  ;-)

There have been some great great contributions lately -- if you're so inclined, I'd be happy to pull in any improvements you submitted!

Cheers,

Garris

**Comment by joe-watkins** [comment]
Thanks @garris I appreciate the work you've done here.  Do you feel like this might possible?

1. Create a template paths.js file that has owns project specific paths assigned and house that in the root of the project. This file could be checked into the repo.

2. Have team member copy that file to /node_modules/backstopjs/gulp/utils/paths.js on setup?

I may try something like that... are there any limitations that spring to mind with an approach like that?

**Comment by garris** [comment]
I think it would be more straightforward to add a `global` top-level node to the backstop.json config where any of the internal paths could be overwritten.   That way you simply swap out different config files depending on which project you want to test and resources are managed in one place.

**Comment by ddluc** [comment]
@garris  I created [grunt-backstop](https://github.com/ddluc/grunt-backstop) which provides a work around for this issue.

**Comment by joe-watkins** [comment]
:thumbsup: on @ddluc 's grunt-backstop works like a charm!

**Comment by garris** [comment]
@ddluc thats fabulous!  Let me know if I can help out in any way.   I'd love to add a link to your repo on the github page -- do you feel like it's solid enough?

**Comment by ddluc** [comment]
@garris I'm not a regular grunt user, so I'm still learning proper conventions for building grunt plugins. I think I need to fix some issues regarding the options. Let me fix that first and then I'll give you the green light.

**Comment by ddluc** [comment]
@garris I pushed version  `0.1.3` to npm which should properly configure the target options and provide defaults. Give it a test run and provide any feedback if things aren't working. If it all checks out with you, feel free to list it on the page.

**Comment by garris** [comment]
Hi @ddluc,  I'm not going to have as much time as I'd like to give this a good test today.  But I've added the link anyway.   Hopefully I can give it a run next week --  anycase, I think it's great that you contributed. Thanks for the effort!
