### ISSUE TITLE
Use md5 hash to compare images

### ISSUE THREAD

**Issue by klausbayrhammer** [garris/BackstopJS#411]
Currently the CLI-comparator takes up to 7 minutes in our build-process because node-resemble is quite slow when comparing larger images. I did a little test on how to improve the performance by using different comparison strategies. I tried to compare md5 hashes of images and the result was amazing. Comparing 100 images with 1.2MB took 0.2sec with md5 while it took 25sec with node-resemble.

We could use this to build a multi-phase compare-process. First we compare the image hashes - if they match the content has to be identical. If they don't match we kick off node-resemble (just as it is now) and return the result.

As a performance reference you can check out https://github.com/klausbayrhammer/compareHashResemble

**Comment by garris** [comment]
Dude, you are the best.  This sounds like a great idea -- I will try to review as soon as I can.  Maybe some of the other guys can give it a look.   Thanks!

**Comment by garris** [comment]
This was merged into @canary.    

Thanks @klausbayrhammer!

**Comment by mirzazeyrek** [comment]
I didn't checked the codes but something came in my mind just asking. 

If md5 hash is same; Do you think is it make sense to delete taken test image and using the reference image link in html report section ? 

I believe it will save a lot of space. What do you think @garris  ?

**Comment by garris** [comment]
Sounds interesting.  How much disk space are we talking about for your use case?  

But also, if you are concerned about using too much space, why not just `backstop test --config=foo && rm -r path_to_test_bitmaps`    IOW: deleting test bitmaps after a successful report.   Would that serve your purpose?

**Comment by mirzazeyrek** [comment]
For 1 test what we have is 490 MB of reference and 514 MB of test images:

TOTAL	PASS	FAIL	 HEALTH
1398	1335	63	 95.7%

I think we might assume test case folder will be around 50 mb if we don't create duplicate images. Assuming those tests will be run around 20 times for a typical work day.  What we are looking is 185.6 GB of data saving in a month.

**Comment by mirzazeyrek** [comment]
Your suggestion sounds good but unfortunately almost none of our tests has 100% success ratio.

**Comment by garris** [comment]
@mirzazeyrek   I guess the thing that is bugging me is the conditional stuff we'd have to put on the main codepath to make that surgical approach work.   I would prefer something less complex.   Something like a config option `maxTestHistory` -- you could say, set this to 10 and backstop would delete any test directories beyond that limit (starting with the oldest ones.)  

In your case you could set that to 100 and know your usage wont really go beyond say 50Gig -- which is probably not horrible?    The upside is that it would be something that's easy to configure & understand for users and even easier to implement for us? 

What do you think?
