### ISSUE TITLE
Breaking change in version 2.6.8

### ISSUE THREAD

**Issue by pgn-vole** [garris/BackstopJS#418]
The `configPath`  CLI argument stopped working in this version. It is caused by this change:
https://github.com/garris/BackstopJS/pull/416/files

The added condition is always truthy because the config property has a default value:
https://github.com/garris/BackstopJS/blob/master/cli/index.js#L11-L13

**Comment by garris** [comment]
@skip405 ^^^

**Comment by garris** [comment]
@skip405 I took a closer look at this.  I am going to roll this back -- you can leave this line as is and are probably going to have to test for an object assignment prior to this line and handle the logic as needed.

**Comment by skip405** [comment]
@garris sorry to hear that my PR is causing troubles... again. The change that needs to be applied is this

`if( options && typeof options.config === "string" && ! customConfigPath )`

**Comment by garris** [comment]
Thanks.  I'll do that right now.

**Comment by garris** [comment]
@skip405    On second thought.  Could you take another pass and maybe try to simplify it?  The logic here is a little clunky.    

I think you have two paths right?  One where you get an object -- the other when you get a string?

Cant we just leave that single assignment and just test weather we got a string or an object?

Then just fork the logic right there?

**Comment by garris** [comment]
Probably also a good idea to have some tests around that one.

**Comment by skip405** [comment]
the `options &&` check is a bit misleading. If there's **always** a value for `options.config` we may shorten it to

```
var customConfigPath = options.backstopConfigFilePath || options.configPath;

if(typeof options.config === "string" && ! customConfigPath){
    customConfigPath = options.config;
}
```

**Comment by garris** [comment]
Just curious, what is wrong with this?  it seems more explicit...
```
var customConfigPath = options && (options.backstopConfigFilePath || options.configPath || options.config);

if (typeof customConfigPath === "object") {
   //do the passed config object case
} else {
   //assume we need to do the passed config string case
}

**Comment by skip405** [comment]
seems fine) Are you OK to make the change yourself?

**Comment by garris** [comment]
Yes.  will do.

**Comment by skip405** [comment]
Thanks. Sorry for being a pain )

**Comment by garris** [comment]
No worries!

**Comment by garris** [comment]
@skip405 I went with your solution because I don't have enough time to rewrite.  (and it looks like your fix will fix it).

@pgn-vole @skip405   can you guys both `npm install backstopjs -g`  and let me know if this works for both of you now?
