### ISSUE TITLE
Allow Click or something else client side

### ISSUE THREAD

**Issue by lbineau** [garris/BackstopJS#42]
I would want to add some code to be executed before the screenshot being taken.
I started to to add the following code into the backstop.json
```json
"testFile" : "styleguide-buttons.js" 
```
But I'm stuck with the part of executing code from file and pause the generation process (for a click or something).
```javascript
if(scenario.testFile){
  var testFile = require('./test_files/'+scenario.testFile);
  casper.waitFor(function check(){
    testFile.dosomething(casper)
  });
  casper.log(testFile);
}
```

**Comment by garris** [comment]
Hi @ibineau,  this is a nice feature.

I would create a separate Casper project and get this concept running there first.  Once you have a Casper script evaluating an external JS file in the Casper context you'll be in business.  It should be easy to integrate from there.

Hope that helps -- keep me posted!

Best GS

**Comment by garris** [comment]
request moved to feature RFC #94
