### ISSUE TITLE
Different reference paths for each scenario

### ISSUE THREAD

**Issue by gavmck** [garris/BackstopJS#420]
Is it possible to change the reference paths per scenario? I'd like to create reference images in my individual component folders.

**Comment by gavmck** [comment]
Maybe I need a separate config file for each component? And then use gulp to search for them and run the tests...

**Comment by garris** [comment]
Setting the directory happens only at the config level.   So multiple configs are necessary for multiple directories.   

That said,  there is a lot of file naming flexibility.   Files include scenario name as well.  So if you name those consistently you could easily ask gulp to find all files that have say "_checkoutFlow_" in them.  Does that make sense?

There is more info on file naming in the docs.

**Comment by garris** [comment]
I just re-read your question.  I think I misunderstood.   Sounds more like you want to publish references with your components (or something like that).

If that's the case you may just want to include a config file with each component and you can then set the reference directory to be relative to each component directory.  (That would be like storing tests locally which makes a lot of sense if you're packaging these things up.

Please let me know what you end up doing -- I like to know how devs are using the app :)

Cheers.

**Comment by gavmck** [comment]
Yeah sounds like it's a config file per component :)

I have a folder per component generated by a yeoman script that contains:
- Angular component js file
- Module export
- Scss file
- Unit tests script
- JSON schema for props
- Readme.md for documentation

Sounds like I should add the backstop config generator to yeoman and then automate the test running with gulp, much like we do with the unit tests. Then each component will have reference images to go with the other bits. Keeps it all nice and self contained.

Thanks for the assistance! Awesome service you've got here, super useful

**Comment by garris** [comment]
Cheers!

**Comment by gavmck** [comment]
Not reopening, but I had a bunch of trouble getting this working so I think I'm gonna go back to single files. 

Using separate configs meant I had to have separate reports so my file structure had ~100 copies of the report (one for each component) which seemed a bit messy.

**Comment by garris** [comment]
Thanks for the update.  Makes sense.
