### ISSUE TITLE
how to run the scenario to loop through multiple URLs

### ISSUE THREAD

**Issue by marlin307** [garris/BackstopJS#425]
So, in my backstop.json -  the only change in my scenarios is the URL. Instead of listing all different scenarios one after the other, is there a way to list all my URLs in an array,string, file..etc and run the same scenario,I tried adding an array and use a for loop and it wasn't working and throwing an 'unexpected token error'. 

Any help is greatly appreciated.
Thanks

**Comment by garris** [comment]
To do that you just need to use a `js` based config (instead of a `json` based one)

Here is an example -- the big difference is that you can use javascript in place of string literals...
https://github.com/garris/BackstopJS/tree/master/examples/jsBasedConfig

In the above example -- you can replace the scenarios array value with a function which takes an array of urls and returns an array of scenarios.

**Comment by skip405** [comment]
@marlin307 Besides @garris's suggestion you may also look into the [Node.js Integration example](https://github.com/garris/BackstopJS/tree/master/examples/nodeIntegration) where the `scenarios` are generated and then passed to BackstopJS as a plain JS object

**Comment by klausbayrhammer** [comment]
If you don't want to duplicate `readyEvent` and `misMatchThreshold` but still want to keep the json-config you can specify them as top-level config elements
```js
{
//...
  "readyEvent": "backstop_ready",
  "misMatchThreshold": 0,
  "scenarios": [
    {"url": "http://localhost:3000/test1"},
    {"url": "http://localhost:3000/test2"},
    {"url": "http://localhost:3000/test3"},
    {"url": "http://localhost:3000/test4"},
    {"url": "http://localhost:3000/test5"},
  //  ...
}
```

**Comment by marlin307** [comment]
Thanks @garris and @klausbayrhammer for your responses. Both solutions worked. Following is my backstop.json file.  Pulled all the constant elements out of the array and made them globals and left the URLs in scenarios along with labels. 

{
  "id": "www",
  "hideSelectors": [],
  "removeSelectors": [],
  "selectorExpansion": true,
  "selectors": ["document"],
  "readyEvent": null,
  "delay": 500,
  "misMatchThreshold" : 0.1,
  "onBeforeScript": "onBefore.js",
  "onReadyScript": "onReady.js",
	  
  "viewports": [
    {
      "name": "phone_portrait",
      "width": 320,
      "height": 480
    },
    {
      "name": "tablet_portrait",
      "width": 568,
      "height": 1024
    },
    {
      "name": "desktop",
      "width": 1024,
      "height": 768
    }
  ],
  "scenarios": [
        {"label": "home", "url": "https://www.google.com"},
	{"label": "home", "url": "https://www.yahoo.com"},	
	{"label": "home", "url": "https://www.msn.com"},
	{"label": "home", "url": "https://www.espn.com"},
	{"label": "home", "url": "https://www.cnn.com"}
  ],
  "paths": {
    "bitmaps_reference": "backstop_data/bitmaps_reference",
    "bitmaps_test": "backstop_data/bitmaps_test",
    "casper_scripts": "backstop_data/casper_scripts",
    "html_report": "backstop_data/html_report",
    "ci_report": "backstop_data/ci_report"
  },
  "casperFlags": [],
  "engine": "phantomjs",
  "report": ["browser"],
  "debug": false
}

**Comment by jennasaurusrex** [comment]
Super helpful. Thanks!
