### ISSUE TITLE
configPath ignored when running from npm script

### ISSUE THREAD

**Issue by bmds** [garris/BackstopJS#428]
running `backstop test --configPath=backstop.config.js` directly on the command line works correctly when within the project directory. Running the same command through a npm script (`"vreg:test": "backstop test --configPath=backstop.config.js",`) fails with the error that backstop.json cannot be found.

backstop is installed locally on the project (v2.6.6)

**Comment by skip405** [comment]
@bmds npm scripts receive parameters after the [double hyphen](https://docs.npmjs.com/cli/run-script). Can you try to run `"vreg:test": "backstop test -- --configPath=backstop.config.js"` to see if it works for you

**Comment by skip405** [comment]
Ah, sorry. Please ignore my previous. Completely wrong )

**Comment by p-clem** [comment]
I think the documentation is wrong. Try --config

https://github.com/garris/BackstopJS/blob/f2a1e9fd170c3e2af5591d750eba527a6aa5afba/core/util/makeConfig.js#L22

**Comment by bmds** [comment]
That does look to be the issue. I'm assuming that `configPath` and `backstopConfigFilePath` are legacy commands

**Comment by bmds** [comment]
I've created a pull request to resolve this

**Comment by garris** [comment]
Thanks guys for resolving this.   Doc update is merged.  Yes,  those other two params are legacy.   There was a bug preventing those from working -- this was since fixed also... https://github.com/garris/BackstopJS/commit/08cb7e9fde3118aff41100e8a3c563ae6678bc04
