### ISSUE TITLE
A way to rename backstop_data directory

### ISSUE THREAD

**Issue by zcchew1202** [garris/BackstopJS#433]
Hi, is there a way to rename `backstop_data` in `backstop.json`? For example, I want to rename it to `results` as it would make more sense to others using the test infrastructure I built. Thanks!

**Comment by garris** [comment]
Yes.  It is very easy.  You can set the paths to anything you want.  See the readme here...
https://github.com/garris/BackstopJS#setting-the-bitmap-and-script-directory-paths

**Comment by zcchew1202** [comment]
`"paths": {
    "bitmaps_reference": "results/bitmaps_reference",
    "bitmaps_test": "results/bitmaps_test",
    "casper_scripts": "results/casper_scripts",
    "html_report": "results/html_report",
    "ci_report": "results/ci_report"
  }`
I've tried doing this, but BackstopJS still does `backstop_data/bitmaps_reference`. Am I missing anything?

**Comment by garris** [comment]
@zcchew1202 Thanks for posting -- I just tried this on my machine and it worked.   To be sure, please make sure your backstopjs version is up to date.   Create a test directory and run `backstop genConfg`

Then manually update the default config with your new paths as above.  Also rename the auto-generated `backstop_data` to `results`.   Then go ahead and run `backstop reference` and then `backstop test`.   That should work for you.

**Comment by zcchew1202** [comment]
Thank you!
