### ISSUE TITLE
Are "real" browsers support possible? If so, through Protractor ?

### ISSUE THREAD

**Issue by fabm22** [garris/BackstopJS#435]
Hi, 

Great project. I would like just to be sure : there is no such thing as an API from BackstopJS to take screenshots "on demand" from inside an "end-to-end" test of something like Protractor (which is aimed particularly at Angular apps and which can give orders to "real" browsers).

I would like to use the nice conveniences that BackstopJS gives by presenting visual diffs etc. but taking screenshots FROM an application directed by Protractor and in a real browser if possible... [An example of what a test looks like](http://www.protractortest.org/#/tutorial#step-2-writing-multiple-scenarios)

> Protractor is built on top of WebDriverJS, which uses native events and browser-specific drivers to interact with your application as a user would.

I know I could use the CasperJS API which doesn't use Selenium/WebDriverJS but Protractor gives its own conveniences for Angular apps and from what I gathered, CasperJS is ONLY aimed at PhantomJS-like browsers. So 

1.  Is indeed BacktotopJS only available for CasperJS which would mean only available for testing inside PhantomJS or SlimerJS (ie not real browsers). 

2. and if not, is there some api to take screenshots on demand from a nodejs tool commanding a real browser (like protractor) ? 

Thanks a lot for precisions.

**Comment by garris** [comment]
@fabm22 Thanks for posting!   You are correct.  Currently, BackstopJS is only integrated with CasperJS.   But there is a web-driver implementation in progress here... https://github.com/garris/BackstopJS/pull/409 

I don't know how well that version is working at the moment -- but you are of-course welcome to pull the PR and see if you can get it to do what you need.

There is no timeline for this feature but we all agree it would be great to have this capability.

Cheers.

**Comment by fabm22** [comment]
Thanks for quick answer and pointing me out to the branch. 
From what I'm seeing over the internet I will give a try to that branch, check if it would cover my use case since it looks like the alternative would be to basically staple something myself which would do the same thing anyway (which would be less functional VERY probably haha).

I'll update around here or on the issue if I see useful info, thanks. Closing.
