### ISSUE TITLE
url changed to "about:blank"

### ISSUE THREAD

**Issue by patrick-vieira** [garris/BackstopJS#439]
Hello, i'm having trouble to use scripts, i see this problem in another issues but i can't resolve it.

my application has a login page and when some one make a login it takes you to the first page localhost:3000/#/potenctial, and it's appears to occurs, but it take me back to the login page

localhost:3000 is the login page
and localhost:3000/#/potential is the first page after login success 

* Detail, it happens in any page who i try to login. like facebook

i was thinking it could be something with the installation, but i installed everything in other Ubuntu and same happens.

![image](https://cloud.githubusercontent.com/assets/10858208/25784731/7aef7d40-3348-11e7-8c16-834ea0d8dc34.png)
![image](https://cloud.githubusercontent.com/assets/10858208/25785336/4cdb2100-3354-11e7-9628-88ae1b707887.png)
[debug.log.txt](https://github.com/garris/BackstopJS/files/981964/debug.log.txt)

this is the backstop.json
```
{
  "id": "prod_test",
  "viewports": [    
    {
      "name": "tablet_h",
      "width": 1024,
      "height": 768
    }
  ],
  "scenarios": [
    {
      "label": "BackstopJS ONE",
      "url": "http://localhost:3000/#/potential",
      "hideSelectors": [],
      "removeSelectors": [],
      "selectorExpansion": true,
      "selectors": [
        "body"
      ],
      "readyEvent": null,
      "delay": 500,
      "misMatchThreshold" : 0.1,
      "onBeforeScript": "onBefore.js",
      "onReadyScript": "onReady.js"
    }
  ],
  "paths": {
    "bitmaps_reference": "backstop_data/bitmaps_reference",
    "bitmaps_test": "backstop_data/bitmaps_test",
    "casper_scripts": "backstop_data/casper_scripts",
    "html_report": "backstop_data/html_report",
    "ci_report": "backstop_data/ci_report"
  },
  "casperFlags": [],
  "engine": "phantomjs",
  "report": ["browser"],
  "debug": true
}

```

and this is the  onBefore.js

  ```
module.exports = function(casper, scenario, vp) {

console.log('#########################################################################');
  console.log('START SCRIPT');
  console.log('#########################################################################');
  casper.start("http://localhost:3000/#/",function(){

    if (this.exists('form.form-signin')) {

      console.log('#########################################################################');
      this.echo('Form exists');

      this.sendKeys('input[id="inputUsername"]', '< USER >');
      this.sendKeys('input[id="inputPassword"]', '< PASSWORD >');
      this.clickLabel('Entrar', 'button');

      // this.fill('form.form-signin', {
      //   'inputUsername': '< USER >',
      //   'inputPassword': '< PASSWORD >'
      // }, true);

      console.log('PASS!');
      console.log('#########################################################################');

    
    }
  }); 

};
```

* node   v7.10.0
* backstopjs@2.6.11

backstopjs is installed locally.

Thank you, and just to be clear i'm new on node, so it maybe not even be a bug.

**Comment by garris** [comment]
I noticed there is a fragment in your URL.  Is it possible you are having an issue related to this?
https://github.com/garris/BackstopJS/issues/172

**Comment by patrick-vieira** [comment]
Hi garris, thank you for the response, but that is not related, I read all the issue and the issues linked too.

After some more research at various issues i found one way to fill the form and submit it without mess up.

clicking manually on the button or using the fill() function throw the same error as before, but if i use fillSelectors() it works.

my code is now.

```
module.exports = function(casper, scenario, vp) {

casper.start("http://localhost:3000/#/",function(){
    casper.waitForSelector("form input[id = inputUsername ]", function() {

      this.fillSelectors('form.form-signin', {
          'input[id = inputUsername ]' : 'user',
          'input[id = inputPassword ]' : "pass!"
      }, true);

      casper.waitWhileSelector("form input[id = inputUsername ]", function(){
          this.echo('form's gone!');
      });

      casper.then(function(){
          this.echo("Page title:" + this.getTitle());
      });
    });

  

}); 

};
```
sorry for that.

**Comment by garris** [comment]
Great to hear you figured it out!  Thanks for posting.  Cheers.
