### ISSUE TITLE
Use BackstopJS for login-required pages

### ISSUE THREAD

**Issue by kyanny** [garris/BackstopJS#44]
Hi, I think it'd be nice if I can use BackstopJS for login-required pages.
So I tried to add tiny patch for BackstopJS to handle Cookie.
https://github.com/garris/BackstopJS/compare/master...kyanny:addCookie
How do you think? Do you have a plan to support Cookie-based login for BackstopJS?

**Comment by garris** [comment]
Hi @kyanny,  can you send me an example cookies.js file with a sample config file so I can see how they work together?  Thank you.

**Comment by kyanny** [comment]
Hi @garris 

Cookie (secure values are masked): https://gist.github.com/kyanny/4feeb13d450f76a49f49
backstop.json: https://github.com/kyanny/BackstopJS-sample/blob/master/backstop.json

**Comment by garris** [comment]
Hi @kyanny, yes I can see that this is very useful in certain cases.  One thing, could you add a config property ('cookiesJsonFile') to the `scenario` node to point to the cookies file?  Then use that value internally instead of hard coding the filename.  This way users can choose where to place their files and BackstopJS won't even try to load a cookies file unless it is specified in the config.    It would also be great if you can document this feature in the readme file.   How does that sound?

**Comment by kyanny** [comment]
Hi @garris, sounds very good and all makes sense! I will try and open Pull Request.

**Comment by jontonsoup** [comment]
+1 cookies would be awesome

**Comment by filipecatraia** [comment]
+1

**Comment by garris** [comment]
Sorry this is taking so long.   Will absolutely try to get this in this weekend!   Thanks for your patience.

**Comment by garris** [comment]
@kyanny, Please take a look at the `cookies` branch.  I've added your code and it looks like there is an issue saving the cookies -- the cookie string does not appear in the page.   Please let me know what you come up with.  Thank you.

**Comment by garris** [comment]
Just occurred to me -- the JSON file is not an array.  Maybe this is the issue.

**Comment by garris** [comment]
Hi @kyanny,  did you have a chance to test the cookies feature?   Is it working for you?

**Comment by kyanny** [comment]
Hi @garris, sorry for delay.
Could you show me the exact command line to run test suite?
I read files in test directory carefully, but I'm still not sure how to integrate them to BackstopJS.

**Comment by garris** [comment]
Thank you @kyanny -- it's no problem.  I have a break coming up in a week -- I will write instructions for running the tests.  I will get back to you as soon as I can.   :)

**Comment by garris** [comment]
This functionality can be supported with custom CasperJS scripts.  see https://github.com/garris/BackstopJS#running-custom-casperjs-scripts-version-080

**Comment by sveetch** [comment]
Is there some sample to achieve this with CasperJS ? I'm a little bit lost with casper as i need some session cookie to be set before the page is rendered, else i won't have the "authenticated only" content.

And from what i understood from the documentation, it seems the page is already rendered when `onReadyScript` is executed, did i miss something ?

**Comment by TimPerry** [comment]
I've got this working in my capser tests by first loading the inital homepage or somerthing, then calling 
```
casper.page.addCookie({some: 'cookie'});
```

However it seems that the implementation for backstop is to use phantom.addCookie, which means you have to know the domain up front, which isnt ideal. I've tried explicitly stating the domain in my cookies.json file but that doesn't seem to work either?

I have noticed that this section about this functionality in the readme is commented out? Are cookies no longer supported?

**Comment by TimPerry** [comment]
@sveetch Got something working by creating a set_cookies.js file in the /scripts directory:

```
module.exports = function(casper, scenario, vp) {
  casper.echo("Settings cookies");
  casper.then(function(){
    casper.page.addCookie({some: 'cookie'});
  });

  casper.thenOpen(scenario.url);
}
```

Then in my scenario I have added this:

```
        "onReadyScript": "set_cookies.js"
```

**Comment by sveetch** [comment]
@TimPerry thank you

I'm trying to achieve my problem with a CasperJS script to launch before just for login and using persistent cookie. I will try your code if i don't succeed.

**Comment by garris** [comment]
@sveetch Thank you for documenting your *cookie* code here.  Much appreciated!  Cheers.

**Comment by sveetch** [comment]
@TimPerry  @garris here it is: https://gist.github.com/sveetch/4a20793b77f2a8b5c045

It works well, it's little bit verbose and maybe messy, but it just works.

**Comment by garris** [comment]
@TimPerry thank you very much for documenting.  Do you mind if I add this snippet to the documentation?

**Comment by TimPerry** [comment]
@garris Of course not, go for it and thank you for creating such a great tool.

**Comment by qileilove** [comment]
@TimPerry  hi Tim, I used the demo for cookies,but it didn't work. 
```
module.exports = function(casper, scenario, vp) {
  casper.echo("Setting cookies");
  casper.then(function(){
    casper.page.addCookie({some: 'cookie'});
  });

  casper.thenOpen(scenario.url);
}

 ```

```
    casper.page.addCookie({some: 'cookie'});

```
what's the meaning of  this piece of code ?
({some:'cookie'}) is cookie file or the cookie hash?

**Comment by TimPerry** [comment]
That would be the cookie hash. I believe it is a call to this method in phantomJS: http://phantomjs.org/api/webpage/method/add-cookie.html
