### ISSUE TITLE
Change exit code to 1 for CI

### ISSUE THREAD

**Issue by mantovanig** [garris/BackstopJS#440]
Hi, 

I'm trying to add backstop visual testing on my pipe of CI.
Now in case of test failed the process exit with code 0. Is possible change this to 1?

Thanks

**Comment by mantovanig** [comment]
Solved with catch the promise that return backstop 👍

**Comment by garris** [comment]
Nice -- thanks for posting the solution!   💯

**Comment by zubhav** [comment]
@mantovanig Did you throw an Error within the catch for this to work? I'm having trouble with causing a failure on CI too.

**Comment by zubhav** [comment]
To ensure the CI build fails if Backstop fails - you can do the following:

`
backstop( 'test' )
    .then( () => {
        console.log( 'Passed' );
        process.exit( 0 );
    })
    .catch( () => {
        console.log( 'Failed' );
        process.exit( 1 );
    });
`
