### ISSUE TITLE
Test/openReport command hangs with SlimerJS + xvfb

### ISSUE THREAD

**Issue by mhavelant** [garris/BackstopJS#444]
I'm trying to run BackstopJS from inside a docker container with SlimerJS as the engine.
Everything is fine, but the process does not terminate, it instead hangs infinitely at the 'opening browser report' stage.

Package versions:
- BackstopJS 2.6.13
- Innophi SlimerJS 0.10.3
- CasperJS version 1.1.4 at /usr/lib/node_modules/casperjs, using phantomjs version 2.1.1
- Mozilla Firefox 45.0.2

Usage:
> xvfb-run backstop test --config=backstop.json

Result (trimmed)
>  report | Test completed...
>  report | 0 Passed
>  report | 6 Failed
>  report | Writing jUnit Report
>  report | Writing browser report
>  report | jUnit report written to: ci_report/xunit.xml
>  report | Browser reported copied
>  report | Copied configuration to: html_report/config.js
> COMMAND | Executing core for `openReport`
> openReport | Opening report.

And then it just hangs there until I force close it.

**Comment by klausbayrhammer** [comment]
Did you try to set `"report": ["CI"]` in your backstop.json file? Otherwise it will try to open the report with a browser which will not be terminated and could prevent your container from terminating

**Comment by garris** [comment]
That openReport command is very very osx-centric.  It probably doesn't work in most other environments.  We should probably guard against that command and warn the user if the guard throws.

**Comment by mhavelant** [comment]
Huh, I didn't even consider that omitting the values from "reports" will only skip opening them, but won't skip generating them. I can work with this, thanks!

**Comment by garris** [comment]
We aim to please!   Reopen if that didn't fix your issue.  Cheers.
