### ISSUE TITLE
Body with overflowhidden : redefine which element scrolls

### ISSUE THREAD

**Issue by stephenbe** [garris/BackstopJS#448]
Hi Garris! :) 

Usually, a document will scroll at the body element. In my specific project, I have overflow hidden the body and there is a huge overlay that has it's own scroll. Backstop doesn't understand that it needs to scroll that huge overlay and not the body element.

Any way to tell backstop : scroll this element and not the body

Thanks

**Comment by garris** [comment]
This article demonstrates how to scroll a div.   https://stackoverflow.com/questions/635706/how-to-scroll-to-an-element-inside-a-div

Take that concept and put it in an onReady script inside of a casper.evaluate() function.

Hope that helps!

**Comment by stephenbe** [comment]
Thanks garris, I never thought of using JS for this!

**Comment by garris** [comment]
Sure, good luck!    At linkedin we have many helper scripts that we use with our backstop tests.  This technique should work very well for you.   cheers.

**Comment by stephenbe** [comment]
@garris holy crap, you use this in LinkedIn??? Do you know if LinkedIn will appropriate the project? Would be awesome having more budget put I to this awesome tool honestly.. let me know please!

**Comment by garris** [comment]
@stephenbe 😄 It's hard to say -- they already give me some time each month to work on the project -- so, you could say that they already underwrite the effort.  Thank you for being very positive about the project -- I am glad it can help developers do better work!

**Comment by stephenbe** [comment]
@garris thats awesome, I remember they hired the creator of sass to work on sass on LinkedIn, such a great company, congrats !! Them giving you time on this project is the dream of many and it could happen to a better programmer in my opinion, keep working hard!! I believe in backstop..all it needs is a logo haha😇😄
