### ISSUE TITLE
Support for other headless browsers

### ISSUE THREAD

**Issue by Primajin** [garris/BackstopJS#450]
I would be very happy to use chrome(ium) headless, since phantom seems to be dead and has very limited support for modern CSS3 functions.

But I think we depend on Casper supporting it, right?
https://github.com/casperjs/casperjs/issues/1825

**Comment by stevector** [comment]
There is an issue for Chrome support here: https://github.com/garris/BackstopJS/issues/370

**Comment by Primajin** [comment]
thanks @stevector
