### ISSUE TITLE
On comparing screenshots no any Test-Report get generated and compare comes with "killed"

### ISSUE THREAD

**Issue by khalistan** [garris/BackstopJS#452]
I am using Backstop on two different places. Where I have same code. On testing locally, there is no any issue. After the "test" I am getting the test_report but here I just do one Test. (For one website with one device e.g Mob). Then same code running on Docker Slaves. Where it tests parallel two websites with three Devices (MOB,TAB,WEB).  Not on every build(Test) but on some it don't generate test result. It do take reference-screenshots and test-screenshots but when it comparing them and then suddenly it shows "kill". Here stack-trace:

```
> 09:29:40 [BackstopJS - Website: example, Mode: test, Device: tab] CasperJS:  Current location is https://example.com/kasse/anmelden?forceApp=tab
> 09:29:41 [BackstopJS - Mandantor: example, Mode: test, Device: mob] compare | ERROR { requireSameDimensions: false size: isDifferent, content: 0.00%, threshold: 0.1% }: mob: example.com MBA test_mob_mob_example_MBA_0_document_0_mob_iphone6_plus.png
> 09:29:41 [BackstopJS - Mandantor: example, Mode: test, Device: mob]    See: /root/workspace/job-webtest/bitmaps_test/20170601-092331/failed_diff_test_mob_mob_example_MBA_0_document_0_mob_iphone6_plus.png
> 09:29:42 [BackstopJS - Mandantor: example, Mode: test, Device: mob] Killed
```

So no any test report is get generated. It can possible that this issue is related to https://github.com/garris/BackstopJS/issues/281 
I tested this on Backstop version: 2.3.7
Thanks

**Comment by khalistan** [comment]
I changed version to 2.4.6. I am not facing this Problem. But Please don't close this issue. I will do more tests. Thanks

**Comment by khalistan** [comment]
till now I am not facing this error, so for now I am closing this issue. @garris

**Comment by garris** [comment]
Just out of curiosity,  are you using an onBefore script?  We did fix a bug related to setting cookies which sometimes caused multiple tests to fail.  In any case,  I am glad it's working for you!

**Comment by khalistan** [comment]
I am still facing this Problem. @garris No I am not using onBefore script but I do use onReadyScript.

**Comment by khalistan** [comment]
Still facing this problem.
`5:28:56 [BackstopJS - Website: exampleDE, Mode: test, Device: web] compare | ERROR { size: ok, content: 0.98%, threshold: 0.1% }: web: Homepage test_web_web_Homepage_0_document_0_web_1280.png
05:28:56 [BackstopJS - Website:  exampleDE, Mode: test, Device: web]    See: /root/workspace/job-webtest/bitmaps_test/20170607-052243/failed_diff_test_web_web_Homepage_0_document_0_web_1280.png
05:28:58 [BackstopJS - Website:  exampleDE, Mode: test, Device: web] Killed`

**Comment by khalistan** [comment]
We have increased RAM, as we saw on Development environment mem. was being used till 6.GB. I will write again if we are facing same problem even after increasing RAM and Shared Memory.
![Uploading slave1und2.png…]()

**Comment by garris** [comment]
Thank you for keeping us posted!  Would be interested to know how many tests/selectors you are running and what your RAM requirements are.

**Comment by khalistan** [comment]
I am have 13 Tests (each test with separate URL/Selector) pro device and pro website. I have three devices and 9 websites. which mean total 351 Tests. But the memory you are seeing above on image was for just13 Tests.

**Comment by garris** [comment]
Thanks.  Please let us know if increasing RAM fixes your issue.

**Comment by khalistan** [comment]
Ja. Increasing RAM solved our Problem. Thanks.

**Comment by khalistan** [comment]
@garris  I have one question, I know its not related to issue but would be nice if you could help a bit.
`Report: {
  "isSameDimensions": false,
  "dimensionDifference": {
    "width": 0,
    "height": -91
  },
  "misMatchPercentage": "0.00",
  "getDiffImage": null
}
Threshold: 1`
MY some tests are failing just because of height. Anyway to let test pass if height/width difference is given somewhere in setting. Or any other way around? 
Thanks

**Comment by garris** [comment]
Thanks @khalistan!

Yes,  there is a setting which allows you to ignore dimensions.  Please check the readme for `"requireSameDimensions" : true`


Hope that helps.

**Comment by khalistan** [comment]
ok. I have created new issue on that at https://github.com/garris/BackstopJS/issues/456
