### ISSUE TITLE
Question: run comparison only

### ISSUE THREAD

**Issue by aboutandre** [garris/BackstopJS#455]
Hi @garris,
I use for private projects BackstopJS and I love it! Thanks for all the hardwork!

However at my company, we currently have a solution that is using our browser pool to make screenshots from different browsers and different OSs.

My question is: is it possible to only compare the images and generate a report, without having to create new screenshots?

Thanks in advance!

**Comment by garris** [comment]
@aboutandre thanks for the kind words!   

There's no ready way to run arbitrary comparisons.   

If you wanted to build it yourself you would need to make modifications by generating your own intermediate comparison manifest (the metafile included with each test bitmap directory)   Then you'd have to add a custom command.  It's doable -- not totally easy -- but doable.

Cheers!

**Comment by aboutandre** [comment]
Hi @garris ,
thanks for the quick answer.

I will take a look at it and see if it's worth using the BSJS report for this task. If yes, I might come with a PR ;)

For the meanwhile I will close this ticket.

Cheerio
