### ISSUE TITLE
The reference and test are opposite with the tag.

### ISSUE THREAD

**Issue by aisensiy** [garris/BackstopJS#460]
I have a html version report [here](https://s3-ap-southeast-1.amazonaws.com/realtopper-artifacts/5-6-20170616051212/backstop_data/html_report/index.html). When I click the image there is a bar to help me show the reference and test image which is very convenient. But I found that on the left top the Reference Tag is on the left side and Test Tag is on the right side, which is opposite with the bar's result: on the left of the bar is the Test Tag and on the right of the bar is Reference Tag which makes me confusing.

![image](https://user-images.githubusercontent.com/661860/27216107-dc1085d8-52a6-11e7-8a32-19d62ddcdff3.png)

I think it is necessary to change the position to the two image to make it right with the left top tag.

**Comment by garris** [comment]
@aisensiy  thank you for posting.  Yes -- you are correct.  There are a few issues with that feature which I would love to see fixed.   In addition to your issue -- there is also an alignment issue which happens at certain aspect ratios which breaks the display.  Please feel free to post a PR.  Thank you.

**Comment by aisensiy** [comment]
Is there some instruction for PR? Or I just PR to master?

**Comment by garris** [comment]
Thanks for asking.  Please PR to the canary branch. 

FWIW:  There isn't much development going on in the "browser" part of the app -- I really appreciate you flagging the issue.   Take your time -- thank you for your effort!

**Comment by aisensiy** [comment]
#467 I created a PR.

**Comment by garris** [comment]
Looks great.  Will merge soon.

**Comment by aisensiy** [comment]
Any update?

**Comment by garris** [comment]
Thank you for this PR -- Apologies for the delay!   This is merged in the backstop-chromy branch which will be released hopefully by september.  This will be bundled with our headless-chrome feature in version 3.

fixed by https://github.com/garris/BackstopJS/commit/d7e242abd77912abfcde87bdac5efa63c3520e69
