### ISSUE TITLE
Memory issue during compare process (version 2.7.5)

### ISSUE THREAD

**Issue by sebastianekstrom** [garris/BackstopJS#462]
I'm experiencing memory leak issues running our backstopJS tests on a Heroku enviroment (backstopJS version `2.7.5`).

Here's my config:

```
export default function() {
  const screenList = [
    '/page/1',
    '/page/2',
    '/page/3',
    '/page/4',
    // ...total of 20 screens
  ]

  const screens = screenList.map((screen) => {
    return {
      "label": 'foo',
      "url": `https://dev-enviroment.com${screen}`,
      "referenceUrl": `https://prod-enviroment.com${screen}`,
      "selectorExpansion": true,
      "delay": 3000,
      "misMatchThreshold" : 0,
      "onBeforeScript": "casperLogin.js"
    }
  })

  return {
    "id": "render_test",
    "asyncCompareLimit": 10,
    "viewports": [
      {
        "name": "desktop",
        "width": 1024,
        "height": 768
      }
    ],
    "scenarios": screens,
    "paths": {
      "bitmaps_reference": "/bitmaps_reference",
      "bitmaps_test": "/bitmaps_test",
      "casper_scripts": "/test/",
      "html_report": "/html_report",
      "ci_report": "/ci_report"
    },
    "ci": {
      "testSuiteName": "backstopJS"
    },
    "casperFlags": [
      "--ignore-ssl-errors=true",
      "--ssl-protocol=any"
    ],
    "engine": "phantomjs",
    "report": ["CI"],
    "debug": false
  }
}
```

And here's the basic implementation:

```
import backstopConfig from './config'

backstop('reference', {
  config: backstopConfig()
})
.then(() => {
  backstop('test', {
    config: backstopConfig()
  })
})
```

When running it, everything is normal until the compare process when the memory usage on the Heroku app spikes:

<img width="591" alt="screen shot 2017-06-21 at 17 10 41" src="https://user-images.githubusercontent.com/1921046/27391588-9b750312-56a4-11e7-8138-be6e115c0385.png">

As you can see, with 20 screens the compare process takes up around ~1GB of memory, and the more screens I had the higher the memory usages gets. Doubling the amount of screens results in a memory usage of about the double (2GB).

Any ideas on how to solve this issue?

**Comment by garris** [comment]
Thank you for posting!     Did you try adjusting the concurrency parameter here...
https://github.com/garris/BackstopJS/blob/master/README.md#tuning-backstopjs-performance


Does that help?

**Comment by sebastianekstrom** [comment]
Setting `"asyncCompareLimit": 100` in the config helped, the memory usage drops down to ~350MB. Thanks a lot!
