### ISSUE TITLE
 font smoothing (ClearType) made the test fail

### ISSUE THREAD

**Issue by patriciamarchand** [garris/BackstopJS#463]
My team an I use one machine for tests. We log on it with different user profile. The setting for the font smoothing Clear Type made the tests fails for my collegue. For this user, we can not change the setting. Is it normal that the font smoothing (ClearType) made the test fail?  I know some difference in the Os made significant difference, like the radio button, scroll bar etc. But for these one I manage the difference not to fail with CSS. 

Any idea how can I bypass this limitation of the clear Type font?

**Comment by garris** [comment]
@patriciamarchand Thank you for your post.  I am sorry but I don't have good advice for you at the moment :(.     I think this is one of he most difficult aspects to manage for visual regression tests.    Where I work we all have nearly identical environments (macOS  and same everything else).  

However -- I have seen an issue where fonts that are running on the OS can been replaced by the OS

**Comment by patriciamarchand** [comment]
Thank, I will let you know the solution if I find one. Maybe add in the documentation a note about the  difference (apparence windows setting, radio button, scrollbar...) if we use different environnement. I'm sure it could be usefull for other in a situation like mine.

**Comment by unindented** [comment]
@swese44 solved this by running all visual regression tests in a Docker container.

**Comment by swese44** [comment]
We run tests locally on our Mac laptops and in Travis CI under a linux container. Visual tests were not possible between the different operating systems (probably font-aliasing) so we set up Docker to locally run the same container as Travis. We plan to open source this project in the near future so you could see the setup then.

Your flow sounds a bit simpler if can always run visual diffs on the same machine. Maybe you could create a shared user account just for visual testing?
