### ISSUE TITLE
Backstop 2.8.x include breaking changes

### ISSUE THREAD

**Issue by pgn-vole** [garris/BackstopJS#471]
Looks like the 2.8.x release of BackstopJS includes breaking changes because of a dependency (https://github.com/OnetapInc/chromy) which require Node.js 8 whereas previously using BackstopJS didn't require such a new version of Node.JS.

I think this change should be released as 3.x so that it follow semver practice and doesn't break existing builds.

FYI the error we are now getting is:

```
/c/dev/project/node_modules/chromy/src/index.js:73
  async start (startingUrl = null) {
SyntaxError: Unexpected identifier
```

**Comment by garris** [comment]
2.8 is the beta version -- please use the @latest (2.7.x) for any production needs.  

We are integrating headless-chrome.  The chromy library will resolve this issue soon... 
 https://github.com/OnetapInc/chromy/pull/19

**Comment by garris** [comment]
@pgn-vole what version of node are you running?

**Comment by pgn-vole** [comment]
Version 6.10.0. Looking at the PR of chromy this issue should be fixed quite soon I hope.

**Comment by garris** [comment]
Just to close the loop on this one.  In the course of implementing chrome headless option it looks like there will be one significant breaking change after all (even though I expect this to affect very few users).  Therefore I have bumped the new version to 3.x.x

_That said, I do not intend to release anything which would break a supported node version.  So, no worries there._ 😉

**Comment by garris** [comment]
Thanks very much for your comments!
