### ISSUE TITLE
Generating browser report without trying to open browser

### ISSUE THREAD

**Issue by seanfoo** [garris/BackstopJS#475]
As part of our test process, I want to generate the html report in a cron job and then copy the generated html results to a server so all can see the results.

However, the program does the following.
```
BackstopJS loading config:  /home-puig/deploy/build/assets/testcss/backstop.json

COMMAND | Executing core for `openReport`
openReport | Opening report.
```

and then hangs until I Ctrl+C to exit.  Is there a way to generate the html and have the program exit normally?

thanks.

**Comment by garris** [comment]
Yes. There totally is.  Set the report property to `report: []`.  It will still create the html report but wont try to open the browser.

**Comment by seanfoo** [comment]
Thank you.  Does running CLI suppress the generation of teh html report?


---
Sean Forman
Sports Reference LLC, President, http://www.sports-reference.com/
https://twitter.com/sean_forman     https://www.linkedin.com/in/seanforman

**Comment by garris** [comment]
no. the report is still generated.  Just doesn't try to open the browser.

**Comment by seanfoo** [comment]
Thank you.

---
Sean Forman
Sports Reference LLC, President, http://www.sports-reference.com/
https://twitter.com/sean_forman     https://www.linkedin.com/in/seanforman
