### ISSUE TITLE
misMatchThreshold of 0 still allows changes on large reference images

### ISSUE THREAD

**Issue by joseph-stano** [garris/BackstopJS#477]
Nice work on Backstop!

We are diff'ing a project with a lot of data on a particular page. The reference image is quite large (1024x23046).

Even with a misMatchThreshold=0, we've noticed very small changes to the image will not fail the test. A single offset word, for example. 

We've tried other misMatchThreshold permutations like 0.00, 0.000000001, etc. and the tests still pass.

I'm guessing this difference is too small of a percentage for resemble.js, fractions of a percent. In which case this is not a Backstop issue, and likely resemble.js. But I thought I'd start here in case we're missing something.

**Comment by kiran-redhat** [comment]
@joseph-stano , What I also observed is when screen size gets bigger misMatchThreshold doesn't seems to work effectively (of course may be because this is the percentage of change).

**Comment by garris** [comment]
Wow -- that is humongous!  In fact, i think headless-chrome (which we are moving to in the near future) tops out in the neighborhood of 16,000.  

In any case, Backstop was never intended for that kind of use case.  What you should do in this case is use the `selectors: []` option and take _much_ smaller shots of various sections of our layout.  I think the neighborhood of 1000x1000 would be much more in the sweet spot.  Your milage may vary. 

Please let me know how it works out!

**Comment by joseph-stano** [comment]
Got it, I'll take a look at selectors.

To explain our use case a bit further - we're using a casper script (pretty slick!) to load multiple pages of our app before taking a full-height shot of our app. So I might try to see if we can take a shot of each page.

**Comment by mikenz** [comment]
`resemble.js:427:                  data.misMatchPercentage = (mismatchCount / (height*width) * 100).toFixed(2);`
It's always rounded to two decimals places.

**Comment by mikenz** [comment]
Probably should move to data.rawMisMatchPercentage
https://github.com/Huddle/Resemble.js/blob/master/resemble.js#L469
```
			data.rawMisMatchPercentage = (mismatchCount / (height*width) * 100);
			data.misMatchPercentage = data.rawMisMatchPercentage.toFixed(2);
```

**Comment by garris** [comment]
I think if you just use backstop to take all the screenshots and test you should be fine.  Otherwise you are better off just writing your own Casper scripts.

**Comment by klausbayrhammer** [comment]
I like @mikenz's suggestion - I think we should use the more accurate rawMisMatchPercentage

**Comment by garris** [comment]
@klausbayrhammer That is interesting.  Doing so would break quite a few tests -- unless we gated it with a config property.   

FWIW: I never had a good feel for the current misMatch metric -- I am open to adding the raw version.

**Comment by kiran-redhat** [comment]
I also like what @mikenz suggested as that will clearly tell the actual mismatch otherwise we are ending up getting false positives.
