### ISSUE TITLE
How to test css :hover? 

### ISSUE THREAD

**Issue by mantovanig** [garris/BackstopJS#478]
You can test css :hover?

**Comment by garris** [comment]
You can do this very easily in an `onReadyScript` handler.  I will try post an example soon.

**Comment by laubsauger** [comment]
You could use the [mouse module](http://docs.casperjs.org/en/latest/modules/mouse.html#move) - assuming casperjs:

Put this in a onReadyScript.js which you reference in your backstop.json. See the readme for details on that.
```javascript
module.export = function(casper) {
    casper.then(function() {
        this.mouse.move("#my-link"); // moves cursor over <a id="my-link">hey</a>
    });
};
```
with chromy you would do almost the same.

**Comment by mantovanig** [comment]
Thanks @laubsauger 
I had tried this solution but it did not work.

I will try again!

**Comment by eshperber** [comment]
any response to this question it was asked a long time ago and still no response to a common issue.

**Comment by garris** [comment]
This was addressed by addition of click and hover helpers.  See docs...

https://github.com/garris/BackstopJS/blob/master/README.md#testing-click-and-hover-interactions
