### ISSUE TITLE
No mention of reference or test commands in README

### ISSUE THREAD

**Issue by lewisnyman** [garris/BackstopJS#48]
Hello!

I noticed that there are no instructions on how to run the tests in the readme, it looks like they were removed in https://github.com/garris/BackstopJS/commit/b03aa5a04fb551c475ed84b18d4678ccd68b7e09

Is that intentional?

**Comment by garris** [comment]
Yowsa!  That's a hell of a catch!  That needs a fix immeadiately.    I should be fired for that one...

Thank you very much for catching this @lewisnyman!

**Comment by garris** [comment]
Ok.  Fixed!    (From my iPad).  Will proofread later...
