### ISSUE TITLE
Chromy engine runs slow with scenarios containing many selectors

### ISSUE THREAD

**Issue by daveaspinall** [garris/BackstopJS#480]
Hi Garris,

Creating a ticket in reference to #479.

Running `backstop reference` while using `"engine": "chromy"` takes forever to finish (not actually had it complete yet), whereas phantomjs finishes in 15s.

Backstop version: `BackstopJS v3.0.4`
Node version: `v7.6.0`

Snapshot of the backstop.json:
```
  "viewports": [
    {
      "name": "mobile",
      "width": 375,
      "height": 564
    },
    {
      "name": "tablet",
      "width": 768,
      "height": 1024
    },
    {
      "name": "desktop",
      "width": 1240,
      "height": 1024
    }
  ],
  "scenarios": [
    {
      "label": "Patternlab",
      "url": "Patternlab/public/styleguide/html/styleguide.html",
      "hideSelectors": [
        "[data-shop-map]",
        "[data-search-map]"
      ],
      "removeSelectors": [
        ".sg-pattern-head",
        ".sg-pattern-extra"
      ],
      "selectorExpansion": true,
      "selectors": [
        ".sg-pattern"
      ],
      "readyEvent": null,
      "delay": 500,
      "misMatchThreshold": 0.1,
      "requireSameDimensions": true
    }
  ],
  "engine": "chromy",
  "report": ["browser"]
```

Just an idea of how long it takes (there are ~54 components on the page):
![gif](http://g.recordit.co/EzIkCNXQ0O.gif "Screencast of reference speed")

Console output when using `"engine": "chromy"`:
```
BackstopJS v3.0.4
Loading config:  /Users/daveaspinall/Sites/oxfam/oxfam-main/backstop.json 

COMMAND | Executing core for `reference`
  clean | backstop_data/bitmaps_reference was cleaned.
createBitmaps | Selcted 1 of 1 scenarios.
Starting Chromy: port:9222 [ '--window-size=375,564' ]
CREATING NEW REFERENCE FILES
Starting Chromy: port:9223 [ '--window-size=768,1024' ]
CREATING NEW REFERENCE FILES
Starting Chromy: port:9224 [ '--window-size=1240,1024' ]
CREATING NEW REFERENCE FILES
9222 INFO >  backstopTools are running
9223 INFO >  backstopTools are running
9224 INFO >  backstopTools are running

Run `$ backstop test` to generate diff report.

      COMMAND | Command `reference` sucessfully executed in [2143.046s]
```

Console output when using `"engine": "phantomjs"`:
```
BackstopJS v3.0.4
Loading config:  /Users/daveaspinall/Sites/oxfam/oxfam-main/backstop.json 

COMMAND | Executing core for `reference`
  clean | backstop_data/bitmaps_reference was cleaned.
createBitmaps | Selcted 1 of 1 scenarios.

Running CasperJS with:  [ '~/.nvm/versions/node/v7.6.0/lib/node_modules/backstopjs/capture/genBitmaps.js',
  '--captureConfigFileName=/var/folders/44/1j9_33pj2kj0ygpsg03jmk_chh6558/T/capture/faaa966138ec0284c589c66a65cb1ca2ffc37025.json' ]
CasperJS:  CREATING NEW REFERENCE FILES
CasperJS:  Ready event received.
CasperJS:  Current location is Patternlab/public/styleguide/html/styleguide.html
CasperJS:  Capturing screenshots for mobile (375x564)
CasperJS:  Ready event received.
CasperJS:  Current location is Patternlab/public/styleguide/html/styleguide.html
CasperJS:  Capturing screenshots for tablet (768x1024)
CasperJS:  Ready event received.
CasperJS:  Current location is Patternlab/public/styleguide/html/styleguide.html
CasperJS:  Capturing screenshots for desktop (1240x1024)
CasperJS:  Comparison config file updated.

Bitmap file generation completed.

Run `$ backstop test` to generate diff report.

      COMMAND | Command `reference` sucessfully executed in [15.859s]
```

Any ideas what could be slowing this down? Let me know if you need any more info and I'll post it up.

Thanks 🤓

**Comment by dotneet** [comment]
Hi @daveaspinall, 
I'm owner of chromy.
Could you tell me your chrome version?

**Comment by daveaspinall** [comment]
Hey @dotneet!

Sure, versions for both stable Chrome and Canary below:

Chrome: Version 59.0.3071.115
Canary: Version 61.0.3163.0

Just wanted to say I'm actually really enjoying Chromy (we use it on some other tests) and thanks for the brilliant work 😇

**Comment by daveaspinall** [comment]
Update: Backstop is using Canary (which is apparently up to date) but it's still very slow

**Comment by dotneet** [comment]
@daveaspinall Thanks! I found the cause for this problem.

@garris Please update chromy version. chromy ver.0.3.3 doesn't work with chrome61 (canary).
0.3.4 or later works.

**Comment by daveaspinall** [comment]
@dotneet Thanks for the speedy solution!

**Comment by garris** [comment]
@dotneet Updated!

**Comment by daveaspinall** [comment]
@dotneet @garris: Updated the dependencies and tried the reference again but it's no faster I'm afraid 😕

**Comment by dotneet** [comment]
@garris Thank you for updating.

@daveaspinall 
In my environment, I've confirmed that the problem that I found in BackstopJS 3.0.4 is fixed.
But your problem seems to be different with the problem I found.
As @garris mentioned in #479, the optimization for selector expansion might be the solution.

**Comment by garris** [comment]
@daveaspinall Sorry to take so long to reply.   Can you pull down this file and run the main backstop test in there?   Then include the console output.  At the end of the log you'll find a line that looks like this... `COMMAND | Command `test` sucessfully executed in [35.681s]`   That timestamp is what I am after.  Thanks!

**Comment by garris** [comment]
@daveaspinall almost forgot to add the repo...
https://github.com/garris/backstop-feature-tests

^^^ please let me know the test time for this  thanks!

**Comment by daveaspinall** [comment]
@garris no problem! Appreciate the help from both of you on this.

Ran the test and it looks much faster! Console output below:

```
COMMAND | Command `reference` sucessfully executed in [43.171s]
```

There must be an issue with my specific config. Going to copy the backstop.json over from these tests and see if that helps.

**Comment by garris** [comment]
I assume the same thing happens if you run test instead of reference?  Also, how many selectors is backstop capturing.   How long does take for your app to become ready?  If you have 100 selectors and your app takes 4 seconds to load you could easily have a 400 second run time.

There is an optimization planned where multiple selectors would only require one page load -- this would probably make a very big difference in your case.

**Comment by garris** [comment]
Ok.  I think this is going to be important.  I will refactor our isExpanded code path.   It could be some time -- but it is the next thing on my list.  Thanks for your patience.

**Comment by garris** [comment]
@daveaspinall are you able to provide me access to the web app which causes the issue.  I would like to benchmark the issue.

**Comment by daveaspinall** [comment]
@garris apologies for the late reply!

>There is an optimization planned where multiple selectors would only require much less rendering work -- this would probably make a very big difference in your case.

This may help, but I've also tried the reference on only 3 selectors and it still ran slow?

>@daveaspinall are you able to provide me access to the web app which causes the issue. I would like to benchmark the issue.

Happy to set up my project for you to test! You may inadvertently find a problem with the setup. I'll send you a link shortly 🙂

**Comment by daveaspinall** [comment]
@garris test project setup for you:

https://github.com/daveaspinall/backstop-patternlab-test

Running `backstop reference` on in this test on my machine takes `[428.798s]`

**Comment by garris** [comment]
Great.  Thank you!

**Comment by garris** [comment]
It is looking like it may be a flaw with the expandedSelectors feature and not necessarily with the count of selectors.   This issue is now my top priority.

**Comment by daveaspinall** [comment]
@garris as I've said before, I really appreciate you putting this issue high priority! 😇

**Comment by dotneet** [comment]
@garris 
I've published chromy v0.4.0 that includes some performance improvements that can be used with chrome61 or later.
And I confirmed that this improvements soften this problem.

NOTE: this version requires chrome60 or later. to get performance improvements using chrome canary is recommended.

**Comment by dotneet** [comment]
In addition, new .screenshotSelector and .screenshotMultipleSelectors can get around the problem that be caused on very long page.

**Comment by garris** [comment]
@dotneet Just tested this.  

Yes speed is much better...  (Even before my refactor work)  But I think there is a chromy regression -- images are double resolution.

**previous version**
`Command `test` sucessfully executed in [19.099s]`
![image](https://user-images.githubusercontent.com/447033/28750505-6b18de02-74a2-11e7-940e-4cb3ea266f89.png)


**0.4.0 version**
`Command `test` sucessfully executed in [12.424s]`
![image](https://user-images.githubusercontent.com/447033/28750508-79f784f0-74a2-11e7-8468-9153e7720df7.png)

**Comment by dotneet** [comment]
Sorry, I've update chromy to v0.4.2 because of a regression bug.

**Comment by daveaspinall** [comment]
@garris @dotneet great! I'll have a play tomorrow!

**Comment by garris** [comment]
@dotneet this is a big improvement-- thank you!    I hope to finish my refactor in the next day or so also.

**Comment by garris** [comment]
UPDATE: This is almost fixed -- I just need to do some cleanup work before pushing a new version.  Early indication is that speed way better!

**Comment by garris** [comment]
Ok.  New version.  Hopefully this issue is sufficiently fixed...

old perf
`Command test successfully executed in [19.099s]`

new perf
`Command test successfully executed in [11.762s]`

tested on `isExpanded` scenario in backstop test repo.

**Comment by garris** [comment]
@daveaspinall Please retest to see if that addresses the issue.  Thanks!

remember to `npm install -g backstopjs`

**Comment by kiran-redhat** [comment]
shouldn't it be 'npm install backstop@beta' ? and
can't we run using locally installed backstop( without -g)?

**Comment by garris** [comment]
@kiran-redhat 😮 Yes!  Great catch!  I fixed the line above.

And yes.  Local install should still work fine.

Thank you for posting!

**Comment by daveaspinall** [comment]
@garris Can confirm the reference task is much much faster!

Was: `COMMAND | Command `reference` sucessfully executed in [2143.046s]`

Now: `COMMAND | Command `reference` sucessfully executed in [35.389s]`

Seriously great work!! 🙌🏼  Going to mark this issue as complete 🎉

Now to fix our issue with Chromy in my Docker container and our setup with be sweet

**Comment by garris** [comment]
Ok. I think this is addressed for now.   

Closing -- but please reopen if your problem is not resolved.

Cheers.
