### ISSUE TITLE
config not defined in getMismatchthreshold

### ISSUE THREAD

**Issue by josh-wilson-sociomantic** [garris/BackstopJS#483]
Running `beta` and chromy, `config` is not defined.

I've a PR prepped/tested locally that sorts this (to follow).

Thanks for the work on chrome headless! It works great outside of this 🎉

**Comment by josh-wilson-sociomantic** [comment]
https://github.com/garris/BackstopJS/pull/484

**Comment by garris** [comment]
Merged!  Thanks for the commit!
