### ISSUE TITLE
UPDATE TRAVIS FOR v3.x.x  [HELP WANTED]

### ISSUE THREAD

**Issue by garris** [garris/BackstopJS#485]
v3 is ready for a public beta.  Anyone who has time -- please help implement!  After this is done we can merge 3.0.x back to master.  Currently working on backstop_chromy branch.

Acceptance Criteria -- ensure the following run successfully...

- install backstopjs in node 6.1 & 8.1
- make folder, run backstop init, backstop test(assert fail), backstop approve, backtop test(assert pass) 
- install https://github.com/garris/backstop-feature-tests and cd into folder `backstop-feature-tests`.
- then backstop reference then backstop test(assert pass)

**Comment by josh-wilson-sociomantic** [comment]
In `backstop-feature-tests` on osx, node 8.1.4  / backstop 3.0.7,  I'm getting   `Error: Cannot navigate to invalid URL` errors on each test.

Similarly if I try and run tests in the `examples` folder in the chromy branch.

**Comment by garris** [comment]
^^ may be a chromy regression.  Just posted issue to chromy repo.

**Comment by garris** [comment]
@josh-wilson-sociomantic the issue was caused by a chromy regression.  

The issue is fixed on the chromy branch so a new backstop install should fix the issue.  

Thank you for working on this issue!

**Comment by garris** [comment]
CLOSED BY 0535303326e658e69d78f6405aac390b620ff222
