### ISSUE TITLE
Chromy onBefore scripts

### ISSUE THREAD

**Issue by tyler36** [garris/BackstopJS#489]
Hi,

Thanks for the continued development of this great app. I find it really useful.
I have not problems running the beta versions with the exception of script.

I know that backstop-chromy is still in beta but was hoping to get a little help with something not covered in the documentation (yet?)

I use Laravel framework and have a route setup to automatically log in users.
In BackstopJs v2.7.5 I used the following onBefore script
```
// EXPORT:      'LoginAsUser' function
module.exports = function LoginAsUser( casper, scenario ) {
    var loginUrl = 'http://app.local/login/id/1;'

    // LOG:     Login in as User
    casper.echo( 'Authenticating at ... ' + loginUrl );
    casper.open( loginUrl, function cb() {
        console.echo( 'Logged in' );
    } );
};
```

I can't seem to figure out how to replicate this with Chromy
```
const Chromy = require( 'chromy' );

module.exports = function ( engine, scenario, vp ) {
    const chromy = new Chromy().chain()
        .goto( 'https://onsen.dev/login/id/1' )
        .close().end();
    console.log( 'Logged in');
};
```
... but this throws the below error (regardless of the URL I use ie; ones that work in the browser)
```
Error: unexpected server response (500)
    at ClientRequest._req.on (I:\workspace\testing\backstop-chromy\node_modules\ws\lib\WebSocket.js:651:26)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
```

By adding a port it seems to work ( i can see the window open and log in)
```
...
// Excuse poor-mans random port generator
    const chromy = new Chromy({port: Math.floor(Math.random() * 20) + 6070, visible: true}).chain()
...
```
however the actual scenario screenshot does not show the user as logged in. The browser sees it as a different session? 

Any ideas for what I could do?

**Comment by garris** [comment]
Here is an example script.  Does this help?

https://github.com/garris/backstop-feature-tests/blob/master/backstop_data/engine_scripts/onReady.js

See the same repo for onBefore script too.

**Comment by tyler36** [comment]
Hi Garris,

The example scripts helped me understand better. Really loving the Chromy version. It feels faster and unlike PhantomJS, I don't have to use old CSS (old flexbox style) or polyfill JS (no es6-promise) to make sure the site works properly in the tests.

Can't wait for the final release.

FYI, I ended up with the simple item below.
```
    return chromy
        .goto( 'https://demo.dev/login' );
```

**Comment by garris** [comment]
Great to hear -- thanks for the feedback!
