### ISSUE TITLE
Backstop instantiates Chrome in main app instance

### ISSUE THREAD

**Issue by josh-wilson-sociomantic** [garris/BackstopJS#491]
So, I've replicated to the problem to just being whenever I have Chrome open and browsing around.

When it's closed and I run backstop my usual Chrome icon fires up, and is clearly being used for a few tests. If I try and open Chrome as normal during this, I get the hanging tests... (as described https://github.com/garris/BackstopJS/issues/479#issuecomment-319684498)

(This might well be a Chromy issue, not sure...) 

On OSX/Sierra / with backstop 3.0.7 / node 8.1.4

**Comment by garris** [comment]
At the moment -- chrome canary latest is required for tests.  Opening chrome canary during testing is not supported.   But I have had multiple regular chrome windows open during tests (while canary is used by backstop-chromy) with no issues.  So maybe that approach will work for you better?

**Comment by josh-wilson-sociomantic** [comment]
> chrome canary latest is required for tests

Aha. I missed that somewhere. Maybe that's why. I'll try more with canaries and if it's not a problem, close this 👍

**Comment by josh-wilson-sociomantic** [comment]
no problems in canary thus far. Cloooosing. Thanks for your patience @garris !

**Comment by garris** [comment]
Sure.  Actually -- this is really an important post.  It made me realize that we really need to help existing users to understand the **chrome canary** requirement.  (It wasn't a requirement before so users may assume that backstopjs will install it for them)  Maybe we need to check the users env and throw a warning at the end of the CLI log if we don't detect it?   Or maybe we can make it easier to run this as an install option `brew install Caskroom/versions/google-chrome-canary`

**Comment by josh-wilson-sociomantic** [comment]
I think if it is _required_, we shouldn't run the tests at all and just throw a warning / note on install? Probably pointing to `brew` as you noted. I think that'd make the most sense/be simplest if it's easily detectable.
