### ISSUE TITLE
Blue Box with Question Mark Inside

### ISSUE THREAD

**Issue by eugenefedoto** [garris/BackstopJS#493]
I'm getting this ->

![image not loading](http://i.imgur.com/lyd5Xi9.png)

The actual website is supposed to have ->

![how it's supposed to look](http://i.imgur.com/d4mREnf.png)

I've tried delaying to 20s.

**Comment by garris** [comment]
Run backstopjs in debug mode.  see if you have any interesting errors.   I bet your image calls are all 404-ing.    Domain issue?  Relative path issue?

**Comment by eugenefedoto** [comment]
@garris Bunch of remote errors such as `[error] [phantom] remote error > http://localhost:3001/images/esfiddle.png failed to load (404)`. I'm able to access that esfiddle.png URL through my browser, but apparently not through phantom.

**Comment by garris** [comment]
what version of backstop are you using?   You could try using chrome headless maybe your problem will just go away.   
`npm install backstopjs@beta`
https://github.com/garris/BackstopJS/blob/backstop-chromy/README.md

**Comment by eugenefedoto** [comment]
I re-installed the non-beta backdropjs and restarted the computer. Now the image is showing up. I'm still getting some remote errors reported by Casper, but I'll figure that out later.
