### ISSUE TITLE
Any plans for using Puppeteer?

### ISSUE THREAD

**Issue by boriskaiser** [garris/BackstopJS#494]
> Puppeteer is a Node library which provides a high-level API to control headless Chrome over the DevTools Protocol. It can also be configured to use full (non-headless) Chrome.

— https://github.com/GoogleChrome/puppeteer/

CC: @garris

**Comment by garris** [comment]
@boriskaiser thanks for the post.  I am very excited about chrome headless and will in-fact be merging a ChromyJS-based implementation into BackstopJS today!

We are actively discussing the Puppeteer integration strategy at the moment and I will update this post when we have settled on a plan.

In the meantime -- you can start using chrome-headless with backstop & ChromyJS today!  `npm install -g backstop@beta` and check out the backstop-chromy branch for documentation.

Cheers!

**Comment by boriskaiser** [comment]
@garris 
Thanks for your quick reply.
I look forward to use the third version.

**Comment by matthew-dean** [comment]
Bump. Would love to test to see if Puppeteer is faster than Chromy, which some say it might be.

**Comment by garris** [comment]
Chromy is awesome and Shinji (the author) is fantastic with support — he really helped us make the jump to headless chrome.

That said, puppeteer is clearly the de-facto standard and i am happy if you want to do the work to explore it.  

Feel free to start a new feature Branch if you want to experiment — but make sure to rebase off of UIV3 Branch — that will soon be merged into master.

Cheers!

**Comment by pkra** [comment]
FYI Shinji is interested in switching Chromy over to puppeteer, see https://github.com/OnetapInc/chromy/issues/64.

**Comment by garris** [comment]
aaaaand...
Puppeteer is in development.

https://github.com/garris/BackstopJS/tree/puppeteer
cloned from...
krisdigital/BackstopJS@b4213d9
