### ISSUE TITLE
Allow `bitmaps_reference` location to be configurable outside the backstopjs folder

### ISSUE THREAD

**Issue by bassettsj** [garris/BackstopJS#50]
Would be great to allow this file location to be outside the backstopjs folder if possible. I would like to be able to check in the reference folder without having to do the following in the `.gitignore` file:

```
node_modules/backstopjs/*
!node_modules/backstopjs/bitmaps_reference/
!node_modules/backstopjs/bitmaps_reference/*
```

**Comment by bassettsj** [comment]
If you think this is a good idea, I would be happy to provide a PR.

**Comment by garris** [comment]
This would be fabulous.  Yes, please send a PR!

**Comment by boriskaiser** [comment]
+1

**Comment by JohnnyEvo** [comment]
:+1:

**Comment by YuliaTsareva** [comment]
+1

**Comment by asilvadelpozo** [comment]
+1

**Comment by garris** [comment]
This was added in 0.6.2.  Cheers.
