### ISSUE TITLE
How to manage animated elements?

### ISSUE THREAD

**Issue by ryuran** [garris/BackstopJS#502]
Hello

One of my tests is on an animated element.
It's fail each time because the screenshot is never taken at same time.
How to avoid this behavior?

**Comment by garris** [comment]
Here is an article which covers capturing after an animation.   The example shows an angular app but the principle applies to any JavaScript or CSS animation.   https://davidwalsh.name/visual-regression-testing-angular-applications

**Comment by ryuran** [comment]
@garris, good information but for a looping animation (loader) I can’t wait the end.
So, I should disable the css animation rules? In the “on ready” script?

**Comment by garris** [comment]
I see.  That's different.  If it were me I would just hide the element -- continuous animation is not something you can test.

**Comment by ryuran** [comment]
I use this on my project and it seems working as I would. Thanks

```
module.exports = function (casper, scenario, vp) {
    casper.evaluate(function () {
        var styleEl = document.createElement('style');

        // Append style element to head
        document.head.appendChild(styleEl);

        // Grab style sheet
        var styleSheet = styleEl.sheet;

        // Insert CSS Rule
        styleSheet.insertRule('*, *:before, *:after { -webkit-animation-delay: 0s !important; -webkit-animation-duration: 0s !important; animation-delay: 0s !important; animation-duration: 0s !important; }', styleSheet.cssRules.length);
    });
    console.log('onReady.js has run for ' + vp.label + '.');
};
```

**Comment by garris** [comment]
Looks great -- thanks for posting your solution!
