### ISSUE TITLE
HideSelector

### ISSUE THREAD

**Issue by tyler36** [garris/BackstopJS#505]
On 3.0.16, everything seems to run fine. 

3.0.17, seems to ignore the 'hideSelectors' option completely during the reports.
I notice the appears of the following error in the console.
```
Chromy requires Chrome ver.61 or later. Please install latest version Chrome.
```

But checking for a new version of the desktop Chrome clients says I'm on the latest version "Version 60.0.3112.101 (Official Build) (64-bit)"

I tried to downgrade back to 3.0.16 (yarn remove -> yarn add) but it seems like it is still using the latest version of Chromy (with console warning and ignoring hideSelectors during reports)

OS: Win10

**Comment by garris** [comment]
Please try downloading and installing Chrome Canary from Google...

here ===> https://www.google.com/chrome/browser/canary.html

**Comment by tyler36** [comment]
Resolved by installing Chrome Canary
