### ISSUE TITLE
error: Chromy requires Chrome ver.61 or later. Please install latest version Chrome.

### ISSUE THREAD

**Issue by garris** [garris/BackstopJS#506]
Hello backstop users:   If you see this error...
```
error: Chromy requires Chrome ver.61 or later. Please install latest version Chrome.
```
then please download and install Chrome Canary from Google!

here ===>  https://www.google.com/chrome/browser/canary.html

**Comment by fede-green** [comment]
Sad! there's not a version for ubuntu yet :(.

Is there a way to downgrade? I'm exploring backstop, seems interesting! :)

**Comment by garris** [comment]
You can just use the phantomjs option until chrome is released for your platform.  They are at parity in terms of BackstopJS features.

**Comment by trevobr** [comment]
I've installed Canary at my Mac but still doesn't work. :(

**Comment by garris** [comment]
@trevobr  please make sure you have latest supported versions of node, npm, backstop, chrome.

**Comment by peterhry** [comment]
If you see that message in your travis log, you’ll need to load the chrome beta addon and set `CHROME_PATH` so chromy knows where to find the beta.

```
addons:
  chrome: beta
env:
  - CHROME_PATH=/usr/bin/google-chrome-beta
```

**Comment by axe312ger** [comment]
Also related to Travis CI:

Chrome 61 was released to Debian on `2017-09-05 20:08:56 UTC`. So you can even skip the Chrome beta now:

```
addons:
  chrome: stable
```

**Comment by garris** [comment]
Chrome 62 (now in beta is the recommended version)  Thanks.
