### ISSUE TITLE
BackstopJS with Chrome headless shell for chromy

### ISSUE THREAD

**Issue by kiran-redhat** [garris/BackstopJS#510]
Hey @garris,  I want to run BackstopJS  with Chrome headless shell this way https://github.com/OnetapInc/chromy/issues/63#issuecomment-324287340

Wondering about your thoughts if you would like you see this change (if it works) or you have any alternatives?

**Comment by garris** [comment]
This is doable now.   Just fire off your chromy script in the ENV and set the chrome flag in your backstop config (use engineFlags prop)

**Comment by kiran-redhat** [comment]
"Just fire off your chromy script in the ENV "  you mean onReady and
onBefore scripts?

**Comment by garris** [comment]
Sorry -- I was on my phone ^^^

More specifically -- you could create an npm script which would first run this...
```
new Chromy({
  launchBrowser: false
})
```

then in the backstop config and in runChromy.js you'll need to add the `chromePath` property which you can set in the config -- (my suggestion to use engineFlags above was wrong).
And your config would have...
```
chromePath: '/path_to/headless_shell_executable'
```

This makes me think we need to rethink the engineFlags property here.  I'd prefer just one top level property that extends the default chromy config object.    But don't worry about this yet.  Just see if your main idea works first.

**Comment by kiran-redhat** [comment]
Thanks @garris , managed to run chrome headless-shell, however not able to use proxy with following flag in backstop config file, where should I be mentioning it?

`  "hostFlags": [
    "--proxy-type=http",
    "--proxy=127.0.0.1:4496"
  ],`

**Comment by garris** [comment]
Apologies -- I was very busy at work today.  (I was mistaken)  you will need to extend BackstopJS to do this.    You can add a property to the config `hostOptions` and internally extend the following object with `scenario.hostOptions`.

https://github.com/garris/BackstopJS/blob/35f822f8248c047b6117b7f29e23072aa7cbd519/core/util/runChromy.js#L164

**Comment by garris** [comment]
@kiran-redhat I just saw @dotneet's post.  Yes, that property will send the flag values to chrome.   If it works with chromy it should work with BackstopJS.

**Comment by kiran-redhat** [comment]
Hey @garris `  "hostFlags": [
'--proxy-server=127.0.0.1:**port**'
  ],` fixed the issue, however, where there are more than 6 viewports am getting "GotoTimeoutError: goto() timeout" error

https://github.com/OnetapInc/chromy/blob/8e46818c723c04f09428df7636f1a85df766d934/src/error.js here is where it is coming from. I guess, one of the chromy got timed out ?

**Comment by garris** [comment]
Will the test work if you remove the last scenario?

**Comment by kiran-redhat** [comment]
Sorry, I meant it hangs after following line of log:

`BackstopExcpetion: <<scenario name>> on <<viewport>>: GotoTimeoutError: goto() timeout`

Do you see any issues when 9 viewports are used?

**Comment by garris** [comment]
No, number of viewports should not be an issue.   Have you tried removing viewports?

**Comment by kiran-redhat** [comment]
Yes, I don't see this issue up to 6 viewports.. it definitely not because
of increase in viewports but I think wait time for one of the ports getting
over once it is over 6 viewports..

**Comment by garris** [comment]
is it the just number or is it a particular value?

**Comment by kiran-redhat** [comment]
Here is the issue: When there are more than 6 view ports, backstop throwing error:

![image](https://user-images.githubusercontent.com/17115939/29698127-77592c2a-89a7-11e7-8656-e9132e755aa7.png)

**Comment by garris** [comment]
Just to be sure, can you try 1 viewport and 6 or 7 scenarios?

Might also be instructive to try setting `asyncCaptureLimit` to 1.

**Comment by garris** [comment]
Maybe you could open activity monitor and see what your CPU/RAM usage is like?   It could just be that if the goto timeout was increased the whole thing would just work -- however slowly.   Perhaps 10 concurrent is too aggressive-- my laptop does seem to get unhappy after attempting to drive 10 chrome instances at the same time.

**Comment by garris** [comment]
When backstop completes it displays a summary of tasks with duration times for each.   It would be helpful if you wanted to list times in relation to various concurrency settings.

**Comment by kiran-redhat** [comment]
I will check this tomorrow. @garris, how much RAM each instance of chrome
 roughly takes?( I understand that we are running 10 of them by default)

**Comment by garris** [comment]
Thanks.  I did not check this myself -- so I don't know.

**Comment by kiran-redhat** [comment]
@garris, this does looks like a memory issue on surface (didn't get chance to did deeper).

However, am able to run with 7 concurrent chrome ports, so configured to accept  concurrent ports count from config file. And added chromePath as well. Here are the changes if you would like me to create PR.

 https://github.com/kiran-redhat/BackstopJS
