### ISSUE TITLE
Expose mismatch threshold as a configurable option

### ISSUE THREAD

**Issue by lewisnyman** [garris/BackstopJS#52]
Right now it's possible for subtle regressions to be missed by the reporting tool. This is a shame because the great value in a tool like this is catching regressions that are easily missed by humans.

The default value right now is:
```
var misMatchThresh = 1;
```
See #21

**Comment by garris** [comment]
I know, this is totally worth doing.  I have some time coming up where I could get it done. Will do a pass ping you when I have something to test.   GS

**Comment by garris** [comment]
Files merged and bugs fixed.

**Comment by MatteoWebDesigner** [comment]
Hi I guess something has changed even if I set mismatch 0.1, the value is not used. Is there an example showing the correct way to config this setting. Thanks

**Comment by garris** [comment]
What version are you on?

**Comment by MatteoWebDesigner** [comment]
1.1.0
config: https://github.com/MatteoWebDesigner/CSS-Architecture/blob/master/backstop.json

**Comment by garris** [comment]
@MatteoWebDesigner 

this line 
https://github.com/MatteoWebDesigner/CSS-Architecture/blob/master/backstop.json#L54

should be

     "misMatchThreshold": 0.1,

(you have `"misMatchThresh": 0.1,`)

**Comment by MatteoWebDesigner** [comment]
I see :O https://github.com/lewisnyman/BackstopJS/blob/f6d2a09d8556294f85fce1ee1bfa625143ce5db0/capture/echoFiles.js#L19

thank you now works fine.

**Comment by garris** [comment]
Cheers.  :+1:
