### ISSUE TITLE
Approve changes and implementation on CI

### ISSUE THREAD

**Issue by anton-kulagin** [garris/BackstopJS#522]
Hello, i`m wounder is there is a way to approve changes(update reference) for one specific screenshot from generated html report for example?  

And please advise a way to implement this tool on team city. I mean maybe you have  an example or article about it.

Also i didn`t find list of format for CI reports? by default it`s junit, but maybe there are more variants?

**Comment by willenium** [comment]
Yes I just wanted to ask this as well. +1

**Comment by kiran-redhat** [comment]
This really will be a good feature to add..

**Comment by garris** [comment]
Moved to #530 

Any help on this greatly appreciated.

**Comment by garris** [comment]
Sorry forgot to comment on CI reports.  There is only one at the moment.  Feel free to contribute new ones!  Cheers.
