### ISSUE TITLE
 BackstopJS Homepage on undefined: Error: Failed to launch a browser.

### ISSUE THREAD

**Issue by reynaldoapb** [garris/BackstopJS#526]
After some error of timeout, even the basic example of backstop throw an error when i try to run $backstop reference or $backstop test command. How can I workaround this? 

p.s.: When i restart windows it get`s back to work properly. 

Do you have some advice? 

error.: SCENARIO > BackstopJS Homepage
      COMMAND | Command `test` ended with an error after [0.031s]
      COMMAND | BackstopExcpetion: BackstopJS Homepage on undefined: Error: Failed to launch a browser.

**Comment by reynaldoapb** [comment]
Facing this problem I can see that the default example (reference and test)  after I ran $backstop init works! But if I change any parameter and run it again (reference or test) I got timeout error. Even if I try a small site like http://google.com.

**Comment by garris** [comment]
Please post config sample.

**Comment by reynaldoapb** [comment]
first try on my localhost.:

{
  "id": "backstop_default",
  "viewports": [
    {
      "label": "phone",
      "width": 320,
      "height": 480
    },
    {
      "label": "tablet",
      "width": 1024,
      "height": 768
    }
  ],
  "onBeforeScript": "chromy/onBefore.js",
  "onReadyScript": "chromy/onReady.js",
  "scenarios": [
    {
      "label": "local homepage",
      "cookiePath": "backstop_data/engine_scripts/cookies.json",
      "url": "http://localhost:8080/checkout/cadastro",
      "referenceUrl": "",
      "readyEvent": "",
      "readySelector": "",
      "delay": 0,
      "hideSelectors": [],
      "removeSelectors": [],
      "hoverSelector": ".chromy",
      "clickSelector": "",
      "postInteractionWait": "",
      "selectors": [],
      "selectorExpansion": true,
      "misMatchThreshold" : 0.1,
      "requireSameDimensions": true
    }
  ],
  "paths": {
    "bitmaps_reference": "backstop_data/bitmaps_reference",
    "bitmaps_test": "backstop_data/bitmaps_test",
    "engine_scripts": "backstop_data/engine_scripts",
    "html_report": "backstop_data/html_report",
    "ci_report": "backstop_data/ci_report"
  },
  "report": ["browser"],
  "engine": "chrome",
  "engineFlags": [],
  "debug": false,
  "debugWindow": false
}

**Comment by reynaldoapb** [comment]
The default config works properly. I mean the file generated with backstop init. But when I change URL for example , I allways got time out error.

**Comment by kiran-redhat** [comment]
are you behind proxy? if so, please use casperFlags(if Casper)/hostFlags(if
chromy).

**Comment by garris** [comment]
I see you have `"hoverSelector": ".chromy"` in your config.  This is the issue as you probably don't have this selector in your layout.

**Comment by reynaldoapb** [comment]
@garris I've did what you say. Reinstalled and update everything (Node,NPM) and it works. Thks. p.s.: And removed additional parameters on bakcstop.json.

**Comment by GhazalMishra** [comment]
Hi, I am not able to login to my application.I get an error as :-
Puppeteer encountered an error while running scenario "Application HomePage"
Error: net::ERR_INVALID_AUTH_CREDENTIALS at https://xxx
I want to bypass the corporate proxy with username/password. How to do that?
Thanks for your help
