### ISSUE TITLE
Help wanted:  add `--filter` arg to backstop approve command

### ISSUE THREAD

**Issue by garris** [garris/BackstopJS#530]
Would love to be able to approve specific files.

E.g.  backstop approve --filter=<regexStr>   (Regex tests filename)

**Comment by anton-kulagin** [comment]
@garris Hi, i do this stuff but can`t create a branch. So here you can see my commit https://github.com/garris/BackstopJS/compare/master...anton-kulagin:approve-filter?diff=split&expand=1&name=approve-filter

**Comment by garris** [comment]
See PR #534

**Comment by garris** [comment]
closed by #534    Thank you!
