### ISSUE TITLE
Compare image not same size

### ISSUE THREAD

**Issue by patriciamarchand** [garris/BackstopJS#531]
Hello, 
just a little suggestion for a more accurate comparison tool. I'm not using it very othen but I propose to change the CSS to not resize the image with height 100%. This way, images images that do not have the same size are more easily comparable. 
`.revealer__top-image .revealer__image {
  position: absolute;
  ...
  /* height: 100%; */
  ...
}
`

I propose also, if the revealer Handel could be thinner It would be more easy to compare.
`.revealer__handle  {
 width:1px;
}`

And a border (green for reference and orange for test) around the images to show dimension. That help also because we remove the height to determine witch image is witch. 

![snag-0039](https://user-images.githubusercontent.com/6225238/29940875-98e61c70-8e5e-11e7-91b8-62ea23311bad.png)

**Comment by garris** [comment]
I totally agree with this!  I would gladly pull in this change!

There are many things I would like to see on this report -- filtering by label is another thing too.
