### ISSUE TITLE
Capturing entire body for different pages without changing viewport width and height

### ISSUE THREAD

**Issue by kiran-redhat** [garris/BackstopJS#532]
Hey @garris , Casper doesn't have this issue but Chromy does.

Let's say page one is of height 3000px and page 2 is of height 5000px. And I have used following in my config file
`  "selectors": [
      "body"
    ],
"viewports": [
    {
      "name": "laptop",
      "width": 1366,
      "height": 4000
    },
    {
      "name": "desktop",
      "width": 1920,
      "height": 4000
    },]`

When `backstop reference` is run, I see page 1 with 1000px of empty space at the end and page 2 doesn't show last 1000px.  What is the best approach towards fixing this?

**Comment by garris** [comment]
Hmmm.  This is something that I never tested for.   Obviously, the different engines handle this differently.   Did you try using the 'document' selector?   Is this an actual problem -- or just a difference you wanted to account for?  

It may be a question for @dotneet.

**Comment by kiran-redhat** [comment]
Yes, I've tried `document`, `body` & `body:noclip`.

**Comment by kiran-redhat** [comment]
chrome 61 built with latest chrome code is working as expected.
