### ISSUE TITLE
local installation doesn't work with slimerJS

### ISSUE THREAD

**Issue by ocetnik** [garris/BackstopJS#533]
When I use your https://github.com/garris/BackstopJS/blob/master/examples/jsBasedConfig/backstopConfig.js, remove `onBeforeScript`, `onReadyScript`, change engine to `slimerjs` and enable `debug`:

My index.js:
```
module.exports = {
    id: 'test',
    viewports: [
        {
            name: 'phone',
            width: 320,
            height: 480
        },
        {
            name: 'tablet_v',
            width: 568,
            height: 1024
        },
        {
            name: 'tablet_h',
            width: 1024,
            height: 768
        }
    ],
    scenarios: [
        {
            label: 'My Homepage',
            url: 'https://garris.github.io/BackstopJS/',
            hideSelectors: [],
            removeSelectors: [],
            selectorExpansion: true,
            selectors: [
                'body',
                '.jumbotron',
                '.firstPanel > div',
                '.secondPanel'
            ],
            readyEvent: null,
            delay: 500,
            misMatchThreshold: 0.1
        }
    ],
    paths: {
        bitmaps_reference: 'backstop_data/bitmaps_reference',
        bitmaps_test: 'backstop_data/bitmaps_test',
        casper_scripts: 'backstop_data/casper_scripts',
        html_report: 'backstop_data/html_report',
        ci_report: 'backstop_data/ci_report'
    },
    casperFlags: [],
    engine: 'slimerjs',
    report: ['browser'],
    debug: true
};
``` 

and I run locally installed backstopJS: `./node_modules/.bin/backstop reference --config index.js 
` i get error `this.filter is not a function`:
```
CasperJS:  Debug is enabled! 
CasperJS:  CREATING NEW REFERENCE FILES 
CasperJS:  this.filter is not a function                                                    
CasperJS:    /myProject/node_modules/casperjs/modules/casper.js:1449 
CasperJS:    /myProject/node_modules/casperjs/modules/casper.js:1449 in log 
CasperJS:    /myProject/casperjs/modules/casper.js:1881 in start 
CasperJS:    /myProject/backstopjs/capture/genBitmaps.js:82 in capturePageSelectors 
CasperJS:    /myProject/backstopjs/capture/genBitmaps.js:345 
```

When I use globally installed backstopJS with the same config: `backstop reference --config index.js ` everything works well.

backstopjs v.3.0.22
slimerjs v.0.10.3

**Comment by garris** [comment]
Can you paste the entire log output?

**Comment by ocetnik** [comment]
```
BackstopJS v3.0.22
Loading config:  /myProject/index.js 

COMMAND | Executing core for `reference`
  clean | backstop_data/bitmaps_reference was cleaned.
createBitmaps | Selcted 1 of 1 scenarios.

Running CasperJS with:  [ '/myProject/node_modules/backstopjs/capture/genBitmaps.js',
  '--engine=slimerjs',
  '--captureConfigFileName=/var/folders/__/c9cfdph90939p5_m2w47nngc0000gn/T/capture/32f9dcae709d8450519960f4d7f04064d6756e52.json' ]
CasperJS:  Debug is enabled! 
CasperJS:  CREATING NEW REFERENCE FILES 
CasperJS:  this.filter is not a function                                                    
CasperJS:    /myProject/file:/myProject/node_modules/casperjs/modules/casper.js:1449 
CasperJS:    /myProject/file:/myProject/node_modules/casperjs/modules/casper.js:1449 in log 
CasperJS:    /myProject/file:/myProject/node_modules/casperjs/modules/casper.js:1881 in start 
CasperJS:    /myProject/file:/myProject/node_modules/backstopjs/capture/genBitmaps.js:82 in capturePageSelectors 
CasperJS:    /myProject/file:/myProject/node_modules/backstopjs/capture/genBitmaps.js:345 

Testing script failed with code: 1

An unexpected error occured. You may want to try setting the debug option to `true` in your config file.
      COMMAND | Command `reference` ended with an error after [1.712s]
      COMMAND | Error: An unexpected error occured. You may want to try setting the debug option to `true` in your config file.
                    at ChildProcess.<anonymous> (/myProject/node_modules/backstopjs/core/util/createBitmaps.js:161:18)
                    at emitTwo (events.js:125:13)
                    at ChildProcess.emit (events.js:213:7)
                    at maybeClose (internal/child_process.js:927:16)
                    at Socket.stream.socket.on (internal/child_process.js:348:11)
                    at emitOne (events.js:115:13)
                    at Socket.emit (events.js:210:7)
                    at Pipe._handle.close [as _onclose] (net.js:545:12)
```

**Comment by garris** [comment]
@ocetnik  Unfortunately this may be a bug in BackstopJS or it may be something that can be addressed in the config.   In the past -- some users had issues using slimer and they solved their issue by using absolute paths in their config file.  Maybe you can search past issues for this.  I am sorry I can't be more of a help here.  I imagine this issue would not be too hard to track down.   (The issue is originating from genBitmaps.js and this is usually easy to fix)  Please post back if you are able to resolve it.  I'm sure other users would appreciate it.   Thank you.

**Comment by kiran-redhat** [comment]
Try changing your config to
`module.exports = {
    id: 'test',
    viewports: [
        {
            name: 'phone',
            width: 320,
            height: 480
        },
        {
            name: 'tablet_v',
            width: 568,
            height: 1024
        },
        {
            name: 'tablet_h',
            width: 1024,
            height: 768
        }
    ],
    scenarios: [
        {
            label: 'My Homepage',
            url: 'https://garris.github.io/BackstopJS/',
            hideSelectors: [],
            removeSelectors: [],
            selectorExpansion: true,
            selectors: [
                'body',
                '.jumbotron',
                '.firstPanel > div',
                '.secondPanel'
            ],
            readyEvent: null,
            delay: 500,
            misMatchThreshold: 0.1
        }
    ],
    paths: {
        bitmaps_reference: 'backstop_data/bitmaps_reference',
        bitmaps_test: 'backstop_data/bitmaps_test',
        casper_scripts: 'backstop_data/casper_scripts',
        html_report: 'backstop_data/html_report',
        ci_report: 'backstop_data/ci_report'
    },
    engine: 'slimerjs',
    "casperFlags": [
        "--engine=slimerjs",
        "--proxy-type=http",
        "--proxy=ip:PORT",
    ],
    report: ['browser'],
    debug: true
};`

Although code doesn't require us to specify engine twice - give it a try (this works for me). Please replace proxy-type & proxy if you are using one.

Are you able to run `backstop test` ?

**Comment by ocetnik** [comment]
@garris Thank you so much. It is probably caused by my other dependencies, because when I create new project which contains only BackstopJS dependency, everything works well. But when I add BackstopJS dependency into my project, the above error will occur. So in the second case BackstopJS uses different dependency/dependencies (installed by my project dependencies) caused by carets in package.json.

@kiran-redhat `backstop test` throws the same error and your config doesn't fix this error. But thank you for your time and willingness.
