### ISSUE TITLE
Config Bug - core/util/runChromy.js:158 & capture/config.default.json:46

### ISSUE THREAD

**Issue by josephmcasey** [garris/BackstopJS#535]
The control logic looks for a reference of `hostFlags`. The default configuration provided to users references `engineFlags`.

**Comment by josephmcasey** [comment]
As an additional note, I believe `--disable-infobars=true` should be added to the default hostFlags constant to prevent false negatives from cropping up when using `debugWindow:true`

**Comment by garris** [comment]
Just pushed a fix for both of these to master.

**Comment by josephmcasey** [comment]
Thanks @garris !
