### ISSUE TITLE
Enabling the WebGL Context for Chromy

### ISSUE THREAD

**Issue by josephmcasey** [garris/BackstopJS#536]
I'd like to suggest that the default flags used for Chromy be removed. Instead of providing `--disable-gpu,--force-device-scale-factor=1,--window-size=1024,768,` by default

I would like to have a default of something like this `--force-device-scale-factor=1,--window-size=1024,768,--disable-infobars,--use-gl=any`. Why not allow or suggest flags to used via the config instead of forcing certain flags by default?

**Comment by josephmcasey** [comment]
Relevant thread regarding these chromium flags, https://bugs.chromium.org/p/chromium/issues/detail?id=477779

**Comment by garris** [comment]
@josephmcasey the reason for disabling gpu is so that diffs from different machines can be compared.  When hardware acceleration is enabled, text anti-ailasing happens on the hardware -- using hardware algorithms -- which result in anti-alias diffs across machines.  This is a primary use case -- that is why it is baked in like this.

I am open to allowing overriding this behavior.  Just needs to make sense for the primary use case.

What are you running into?

**Comment by josephmcasey** [comment]
Steps to reproduce the problem:
1. `npm install -g backstopjs`
2. Change directory to desired project
2. `backstop init`
3. Change `"debugWindow": false` to `"debugWindow": true` in backstop.json 
3. `backstop test`
4. Open Chrome Canary console
5. type `document.createElement('canvas').getContext('experimental-webgl')`
6. returns null

What is the expected behavior?
returns WebGLRenderingContext

What went wrong?
returns null

Root Cause?
Chrome flags should include `--use-gl=any` and not include `--disable-gpu`

**Comment by garris** [comment]
^^^ Now THAT is a professional ticket!

**Comment by garris** [comment]
ok.  then how about this.  If someone overrides `engineFlags` it will be a true override -- not an extension.   Except for maybe the `--window-size=x,y` case.  In that case we can peek the array -- if found, we override.  If not, we go ahead and append?

How do we like that?

**Comment by josephmcasey** [comment]
I like that solution very much @garris

**Comment by garris** [comment]
Ok.  It is in the queue.   I would gladly merge a PR if anyone can get to it before me.

**Comment by josephmcasey** [comment]
Where do you post your priority queue?

**Comment by garris** [comment]
In a todo app on my laptop 😄     _this is a scrappy operation_

**Comment by josephmcasey** [comment]
Could you post it under the project/wiki tab in Github so others, like myself, can help address issues at the top of the priority queue?

**Comment by garris** [comment]
Sure -- that's a great idea.

**Comment by josephmcasey** [comment]
Thanks for doing that @garris!

**Comment by garris** [comment]
@josephmcasey I just implemented this for you.  Please update to @latest and validate if you get a chance.  Cheers.
