### ISSUE TITLE
"Converting circular structure to JSON" errors

### ISSUE THREAD

**Issue by AdrianRichardson** [garris/BackstopJS#538]
When passing config to backstop as an object instead of using a configuration file (integration option), you end up with circular references in configJSON in decorateConfigForCapture(), eg env: { args: { config: [Circular] }, ...

This then causes JSON.stringify to fail in writeReferenceCreateConfig()

Seems to have been introduced from 2.8.0

**Comment by garris** [comment]
Thanks for posting!  So sorry about the regression.  Would be great if someone can look into it.
