### ISSUE TITLE
Blank screen being captured if new port gets initiated before first set of 'asyncCaptureLimit' limit

### ISSUE THREAD

**Issue by kiran-redhat** [garris/BackstopJS#540]
I've '"asyncCaptureLimit": 8' 

Issue: Blank screenshot is being captured If a new port gets started after initial 8(`Starting Chromy: port:9230` from below log) before all initial 8 runs are completed.

In other words, there is no issue if all other 7 viewports runs soon after laptop but getting blank screen for laptop if a new port gets initiated in between (`Starting Chromy: port:9230` in below log)

'	Starting Chromy: port:9222 --disable-gpu,--force-device-scale-factor=1,--window-size=1366,4000,--proxy-server=127.0.0.1:4232
	onBefore.js is running for:  laptop
	onBefore.js is running for: Test  for viewport:  laptop
	Starting Chromy: port:9223 --disable-gpu,--force-device-scale-factor=1,--window-size=1920,4000,--proxy-server=127.0.0.1:4232
	onBefore.js is running for:  desktop
	onBefore.js is running for: Test  for viewport:  desktop
	Starting Chromy: port:9224 --disable-gpu,--force-device-scale-factor=1,--window-size=375,7000,--proxy-server=127.0.0.1:4232
	onBefore.js is running for:  iPhone6_v
	onBefore.js is running for: Test  for viewport:  iPhone6_v
	Starting Chromy: port:9225 --disable-gpu,--force-device-scale-factor=1,--window-size=320,7200,--proxy-server=127.0.0.1:4232
	onBefore.js is running for:  iPhone5S_v
	onBefore.js is running for: Test  for viewport:  iPhone5S_v
	Starting Chromy: port:9226 --disable-gpu,--force-device-scale-factor=1,--window-size=667,6000,--proxy-server=127.0.0.1:4232
	onBefore.js is running for:  iPhone6_l
	onBefore.js is running for: Test  for viewport:  iPhone6_l
	Starting Chromy: port:9227 --disable-gpu,--force-device-scale-factor=1,--window-size=360,7000,--proxy-server=127.0.0.1:4232
	onBefore.js is running for:  SamsungS7_v
	onBefore.js is running for: Test  for viewport:  SamsungS7_v
	Starting Chromy: port:9228 --disable-gpu,--force-device-scale-factor=1,--window-size=414,7000,--proxy-server=127.0.0.1:4232
	onBefore.js is running for:  iPhone6Plus_v
	onBefore.js is running for: Test  for viewport:  iPhone6Plus_v
	Starting Chromy: port:9229 --disable-gpu,--force-device-scale-factor=1,--window-size=768,3500,--proxy-server=127.0.0.1:4232
	onBefore.js is running for:  iPad_v
	onBefore.js is running for: Test  for viewport:  iPad_v
	**9222 LOG >  Testing viewport: laptop**
	**_Starting Chromy: port:9230 --disable-gpu,--force-device-scale-factor=1,--window-size=1024,3500,--proxy-server=127.0.0.1:4232_**
	onBefore.js is running for:  iPad_l
	onBefore.js is running for: Test  for viewport:  iPad_l
	9227 LOG >  Testing viewport: SamsungS7_v
	9226 LOG >  Testing viewport: iPhone6_l
	9223 LOG >  Testing viewport: desktop
	9228 LOG >  Testing viewport: iPhone6Plus_v
	9229 LOG >  Testing viewport: iPad_v
	9224 LOG >  Testing viewport: iPhone6_v
	9225 LOG >  Testing viewport: iPhone5S_v`

**Comment by garris** [comment]
I think this is going to come down to a RAM issue. Would be helpful to know how much RAM each chrome instance is using.   Please try setting your limit to something safe like 5 for a while and see if that consistently addresses your issue.  If it does I may set the default to 5.

**Comment by kiran-redhat** [comment]
Each instance of chrome port seems to be using around 920MB . As you mentioned this probably could be because of memory, so closing.

![image](https://user-images.githubusercontent.com/17115939/30088612-8ae29350-92fb-11e7-9914-12f47892c6e6.png)

**Comment by garris** [comment]
😮Wow!  Much heavier than I thought. Thank you for sharing this.  What is your hardware profile?

**Comment by kiran-redhat** [comment]
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 58
Model name:            Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
Stepping:              9
CPU MHz:               3192.826
BogoMIPS:              6388.72
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              6144K
NUMA node0 CPU(s):     0-3
