### ISSUE TITLE
Error: Cannot find module 'babel-runtime/helpers/typeof'

### ISSUE THREAD

**Issue by pgn-vole** [garris/BackstopJS#544]
I get an error when trying to run backstop js.

```
$ npm install backstopjs@3.0.25
+ backstopjs@3.0.25
added 225 packages in 48.671s

$ node_modules/.bin/backstop test
module.js:471
    throw err;
    ^

Error: Cannot find module 'babel-runtime/helpers/typeof'
```

I'm using the verison 2.6.13 and wants to upgrade.

**Comment by dotneet** [comment]
Hi @pgn-vole, what is your node version? that error is caused by old node.

**Comment by pgn-vole** [comment]
version 6.10.0

**Comment by dotneet** [comment]
I've tried to reproduce this problem with same node version but I couldn't.
`node_modules/babel-runtime/helpers/typeof.js` is installed correctly.
Is your OS Mac or Win?
What if clean and install node_modules?

**Comment by garris** [comment]
This happened to me last week.  I think I fixed it by uninstalling, cleaning cache and re-installing.

something like this...
```
npm uninstall -g backstopjs
npm cache clean
npm install -g backstopjs
```

Please let me know if that fixes your issue!

**Comment by pgn-vole** [comment]
@garris sorry with the late reply. Cleaning my cache solved the issue. Thanks !
Backstop3 is working really well! Thanks for your work.
