### ISSUE TITLE
viewport height works differently after update to v3.0

### ISSUE THREAD

**Issue by asci** [garris/BackstopJS#546]
Hello,

My snapshots got clipped by viewport height. Previously, the height of rendered picture was responsive — if my page higher than viewport height it will still render everything. Now it renders only the part under viewport dimensions. 

I tried to set the height to 0 — no luck. Any ideas? Don't see any documentation about this

**Comment by asci** [comment]
the only workaround is to set the height to a high number, but then I got big blank margin at the bottom.

**Comment by garris** [comment]
What version are you running?

**Comment by asci** [comment]
"version": "3.0.25"

**Comment by garris** [comment]
Chrome and Phantom options have different behaviors -- is that what you're referring to?

Maybe your issue is related to this?  https://github.com/garris/BackstopJS/issues/532

**Comment by kiran-redhat** [comment]
@asci, I found the simplest way to solve this if you are using chrome is to change selector to "document". Are you using chrome or Firefox?

**Comment by asci** [comment]
Actually, I didn't do any adjustments, I guess I used phantomjs

**Comment by garris** [comment]
Please post your config.

**Comment by asci** [comment]
I changed the selector to 'document' and it helps. Thanks @kiran-redhat
