### ISSUE TITLE
Doesn't work with phantomJS 2.0

### ISSUE THREAD

**Issue by onaliugo** [garris/BackstopJS#55]
Hello there,

I tried to run `gulp reference` with phantomJS 2.0 installed, and I got
```
CasperJS: CasperJS needs PhantomJS v1.x

CasperJS:   /usr/local/lib/node_modules/casperjs/bin/bootstrap.js:91 in __die

Testing script failed with code: 1

Looks like an error occured. You may want to try running `$ gulp echo`. This will echo the requested test URL output to the console. You can check this output to verify that the file requested is indeed being received in the expected format.
````
![capture d ecran 2015-04-28 a 17 54 23](https://cloud.githubusercontent.com/assets/5040476/7373931/beacb5fe-edcf-11e4-9084-3e76c026e36d.png)

Also i tried with phantomJS 1.9.7, and all worked fine
![capture d ecran 2015-04-28 a 17 48 18](https://cloud.githubusercontent.com/assets/5040476/7373966/dcea718c-edcf-11e4-90c4-9e10b8e1f25f.png)

Can you do something for this?
Thanks.

**Comment by garris** [comment]
Hi, please see this CasperJS ticket -- https://github.com/n1k0/casperjs/issues/1150

There *is* a fix but it's not immediately apparent if the fix is in the latest CasperJS release...

What CasperJS version are you running?

**Comment by onaliugo** [comment]
Hi, thanks for your answer.

Oups, my bad!

```
casperjs -v
CasperJS needs PhantomJS v1.x

  /usr/local/lib/node_modules/casperjs/bin/bootstrap.js:91 in __die
```

**Comment by garris** [comment]
No problem.  Cheers.   GS
