### ISSUE TITLE
Tag Docker image for each BackstopJS release

### ISSUE THREAD

**Issue by fusionfox** [garris/BackstopJS#562]
It would be great if we could lock down our dependancy to a particular release of BackstopJS using the docker container, but the only tag on there at the moment is 'latest'

https://hub.docker.com/r/backstopjs/backstopjs/

**Comment by TimPerry** [comment]
+1

**Comment by rupamsaha** [comment]
+1

**Comment by garris** [comment]
What do you recommend?  Let’s do it.   Also,  that container is new,  I don’t remember what version of chrome it’s using — but we should set it to >=v62 to be compatible with the flags we’re using.

**Comment by garris** [comment]
FWIW: I don’t have much experience with containers— Would be super helpful if someone wants to take the lead to manage this.

**Comment by fusionfox** [comment]
I think the Docker container should have the same semver as the version of BackstopJS it's using. Do you ever rebuild the container for the same version of Backstop?

**Comment by garris** [comment]
Sounds like a sensible idea.    

I'm sorry but I am not sure I understand the question -- but I'll try to explain.  The container rebuild is triggered on every github push -- regardless of package version.   I only bump the package version value before releasing a new NPM build.   Hope that helps.

**Comment by garris** [comment]
Closed by https://github.com/garris/BackstopJS/pull/668
