### ISSUE TITLE
Typo in 'Command executed' message

### ISSUE THREAD

**Issue by mhavelant** [garris/BackstopJS#567]
When I run a reference command, there's a typo:
> COMMAND | Command `reference` sucessfully executed in

This should be

> COMMAND | Command `reference` successfully executed in

(sucessfully => successfully)

BackstopJS v3.0.29

**Comment by daveross** [comment]
Fixed in #573 , commit ffb8ee9a8e2d82978586ba175e41d273f9f7c222

This can probably be closed.

**Comment by garris** [comment]
Thanks for reviewing!
