### ISSUE TITLE
Lazyload and font icons

### ISSUE THREAD

**Issue by MaikelGG** [garris/BackstopJS#57]
It seems like backstopJS cannot process font-icons? I am also struggling with images that are lazy loaded. They are not shown at all (https://github.com/aFarkas/lazysizes).

This is the page I am testing (local): http://ggw-prototype.goalgorilla.com/components/teasers.html (WIP)

Does anyone have a clue how to solve this? I want to keep the markup as close to the production code as possible, for obvious reasons.

The snapshot looks like this (missing the preview and the icons are not displayed properly) 
![0_0_node-teaser-news_2_tablet](https://cloud.githubusercontent.com/assets/5907886/7608445/efceb79a-f969-11e4-8833-b3c8e2105f6d.png)

**Comment by garris** [comment]
Hi @MaikelGG, If it is simply a timing issue where the images have not loaded yet you can use the `delay` property.  This is the simplest way to provide extra time for your images to load.   There is also a `readyEvent` you could use to be absolutely sure images are loaded.   There is an article here which goes into some detail on usage ... http://davidwalsh.name/visual-regression-testing-angular-applications 

Please let me know if that solves your issue.  cheers.  GS

**Comment by MaikelGG** [comment]
Hi @garris, thanks for your reply. I have already implemented the delay and readyEvent. The ready event is set to the moment the last JS function has executed on document.ready. However I think the problem might be caused by the fact the the image source is replaced with the srcset attribute, depending on the fact if the image is in the viewport. I think the test cannot determine the image is actually in the viewport? 

The problem of the font icons is something different I think, have you already seen a project where font-icons are included in the test?

**Comment by garris** [comment]
Oh right, sorry, I forgot to address the font icon issue.  That is probably an issue with PhantomJS (which BackstopJS is built on).  PhantomJS has had a well known web-font rendering issue forever. Installing that font on your local machine's OS will solve the issue.  I know that's not ideal, but that is just a limitation at the moment.  There is a new version of phantomjs which I think resolves the issue but it's not compatible with some other dependencies at the moment.   Perhaps everything will fix it's self in the next half year or so.   Till then, try installing the font locally and let me know if that fixes it.

The loading issue may be another thing.  You said you're calling `readyEvent` when your document.ready has returned -- but this is not actually when your images have loaded (it is likely before your images have had a chance to load).  If you want to be sure your images have loaded you need to listen to the load events on your image DOM.

**Comment by garris** [comment]
BackstopJS now supports SlimerJS so webfonts can be more reliably rendered.

**Comment by seanBlommaert** [comment]
Just posting this for anyone who gets here looking for a solution related to lazy loading content or images.

When you use the following code in your custom onReady script, the page will scroll down 100px every 100ms until the bottom is reached. This solved the lazy loading issues for us (got the code from https://stackoverflow.com/questions/51529332/puppeteer-scroll-down-until-you-cant-anymore):

It slows everything down quite significantly, but you can play around with the scroll distance and timer to improve that.

```
  await page.evaluate(async () => {
    await new Promise((resolve, reject) => {
      var totalHeight = 0;
      var distance = 200;
      var timer = setInterval(() => {
        var scrollHeight = document.body.scrollHeight;
        window.scrollBy(0, distance);
        totalHeight += distance;

        if(totalHeight >= scrollHeight){
          clearInterval(timer);
          resolve();
        }
      }, 100);
    });
  });
  await page.waitFor(1000);
```

**Comment by tpraxl** [comment]
In case anyone uses native lazy loading (as in `<img … loading="lazy">`). If you would rather load the images eagerly, instead of investing the time to trigger the load by scrolling, just modify the loading attribute in your `onReady` script:

```js
  page.evaluate(async () => {
    document.querySelectorAll('[loading="lazy"]').forEach((elem) => {
      elem.loading = 'eager';
    });
  });
```

**Comment by fastfedora** [comment]
The solution from @tpraxl worked for me, except that I also had to change the `decoding` from `async` to `sync` for images in my `onReady` script:

```  
   // Ensure all images loaded before doing the screenshot
  page.evaluate(async () => {
    document.querySelectorAll('[loading="lazy"]').forEach((element) => {
      element.loading = 'eager';
    });

    document.querySelectorAll('[decoding="async"]').forEach((element) => {
      element.decoding = 'sync';
    });
  });

  await require('./clickAndHoverHelper')(page, scenario);
```

**Comment by yahilmadakiya** [comment]
@tpraxl @fastfedora I tried to remove the `loading` attribute from image but it says document is not available. and based on google search for that
> [document](https://developer.mozilla.org/en/docs/Web/API/Document) relates to the DOM (Document Object Model) in a web browser.
Node.js, however, is not a browser environment. It is a server environment, much like PHP or Perl, and as such, you can’t access the browser’s DOM or do anything specific to browser-hosted JavaScript.

May I know how it's working for you?
