### ISSUE TITLE
Integrating backstop scenarios with react-styleguidist's use cases

### ISSUE THREAD

**Issue by chaffneue** [garris/BackstopJS#587]
So I'm seeing some great value in using [react-styleguidist](https://github.com/styleguidist/react-styleguidist) to generate live component examples and I'm using backstopjs to pin out the functionality of each component by providing an automated gui test for all of our documented scenarios. So far I've gotten a lot of mileage just using expandSelectors, but right now each test case is just automatically named "__n1" and the scenario settings only apply to the first match.

What I'd like is to define a scenario for each of the headings in styleguidist like this: 

![backstop-targeting-selectors-by-index](https://user-images.githubusercontent.com/399764/32351046-63ad14d0-bfd9-11e7-86b2-a5fbaaf67c3f.jpg)

That would mean allowing things like hover states and delays and other great scenario use cases per type of button as well as a meaningful label when tracking regressions. I was thinking maybe an index for document.querySelectorAll(...)[$index] would do the trick. Any ideas?

**Comment by garris** [comment]
Hi there @chaffneue.   Please bear with me — I’m not totally sure I understand the question — but is this what you need to do...

```
...
selectors: ’li.iteratedContainer:nth-of-type(<index>) div[data-preview=Button]’,
selectorExansion: false,
...
```

**Comment by VladimirPittner** [comment]
As @garris said, you can use js-based config where you can write some function to generate scenario and parse your styleguide.

Just an idea explanation example for generating scenario could be something like this:
```
let scenarios = [];

arrayOfElements.forEach((element, index) => {
    scenarios.push(makeScenario(element, index));
});

let config = {
...
    scenarios: scenarios,
...
};

module.exports = config;
```

Where `arroyOfElements` is scraped data in array from you styleguide and `makeScenario` is function to generate scenario - could be something like this:
```
function makeScenario(element, index){
    return {
        label: `${element.label}-${index}`,
        ...
        selectors, and other config for scenarios
        ...
    }
})
```

Its pretty much up to you then how much of the scenario config you with to have generated dynamically and how much you want hard-coded. I personally have default settings which then for each scenario I can overwrite with options.

I hope you get the idea behind the concept.

**Comment by chaffneue** [comment]
Thanks for your replies - I'll schedule some time to try this out and get back to you. Previously when I tried:

`
selectors: ['div[data-preview=Button]:nth-of-type($index)'],
selectorExansion: false
`

I got 'not found' for any index over 1. I think iterating on the container may be the part I was missing.

**Comment by chaffneue** [comment]
So even iterating the parent container, I still get "not found" for the second case. Maybe CSS selectors can't be used in this way? event when I run it in the browser I get "null"
 
![backstop-targeting-by-css](https://user-images.githubusercontent.com/399764/32400506-4aa07672-c0be-11e7-8225-dd3cf157e55d.jpg)

'
> document.querySelector('article[class^=root]:nth-of-type(2) div[data-preview=Button]')
null
'

**Comment by kiran-redhat** [comment]
Backstop chromy can't find it If selectors not locatable in chrome console.

Can you try finding correct locator for this and try again?

**Comment by VladimirPittner** [comment]
Hmmm I am not sure if this could be the issue but did you try to use "" for the strings? like this ->
```document.querySelector('article[class^="root"]:nth-of-type(2) div[data-preview="Button"]')```
... maybe try also querySelectorAll (could be issue, I don't know). But as Kiran said, make sure first that the selector exists :).

**Comment by chaffneue** [comment]
The selector definitely exists - I think this is just a limitation of querySelector:

using the demo styleguide here if that helps zero in on what I might be missing - https://react-styleguidist.js.org/examples/basic/#!/Button


```
document.querySelector('article[class^="rsg--root"]:nth-of-type(1) div[data-preview="Button"]')
<div class=​"rsg--preview-59" data-preview=​"Button">​…​</div>​

document.querySelector('article[class^="rsg--root"]:nth-of-type(2) div[data-preview="Button"]')
null

document.querySelectorAll('article[class^="rsg--root"] div[data-preview="Button"]')
(6) [div.rsg--preview-59, div.rsg--preview-59, div.rsg--preview-59, div.rsg--preview-59.checks, div.rsg--preview-59, div.rsg--preview-59]
```

So I think we're back to square one - how do I get access to this nodelist from expanded selectors?

**Comment by bluetidepro** [comment]
@chaffneue I'm trying to actually integrate backstop with my styleguidist project, as well. Would you mind sharing your backstop configs and such in full, by any chance? I'm having a little trouble with it, and it seems like you got it all sorted out!

**Comment by bluetidepro** [comment]
@chaffneue Ahh okay. So you have to manually input all the components in the `scenarios` array? There isn't a way for it to detect all the components from Styleguidist itself?

**Comment by garris** [comment]
@chaffneue  you can check the backstop docs for integrating backstop into other apps.  If you can extract styleguidest data then you should be able to map component data into a scenario template and directly pass this into backstop.
