### ISSUE TITLE
How wait after clickSelector?

### ISSUE THREAD

**Issue by iKick** [garris/BackstopJS#588]
Hi all. I can't find how wait after click, because page won't load. Also i have problem with popup.

This is example of backstop.json:
[backstop.json.txt](https://github.com/garris/BackstopJS/files/1446314/backstop.json.txt)

> {
  "id": "test",
  "viewports": [
    {
      "label": "desktop",
      "width": 1366,
      "height": 768
    }
  ],
  "onBeforeScript": "chromy/onBefore.js",
  "onReadyScript": "chromy/onReady.js",
  "scenarios": [
    {
      "label": "test 2",
      "cookiePath": "backstop_data/engine_scripts/cookies.json",
      "url": "https://google.com",
      "referenceUrl": "",
      "readyEvent": "",
      "readySelector": "",
      "delay": 3000,
      "hideSelectors": [],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "input[name='btnI']",
      "postInteractionWait": "",
      "selectors": [],
      "selectorExpansion": true,
      "misMatchThreshold" : 0.0,
      "requireSameDimensions": true
    }
  ],
  "paths": {
    "bitmaps_reference": "backstop_data/bitmaps_reference",
    "bitmaps_test": "backstop_data/bitmaps_test",
    "engine_scripts": "backstop_data/engine_scripts",
    "html_report": "backstop_data/html_report",
    "ci_report": "backstop_data/ci_report"
  },
  "report": [""],
  "engine": "chrome",
  "engineFlags": [],
  "asyncCaptureLimit": 1,
  "asyncCompareLimit": 50,
  "debug": false,
  "debugWindow": false
}

Thank for help

**Comment by VladimirPittner** [comment]
Hi, 
what do you mean by page won't load? It won't load before click or after click? And what kind of popup you mean?
Try run in `debugWindow: true` mode, so you can observe what exactly is happening in the browser.

**Comment by iKick** [comment]
Hi,
I'm sorry, I did not correctly explain. 
I mean, when I make a clickSelector, pop-up opens. Locally my computer sees pop-up, but on the server it is missing. So I want a delay after a clickSelector.

**Comment by VladimirPittner** [comment]
In that case if I am not wrong it is the `postInteractionWait` parameter you want to use to setup wait time.

**Comment by iKick** [comment]
Oh ... I figured out what the problem was. After when backstop.json is created, variable `"postInteractionWait": ""`. When I try to change the value, I entered it like string. And it is don't work.

in file clickAndHoverHelper.js i find this `var postInteractionWait = scenario.postInteractionWait; // selector [str] | ms [int]`. I change in [int] and now it work, thnks. 
I apologize for the distraction.

PS: "Maybe change descriptons **Advanced Scenarios** in https://github.com/garris/BackstopJS, and  write there variable can have two values "

**Comment by garris** [comment]
Glad you found the issue.  Thanks for following up!

**Comment by Bronovitskiy** [comment]
does not work clickSelectors please help

**Comment by panpan31415** [comment]
it doesn't work.... 
I have tried to use page.waitFor(3000) in onReadyScript , it still doesn't work

**Comment by panpan31415** [comment]
finally it worked. the way how I did it is to use onReadyScript , add await in front of  page.evaluate call , and add await in front of page.waitFor(miliseconds).
