### ISSUE TITLE
Intermittent Failures

### ISSUE THREAD

**Issue by joseph-stano** [garris/BackstopJS#589]
Hey all,
We're hitting intermittent bumps in our chromy-based backstop suite.

On a semi-regular basis we get false failures of this:
`compare | Chromy error: Error. See scenario – xxx xxx xxx xxx`

Accompanied by a report that looks like this:
![screen shot 2017-11-07 at 2 39 41 pm](https://user-images.githubusercontent.com/6355829/32516645-a6ee3a50-c3c9-11e7-8a3c-1761fac706f7.png)

We've played with asyncCapture/compare limit, played with `delay`, but no dice. Sometimes it can be resolved by `pkill Chrome`, but generally we're struggling to find the special sauce to solve them for good.

First question - have you encountered these intermittent failures?
Second question - Is there a chromy/backstop flag we can set to investigate the error or capture some more context around this `Chromy error`?

**Comment by kiran-redhat** [comment]
+1.
I've see this issue intermittently, tried running on windows (in addition to amazon linux AMI) still I could see above issue. As you mentioned, I think chromy may not be able to close connections. @joseph-stano did you see this issue happening when asyncCaptureLimit is set to 1 ? (I am going to try this now)

In addition to above issue, I see following issue happening (which looks similar but mentioning): Note: Reference has a expected image (which is not here in this screenshot):
![image](https://user-images.githubusercontent.com/17115939/32519455-b1a1e8e0-c471-11e7-928f-dfdc8a655652.png)

**Comment by garris** [comment]
Did either of you attempt to consistently run `pkill -f "(chrome)?(--headless)"`  before running your tests?  Does that make a difference?

**Comment by kiran-redhat** [comment]
@garris , thanks for quick response. These tests are running in AWS code build, also I've tried in bamboo agent - every time test runs there shouldn't be any hanging processes as systems freshly gets created every time. 

Would you like me to try killing and see ?

**Comment by garris** [comment]
@kiran-redhat oh.  yeah.  good point.   Hmmm.   Intermittent?   


And BTW:  That diff is what happens when images of different sizes are compared.   In this case I think it's comparing against no image (in which case I think the default for that case is a 1x1 png.)

**Comment by garris** [comment]
Some things I have seen cause intermittent errors...
- cookies
- zombie chrome-headless instances
- server returns error
- some other app using chromy ports

**Comment by garris** [comment]
@joseph-stano 
Here is where we handle chromy errors...
https://github.com/garris/BackstopJS/blob/master/core/util/runChromy.js#L319

Maybe you can `console.log('e>>', e)`  right there -- or earlier in the chain to see what might be going on?

**Comment by kiran-redhat** [comment]
My observations:

cookies  - In my case, we can eliminate, as am not using cookies
zombie chrome-headless instances - I see same issue on Amazon Linux AMI, Mac & Windows 10, so not sure if this might be a issue
server returns error  -  Not sure about this, 3-4 times out of 10 times these tests fails and they are not same tests.
some other app using chromy ports - Got the issue on bamboo so other no chance for other apps to use.

**Comment by kiran-redhat** [comment]
I ran my tests with asyncCaptureLimit as 1 and I see no problem. do you see any issues with  asyncCaptureLimit as 1 @joseph-stano ?

**Comment by joseph-stano** [comment]
Thanks @garris and @kiran-redhat.

I've been pounding on our test suite this morning and seemed to slim down our issues with @garris `pkill -f "(chrome)?(--headless)"` before each backstop instantiation, but even still I saw occasional failures.

@kiran-redhat - I'll try `"asyncCaptureLimit": 1` and let that bake for a bit.  When refactoring our backstop suite awhile back to leverage async more effectively, I thought I had seen some correlation between the asyncCaptureLimit and intermittent failures. But now I can't seem to reliably reproduce the issue regardless of the limit.

**Comment by garris** [comment]
Thanks guys for working on this!  Something else just came to mind — multiple concurrent instances of backstop running chromy won’t work because of likely chrome-headless port collisions.    Just wanted to rule out that multiple async `backstop test` calls.

**Comment by VladimirPittner** [comment]
Oh so I tought it is just some problem in my over-complicated code but now I see we all face this ... hmm.
From my observations its not cookies, I do kill all before, I do run asyncCaptureLimit: 1, and I even run chrome in incognito mode and still get the issue mentioned in the first post. Its absolutely random, I watched it happen several times with debugWindow turned on and I could not find why it happens :(. Sometimes Chromy wouldnt even open the url, somtimes it would miss the load event and get stuck on waitLoadEvent ... It seems like sometime the chain broke and things start to run async.

**Comment by garris** [comment]
@VladimirPittner Just to be clear -- I don't have this issue -- asyncCaptureLimit is a control provided for performance -- it will not really be effective for compatibility.  Backstop using chrome is very stable for me other than the known instances above.   I think the issue you have is related to environment.  Once you find the issue you will probably get consistent behavior.   

I am suspecting there may be a port issue.  Chromy instances start using port 9222 and increment for each scenario.  so if you have 50 tests and 2 viewports you will need ports 9222-9322 to be available.  This is not a problem in my workgroup -- but may be an issue for you?

Just an idea.  good luck!

**Comment by VladimirPittner** [comment]
@garris yes I know that those 30 minutes are caused by slow server response in my case (that is why I had to change waitTimeout time :D) and thats why I prefer to run async 3 which fits my 3 viewports ... 
Anyway If I run async 1 and just few tests it works, however if I run more tests it seems to get troubles ... maybe it really is some issue with ports hmm or really some leak in my code ... will see ... and also will see if guys keep having issues if they run async 1

**Comment by garris** [comment]
Hmmm  —  I think the default waitTimeout is 30 secs?  Are you saying you need more time than that to get a successful app load?

**Comment by VladimirPittner** [comment]
@garris yeah unfortunately it sometimes takes longer than 30secs to get respond from test server when executing some things and navigating through app ... and I cannot do anything about it, so you can imagine the pain ;)

**Comment by kiran-redhat** [comment]
@VladimirPittner Following are my scenarios:

I ran **Project 2 & 3** for 13 times with asyncCaptureLimit 1 all good all pass - no issues
I ran **Project 1** for 2 times with asysnCaptureLimit 1 - I see above issue (Blank screen displayed)

**Project 1:** 3 viewports - total of 70 tests (using 'viewport and 'document as selectors) - This at fist takes reference in one environment then compares with tests on other environment. I ran `pkill -f "(chrome)?(--headless)"` before running `backstop reference` and `backstop test`
**Project 2:** 3 viewports - total of  117 tests (using specific selectors/components of page). This as pre-defined reference images so it just runs `backstop test`
**Project 3:** 9 viewports - total of  126 tests (Using 'viewport' and 'document' as selectors). This as pre-defined reference images so it just runs `backstop test`

**Comment by VladimirPittner** [comment]
@kiran-redhat and those with blank screen have the same error message as described in first post? Is your chromy code correct?

In previous version of backstop it used to happen to me that a variable passed through evauluate would sometimes cause error that it is undefined, however I thought that was fixed already.

Code like this would give me error from time to time:
```
chromy
        .evaluate(`_url = ${url}`)
        .evaluate(() => {
            let result = document.baseURI.match(_url) !== null;
            return result;
        })
```
As if second evaluate would run before the first, which shouldn't be possible

**Comment by ackmanx** [comment]
@garris Regarding @joseph-stano OP, I modified backstop source in `node_modules` like you mentioned and received the following error for every one of our tests that result in the white diff for all 3 images as in the OP screenshot.

    { Error: An error has occurred evaluating the script in the browser.TypeError: Cannot read property 'focus' of null
        at <anonymous>:2:102
        at <anonymous>:2:112
        at EvaluateError.ExtendableBuiltin (/Users/*****/code/*****/node_modules/backstopjs/node_modules/chromy/dist/error.js:19:28)
        at new EvaluateError (/Users/*****/code/*****/node_modules/backstopjs/node_modules/chromy/dist/error.js:133:131)
        at Chromy._evaluateWithReplaces$ (/Users/*****/code/*****/node_modules/backstopjs/node_modules/chromy/dist/document.js:448:21)
        at tryCatch (/Users/*****/code/*****/node_modules/backstopjs/node_modules/regenerator-runtime/runtime.js:65:40)
        at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/*****/code/*****/node_modules/backstopjs/node_modules/regenerator-runtime/runtime.js:299:22)
        at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/*****/code/*****/node_modules/backstopjs/node_modules/regenerator-runtime/runtime.js:117:21)
        at tryCatch (/Users/*****/code/*****/node_modules/backstopjs/node_modules/regenerator-runtime/runtime.js:65:40)
        at invoke (/Users/*****/code/*****/node_modules/backstopjs/node_modules/regenerator-runtime/runtime.js:155:20)
        at /Users/*****/code/*****/node_modules/backstopjs/node_modules/regenerator-runtime/runtime.js:165:13
      object:
       { type: 'object',
         subtype: 'error',
         className: 'TypeError',
         description: 'TypeError: Cannot read property \'focus\' of null\n    at <anonymous>:2:102\n    at <anonymous>:2:112',
         objectId: '{"injectedScriptId":2,"id":1}'
       } 
    }

Do you have any tips on how we can learn more about what file `anonymous` is, or perhaps what `injectedScriptId` is pointing to? I've removed all instances of `focus` from our code base and still receive the errors consistently.

Also, I set `asyncCaptureLimit` to 1. Instead of getting a third of the tests erroring, I only got one that errored. It errored with the same error message directly above.

**Comment by VladimirPittner** [comment]
In my case I get this:
```
e>> { Error: An error has occurred evaluating the script in the browser.ReferenceError: _scenarioResult is not defined
    at result (<anonymous>:4:13)
    at <anonymous>:6:11
    at EvaluateError.ExtendableBuiltin (C:\CBS\checkouts\cbs-inet-theme\branches\releases\1.6\cbs-inet-theme-ebank-mba\tests\ui-tests\node_modules\backstopjs\node_modules\chromy\dist\error.js:19:28)
    at new EvaluateError (C:\CBS\checkouts\cbs-inet-theme\branches\releases\1.6\cbs-inet-theme-ebank-mba\tests\ui-tests\node_modules\backstopjs\node_modules\chromy\dist\error.js:133:131)
    at Chromy._evaluateWithReplaces$ (C:\CBS\checkouts\cbs-inet-theme\branches\releases\1.6\cbs-inet-theme-ebank-mba\tests\ui-tests\node_modules\backstopjs\node_modules\chromy\dist\document.js:448:21)
    at tryCatch (C:\CBS\checkouts\cbs-inet-theme\branches\releases\1.6\cbs-inet-theme-ebank-mba\tests\ui-tests\node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:65:40)
    at Generator.invoke [as _invoke] (C:\CBS\checkouts\cbs-inet-theme\branches\releases\1.6\cbs-inet-theme-ebank-mba\tests\ui-tests\node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:299:22)
    at Generator.prototype.(anonymous function) [as next] (C:\CBS\checkouts\cbs-inet-theme\branches\releases\1.6\cbs-inet-theme-ebank-mba\tests\ui-tests\node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:117:21)
    at tryCatch (C:\CBS\checkouts\cbs-inet-theme\branches\releases\1.6\cbs-inet-theme-ebank-mba\tests\ui-tests\node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:65:40)
    at invoke (C:\CBS\checkouts\cbs-inet-theme\branches\releases\1.6\cbs-inet-theme-ebank-mba\tests\ui-tests\node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:155:20)
    at C:\CBS\checkouts\cbs-inet-theme\branches\releases\1.6\cbs-inet-theme-ebank-mba\tests\ui-tests\node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:165:13
  object:
   { type: 'object',
     subtype: 'error',
     className: 'ReferenceError',
     description: 'ReferenceError: _scenarioResult is not defined\n    at result (<anonymous>:4:13)\n    at <anonymous>:6:11',
     objectId: '{"injectedScriptId":6,"id":1}' } }
```

Where basically something like this is exectuted:
```
.chromy
        .click('some-selector', true)
        .evaluate(`_scenarioResult = ${scenartioResult}`)
        .evaluate(() => {
            // ... some code ...
            _scenarioResult = _scenarioResult ? result : false;
            return result;
        })
```

The `_scenarioResult ` is just variable I am passing during tests in chrome.
As I mentioned in previous post I use to get this error also with `_url` variable.

I am thinking maybe the click event does not successfully wait for the load event, then the evaluate is triggered before the browser reloads, and after reload the variables are lost and that creates error undefined. But why is the evaluate executed before click is finished I have no idea.

Is there any way to get return from evaluate be returned out of chromy?
Something like this:
```
let result = chromy.evaluate(() => { 
    // some code
    return result;
});
```

**Comment by kiran-redhat** [comment]
@VladimirPittner , try using this and see if it helps?

`.chromy
        .click('some-selector', true)
        .evaluate(`_scenarioResult = ${scenartioResult}`)
        .evaluate(() => {
            // ... some code ...
            `${_scenarioResult}` = `${_scenarioResult}` ? result : false;
            return result;
        })`

**Comment by nzufall** [comment]
@garris I am seeing the same thing as the OP. When I run my tests with 10 `asyncCaptureLimit` I am encountering `(node:27500) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit`

Is this a hint as to the root cause perhaps?

**Comment by nzufall** [comment]
Ours seems to have been user error in scenario configuration. Some user was passing: 
```JSON      
"hideSelectors": [
        ""
],
```

**Comment by kiran-redhat** [comment]
**I think this was the issue:**
Since the error is being resolved by BackstopJS (https://github.com/garris/BackstopJS/blob/master/core/util/runChromy.js#L319), tests are continuing even though there are some errors in onReady scripts where are before they were failing abruptly before. Because of which I think it is having blank screen.

**Solution:**
In onBefore or onReady scripts: 
1. see if there are any selectors that are not present in DOM are being waited for(using chromey.wait or postInteractionWait) 
2. see if there are any functions that can't be resolved (This way you can be sure if they are being correctly resolved: `module.exports = function (chromy, scenario, vp) {
  let path = require('path');
  let absolutePath = path.resolve(path.basename(__filename));
  console.log(`'${absolutePath}' is running for: '${scenario.label}' on viewport:  '${vp.label}'`);

  return chromy
    .evaluate(`_absolutePath = '${absolutePath}', _scenario = '${scenario.label}', _vpLabel = '${vp.label}'`)
    .evaluate(function () {
      console.log(`'${_absolutePath}' successful for : '${_scenario}' on viewport: '${_vpLabel}'`);
    });
};`
`)

You can figure out 1 & 2 by changing https://github.com/garris/BackstopJS/blob/master/core/util/runChromy.js#L319 to `  .catch(e => console.log(e));`

**Still open question:**
Not sure why this issue not happening when asyncCaptureLimit to 1.

**Comment by garris** [comment]
@kiran-redhat -- thank you for tracking this down!   I completely agree with your idea.  We should add a log.error at line 319 which also includes the scenario label+viewport.  This would make debugging MUCH easier for engineers!

**Comment by kiran-redhat** [comment]
@VladimirPittner , please see if point 2 above can help you.

 @joseph-stano please try point 1 above with following change which should tell you what exactly the problem is: https://github.com/garris/BackstopJS/blob/master/core/util/runChromy.js#L319 to .catch(e => console.log(e));

**Comment by ackmanx** [comment]
@kiran-redhat The error @joseph-stano and I are getting is in my post above. It unfortunately does not tell us much, other than somewhere some unknown file is hitting an undefined.

**Comment by kiran-redhat** [comment]
@ackmanx & @joseph-stano, do you guys use onReady.js (either global or local)? if you use paste below code into it (if not, please create one global onReady.js and paste below code) this will tell you exactly which scenario with which viewport having issue. Once you have onReady.js, please use `"onReadyScript": "onReady.js"` in your backstop config file.


`module.exports = function (chromy, scenario, vp) { let path = require('path'); let absolutePath = path.resolve(path.basename(__filename)); console.log('${absolutePath}' is running for: '${scenario.label}' on viewport: '${vp.label}'`);
return chromy
.evaluate(_absolutePath = '${absolutePath}', _scenario = '${scenario.label}', _vpLabel = '${vp.label}')
.evaluate(function () {
console.log('${_absolutePath}' successful for : '${_scenario}' on viewport: '${_vpLabel}');
});
};`

**Comment by kiran-redhat** [comment]
Hey guys, I got to the bottom of finding where exactly the problem is, do these 3 steps which will tell you where the problem is:

Step 1 should tell you which scenario has the problem, step 2 will print BackstopJS error and step 3 will tell you exactly which selector not present in DOM.

**Step 1.** Add a onReady.js for your test and place this code in it `let path = require('path');
  require('../../../../helpers/clickAndHoverHelper')(chromy, scenario);
  let absolutePath = path.resolve(path.basename(__filename));
  console.log(`'${absolutePath}' is running for: '${scenario.label}' on viewport:  '${vp.label}'`);`
**Step 2:**  Replace line 294 with  `.catch(e => console.log('e: '));` in file node_modules\backstopjs\core\util\runChromy.js line 294 in 
**Step 3:**  Add `console.log(`Selector '${selector} not present in DOM'`);` in Line 702 in `node_modules\chromy\dist\document.js`

**Comment by VladimirPittner** [comment]
Hi @kiran-redhat as for the suggested:
```
.evaluate(() => {
    // ... some code ...
    ${_scenarioResult} = ${_scenarioResult} ? result : false; 
    return result; 
})
```

Is not valid code ;)
I will look at other suggestions later

**Comment by kiran-redhat** [comment]
Hey @VladimirPittner , not sure why it isn't working for you (this is working perfectly fine for me).

How are you getting `_scenarioResult` into chromy ?

**Comment by ackmanx** [comment]
@kiran-redhat Thanks for the tips. It would be helpful if you could utilize multi-line code blocks when posting code in here, because the github formatting and markdown interpretation of your code makes your code samples syntactically invalid.

**Comment by kiran-redhat** [comment]
@ackmanx thanks for that,  will change. 

Hey what you pointed exactly right,  getting that black screen eventhough all set up is correct when asyncCaptureLimit is > 1 where all good if asyncCaptureLimit is 1.

**Comment by joseph-stano** [comment]
Good find, @ackmanx. To summarize, we're thinking our DOM changes slow down in an async runtime, and chromy is attempting to interact with an element before it's available.

We will try leveraging chromy's `wait(<selector>)` on all of our DOM interactions (mostly just `click()` and `type()`).

We'll update this thread with our findings.

**Comment by VladimirPittner** [comment]
Latest update from my experiments:
* I have removed all `.waitLoadEvent` functions and now use `.wait(selector)` instead (it gives less flexibility unfortunately, but its much more stable and reliable)
* I make sure in code that every time I am passing some variable with `.evaluate()` page is fully loaded and ready (so I do not get variable removed by browser reload)

Result is for now that I am able to run even `asyncCaptureLimit: 3` without problem so far
I will test later on other machines and will give update.

Thanks all for the ideas, inspirations and help.

**Comment by joseph-stano** [comment]
Alright, good news guys. That seemed to be our issue. We added `wait(<selector>)` to all of our DOM interactions and we've run our suite 15+ times with `"asyncCaptureLimit": 20`. All clear!

Here are the guts of our solution if you're interested.

We have a helper script in which we introduced two functions for `click()` and `type()`:
```
let chromy
exports.init = (chromyReference) => {
    chromy = chromyReference
    return this
}
exports.click = (selector) => {
    chromy.wait(selector).click(selector)
    return this
}
exports.type = (selector, text) => {
    chromy.wait(selector).type(selector, text)
    return this
}
```

And then in our `onReadyScript`:
```
const interactions = require('../interactions.js')
module.exports = function (chromy, scenario, vp) {
	interactions
		.init(chromy, vp)
		.click('.some-selector')
		.type('.another-selector', 'text to type')
}
```

A few chromy/backstop tweaks helped us debug this work:
  - **backstop**: _index.js:65_  - log uncaught errors (this is generally helpful to catch errors in `onReadyScript` too)
  - **chromy**: _document.js_ - in `reject(new WaitTimeoutError('...'))` - we added the selector on which we were waiting. In a few of our scenarios we discovered we had bogus selectors that were never working in the first place, so our test was timing out.

Hope this helps others with the same issue!

**Comment by Kenith** [comment]
Hello @VladimirPittner & @joseph-stano:

Need to bother you a question.
Sometimes chromy fails to capture the screenshot, because the selector in `chromy.wait(selector)` is not in the web page, and then chromy will wait until timeout occurs. For this case, unlike phantomjs, the chromy won't capture the screen.

Therefore, my question is: Is there any solution to capture the sreen even the timeout or the selector not there? 

I tried the following code in **chromy/onReady.js**, seems wrong.
```
chromy.wait("selector");
chromy.then(() => {console.log("Timeout occurs waiting the locator")});
```

Thank you,
Ken

**Comment by joseph-stano** [comment]
@Kenith - Sorry for the delay. I'm not quite sure, but I wonder if you could do something like this:
```
try {
    chromy.wait("selector")
} catch (e) {
    if (e instanceof WaitTimeoutError) {
        console.log('all good')
    } else {
        throw e
    }
}
```
Only problem is that test may take awhile as it reaches the timeout (20sec I think). You may want to play with those timeouts if this is a common use case.
