### ISSUE TITLE
Slider in HTML Report?

### ISSUE THREAD

**Issue by tbal** [garris/BackstopJS#590]
This article https://blog.docksal.io/visual-regression-testing-with-backstopjs-in-a-docker-container-dfd1b9ae8582 mentions a slider do compare screenshots and also shows a gif of this feature:
![](https://media.giphy.com/media/l378gCQ8Uespd6Eg0/giphy.gif)

How can I activate this feature? Do I miss something? I'm using v3.0.26.

**Comment by garris** [comment]
From the HTML report — click on either the test or reference image.  Does that work for you?

**Comment by tbal** [comment]
@garris That works! I remember that i clicked several times on the diff image, but never thought about clicking on the others.. :see_no_evil:
Maybe that could be visually improved with a "cursor: pointer" css property on both images, so that one knows they are clickable.
I love this feature, thanks for all the work!

**Comment by garris** [comment]
Great idea — thanks.   Glad it’s working for you.  Cheers.
