### ISSUE TITLE
404 - Request is serviced by NPM metadata service, remote access not needed from DefaultNpmProxyRepository(id=npmjs)

### ISSUE THREAD

**Issue by devm87** [garris/BackstopJS#595]
Hi all, when running the backstop JS command I am facing a 404 error (Request is serviced by NPM metadata service, remote access not needed from DefaultNpmProxyRepository(id=npmjs).
Any ideas what could be going wrong here? 
Many thanks,

D:\AEM_BACKSTOPJS_SMOKE_TESTS>npm install -g backstopjs
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @types/mkdirp@^0.3.29 (node_modules\backstopjs\node_modules\chrome-launcher\node_modules\@types\mkdirp):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unexpected token < in JSON at position 0
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: <html>
npm WARN optional SKIPPING OPTIONAL DEPENDENCY:   <head>
npm WARN optional SKIPPING OPTIONAL DEPENDENCY:     <title>404 - Request is serviced by NPM metadata service, remote access not needed from DefaultNpmProxyRepository(id=npmjs)</title>
npm WARN optional SKIPPING OPTIONAL DEPENDENCY:     <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
npm WARN optional SKIPPING OPTIONAL DEPENDENCY:
npm WARN optional SKIPPING OPTIONAL DEPENDENCY:     <link rel="icon" type="image/png" href="https://nexus.aem.avivaaws.com/nexus/favicon.png">
npm WARN optional SKIPPING OPTIONAL DEPENDENCY:     
npm WARN optional SKIPPING OPTIONAL DEPENDENCY:
npm WARN optional SKIPPING OPTIONAL DEPENDENCY:     <link rel="stylesheet" href=
"https://nexus.aem.avivaaws.com/nexus/static/css/Sonatype-content.css?2.14.3-02" type="text/css" media="screen" title="no title" charset="utf-8">
npm WARN optional SKIPPING OPTIONAL DEPENDENCY:   </head>
npm WARN optional SKIPPING OPTIONAL DEPENDENCY:   <body>
npm WARN optional SKIPPING OPTIONAL DEPENDENCY:     <h1>404 - Request is serviced by NPM metadata service, remote access not needed from DefaultNpmProxyRepository(id=npmjs)</h1>
npm WARN optional SKIPPING OPTIONAL DEPENDENCY:     <p>Request is serviced by NPM metadata service, remote access not needed from DefaultNpmProxyRepository(id=npmjs)</p>
npm WARN optional SKIPPING OPTIONAL DEPENDENCY:   </body>
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: </html>
npm WARN optional SKIPPING OPTIONAL DEPENDENCY:
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @types/core-js@^0.9.41 (node_modules\backstopjs\node_modules\chrome-launcher\node_modules\@types\core-js):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unexpected token < in JSON at position 0
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: <html>
npm WARN optional SKIPPING OPTIONAL DEPENDENCY:   <head>
npm WARN optional SKIPPING OPTIONAL DEPENDENCY:     <title>404 - Request is serviced by NPM metadata service, remote access not needed from DefaultNpmProxyRepository(id=npmjs)</title>
npm WARN optional SKIPPING OPTIONAL DEPENDENCY:     <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
npm WARN optional SKIPPING OPTIONAL DEPENDENCY:npm WARN optional SKIPPING OPTIONAL DEPENDENCY:     <link rel="icon" type="image/png" href="https://nexus.aem.avivaaws.com/nexus/favicon.png">
npm WARN optional SKIPPING OPTIONAL DEPENDENCY:     
npm WARN optional SKIPPING OPTIONAL DEPENDENCY:
npm WARN optional SKIPPING OPTIONAL DEPENDENCY:     <link rel="stylesheet" href=
"https://nexus.aem.avivaaws.com/nexus/static/css/Sonatype-content.css?2.14.3-02"
type="text/css" media="screen" title="no title" charset="utf-8">
npm WARN optional SKIPPING OPTIONAL DEPENDENCY:   </head>
npm WARN optional SKIPPING OPTIONAL DEPENDENCY:   <body>
npm WARN optional SKIPPING OPTIONAL DEPENDENCY:     <h1>404 - Request is serviced by NPM metadata service, remote access not needed from DefaultNpmProxyRepository(id=npmjs)</h1>
npm WARN optional SKIPPING OPTIONAL DEPENDENCY:     <p>Request is serviced by NPM metadata service, remote access not needed from DefaultNpmProxyRepository(id=npmjs)</p>
npm WARN optional SKIPPING OPTIONAL DEPENDENCY:   </body>
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: </html>
npm WARN optional SKIPPING OPTIONAL DEPENDENCY:
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "backstopjs"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! Unexpected token < in JSON at position 0
npm ERR! <html>
npm ERR!   <head>
npm ERR!     <title>404 - Request is serviced by NPM metadata service, remote ac
cess not needed from DefaultNpmProxyRepository(id=npmjs)</title>
npm ERR!     <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
npm ERR!
npm ERR!     <link rel="icon" type="image/png" href="https://nexus.aem.avivaaws.com/nexus/favicon.png">
npm ERR!     
npm ERR!
npm ERR!     <link rel="stylesheet" href="https://nexus.aem.avivaaws.com/nexus/static/css/Sonatype-content.css?2.14.3-02" type="text/css" media="screen" title="no title" charset="utf-8">
npm ERR!   </head>
npm ERR!   <body>
npm ERR!     <h1>404 - Request is serviced by NPM metadata service, remote access not needed from DefaultNpmProxyRepository(id=npmjs)</h1>
npm ERR!     <p>Request is serviced by NPM metadata service, remote access not needed from DefaultNpmProxyRepository(id=npmjs)</p>
npm ERR!   </body>
npm ERR! </html>
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\AEM_BACKSTOPJS_SMOKE_TESTS\npm-debug.log

D:\AEM_BACKSTOPJS_SMOKE_TESTS>

**Comment by devm87** [comment]
Anyone who can help with the above? :(

**Comment by deepikathimmegowda** [comment]
Even i am facing same issue!! any help anyone?
