### ISSUE TITLE
 COMMAND | Command `reference` ended with an error

### ISSUE THREAD

**Issue by L0wry** [garris/BackstopJS#596]
Hey, 

Backstop runs fine locally but struggling in CI on Ubuntu, I've set `debug: true`
and this is my output. Latest chrome is installed 😢 

![screen shot 2017-11-14 at 14 39 45](https://user-images.githubusercontent.com/12037104/32785869-6f1f26da-c94a-11e7-8f6c-b781cd467744.png)

**Comment by L0wry** [comment]
this is also really sad 

```
   promise.catch(function (error) {
          var perf = (new Date() - config.perf[command.name].started) / 1000;
          logger.error('Command `' + command.name + '` ended with an error after [' + perf + 's]');
          // logger.error(error);
        });
```

`8e0074f8`Garris Shipon, a month ago   (October 13th, 2017 9:10am)

fix 549 — backstop hangs on error

**Comment by L0wry** [comment]
okay figured it out after uncommenting the swallowed error. 

For reference - the application exited correctly!

**Comment by garris** [comment]
@L0wry Thanks for pointing this out.  Sorry about that.  I have a todo to put the error back.
