### ISSUE TITLE
index_bundle.js missing

### ISSUE THREAD

**Issue by YStrauch** [garris/BackstopJS#600]
I use the latest version (3.0.32).

When running a regression test, the html_report has no index_bundle.js, therefore the report page is not rendering. Running the init command did not create this file either.

**Comment by VladimirPittner** [comment]
Hi,
this is duplicate of this -> https://github.com/garris/BackstopJS/issues/597

**Comment by YStrauch** [comment]
Indeed it is, thank you for noticing!
