### ISSUE TITLE
Tagging docker images

### ISSUE THREAD

**Issue by samuelhwilliams** [garris/BackstopJS#602]
At the moment it looks like BackstopJS only records a single docker image tag: latest. This means it's not easy to use a consistent, reproducible image without copying the Dockerfile and using that to generate a static image.

It would be great if this project could start tagging releases with unique references, as well as updating latest, so that those who want to (e.g. me) can reference a specific build to minimise the risk of an update to this library inadvertently breaking our tests in some way.

**Comment by garris** [comment]
I still don't know what I'm doing with docker. 😔   

what needs to happen?   Can you give me the steps?   It's probably pretty easy right?

**Comment by samuelhwilliams** [comment]
What do you currently do to build and push a new docker image? I don't see the Dockerfile in this repo; do you have it somewhere else in source control?

I presume you run something like `docker build -t backstopjs/backstopjs .`. This will default to building an image tagged as `latest`, and when you push this up, it'll overwrite the previous image tagged as `latest`.

The simplest thing to do is start explicitly including tags when you build and push your docker images. You can do this like so: `docker build -t backstopjs/backstopjs:3.0.32 .`. This will create an image tagged as `3.0.32` (the BackstopJS version used in the latest Docker image, which is probably a reasonable place to start, unless you expect to do ever update the dockerfile without updating the Backstop version). You can then push it up with `docker push backstopjs/backstopjs:3.0.32`.

The `latest` tag doesn't necessarily do what you expect, insofar as it doesn't track the latest image you've pushed. It's just another tag name. So if you also want to update latest, you could instead run `docker build -t backstopjs/backstopjs:3.0.32 -t backstopjs/backstopjs:latest .` and then push up both tags (separately as you can't push multiple tags at once).

This would help people integrate a specific version of Backstop rather than having to track latest or copy your Dockerfile and build the image locally.

**Comment by samuelhwilliams** [comment]
Apologies, just noticed this is already open in https://github.com/garris/BackstopJS/issues/562.

I will have a think about how to tie this into your hook already so that it can be handled automatically.

**Comment by samuelhwilliams** [comment]
@garris Ok, so I assume you're using Docker Hub's automated builds, configured at https://hub.docker.com/r/backstopjs/backstopjs/~/settings/automated-builds.

Here you can add a tag rule (see below) which will automatically build Docker images with the same tag. All you'd need to do is start tagging your commits when you bump the version number, which would probably be a nice thing to do anyway. Once you push these tags up to GitHub, DockerHub will trigger the build and you'll have this problem neatly solved. 👍

You could potentially use a post-commit hook or a webhook to automatically create git tags when the version of BackstopJS is updated, in which case you wouldn't have to take any manual action. But that would be a bit more work up front. :)

<img width="1292" alt="screen shot 2017-11-22 at 23 49 04" src="https://user-images.githubusercontent.com/2920760/33154388-f601a0ce-cfdf-11e7-82b7-627dfa05614f.png">

**Comment by garris** [comment]
I am happy to give you write permission so that you could make the adjustments— I really would like someone to take ownership of the docker admin.   Just let me know what you think.   Thanks.

**Comment by garris** [comment]
@samuelhwilliams thank you for the tips -- that made it super easy!   Ok.  So now there is a latest and a tags build.   I think maybe I should delete the latest rule -- I can't imagine anyone would want to pull from that.

I just pushed a new tag and docker started building...

Please let me know if that is working for you!

![image](https://user-images.githubusercontent.com/447033/33307117-43a7165e-d3ca-11e7-8907-ba84926912c4.png)

**Comment by samuelhwilliams** [comment]
Nice, this looks like a good set up. I'd probably keep `latest` even though people are unlikely to rely on it, as it makes it easy for people who are pulling the image and just want to play around before pinning the version.

It looks like the latest few builds in Docker Hub have failed due to being unable to pull the package through NPM. I can only think that maybe the latest versions aren't published yet?

Weirdly enough, I could also see the cancel button on the Docker Hub build. Haven't tried clicking it, but wonder if the settings are too permissive and maybe the public can cancel builds?

<img width="899" alt="screen shot 2017-11-28 at 07 48 49" src="https://user-images.githubusercontent.com/2920760/33308256-961c35f8-d411-11e7-81b1-1cc9efb76473.png">

**Comment by garris** [comment]
@samuelhwilliams Ahh -- I see the fail too.   So I guess that means I need to publish the new tagged version to NPM before pushing my tag to github.  That makes sense.  One question though...

In the `./docker` file there is a `BACKSTOPJS_VERSION` property.  Does this version need to match the tagged version -- IOW does this file need to be updated with the current tag each time I publish?
![image](https://user-images.githubusercontent.com/447033/33332351-f07e58ee-d418-11e7-8c1f-67193578cda7.png)

**Comment by samuelhwilliams** [comment]
Probably best to have the tag on the docker image match that of the BackstopJS version inside it, as that's what most people would expect to be the case.

It looks like the Dockerfile only uses `BACKSTOPJS_VERSION` with `npm install`, which only seems to accept specific version numbers, so it looks like we'll need to update Dockerfile BACKSTOPJS_VERSION in line with `version` in package.json.

Might be I can throw something together to automate/simplify some of these release processes/artifacts, if you would like. Not sure what you do at the moment for releasing to npm/docker/anywhere else. Is it all manual at the moment?

**Comment by Baltazardoung** [comment]
You can probably use a hook to [automatically publish a tag using the version declared in your `Dockerfile`](https://docs.docker.com/docker-cloud/builds/advanced/#push-to-multiple-tags)

It is then enough to add in your file "`docker`" a sub folder "`hooks`" containing a file "`post_push`":
```shell
#! / Bin / bash
eval $ (grep -o 'BACKSTOPJS_VERSION = [^] *' $ (dirname "$ 0") /../ Dockerfile)

docker tag $ IMAGE_NAME $ DOCKER_REPO: $ BACKSTOPJS_VERSION
push docker $ DOCKER_REPO: $ BACKSTOPJS_VERSION
```

**Comment by Baltazardoung** [comment]
In addition, if you want to use the version number referenced in the "`package.json`" file directly within the `Dockerfile`, you can use [the `build` hook to retrieve this information and pass it as an argument to the build](https://docs.docker.com/docker-cloud/builds/advanced/#override-the-build-phase-to-set-variables).

See 025555bf0566d468bcbd83ae7abc03f2e9d89520

**Comment by Baltazardoung** [comment]
The best solution was probably a mix of previous proposals.
1. Implementation of a single DockerHub rule based on a tag.
![screenshot_20171214-174521](https://user-images.githubusercontent.com/13434663/34003906-d8993fd8-e0f6-11e7-9909-0c730041a345.jpg)
1. Update `Dockerfile` and add the `build` hook to pass the version as argument (extracted from the `package.json` file).
```Shell
FROM node:8.5.0-alpine

ARG BACKSTOPJS_VERSION

ENV \
	PHANTOMJS_VERSION=2.1.1 \
	CASPERJS_VERSION=1.1.4 \
	SLIMERJS_VERSION=0.10.3 \
	BACKSTOPJS_VERSION=$BACKSTOPJS_VERSION \
#...
```
```Shell
#!/bin/bash
BACKSTOPJS_VERSION=$(grep -Po '(?<="version": ")[^"]*' $(dirname "$0")/../../package.json)

docker build --build-arg BACKSTOPJS_VERSION=$BACKSTOPJS_VERSION -t $IMAGE_NAME .
```
3. Add the "`post_build`" hook (to generate the "`latest`" image)
```Shell
#!/bin/bash
docker tag $IMAGE_NAME $DOCKER_REPO:latest
docker push $DOCKER_REPO:latest
```
What do you think ?

**Comment by samuelhwilliams** [comment]
Sounds pretty good to me.

**Comment by garris** [comment]
Thank you @Baltazardoung and @samuelhwilliams!   And many apologies for the late response Samuel!

I have an hour tomorrow to try to implement this.  I would totally appreciate if either of you would be able to do a Skype call to make sure I don’t screw this up.😄   No worries either way—I’ll give it my best shot.  Cheers!

**Comment by Baltazardoung** [comment]
@garris see  pl #617 :smile:

**Comment by fusionfox** [comment]
Sorry, I got busy after raising #562 - happy to see that this got picked up 😄
