### ISSUE TITLE
No bitmaps_reference folder created when I run reference. 

### ISSUE THREAD

**Issue by conanmalanaphy** [garris/BackstopJS#611]
The steps I have taken is similar to https://css-tricks.com/automating-css-regression-testing/ 

1. npm install backstopjs
2. inside _node_modules/backstopjs/_  npm run genConfig
3. then npm run reference

I get the message it is completed succesfully
![image](https://user-images.githubusercontent.com/22730581/33661250-e6d031e8-da7e-11e7-8a7d-61dffa088e4a.png)

but no reference folder is created in the backstop_data folder. Here is the boilerplate BackStop.json config I used. 
![image](https://user-images.githubusercontent.com/22730581/33661345-6f1503bc-da7f-11e7-99f9-f86c7fd35430.png)

Thanks for you help :)

**Comment by garris** [comment]
This should help... https://github.com/garris/BackstopJS/issues/518
