### ISSUE TITLE
Port numbers for Chromy are hardcoded.

### ISSUE THREAD

**Issue by alexus2005** [garris/BackstopJS#614]
Hi,

I discovered that ports on my machine are used by another application I have no control over(large company, administrator controlled). I needed to switch ports for Chromy from 9222 to something else, but found out that there is no way to do so unless you edit the source code.

Is there a way to expose that as part of settings?

Thanks,
Alex

**Comment by garris** [comment]
@alexus2005  I just merged this feature yesterday.  I haven’t published this to npm yet — will probably do this on Friday.

**Comment by grafbumsdi** [comment]
I would also need this fix, please!

**Comment by garris** [comment]
Feature has landed.  See docs.  Reopen if there is an issue.  Thanks.

**Comment by garris** [comment]
Thanks @timrnz

**Comment by alexus2005** [comment]
Thank you @garris! This is one of the best visual comparison tools I have seen :)

**Comment by garris** [comment]
@alexus2005 Cheers!
