### ISSUE TITLE
Create separate html report directory for each scenario

### ISSUE THREAD

**Issue by anandsourabh** [garris/BackstopJS#618]
I have a huge number of test scenarios for regression testing (200+). Having all the screen shots in the same html_report index.html is not feasible. Is it possible to create a new html report directory for each scenario being executed? or perhaps group the reports by test suits?

**Comment by ackmanx** [comment]
> or perhaps group the reports by test suits?

My team's solution to this part was to create a different config for separation. So, we have a "large view" config and a "small view" config. Every config gets its own report. Combined with a JavaScript module approach to generating the configs, it's pretty clean.

**Comment by garris** [comment]
@ackmanx thank you for posting your question _and_ your solution!  That is exactly what I was going to suggest — glad it’s working for you! 😊

Cheers.

**Comment by anandsourabh** [comment]
Thanks @ackmanx  and @garris. I was asked to have a seperate report for each scenario, I managed to get this done by creating separate jsons based on test data that I was provided. I am encountering a unique problem though, that I will pose as another issue. Thanks again!
