### ISSUE TITLE
Junit report issue

### ISSUE THREAD

**Issue by anton-kulagin** [garris/BackstopJS#620]
Good day, my case is really specific but i think we can fix it.
1. I have Expressjs server with services which run backstop
``backstop("test", {filter: someFilter });``
2. CI report enabled
3. Each run of this service are push result to junit report. And for example if we start twice one test it will have 2 result in junit but should have only last test result.
The problem is, that while server process is running it keep all previous test result in closure and push(not replace)  new one. I make a really small fix to prevent such behavior. And it will be  great if you will merge it to master.
Pull request was already created [PR619](https://github.com/garris/BackstopJS/pull/619)

**Comment by garris** [comment]
Thank you for the PR.  It’s merged!

**Comment by anton-kulagin** [comment]
@garris Thank you. Could you close this issue.
