### ISSUE TITLE
Clearing bitmaps_test directory

### ISSUE THREAD

**Issue by dennis-best** [garris/BackstopJS#625]
Are there settings to limit the number of recent tests? Or do I need to set up a task somewhere to to clear it occasionally?

My "bitmaps_test" directory is getting getting pretty full. It's possible I'll run tests a dozen times a day.

**Comment by garris** [comment]
Hi @dennis-best,  there were a few proposals but nothing baked-in.   I think a lot of users just run something to clean-up any files older than n-days (or whatever).

**Comment by dennis-best** [comment]
Good to know. Thanks!
