### ISSUE TITLE
Zoom images in report

### ISSUE THREAD

**Issue by YuliaTsareva** [garris/BackstopJS#63]
If screenshot is quite large, it is difficult to understand what has been changed. It would be great to zoom images on click. What do you think?

**Comment by garris** [comment]
Hi Yulia, yes sure, if you want to have the image open in a new tab I'd be happy to pull that in.  What is your idea?

**Comment by YuliaTsareva** [comment]
My idea was to open modal dialog with image. Something similar to this: http://dimsemenov.com/plugins/magnific-popup/

**Comment by garris** [comment]
Hi Yulia, sorry for the delay.  For you, what is the benefit of the pop-up as opposed to a new tab?   Also, I don't think we included jquery in this project.

**Comment by YuliaTsareva** [comment]
Pop-ups provide smoother user experience because they do not make user to switch between tabs. I also would prefer not to add jquery, but I don't know any library which could do such zooming without jquery.

**Comment by YuliaTsareva** [comment]
Actually, I've already solved it for myself using lightbox2. It looks exactly as I wanted and solved the problem (well, I need to test it with larger screenshots, but for now it looks quite good).

![bs](https://cloud.githubusercontent.com/assets/8158578/8173582/7cf4aeb2-13d8-11e5-8c54-a24b84a4d10a.png)

In my opinion there are some advantages over new tab:
* user stays in current tab and can open and close image quickly;
* it is possible to navigate from zoomed reference image to zoomed test image and then to zoomed diff with just one click on image;
* it shows small description under the image so I always understand which exactly image I see now (is it reference or is it test).

But also there are disadvantages:
* it needs jquery;
* it use `compileProvider.aHrefSanitizationWhitelist` to whitelist `data:image` in `a href` (which I consider a bad practice but can't avoid it for now).

It is just my opinion, may be you can offer better solution :)

**Comment by garris** [comment]
This should be very easy to build.

1) Create a div  for the pop up.  Give class with Position: fixed, centered on screen (e.g. bottom:100px;top:100px;left:100px;right:100px, display:none, **background-size:contain**. 

2)  add click handler for report images and set the background-image source to the selected image src value.   Also add a 'show' class which will set display:block on the popup div.

3) when the user clicks anywhere you can remove the 'show' class.

I think this is most of what you need to implement in NG's jqLite version.
------------

You should try it -- it is very simple stuff once you adjust to html5/angular.  Then you can provide a much better experience and you would improve your skills!

**Comment by YuliaTsareva** [comment]
Of course, if it as easy as you say, it makes sense.

But won't it stretch images to all available place? I suppose that screenshot should be centered if it is smaller than screen size (not stretched) and should be adjusted to available place if it is larger.

**Comment by garris** [comment]
Yes, that is correct. `background-size:contain` will only scale down images which are too big to fit.  We would not want images scaled up beyond their native resolution.   All the data you need for display titles and paging through result rows is already available via angular.

If you don't already work with angular you will be glad you took the time to learn it.   Or you could do it jQuery style and just use jQLite or html5 methods.  But I encourage you to learn new things -- there are no deadlines or hovering project managers here!  ;)

**Comment by YuliaTsareva** [comment]
Actually I work with angular every day :) One more reason why I prefer third-party library is that its quality is more or less guaranteed, no need to test it (by the way, would be great to have more tests).

Well, I understand your point of view and probably will try to do it. Although for now my solution solves my problem.

**Comment by garris** [comment]
Ok.  Sounds good.  :+1:

**Comment by axe312ger** [comment]
Nice idea. I'd prefer https://github.com/dimsemenov/photoswipe instead of magnific popup since it provides better options in zooming into the picture. Also the touch support is way better.
The api is good and it is from the same guys as magnific popup.

@YuliaTsareva let me know is you need any help or discussion about this :)

**Comment by kamlesh-astech** [comment]
Hi @YuliaTsareva ,
Is your lightbox for images is done completely???

**Comment by YuliaTsareva** [comment]
Hi @kamlesh-astech,
Short answer is no.

And long answer:
I implemented it using lightbox2 script in my fork and it satisfied my needs completely. But my solution needed jQuery to be included. As BackstopJS itself doesn't need jQuery (at least, it didn't need it 6 months ago), we decided that this improvement should be implemented in other way.

As I stopped working on a project where I needed BackstopJS, I haven't returned to this issue.

**Comment by kamlesh-astech** [comment]
Can u help to solve error upon " a href unsafe base 64 url" that we get for the diff / mismatch image.

http://grab.by/Oo5m

**Comment by YuliaTsareva** [comment]
@kamlesh-astech
Try to inject $compileProvider to compareApp.config and add a line:
`$compileProvider.aHrefSanitizationWhitelist(/^\s*(https?|ftp|file):|data:image\//);`

It should help.

**Comment by kamlesh-astech** [comment]
Thanks for ur help. It sorted my issue
