### ISSUE TITLE
Add 'pkill -f "(chrome)?(--headless)"' alternative for Windows in Troubleshooting section of the README

### ISSUE THREAD

**Issue by liamaharon** [garris/BackstopJS#640]
I (and from looking through the issues list other people too) am having issues where sometimes headless Chrome instances are not closed after running tests, causing the next run of tests to fail. 

Under "Troubleshooting" in the README, there's a [solution](https://github.com/garris/BackstopJS#chromy-error-error-see-scenario-) that works on Mac and Linux, but not Windows.

One solution for Windows users is to run `taskkill /F /IM chrome.exe`, however this is unideal as it closes _all_ Chrome instances, not just headless ones.

I think a one-liner that terminates all headless Chrome instances on Windows would be a welcome addition to the README.

**Comment by garris** [comment]
I don’t know how to do that on windows— but I would gladly publish that in the docs if someone could validate the way to do it.

In the meantime, will installing chrome canary help at all?  If you install chrome canary on macOS it will coexist with your regular chrome and backstopjs will use canary by default.   You may be able to more easily create a windows command to close chrome canary?  Please post back your solution if you can make progress.  Cheers!

**Comment by liamaharon** [comment]
@garris Had a play with Canary but sadly was not able to find an obvious solution. 

Feeling clueless as ever, I reached out to the kind community over at Superuser who provided a [solution](https://superuser.com/questions/1288388/how-can-i-kill-all-headless-chrome-instances-from-the-command-line-on-windows/1288391#1288391) that runs in PowerShell! 

Here's the command, which I've verified working on my W10 64bit setup
`Get-CimInstance Win32_Process -Filter "Name = 'chrome.exe' AND CommandLine LIKE '%--headless%'" | %{Stop-Process $_.ProcessId}`

If somebody else doesn't get around to it first, I'll submit a PR over the weekend. 👍

**Comment by garris** [comment]
That looks great — thank you!  Feel free to PR if you get the chance.  Cheers.

**Comment by anton-kulagin** [comment]
This script doesn`t work for me. Windows Server 2008
``
>Get-CimInstance Win32_Process -Filter "Name = 'chrome.exe' AND Com
mandLine LIKE '%--headless%'" | %{Stop-Process $_.ProcessId}
'Get-CimInstance' is not recognized as an internal or external command,
operable program or batch file.
``

**Comment by garris** [comment]
Uh oh.  @anton-kulagin could you please reach out to @liamaharon for this?

**Comment by liamaharon** [comment]
@anton-kulagin are you running the script inside PowerShell? How and at what point is it failing?

**Comment by liamaharon** [comment]
@anton-kulagin are you running the script inside PowerShell?

**Comment by anton-kulagin** [comment]
@liamaharon, @garris Sorry guys, looks like my fault. I`m try to start script in cmd, but should in Power-Shell.

**Comment by liamaharon** [comment]
No worries, good to hear it's working for you now.
