### ISSUE TITLE
Does Backstop works with data atrributes?

### ISSUE THREAD

**Issue by andrepm06** [garris/BackstopJS#644]
Its possible select elements using data attributes?

For example:
`
 "selectors": ["SummaryCardContentOverview"]`

**Comment by andrepm06** [comment]
Turns out react needed some time to renderize those components.

I got it working with this:

```
"readySelector": "[data-test-id]"
"selectors": ["[data-test-id=SummaryCardContentOverview]"]
```

**Comment by djskinner** [comment]
Good spot - thanks for this. The error information can sometimes offer very little help.
