### ISSUE TITLE
screen capture for dynamically generated content

### ISSUE THREAD

**Issue by awongCM** [garris/BackstopJS#65]
Hi,

I'm not sure whether this has been addressed or implemented already as part of the feature of backstopjs.  Nevertheless I would raise it otherwise if it hasn't been done.

It would be great to see how you can extend Backstop feature further to capture screenshots for any dynamically generated content such as AJAX calls or animated image/text carousel pages.

Cause what I often find is with these scenarios, (since started using it) I would like to see the dynamic content in its ready/paused state for backstop to take quick snapshots and I didn't have much success on its current build.

Is that the case?

Let me know if you wish me to clarify further.

**Comment by garris** [comment]
Are you having a problem with backstopjs taking the screenshot too early?  Please let me know.  Thanks.

**Comment by awongCM** [comment]
Hi @garris - somewhat "yes".

I explain to you a scenario.

I have a site that has an animated carousel image gallery on the page.  Let's say I have the following markup:

    <div id="some-carousel" class="carousel slide" >
      <div class="carousel-inner">
         <div class="item">
            <img src="carousel_pic_1.jpg" class="visible-xs" alt="">
         </div>
         <div class="item active left">
            <img src="carousel_pic_2.jpg" class="visible-xs" alt="">
         </div>
         <div class="item next left">
            <img src="carousel_pic_3.jpg" class="visible-xs" alt="">
         </div>
         <div class="item">
            <img src="carousel_pic_4.jpg" class="visible-xs" alt="">
         </div>
      </div>
   </div>

As this is a typical markup setup for carousel gallery, the `item` tags will toggle to scrollswap images (due to some fancy jquery animation library obviously) at some regular interval.

But what I would like to achieve is I'm interested to capture a screenshot for pic item `carousel_pic_3.jpg`.  And I can only have that the 3rd `<div class="item">` tag would set to `active`.

But there's nothing in `backstop.json` file to offer a variable or parameter to select that particular DOM selector, captured as a screenshot while the carousel is being animated.

I tried setting in the `selectors` param something like `.carousel-inner.item:nth-child(3)`.  But I don't think that works??

**Comment by garris** [comment]
Just to confirm, Do you want the screenshot to capture at a specific time -- when your carousel gets to some point ?

**Comment by awongCM** [comment]
Precisely.

**Comment by garris** [comment]
Read this article -- it is a tutorial for BackstopJS testing on client side apps with async behaviors.  The example is an Angular app but the principle is the same...
http://davidwalsh.name/visual-regression-testing-angular-applications

**Comment by awongCM** [comment]
Thanks @garris - Makes sense.  I get the point.

Wonder how I should incorporate this principle into vendor's complex animation jquery plugin...

But it's doable.

Cheers for that.

**Comment by garris** [comment]
Great.  Most plugins have some kind of callback for that kind of thing.   (E.g. carousel.onNext( yourFn(nextObjData ) )

FWIW: This slider probably won't suit your needs -- but it is cool... TremulaJS.org

**Comment by kamlesh-astech** [comment]
An additional further point to this conversation.
How can we check bootstrap modal, alerts, tabs or an item in an bxslider.
using backstop. 
It would be very helpful if you explain with an example related to any of the tags that i have added
