### ISSUE TITLE
TESTERS NEEDED:  BackstopJS 3.1 is in canary!

### ISSUE THREAD

**Issue by garris** [garris/BackstopJS#650]
**Backstoppers!** I would like to present to you a brand new UI by Italian stylist-engineer Gabriele Mantovani!  @mantovanig

Please test and comment! `npm install backstopjs@canary`

![screen shot 2018-01-31 at 8 56 45 pm](https://user-images.githubusercontent.com/447033/35662296-36570506-06cc-11e8-9c96-b7ccf9abcbcb.png)

![screen shot 2018-01-31 at 8 56 37 pm](https://user-images.githubusercontent.com/447033/35662315-55ee130a-06cc-11e8-82bb-cc641c1da9fb.png)

Grazie!

**Comment by matthiaskomarek** [comment]
Hello @garris i have tested it with our current setup and i'am impressed by the new ui. Is there any ETA when this will land on master?

**Comment by garris** [comment]
Pushed it Tuesday — it’s at latest now! 

`npm install backstopjs`

Thanks for posting!   I guess I can close this ticket now. 😄

**Comment by kiran-redhat** [comment]
Yup, we can close. I've tested 3.1.17 with my app all good.

**Comment by garris** [comment]
Thanks everybody!  Yes and I have received a lot of direct messages as well. Cheers!
