### ISSUE TITLE
Backstopjs docker `Connection refused`

### ISSUE THREAD

**Issue by creaux** [garris/BackstopJS#651]
I'm trying to access host from docker container but unfortunately I don't have success. Problem is that docker image can't reach host. For this reason I can't run tests against host where is running my web instance.

1. I tried access host by localhost as my knowledge of Docker is really naive I'm not sure whether is that even possible according setting of your container
2. I tried as well with --net="host" same result
2. I even tried to access it using that what I found in adapter setting its usually 172.17.0.1 by default. Even that host is not accessible.

In my env firewall is off etc. All the time when I run curl getting (even with port specified):

```
bash-4.3# curl localhost:6007
curl: (7) Failed to connect to localhost port 6007: Connection refused
```

`localhost:6007` is of course accessible by browser in my host directly.

Can you please point me in right direction?

**Comment by x1c0** [comment]
Hi @creaux , did you manage to fix your issue? I'm having the same problem, I have a local storybook and I want to visual regression test it..

**Comment by creaux** [comment]
Hi, yes but thing is that it is already year ago I can’t remember what was the solution. I suggest to run everything inside of docker instance.

**Comment by x1c0** [comment]
But since the docker instance is from this repo, how can I also run my web server there? Is that even possible?

**Comment by x1c0** [comment]
Maybe this is not the cleanest solution, but that's how I make this work for someone getting here with the same problem.

Basically this setup allows running backstopJs in docker in all 3 OS (mac, linux and windows) against a local web server (this case storybook) and the problem was the connection from docker container into the host machine, where the web server was running.

`package.json`
```
{
    "visual-regression-test:linux": "start-server-and-test build-sb-and-serve http://localhost:8085 docker:linux:test",
    "visual-regression-test:mac": "start-server-and-test build-sb-and-serve http://localhost:8085 docker:mac:test",
    "visual-regression-test:win": "start-server-and-test build-sb-and-serve http://localhost:8085/index.html docker:win:test",
    "build-sb-and-serve": "npm run build-storybook && http-server -p 8085 .out",
    "docker:linux:test": "docker run --network host --rm -v $(pwd):/src backstopjs/backstopjs test --configPath=backstop.config.js",
    "docker:mac:test": "docker run -e IS_MAC=true --network=\"host\" --rm -v $(pwd):/src backstopjs/backstopjs test --configPath=backstop.config.js; backstop openReport --configPath=backstop.config.js",
    "docker:win:test": "docker run -e IS_WIN=true --network=\"host\" --rm -v %cd%:/src backstopjs/backstopjs test --configPath=backstop.config.js & backstop openReport --configPath=backstop.config.js"
}
```

`backstop.config.js`
```
const isMac = process.env.IS_MAC;
const isWin = process.env.IS_WIN;

// by default uses localhost, only works on linux
let storybookPath = `http://localhost:8085/iframe.html?id=`;
if(isMac) {
  storybookPath = storybookPath.replace('localhost', 'docker.for.mac.host.internal');
} else if(isWin) {
  storybookPath = storybookPath.replace('localhost', 'host.docker.internal');
}

const defaultOptions = {
  readySelector: "storybook-dynamic-app-root"
};

let scenarios = [
  {
    "label": "Accordion closed",
    "url": `${storybookPath}accordion--simple-header-body-closed`,
  },
  ...
];

scenarios = scenarios.map(scenario => { return {...defaultOptions, ...scenario}});
```

**Comment by garris** [comment]
Thanks for posting a solution!

**Comment by alexandroid** [comment]
Thanks! So basically BackstopJS needs `host.docker.internal` instead of the `localhost` in the scenarios URL (I am running tests in WSL):
```
"url": "http://host.docker.internal:3000",
```
