### ISSUE TITLE
change localhost/compare url default auto-shutdown time 

### ISSUE THREAD

**Issue by awongCM** [garris/BackstopJS#66]
After I run `grunt backstop:test`, I noted this line

    $ grunt backstop:test
    Running "backstop:test" (backstop) task
    .......................................
    .......................................
    .......................................
    Server launched in background with PID: 7448
	NOTE: Sever will auto-shutdown (default time 15 mins). See documentation for more info.

	[11:13:59] Starting 'openReport'...

	Opening report ->  http://localhost:3001/compare/
	[11:13:59] Finished 'openReport' after 5.16 ms

It says that server will auto-shutdown within 15 mins by default.

How can I modify this to increment the auto-shutdown time.  Where is the documentation for this?

**Comment by garris** [comment]
There is currently a pull request for this feature (adding a flag at the command line).  Just curious, what is your use case for increasing that timeout?

**Comment by awongCM** [comment]
I haven't actually thought of one till you raised that question in this thread.

I'm just curious to find out is this part of the setup configurable via json file at all? I'm just keen to understand what goes under hood - that's all.

However, I just had a brainstorm about this while we're in discussion.  I want to find out if it is possible to output/download the entire compare report into a spreadsheet/doc/pdf.  That way I can share, not only with my development team to discuss the impact of such changes, but also to our client as well.  This would aid to gauge open dialogues on the UI/UX of web apps/websites with all stakeholders and illustrate greater visibility of the overall user look and feel across monolithic sites.

Hope this makes sense to you.

Let me know if you need to clarify my point further, I'm not clear with the above statement.

**Comment by garris** [comment]
1) After the report runs you should just save the webpage as a PDF.

2) so, it sounds like you don't have a use case for changing server timeout.

**Comment by awongCM** [comment]
1. Okay.

2. No.  However, I would like to know is it possible to re-access the same report (after it auto-shutdown)  by not having to run `grunt backstop:test` again?

**Comment by YuliaTsareva** [comment]
You can open the same report with `gulp report` command.

**Comment by garris** [comment]
@YuliaTsareva  Thanks for answering this!

Also FWIW:  When I work with a team my workflow is usually to: 
1) run the report
2) print to PDF then make notes on that PDF file  (sometimes I just cut and paste a particular image)
3) email the marked up file ... repeat back to 1 as much as necessary.

4) file a clean report with my release notes.

This is pretty good for small teams because I usually have notes in addition to simply showing a developer that something is not passing.

**Comment by awongCM** [comment]
Thanks guys.

@YuliaTsareva - Though you could also technically write a wrapper function for grunt to execute `gulp report` as well.  

That would be nice. 

Cause I don't have to navigate the bower components folder every time to do this.  Can stay within the root folder.

**Comment by garris** [comment]
Timeout was added in latest release.
