### ISSUE TITLE
Tests fails inside docker run - Seems like Backstop tools not installed kind of

### ISSUE THREAD

**Issue by vininaag** [garris/BackstopJS#660]
when i try to run the tests local they ran fine and screenshots created. Where as same tests when i ran using docker it fails. There is only one difference between the console logs of Local runs vs Docker run is below statement is missing for docker run  after `9223 Chrome v63 detected.`

`9222 INFO >  BackstopTools have been installed.`

Because of this the screenshots are not getting created.
Please see the attached screen

I am using the official docker `https://hub.docker.com/r/backstopjs/backstopjs/`

**Comment by garris** [comment]
Does your container work with a default backstop config?  What backstop version is your container running?

**Comment by vininaag** [comment]
@garris 
I am facing a strange behaviour. The [docker Image](https://hub.docker.com/r/backstopjs/backstopjs/) says "A self-contained Docker image with no external dependency"
I am running the docker image in my machine (mac), it runs the scripts and able to take the screenshots.
When i ran the same docker image in another machine(mac), it runs the scripts but screenshots not created.
When i ran the same docker image in aonther machine (Linux), again it runs the scripts but screenshots not created.

Below are more details:
Backstopjs version i am using BackstopJS 3.x  (from the docker image only. Not installing externally)
my `dockerfile`
```
FROM dockertr.xxx.xxx/backstopjs

USER root
COPY package.json /src
```
my `docker-compose.yml`
```
version: "2.3"
services:
  test:
    build:
      context: .
      dockerfile: dockerfile
    cap_add:
      - SYS_ADMIN
    volumes:
      - .:/src
      - /dev/shm:/dev/shm
    shm_size: 1024M

```
How i am starting "`run_tests.sh`"
docker-compose build test
docker-compose run --entrypoint 'sh abc.sh' test
result=$?
docker-compose stop
docker-compose rm -f
exit $result

The `abc.sh` file
```
#Below will generate and update the cookie.json available in engine_scripts
node src/gencookie.js
pkill -f "(chrome)?(--headless)"
backstop test
echo 'THE END'
```

NOTE: 
1. The current directory (mapped in docker-compose) is having the below folder structure.
 |_docker-compose
 |_abc.sh
 |_run_tests.sh
 |_src
     |_engine_scripts
 |_backstop.json 
 |_package.json

2. I am using the chromy (again provided inside the docker image)

3. running the run_tests.sh in my machine working fine. Failing in another.  The only difference between mymachine run and other machine runs console is  
`9222 INFO > BackstopTools have been installed.`
  both are mac. See the attached image of consoles
![mymac_another](https://user-images.githubusercontent.com/20348542/35957506-edd0cfdc-0cc1-11e8-8dd4-563c0829222f.png)

**Comment by vininaag** [comment]
Found the issue, When run inside docker it was requiring a proxy and waiting and getting timed out.

**Comment by garris** [comment]
Thank you for figuring it out and posting back!
