### ISSUE TITLE
How to set Proxy for the chrome browser present inside backstop docker

### ISSUE THREAD

**Issue by vininaag** [garris/BackstopJS#664]
I am using the official backstopjs docker image. We are inside our company network. 
When I try to run my tests using chrome engine it is getting timeout error.
Where as if i change the engine to phantomjs it able to access the pages.
I believe it is because the chrome proxy needs to be set so that it can access my page.
Could someone tell how to set proxy for chrome present inside docker?
Tried below in backstop.json but doesn't seems to work
```
"chromeFlags": ["--no-check-certificate","--disable-dev-shm-usage","--proxy-server=http://proxy.ab.abc.com:8080"]
   },
```

**Comment by vininaag** [comment]
My issue resolved with disabling the some external cdns from the site i am testing.  The Resolutions for other if they want to change. They can try below two ways.
1. 
`"chromeFlags": ["--no-check-certificate","--disable-dev-shm-usage","--proxy-server=http://proxy.ab.abc.com:8080"]
`  
2. use docker HTTP_PROXY & HTTPS_PROXY in docker-compose.yml

**Comment by garris** [comment]
Thank you for posting your solution.  Cheers!
