### ISSUE TITLE
Cannot install 3.1.15 behind a proxy

### ISSUE THREAD

**Issue by FabienDeshayes** [garris/BackstopJS#669]
First of all, congrats on the 3.1.x release, looks great!

I tried to install it but getting this error:
```
npm ERR! Error while executing:
npm ERR! C:\Dev\devtools\bin\git\bin\git.EXE ls-remote -h -t ssh://git@github.com/garris/react-twentytwenty.git
npm ERR!
npm ERR! ssh: Could not resolve hostname github.com: no address associated with name
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
```

This is because I'm running the command in my company, behind a proxy (we have an internal registry).

This is happening because one dependency tries to pull from github directly, as it's not yet released:

https://github.com/garris/BackstopJS/blob/master/package.json#L84

Could you please release your fork of `react-twenty-twenty`? Or let us know when it's gone back up the source repository and released with your fix?

Thanks

**Comment by garris** [comment]
Oh crap!  Thank you for reporting!   I forgot to change this.

I think twenty-twenty updated my pull request and their NPM package should work now.   Are you able to update the backstop package.json and test this?

**Comment by garris** [comment]
FIXED.  

Please verify.

Thanks.

**Comment by FabienDeshayes** [comment]
Looking good, thanks!
