### ISSUE TITLE
Bug with headless Chrome

### ISSUE THREAD

**Issue by SheffBRC** [garris/BackstopJS#670]
Sometimes, when I try run `reference` or `test`, chrome has been crashed. In terminal i receive message about successes operation. But, if `reference` was run, app doesn't created reference images, if `test` was run, app create next report:
![image](https://user-images.githubusercontent.com/15000715/36197814-8caf1a90-117d-11e8-8776-6567cc1b7b36.png)
In this instance Chrome satays at system processes. If it don't remove manually, next operations with backstopjs will failed.

**Comment by iain17** [comment]
Which version of chrome are you running?

**Comment by garris** [comment]
Also, please update your backstop — we released a new version (3.1.15) yesterday that should address this bug.

**Comment by SheffBRC** [comment]
Thank you!
I'll try

**Comment by SheffBRC** [comment]
I had 3.0.38

**Comment by SheffBRC** [comment]
Hello! I've updated backstopjs version. But problem didn't disappear
My Chrome Version 63.0.3239.132 (Official Build) (64-bit)
![image](https://user-images.githubusercontent.com/15000715/36304205-6edcfd48-1317-11e8-8b51-fe4141d55f4f.png)

**Comment by iain17** [comment]
Try updating to chrome build version 64, I think in they might've fixed this issue.

**Comment by SheffBRC** [comment]
Hello!
I found same problem - https://bugs.chromium.org/p/chromedriver/issues/detail?id=1699
and its solution 

> I added the definition of this environment variable in the script, like this:
    def setUp(self):
        os.environ["DBUS_SESSION_BUS_ADDRESS"] = '/dev/null'
        chrome_options = Options()

And it really helped.
Build was launched about 20 times, and all were successfully passed, although before that, chrome hung on 3-5 launch for sure.

Can you try this, please?

**Comment by SheffBRC** [comment]
Bug depend on hardware. Bug was at mac mini 2014 with HDD
![image](https://user-images.githubusercontent.com/15000715/40235636-8bb87968-5ab3-11e8-8a63-47723fcec650.png)

There are no problems at MacBook with I5 2.3 Ghz, 8 Gb RAM and SSD
