### ISSUE TITLE
Tag the latest docker build?

### ISSUE THREAD

**Issue by kevinmpowell** [garris/BackstopJS#671]
@garris loving the work you're doing and we just started to use the docker image you're providing. I noticed that you pushed a new docker image yesterday that's got a slick new UI for the test results page. However it's currently available at the `latest` tag in docker, so I can't lock our project to that build. Is it possible to tag the current version in addition to having the `latest` tag for those of us that can't live on the bleeding edge?

Keep up the great work!

**Comment by garris** [comment]
@kevinmpowell  thanks for reporting!   The Docker tags are supposed to generate on each GH commit.  I just checked the docker log and there saw that the last few builds broke.  I don’t know if I will have time to fix this today, but if you can troubleshoot and PR I would totally pull it in.  No problem if you can’t — I’ll try to get to it as soon as possible.  Cheers.

**Comment by garris** [comment]
Hmmm,  Just took a look -- Maybe related to this...  https://github.com/garris/BackstopJS/issues/669

**Comment by garris** [comment]
BOOM.  FIXED!

v3.1.17 just built itself.   

Thanks again for reporting!

**Comment by iain17** [comment]
Let us close this issue @garris :-)
