### ISSUE TITLE
unable to create reference img when using clickSelector

### ISSUE THREAD

**Issue by ducle91** [garris/BackstopJS#675]
I have a page where I need to click on a button on a modal before taking a screenshot, but I'm not able to create reference img when I have something in the clickSelector property. However, when I leave the clickSelector empty I am able to create my reference img, but it is not the screen I want to take a screenshot. Any idea why this might occur? I'm using BackstopJS ver. 3.1.17.

**Comment by garris** [comment]
Backstop will wait for the selector.  If the selector is not found an error will be thrown.  Is that what is happening?

**Comment by ducle91** [comment]
The selector is there. After further inspection, I noticed on the modal (there are 2 buttons) one button is using the <button> element. The other button uses an <a> tag. If I used the <button> element for clickSelector in my backstop then it works, but if I tried and use <a> in the clickSelector then it doesn't. Both buttons function like it supposed to, except the button with <a> will redirect the user to another URL instead.

**Comment by garris** [comment]
I see.  So, this is a grey area for BackstopJS.  Page redirects like this aren't _really_ supported.  The main use-case is testing UI states -- changing the URL is essentially invalidating your current state and loading a new app state from scratch -- which is out of scope. If you want to visually test the next page then simply create a new scenario with the correct URL and just test it.

**Comment by ducle91** [comment]
Thanks for the prompt reply Garris! I have created a new scenario like you've mentioned above.
