### ISSUE TITLE
Font issues between environments

### ISSUE THREAD

**Issue by cactusa** [garris/BackstopJS#677]
Hi there,
I am experiencing issues where fonts mismatch slightly between environments. Running OSX locally and CentOS on a test env. When I generate the reference images in local and then run them on the test env backstop finds a diff in every snapshot where there are fonts in them.
I know this has been already discussed in other posts and it's very likely to be anti-aliasing or font smoothing setting somewhere, but I am seeing some additional weirdness going on.
If I go manually to our test env and inspect/compare the reference images (taken from my local) and the test images (taken from the test env) with my own eyes, there is absolutely no apparent difference, but at the same time backstop reports them as 1.6% different and creates a diff image. See images below.

Reference image:
![ref-img](https://user-images.githubusercontent.com/1981415/36305547-f1cbdd52-130b-11e8-82eb-efb5784bab6f.png)
Test image:
![test-img](https://user-images.githubusercontent.com/1981415/36305554-f69d252a-130b-11e8-92e8-83258f462952.png)
Diff image:
![diff-img](https://user-images.githubusercontent.com/1981415/36305560-f8b7be06-130b-11e8-9b06-e0049c82373a.png)

Any idea why is this happening @garris ?

**Comment by roma-glushko** [comment]
@cactusa what was wrong with your case? I seem to have the same issues
