### ISSUE TITLE
BackstopJS (Docker) will not run with backstop.config.js

### ISSUE THREAD

**Issue by cactusa** [garris/BackstopJS#679]
Hi there,
I have been trying to go around the issue of font rendering across operating systems by using the docker version of backstop, but I have and issue with using a non json version of the config file. If I use a regular backstop.json it all works as expected but if I try to pass a custom backstop.config.js it produces this error and I don't know what to do with it:

```
$ docker run --rm -v $(pwd):/src backstopjs/backstopjs test --config=backstop.config.js 
BackstopJS v3.1.15
Loading config:  /src/backstop.config.js 

COMMAND | Executing core for `test`
/usr/local/lib/node_modules/backstopjs/core/util/createBitmaps.js:52
  configJSON.paths.tempCompareConfigFileName = config.tempCompareConfigFileName;
                                             ^

TypeError: Cannot set property 'tempCompareConfigFileName' of undefined
    at decorateConfigForCapture (/usr/local/lib/node_modules/backstopjs/core/util/createBitmaps.js:52:46)
    at writeReferenceCreateConfig (/usr/local/lib/node_modules/backstopjs/core/util/createBitmaps.js:80:68)
    at module.exports (/usr/local/lib/node_modules/backstopjs/core/util/createBitmaps.js:195:10)
    at Object.execute (/usr/local/lib/node_modules/backstopjs/core/command/test.js:7:12)
    at Object.execute [as test] (/usr/local/lib/node_modules/backstopjs/core/command/index.js:52:49)
    at execute (/usr/local/lib/node_modules/backstopjs/core/command/index.js:102:31)
    at module.exports (/usr/local/lib/node_modules/backstopjs/core/runner.js:6:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/backstopjs/cli/index.js:45:3)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
```

Is this an existing drawback of using docker @garris ?

**Comment by garris** [comment]
Hmmm.  as far as I know this should not be a limitation of using docker.   Are you sure your JS config is formatted correctly?   Does that file work locally?

**Comment by cactusa** [comment]
Yes it works as expected locally.

**Comment by cactusa** [comment]
Just noticed that when I updated my npm package file to backstop v3.1.17 when I run the docker instance it still runs at v3.1.15 could that be a problem?

**Comment by cactusa** [comment]
I tried to make this work by using by using a backstop.json file and run just a fraction of the scenarios from the backstop.config.js file, just to see if that way it would just work, but unfortunately I experienced a different issue. When I run reference or test it only captures "not found" images for some reason. Why would this happen? Could it be because or certificate prompt, in which case is there a way to circumvent that with a flag or something?
I am at a loss here not sure what to do. Any suggestions @garris ?

**Comment by cactusa** [comment]
OK, it was not a certificate issue. The "not found" images were caused because chrome could not go to the address I was sending it to, because the address was actually to a local instance of my webapp which was also running in another docker container, so I had to add this option to the run command ```e.g. --add-host 'address:1.2.3.4' ``` in order for the backstop container to be aware of my webapp.
However another issue uncovered - now that I can actually do the "reference" and "test" commands I have observed that not every command run completes successfully. Roughly half of the command executions just hang and never complete. Any idea why? I did restart my docker just in case, but that did not help. How can I get some debug output from this?

**Comment by garris** [comment]
Thank you for posting your findings!   Unfortunately -- I am not an expert in the docker implementation -- so hopefully someone else can advise.   One thing I can recommend -- please make sure you are running v3.1.17 or latest -- as those have important bug fixes.

**Comment by cactusa** [comment]
@garris well as I was saying earlier the local backstop installation is v3.1.17 but when I run the docker commands it displays that it's running v3.1.15 and this is on a fresh install,  npm cache cleared. I'd guess it will happen for you as well.
I am installing backstop by default from npm, should I switch to using a direct github build address?

**Comment by cactusa** [comment]
Just tried reinstalling backstop from ``` git+ssh://git@github.com:garris/BackstopJS.git#v3.1.17 ``` , but yet again the docker backstop instance runs in v3.1.15
Does that happen for you as well @garris ?

**Comment by garris** [comment]
No.   My instance says v3.1.17

**Comment by iain17** [comment]
I'm using docker and using a config file like that which is working fine. The way your passing is correct aswell. Please post the .js file, by reading the first post it seems to be an error in that file.

**Comment by cactusa** [comment]
Sorry the version of backstop in the docker instance was not changing because of my own lack of knowledge in docker. That has been sorted now, I just need to delete the existing container when I update backstop from npm. I am now running v3.1.19 consistently.

However the hanging issue persists. Even if I log into the container with the provided debugging command and run the "reference" command its will intermittently just hang and not complete. I monitored the processes in that docker instance then I ran backstop and as expected a bunch of chrome processes appeared and most of them closed again almost immediately, but a few just remained open forever. This is what I get:
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND     
    1 root      20   0   20248   3212   2732 S   0.0  0.2   0:00.04 bash        
 1117 root      20   0   20248   2988   2696 S   0.0  0.1   0:00.02 bash        
 1122 root      20   0   21920   2320   1992 R   0.0  0.1   0:00.18 top         
 1687 root      20   0 1226124  51448  24688 S   0.0  2.5   0:00.92 node        
 1862 root      20   0  597420  82508  58824 S   0.0  4.0   0:00.27 chrome      
 1884 root      20   0    4392    704    620 S   0.0  0.0   0:00.00 cat         
 1885 root      20   0    4392    720    636 S   0.0  0.0   0:00.00 cat         
 1887 root      20   0  350692  40076  31860 S   0.0  2.0   0:00.01 chrome      
 1934 root      20   0  403824  46936  37968 S   0.0  2.3   0:00.03 chrome  
```
Shall I open up a new issue for this one @garris ?
Any ideas anyone?

**Comment by cactusa** [comment]
@iain17 Here it is:
```
module.exports = function (options) {
    'use strict';

    var styleguideFiles = [
        'patterns/section-1.html',
        'patterns/section-2.html',
        'patterns/section-3.html',
        'patterns/section-4.html',
        'patterns/section-5.html',
        'patterns/section-6.html',
        'patterns/section-7.html',
        'patterns/section-8.html',
        'patterns/section-9.html',
        'patterns/section-10.html',
        'patterns/section-11.html',
        'patterns/section-12.html',
        'patterns/section-13.html',
        'patterns/section-14.html',
        'patterns/section-15.html',
        'patterns/section-16.html',
        'patterns/section-17.html',
        'patterns/section-18.html',
        'patterns/section-100.html',

        'modules/section-1.html',
        'modules/section-2.html',
        'modules/section-3.html',
        'modules/section-4.html',
        'modules/section-5.html',
        'modules/section-6.html',
        'modules/section-7.html',
        'modules/section-8.html',
        'modules/section-9.html',
        'modules/section-10.html',
        'modules/section-11.html',
        'modules/section-12.html',
        'modules/section-13.html',
        'modules/section-14.html',
        'modules/section-15.html',
        'modules/section-16.html',
        'modules/section-17.html',
        'modules/section-18.html',
        'modules/section-19.html',
        'modules/section-20.html',
        'modules/section-21.html',
        'modules/section-22.html',
        'modules/section-23.html',
        'modules/section-24.html',

        'themes/section-1.html',
        'themes/section-2.html'
    ];

    var scenariosArray = [];

    for (var i=0; i<styleguideFiles.length; ++i) {
        scenariosArray.push(
            {
                'label': styleguideFiles[i].slice(0, -5).replace('/', '_'),
                'cookiePath': 'backstop_data/engine_scripts/cookies.json',
                'url': options.url + styleguideFiles[i],
                'referenceUrl': '',
                'readyEvent': '',
                'readySelector': '',
                'delay': 0,
                'hideSelectors': ['.js-phantomcss-hide'],
                'removeSelectors': [],
                'hoverSelector': '',
                'clickSelector': '',
                'postInteractionWait': '',
                'selectors': ['.js-phantomcss-capture'],
                'selectorExpansion': true,
                'misMatchThreshold': 0.1,
                'requireSameDimensions': true
            }
        );
    }

    var report = [];

    switch (options.env) {
        case 'development':
            report = ['browser'];
            break;
        case 'sit':
            report = ['CI'];
            break;
        default:
            report = [];
            break;
    }

    return {
        'id': 'Styleguide',
        'viewports': [
            {
                'label': 'jelly',
                'width': 320,
                'height': 480
            },
            {
                'label': 'custard',
                'width': 600,
                'height': 960
            },
            {
                'label': 'cream',
                'width': 1008,
                'height': 1920
            },
            {
                'label': 'sprinkles',
                'width': 1366,
                'height': 2048
            }
        ],
        'onBeforeScript': 'chromy/onBefore.js',
        'onReadyScript': 'chromy/onReady.js',
        'scenarios': scenariosArray,
        'paths': {
            'bitmaps_reference': 'tests/visual/backstop_data/bitmaps_reference',
            'bitmaps_test': 'tests/visual/backstop_data/bitmaps_test',
            'engine_scripts': 'tests/visual/backstop_data/engine_scripts',
            'html_report': 'tests/visual/backstop_data/html_report',
            'ci_report': 'tests/visual/backstop_data/ci_report'
        },
        'report': report,
        'engine': 'chrome',
        'engineFlags': [],
        'asyncCaptureLimit': 10,
        'asyncCompareLimit': 100,
        'debug': false,
        'debugWindow': false
    };
};
```
Yes it is parametarised, but even if I hardcode the "options" values it still does not work with docker, but works on the locally installed backstop ...

**Comment by cactusa** [comment]
@garris and @iain17 so I have been doing step by step changes to the default config to bring it closer to the config I want to use. I have managed to pinpoint the error happening when I change ```module.exports = {...};``` to ```module.exports = function () { return {...}; }``` which is something similar to what is done here: https://github.com/garris/BackstopJS/blob/master/examples/nodeIntegration/backstop.config.js

Another question - if I want to pass arguments to the config like I have done in the example in the previous post, how do I express that in a docker command (```docker run --rm -v $(pwd):/src backstopjs/backstopjs test --config=backstop.config.js```). Would it be something like: ```docker run --rm -v $(pwd):/src backstopjs/backstopjs test --config=backstop.config.js -options={...}```.
Is this at all possible?

**Comment by garris** [comment]
1.  Backstop expects an object back.  Can you do this?
```
module.exports = function (options) { return 'the options are ' + options } ('some options');
```
The other way to go about this is to include backstop into whatever script you're generating your data with.   Please see https://github.com/garris/BackstopJS#integration-options-local-install

2.  Please check Docker docs to find out how to pass parameters. My guess is that anything you pass with the `--argument=value` pattern will be parsable by minimist inside your backstop.config.js file.

**Comment by cactusa** [comment]
I have parked this one for a while, now getting back to it.
Couldn't make any of these options work. I am basically trying to make the config file take as value (option) the environment it's in so it can run the tests against the correct URL. Only feasible solution I can come up with is creating separate config files for the different environments and then use ```--config=``` to specify the config.
Oh I am also working with Grunt task runner. So I will have to use something like grunt-exec to execute the docker run command with all its options together with the config file name.

Does that seem like a sensible solution? It's not ideal, but I can't think of a better way. I don't know much about docker.

**Comment by cactusa** [comment]
I have finally managed to string things together from your last message. It does work as you have suggested. Thank you very much for your help @garris :D
