### ISSUE TITLE
Still seeing backstopjs hang at the end of a run with the newest release. (3.1.17)

### ISSUE THREAD

**Issue by cmachemer73** [garris/BackstopJS#681]
Trying to get it to work inside a bamboo build job, but it never exits out, so the build never finishes.  Seeing the same behavior locally.

       report | Test completed...
       report | 20 Passed
       report | 57 Failed
       report | Writing browser report
       report | Resources copied
       report | Copied configuration to: /Users/cmachemer/ourProject/backstop_data/desktop/html_report/config.js
       report | *** Mismatch errors found ***
      COMMAND | Command `report` ended with an error after [35.229s]
      COMMAND | Error: Mismatch errors found.
                    at /Users/cmachemer/ourProject/node_modules/backstopjs/core/command/report.js:113:17
                    at <anonymous>
      COMMAND | Command `test` ended with an error after [201.389s]
      COMMAND | Error: Mismatch errors found.
                    at /Users/cmachemer/ourProject/node_modules/backstopjs/core/command/report.js:113:17
                    at <anonymous>

**Comment by iain17** [comment]
That's very odd. Could you give us some more details on how you're calling the backstop test? Are you running it through npm, tell us what's inside ur package.json etc.

**Comment by cmachemer73** [comment]
Interestingly, it hangs locally, but I pushed the branch with the upgrade on it to our git, and bamboo built it, and it didn't hang.  So the fact that it hangs on my Mac laptop is mildly annoying, what's really important is that the builds finish, which they do.  So I'll close this ticket.  Thanks for responding.  Also we're running it using yarn, just fyi.
