### ISSUE TITLE
BackstopJS (Docker) will randomly hang during execution

### ISSUE THREAD

**Issue by cactusa** [garris/BackstopJS#682]
I have been experiencing this issue where a command such as reference or test would just hang an not complete execution when run in docker.
```
$backstop reference
BackstopJS v3.1.19
Loading config:  /src/backstop.json 

COMMAND | Executing core for `reference`
  clean | tests/visual/backstop_data/bitmaps_reference was cleaned.
createBitmaps | Selected 1 of 1 scenarios.
searching for 4 available ports.
These ports will be used: [9222,9223,9224,9225]
Starting Chromy: {"chromeFlags":["--disable-gpu","--force-device-scale-factor=1","--disable-infobars=true","--window-size=320,480"],"port":9222,"waitTimeout":30000,"visible":false}
CREATING NEW REFERENCE FILES
Cookie state restored with: [
  {
    "path": "/",
    "name": "yourCookieName",
    "value": "yourCookieValue",
    "expirationDate": 1798790400,
    "hostOnly": false,
    "httpOnly": false,
    "secure": false,
    "session": false,
    "sameSite": "no_restriction",
    "url": "https://.www.yourdomain.com"
  }
]
SCENARIO > patterns_section-1
Starting Chromy: {"chromeFlags":["--disable-gpu","--force-device-scale-factor=1","--disable-infobars=true","--window-size=600,960"],"port":9223,"waitTimeout":30000,"visible":false}
CREATING NEW REFERENCE FILES
Cookie state restored with: [
  {
    "path": "/",
    "name": "yourCookieName",
    "value": "yourCookieValue",
    "expirationDate": 1798790400,
    "hostOnly": false,
    "httpOnly": false,
    "secure": false,
    "session": false,
    "sameSite": "no_restriction",
    "url": "https://.www.yourdomain.com"
  }
]
SCENARIO > patterns_section-1
Starting Chromy: {"chromeFlags":["--disable-gpu","--force-device-scale-factor=1","--disable-infobars=true","--window-size=1008,1920"],"port":9224,"waitTimeout":30000,"visible":false}
CREATING NEW REFERENCE FILES
Cookie state restored with: [
  {
    "path": "/",
    "name": "yourCookieName",
    "value": "yourCookieValue",
    "expirationDate": 1798790400,
    "hostOnly": false,
    "httpOnly": false,
    "secure": false,
    "session": false,
    "sameSite": "no_restriction",
    "url": "https://.www.yourdomain.com"
  }
]
SCENARIO > patterns_section-1
Starting Chromy: {"chromeFlags":["--disable-gpu","--force-device-scale-factor=1","--disable-infobars=true","--window-size=1366,2048"],"port":9225,"waitTimeout":30000,"visible":false}
CREATING NEW REFERENCE FILES
Cookie state restored with: [
  {
    "path": "/",
    "name": "yourCookieName",
    "value": "yourCookieValue",
    "expirationDate": 1798790400,
    "hostOnly": false,
    "httpOnly": false,
    "secure": false,
    "session": false,
    "sameSite": "no_restriction",
    "url": "https://.www.yourdomain.com"
  }
]
SCENARIO > patterns_section-1
9224 Chrome v64 detected.
9225 Chrome v64 detected.
9223 Chrome v64 detected.
9222 Chrome v64 detected.
9224 INFO >  BackstopTools have been installed.
9222 INFO >  BackstopTools have been installed.
9223 INFO >  BackstopTools have been installed.
9225 INFO >  BackstopTools have been installed.
```
Even if I log into the container with the provided debugging command and run the "reference" command its will intermittently just hang and not complete. I monitored the processes in that docker instance then I ran backstop and as expected a bunch of chrome processes appeared and most of them closed again almost immediately, but a few just remained open forever. This is what I get:
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND     
    1 root      20   0   20248   3212   2732 S   0.0  0.2   0:00.04 bash        
 1117 root      20   0   20248   2988   2696 S   0.0  0.1   0:00.02 bash        
 1122 root      20   0   21920   2320   1992 R   0.0  0.1   0:00.18 top         
 1687 root      20   0 1226124  51448  24688 S   0.0  2.5   0:00.92 node        
 1862 root      20   0  597420  82508  58824 S   0.0  4.0   0:00.27 chrome      
 1884 root      20   0    4392    704    620 S   0.0  0.0   0:00.00 cat         
 1885 root      20   0    4392    720    636 S   0.0  0.0   0:00.00 cat         
 1887 root      20   0  350692  40076  31860 S   0.0  2.0   0:00.01 chrome      
 1934 root      20   0  403824  46936  37968 S   0.0  2.3   0:00.03 chrome  
```

Does this happen for anyone else?

**Comment by cactusa** [comment]
@garris @iain17 sorry to be such an annoyance, but do you guys have any input into this?
Have been trying to make this work for weeks now and I am on my way to give up.

**Comment by garris** [comment]
@cactusa I am sorry -- I don't really know enough about the docker environment to help you here.  If chrome processes close right away it could be a network or authentication problem or there could be an exception which causes chrome to actually crash (and become a zombie).    Other users have discovered lack of ENV memory causes unexpected behavior as well.  see https://github.com/garris/BackstopJS#issues-with-chrome-headless-in-docker

If it were me -- I would try to simplify as much as possible to troubleshoot.   Use a default configuration (using `backstop init`), make sure that works first.   Then modify `backstop.json`  change name to `backstop.js` and add the necessary export declaration to ensure that simple .js files are working.   (here is an example of a working .js file https://github.com/garris/BackstopJS/blob/master/test/configs/backstop_features.js -- for example only -- yours should be much simpler).  

If you can get to this point successfully it means that there could be something wrong with your configuration script.

If you can figure it out please post back here.  

Best wishes.

**Comment by cactusa** [comment]
@garris Thanks for your response.
I think I might have explained it in an ambiguous way. When backstop is executed we do expect chrome processes to be started when a snapshot of the page is taken very quickly and then the chrome process is closed - all this should happen within a second and this is the expected behaviour. The odd behaviour is that some of the chrome processes just stay on forever. This issue happens intermittently, so it could be a memory thing - will investigate that.

Concerning the other issue #679 I have posted my config.js file in the other issue for you guys to have a look. I have already been trying what you suggested with the config file, that is how I discovered the issue of hanging in docker. Will continue on this path as you suggested to find out what I've done wrong. But I'm still dubious how would my config file work without a problem on locally installed bacstop, but not work with docker... will try again tomorrow.

Thanks again.

**Comment by garris** [comment]
Yes.  these are good points.   One thing I am suspecting, there are some relative paths in your config -- could there be a directory mapping issue there?   Again, my docker experience is very limited -- so I don't really know if this is an issue -- just a guess.   Good luck!

**Comment by cactusa** [comment]
Yup the hang was totally cause by this memory issue, thanks for that. I guess it's my fault for not reading the readme properly ...
