### ISSUE TITLE
Webpack in dependencies

### ISSUE THREAD

**Issue by wojtekmaj** [garris/BackstopJS#685]
Should webpack be defined as a dependency? It seems to me that backstop is using it internally for tool development. As I upgraded to Webpack 4, now two versions of Webpack are installed, one from my package.json and the other from backstopjs.

If it's necessary for the tool to run, perhaps consider defining a range of supported version instead of explicityl requiring one.

**Comment by garris** [comment]
Webpack is required as a runtime dependency.  Would be nice to know if webpack 4 is compatible with our implementation.

**Comment by wojtekmaj** [comment]
@garris,
in your case update should be pretty quick. Adding `mode` in [Webpack config](https://github.com/garris/BackstopJS/blob/master/compare/webpack.config.js) should be enough for you to make an upgrade to Webpack 4.x.
