### ISSUE TITLE
Show link on result page

### ISSUE THREAD

**Issue by matthiaskomarek** [garris/BackstopJS#687]
Hey @garris,

first i would like to thank you for this great tool.

It would be nice if there would be a link to the url of the scenario on the "BackstopJS Report" page, to quickly check whats the problem on the tested page. Maybe under the "Text info" panel.

I would like to create a PR for this, if you are interested in this feature.

Thanks

**Comment by garris** [comment]
Sounds good!

**Comment by matthiaskomarek** [comment]
Hey @garris i would kindly follow up on this issue. I have already created a PR, would be nice if you could take a look on this.
