### ISSUE TITLE
[Question]How to add cookie to cookie.json and which elements are required?

### ISSUE THREAD

**Issue by heaven1025** [garris/BackstopJS#688]
- env:
  - node: V8.9.4,  BackstopJS v3.1.19,  tomcat : 7.0.85
- test flow:
1. config tomcat-user , startup tomcat , listening port :8080, and service is working, tomcat-user can access tomcat example system;
2. execute "backstop  init" to generate test project and config backstop.json : 
`
{
    "id":"backstop_default",
    "viewports":[
        {
            "label":"tablet",
            "width":1024,
            "height":768
        }
    ],
    "onBeforeScript":"chromy/onBefore.js",
    "onReadyScript":"chromy/onReady.js",
    "scenarios":[
        {
            "label":"Tomcat Homepage",
            "cookiePath":"backstop_data/engine_scripts/cookies.json",
            "url":"http://localhost:8080/manager/status",
            "referenceUrl":"",
            "readyEvent":"",
            "readySelector":"",
            "delay":10,
            "hideSelectors":[

            ],
            "removeSelectors":[

            ],
            "hoverSelector":"",
            "clickSelector":"",
            "postInteractionWait":"",
            "selectors":[

            ],
            "selectorExpansion":true,
            "misMatchThreshold":0.1,
            "requireSameDimensions":true
        }
    ],
    "paths":{
        "bitmaps_reference":"backstop_data/bitmaps_reference",
        "bitmaps_test":"backstop_data/bitmaps_test",
        "engine_scripts":"backstop_data/engine_scripts",
        "html_report":"backstop_data/html_report",
        "ci_report":"backstop_data/ci_report"
    },
    "report":[
        "browser"
    ],
    "engine":"chrome",
    "engineFlags":[

    ],
    "asyncCaptureLimit":5,
    "asyncCompareLimit":50,
    "debug":true,
    "debugWindow":true
}

`

3. config cookie.json file : 
`

[
    {
        "domain":".127.0.0.1:8080",
        "path":"/",
        "name":"tomcat",
        "value":"tomcat",
        "expirationDate":1551261424,
        "hostOnly":false,
        "httpOnly":false,
        "secure":false,
        "session":false
    }
]

`
4. executed "backstop reference", and debugWindow notice to input tomcat-user and password.
![image](https://user-images.githubusercontent.com/20590402/36722347-4027e7fe-1be8-11e8-813b-89b56d989a9a.png)

5. change context of cookie.json to "SESSIONID" (copy from browser)
![jsessionid](https://user-images.githubusercontent.com/20590402/36722704-35b9d6b4-1be9-11e8-9ed9-a876471c5ad2.png)
![image](https://user-images.githubusercontent.com/20590402/36722739-5586cc9a-1be9-11e8-81ad-ab99db61a5f6.png)
![cookies](https://user-images.githubusercontent.com/20590402/36723541-845d0276-1beb-11e8-87aa-3951818a0a4a.png)

6. run "backstop reference" and notice authorization. but it works successfully in browser.
![image](https://user-images.githubusercontent.com/20590402/36722930-d9ada232-1be9-11e8-89e6-f5682793cb1f.png)

- my question:
1. how to set cookies in cookie.json file and what elements are required?
2. are the username and password fields which in cookie.json parts of page submit-form?
3. can backstopJS work with cookie-info generated by browser?

thanks~

**Comment by heaven1025** [comment]
today, I download the chrome-plugin recommended by author , Export cookie data from chrome and paste to cookie.json. 
`
[
  {
    "domain": "127.0.0.1",
    "hostOnly": true,
    "httpOnly": true,
    "name": "JSESSIONID",
    "path": "/manager",
    "sameSite": "no_restriction",
    "secure": false,
    "session": true,
    "storeId": "0",
    "value": "6F20B6A9DE53526B32DC20A5AAB90277",
    "id": 1
  }
]
`

then, execute "backstop reference" to generate reference bitmap, but it still notice to input username and password.....

please help me~

**Comment by Kenith** [comment]
@heaven1025 your cookies is right.
If you use chrome, try to find the backstop_data/chromy/loadCookies.js, replace the
`cookie.url = 'https://' + cookie.domain;` => `cookie.url = 'http://' + cookie.domain;`

Here is the full sample:
```
var fs = require('fs');

module.exports = function (chromy, scenario) {
  var cookies = [];
  var cookiePath = scenario.cookiePath;

  // READ COOKIES FROM FILE IF EXISTS
  if (fs.existsSync(cookiePath)) {
    cookies = JSON.parse(fs.readFileSync(cookiePath));
  }

  // MUNGE COOKIE DOMAIN FOR CHROMY USAGE
  cookies = cookies.map(cookie => {
    cookie.url = 'http://' + cookie.domain;
    delete cookie.domain;
    return cookie;
  });

  // SET COOKIES VIA CHROMY
  chromy.setCookie(cookies);
  console.log('Cookie state restored with:', JSON.stringify(cookies, null, 2));
};

```

**Comment by heaven1025** [comment]
@Kenith  thanks for help at first!! And it works successfully after changing "https" to "http" protocol.
Thanks very much~

 But I want to know reasons, is user authentication specified by the Chrome browser?

**Comment by heaven1025** [comment]
thanks @Kenith  again~, close question

**Comment by derting** [comment]
This will be a common problem, it is very easy to make mistakes without any prompts.
