### ISSUE TITLE
Backstop creates extended duplicate

### ISSUE THREAD

**Issue by ducle91** [garris/BackstopJS#690]
Hi Garris,

I was using the tool today to take a screenshot of a very long webpage. I noticed it half way thru the tool started taking screenshot from the top again and attach it to the bottom of the first part of the screenshot. So it took screenshot half way thru the page, then went back and started from the top and added the remaining to the first half of the screenshot. This webpage is very long, not sure how that would be handled.

**Comment by ducle91** [comment]
I found the same issue posted previously #604. someone suggested removing `disable-gpu` , but I'm not sure where to find the config for that.

**Comment by ducle91** [comment]
Even after I disabled the flag for gpu, it still wasn't able to capture the entire document and instead split it in two. Chromy limitation?

**Comment by garris** [comment]
There is a height limitation set by chrome-headless.   Please check Chromy lib — I think there is a tread about this.

**Comment by ducle91** [comment]
I found a work around, by switching to "engine": "casper" config it was able to capture the entire webpage. I found out the entire page is about 27k pixel in height , yikes!
