### ISSUE TITLE
Not really reliable results using engine Chromy

### ISSUE THREAD

**Issue by krisdigital** [garris/BackstopJS#696]
I have searched the issues and found many problems regarding zombie processes. Even if I stop all zombies, I have a failure rate between 10-30%, having 35 scenarios with three viewports each.
I digged into the code and logged out the errors saying

`Error: Invalid target undefined` in `chrome-remote-interface/lib/chrome.js` which seems to be related to ports already in use by another instance.

If I change the port assigning code so that the port is chosen short before Chromy is initialized like

```js
 const portfinder = require('portfinder');
  
  let port = await portfinder.getPortPromise();
  let defaultOptions = {
    chromeFlags: undefined,
    port: port,
    waitTimeout: TEST_TIMEOUT,
    visible: config.debugWindow || false
  };
```

I actually get no port errors or any other errors, but I still only got 97 of 105 screenshots. I also tried decreasing the concurrent processes to 5 or less, but I never got all screenshots.

Is anybody running a similar scenario with more success? I am using the newest version of everything.

**Comment by garris** [comment]
Please try a test with `asyncCaptureLimit: 0`

Does that run without errors?

**Comment by krisdigital** [comment]
@garris Thank's for the tip.  Already did the test with `asyncCaptureLimit: 0` and wondered, but it worked 😬 Got 100/105 screens, one waitTimeout and 4 goto timeout errors, all happening in the second half. I also noticed that with my port fix from above, different ports are used after a crash.

I will try to rule out my scenarios by screenshotting a different webpage.

So you say it is working reliable for you?

**Comment by krisdigital** [comment]
Update: With a concurrency of 10 and shooting google.com 105 times I still got 100/105 without any error messages. Not sure if chromy is not reporting the errors or there is just no BackstopException fired.

**Comment by Kenith** [comment]
you could refer to: https://github.com/garris/BackstopJS/issues/663
based on my expertise, set the asyncCaptureLimit=2 should be stable.

**Comment by garris** [comment]
Does #670 relate to your issue?

**Comment by garris** [comment]
Also, I noticed above you set `asyncCaptureLimit: 0`.  What are your results for `asyncCaptureLimit: 1`?

Also,  do not attempt to _test_ google.  Please troubleshoot with a simple local html page to start.

**Comment by krisdigital** [comment]
Thank's @Kenith and @garris! I did some more testing and noticed that for some sites it works flawlessly even with ten concurrent workers. With the setting `asyncCaptureLimit: 1` it works for all environments. So now I think that it does not have anything to do with backstop itself but maybe it is some flood/dos protection kicking in. I cannot say that the sites that are working with more processes are less complex and resources cannot be the issue. Will have to look deeper into it...

**Comment by krisdigital** [comment]
@garris I tried really hard but had all kinds of trouble, wrong window size, missing screenshots and what not. I integrated Puppeteer just to see if it improves things and it  [worked flawlessly right of the bat] (https://github.com/krisdigital/BackstopJS/commit/b4213d93cc482cd6789f341445571359ef177046) 💯 It is also much faster.

**Comment by garris** [comment]
@krisdigital HOLY CRAP -- that is awesome!  Thank you for starting a puppeteer fork!  I have cloned your fork and added it to MY BackstopJS repo so others can collaborate.   I have not tried it out yet but I am happy it's working for you.

Do you plan to do more work on this integration or should I solicit help from the community to bring it up to feature par with chromy?

**Comment by Kenith** [comment]
@krisdigital @garris Really good news!!!!!

**Comment by krisdigital** [comment]
@garris 😅Actually it was really easy so far and I could reuse many things, the only feature that is missing is screenshotting a selector different from `viewport` or `document`. As we are using it now I will make it stable so that it is a solid base for others to improve on. Do you think chromy and puppeteer should co-exist? Would be no big deal technically...

**Comment by garris** [comment]
@krisdigital that all sounds great.  We most definitely want to **ADD Puppeteer** _not replace Chromy_.  so we'll want to create a unique code path for Puppeteer starting with...
![image](https://user-images.githubusercontent.com/447033/37530412-b23fb694-28f6-11e8-99eb-cc7012cb281e.png)

I'll continue to track your fork on the puppeteer branch and let others know they should coordinate with you.  And please don't feel the need to contribute anything if you get too busy with other projects.  We don't want to deprive the world of great open source AU plugins! 😸

Please let me know if I can help in any way.  Cheers.

**Comment by krisdigital** [comment]
@garris All right, I will try to get the selector screenshots running and to make Puppeteer and Chromy coexist to get it to a 'near release' status! Thank's for the coordination and if you need a AU Plugin let me know

**Comment by cactusa** [comment]
@krisdigital great many thanks for your contribution kind sir. Can't wait to try it out myself!

**Comment by krisdigital** [comment]
@cactusa actually you can already try it, checkout the branch "puppeteer" in this repository..

**Comment by garris** [comment]
Just bumped to 3.2.0 and pushed to NPM!

You can...
```
npm install backstopjs@beta
```

**Comment by garris** [comment]
I am going to close this ticket and move to #704
