### ISSUE TITLE
Puppeteer support?

### ISSUE THREAD

**Issue by AkA84** [garris/BackstopJS#700]
Hello, is there any plan to support [puppeteer](https://github.com/GoogleChrome/puppeteer) in the future?

I'm trying to migrate a pretty big test suite from PhantomJS+CasperJS to Headless Chrome+Chromy, but I found that the latter's API is quite lacking compared to CasperJS's, and I'm at a point where I started to wonder if I can even complete the migration at all.

Puppeteer on the other hand seems to have a pretty comprehensive [api](https://github.com/GoogleChrome/puppeteer/blob/v1.1.0/docs/api.md), so I was wondering...

Thanks!

**Comment by garris** [comment]
I am totally supportive of adding a puppeteer engine option!  If you want to create a PR I would gladly review it.

That said, if you have any near term questions regarding Chromy -- you can post issues on the chromy page.

**Comment by garris** [comment]
boom!   Puppeteer is in development...

https://github.com/garris/BackstopJS/tree/puppeteer
cloned from...
https://github.com/krisdigital/BackstopJS/commit/b4213d93cc482cd6789f341445571359ef177046
