### ISSUE TITLE
are all CSS selectors that can be used in backstop.json file?

### ISSUE THREAD

**Issue by awongCM** [garris/BackstopJS#71]
For eg `+`, `>`, '~'.

I tried using these and I found none of them are actually working.

**Comment by garris** [comment]
This depends on phantomJS.  See http://phantomjs.org/

**Comment by YuliaTsareva** [comment]
@awongCM @garris Actually, such selectors should work. I tried to add `p.version+div`, `div>p.version` and `p~p` to example backstop.json and everything was OK.

@awongCM Can you show example of selector which doesn't work for you?

**Comment by awongCM** [comment]
Hi @YuliaTsareva,

Sorry for late reply.

There's a client site at work that I'm working on, and I'm struggling to get the correct css selector to get  screenshot by backstopjs cause it's html markup content looks unusual.  Due to the type of nature of work I'm doing, I rather not have this discussed this on a public forum such as this.  Can I send you a PM to discuss further?
