### ISSUE TITLE
enable large view for diffs

### ISSUE THREAD

**Issue by garris** [garris/BackstopJS#710]
A large page is hard to see -- would be nice to see that in item view.

Also, somehow the ref/test/scrubber radio buttons got borked.  Please fix!  🕉

**Comment by kiran-redhat** [comment]
this is true, seeing this from the time we got nw react component to show
the difference, It was very clear before

**Comment by garris** [comment]
Scrubber bit is fixed with v3.1.21

**Comment by matthiaskomarek** [comment]
@garris I would like to have the diff image in item view. What do you think about an extra button to show just the diff image? Scrubber will still switch between reference and test

![diff](https://user-images.githubusercontent.com/6169269/37997566-7c3db054-321b-11e8-947a-622f5b1bc8ae.png)

**Comment by garris** [comment]
@matthiaskomarek   Yes -- sounds great!  

Please note:   Currently, if you are in the list view and click a test image, the item view opens with `test` selected.  If you click a reference image then the item view opens with `reference`.  Would be great to keep this behavior consistent with the DIFF as well.

**Comment by matthiaskomarek** [comment]
@garris Good to know, thanks.

I will create a PR for this.

**Comment by ackmanx** [comment]
If I understand correctly, a DIFF button would open up just the diff image at full size (or fit-to-window)? Using 3.0.37 it's very easy to skim the report to see the differences on a large page, but with 3.1.21 the images appear to be zoomed out so it's impossible to see the diff on a scan down the report.

**Comment by matthiaskomarek** [comment]
@ackmanx It will open up the "detail view" (that thing when you now click on the test or reference image, images are full-size) and will show the Diff image

**Comment by mikkelrom** [comment]
Hi @matthiaskomarek - did you find time to look at this feature? I would love to have that as well :)

**Comment by matthiaskomarek** [comment]
Hey @mikkelrom i currently don't have any free time to solve this issue. You can work on this, if you want.

**Comment by garris** [comment]
:+1:

**Comment by mikkelrom** [comment]
Hey @matthiaskomarek and @garris - okay, I will try and see if I can find the time soon :)

**Comment by mikkelrom** [comment]
This is now published in beta 🎉

**Comment by garris** [comment]
@mikkelrom    Dude,  it’s in @latest!   Great feature.  Thank you!  😺

**Comment by mikkelrom** [comment]
Awesome @garris. 
I guess this issue can be closed, right?
