### ISSUE TITLE
[puppeteer engine] npm run smoke_test failures 

### ISSUE THREAD

**Issue by garris** [garris/BackstopJS#712]
About half of the tests are failing out.  

We can release once we can get this test stable.

**Comment by krisdigital** [comment]
@garris I think I fixed them? https://github.com/garris/BackstopJS/pull/713

**Comment by garris** [comment]
Ok.  Just tested this.  Almost there!

There are a few subtle cases which need handling.

1) selectors which exist but are hidden
2) selectors which don't exist

These are handled the same in phantom and chromy options.  Here is an example of the chromy handling...
![image](https://user-images.githubusercontent.com/447033/37883883-fd1d094c-3061-11e8-9121-845e98668d41.png)

This copies stub icons representing those states so that changes in selector visual states can be detected.  E.G.  reports look like this...

![image](https://user-images.githubusercontent.com/447033/37883946-59c5d7c8-3062-11e8-8eeb-9947ddabe4c0.png)

and...

![image](https://user-images.githubusercontent.com/447033/37883958-6b648cd6-3062-11e8-892e-cd02814da6a3.png)

**Comment by krisdigital** [comment]
@garris Aahhhh, now I remember seeing these images! Should be a small fix!

**Comment by garris** [comment]
Yeah.  I think the fix is pretty easy too.  Feel free to ping if you run into any difficulties — Cheers!

**Comment by garris** [comment]
@krisdigital If you are able to do it,  It would (probably) be cool to replace the existing error-mode images with these...

![selectornotfound](https://user-images.githubusercontent.com/447033/37927389-c6368466-30ee-11e8-8e0e-4881f0db72bf.png)

![selectornotvisible](https://user-images.githubusercontent.com/447033/37927394-c97667ae-30ee-11e8-8346-38e36127f21c.png)

![somethingunexpectedhappened](https://user-images.githubusercontent.com/447033/37927395-cbe26484-30ee-11e8-92bb-397aec03dd34.png)

No pressure/problem if you cant get to it.  I will update later if I get the chance.

Cheers!

**Comment by krisdigital** [comment]
@garris It should work now! The new images are way cooler 😎 https://github.com/garris/BackstopJS/pull/718

**Comment by garris** [comment]
Great Job!   Puppeteer branch is merged to master.
https://github.com/garris/BackstopJS/commit/72d0b0534927e8b4143991b4a2c7b11932833c8c

**Comment by krisdigital** [comment]
Wohoooooo!!
