### ISSUE TITLE
Bump Chromy version to 0.5.11

### ISSUE THREAD

**Issue by AkA84** [garris/BackstopJS#717]
Hello, would it be possible to bump the version of Chromy from 0.5.7 to 0.5.11? It contains a nice addition (see [here](https://github.com/OnetapInc/chromy/issues/20#issuecomment-372733450), and [here](https://github.com/OnetapInc/chromy/commit/a2fbfe88b8c749cb137fe33424f5561eb73a4af4)) that would be most useful to use in the engine scripts

**Comment by garris** [comment]
Looks good -- will do!

**Comment by garris** [comment]
Fixed by https://github.com/garris/BackstopJS/commit/72d0b0534927e8b4143991b4a2c7b11932833c8c
