### ISSUE TITLE
Scenario urls: Crawl a set list of pages behind a login

### ISSUE THREAD

**Issue by relhtml** [garris/BackstopJS#72]
Is it possible to have BackStop crawl a set of pages rather than having to handcode each individual scenario?

Here's the code that defines a scenario in BackStop:

  "scenarios": [
    {
      "label": "http://getbootstrap.com",
      "url": "http://getbootstrap.com",
      "hideSelectors": [],
      "removeSelectors": [
        "#carbonads-container"
      ],
   .....

Is it possible to pass in a function in place of a hardcoded url here? So for example:

  "scenarios": [
    {
      "label": "http://getbootstrap.com",
      "url": crawlSite(),
      "hideSelectors": [],
      "removeSelectors": [
        "#carbonads-container"
      ],

The crawlSite() function would be using click() functions to target links used in possibly CasperJS or PhantomJS as a means to crawl the site, where you would use either of those to initiate browser clicks to proceed to the next page in order to compare the reference screenshots. Additionally, the "gulp reference" command would have to crawl the entire site (using a custom PhantomJS/CasperJS script) to make the comparisons against. 

Any suggestions?

**Comment by garris** [comment]
Hi @relhtml -- this is a nice feature idea!  I recently received another request where a developer was hoping to assign a RexEx value to the url property -- which is also a good way to implement this.  Sadly, neither would work at the moment.  But... I think this would be an easy enough feature to create -- and the good news is that one would need very little knowledge of BackstopJS internals -- it can be done all through the config API.  

E.G.  Imagine *a new module* written in CasperJS which opens a root URL and walks all the links found on the returned HTML document.  Each link which changes a state or leads to a new URL is thrown into a *follow* array.  Then the process is started again for each url in the *follow* array until you have a humongous array containing all the child states and/or pages of a root URL.  (let's assume you can also add your own regEx or other filtering jig so only the urls you care about are kept).   The final step would be to generate and save a new backstop.json config file (built from your *follow* array).   You could either kick off a BackstopJS process right there or allow editing/fine tuning of the new JSON config document.   Extra points for saving that document to mongoDB or writing a UI around maintaining config files.

So, yes. Awesome idea. I am happy to support you or anyone interested in building such a thing!   If you built it standalone (e.g. output different config formats for various other testing or utility apps), it might be useful to others in completely different contexts.  

Please let me know how I can help.

**Comment by garris** [comment]
closed by #94
