### ISSUE TITLE
font rendering issues?

### ISSUE THREAD

**Issue by rossPatton** [garris/BackstopJS#73]
I'm curious to see if anyone else is having trouble getting fonts to render correctly in their screenshots.

I initially thought my problem was that I async everything (async typekit embed, loadCSS for everything else), so I added a readyEvent and a long delay. This appeared to fire correctly (as far as I can tell) but didn't fix the issue of fonts not rendering properly.

So as a test I went and made everything synchronous again. No loadCSS, and the default sync typekit script. Fonts still do not render properly.

Anyone else have this issue? Anything I might be doing wrong?

edit: actually, after more testing, it appears to not even render properly at all, like a significant chunk of the css isn't getting parsed

**Comment by garris** [comment]
This is a common issue with phantomJS.  Please see https://github.com/ariya/phantomjs/issues/10592 for possible workarounds / status of fixes / new version release.

**Comment by garris** [comment]
SlimerJS support added in latest release.
