### ISSUE TITLE
Invalid syntax in sanity test for Windows

### ISSUE THREAD

**Issue by pbb72** [garris/BackstopJS#730]
The sanity test command as displayed in the readme will never run on Windows. I am not an expert (haven't even managed to run Backstop yet) but I can see two clear problems:

* Windows uses `&` for multiple commands, not `;`.
* Just running a .js file won't work (at least it doesn't for me), you'll have to add `node` before it: `node node_modules/backstopjs/cli/index.js`.

**Comment by garris** [comment]
Thanks for reporting!   I just updated the readme.   

This worked for me in Powershell...
```
mkdir backstopSanityTest; cd backstopSanityTest; npm install backstopjs; node ./node_modules/backstopjs/cli/index.js test --config=node_modules/backstopjs/test/configs/backstop
```

**Comment by garris** [comment]
Please let me know if you have a better (more win-centric) suggestion.   Cheers.

**Comment by garris** [comment]
And also -- you'll want node LTS.  >=8.11.1

**Comment by pbb72** [comment]
You are completely correct. I was using regular Command Prompt, and I was using a very old version of Node!

By the way, the test does work fine also in Command Prompt if using `&`. My main mistake was the outdated Node.

**Comment by garris** [comment]
Thanks for the follow up.  Cheers!
