### ISSUE TITLE
Race condition in readyEvent

### ISSUE THREAD

**Issue by KenCoder** [garris/BackstopJS#739]
There is a race condition where if your code emits readyEvent too early, it won't be captured. This is because the log is captured only after the navigation starts, and indeed all navigation might have finished at that point. In Puppeteer at least, the log is already hooked before navigation starts using page.on, so why not use that rather than the backstopTools injector? I tried this and it's working much more reliably for me. I will submit a PR for fixing in puppeteer.

Likely this is behind #520, #674 and #542. 

What other engines are you supporting going forward? Is it worth trying to make this work in other engines?

**Comment by garris** [comment]
This has been merged to master.  Please reopen if there are any issues.
