### ISSUE TITLE
Ability to use Slimerjs?

### ISSUE THREAD

**Issue by jghazally** [garris/BackstopJS#74]
Is there a way to use slimerjs? in the casper options?

**Comment by jghazally** [comment]
sorry wrong window~

**Comment by garris** [comment]
In theory, yes. It would take some effort -- but it can probably be done.

**Comment by jghazally** [comment]
Yea thought it would be easy (I was trying to add `--engine=slimerjs` to the casperArgs variable in test.js but that didnt seem to work. If you have suggestions / can point me in the right directions I may have another crack at a pull request..

**Comment by garris** [comment]
Sure.   My first question would be, have you already successfully prototyped taking a screenshot with a plain implementation of casper.js using slimerjs?

**Comment by sillylogger** [comment]
I have, screenshots w/casper using slimerjs work fine.. If you have slimerjs installed on your system and in the path you can add `'--engine=slimerjs'` to https://github.com/garris/BackstopJS/blob/master/gulp/tasks/test.js#L48
and it'll run with slimerjs.  Works fine for me.  Would be nice for this to be an argument / option to backstop... when I get sometime :-)

**Comment by garris** [comment]
Hey Nice.  Will give this a shot.  Thanks!

**Comment by axe312ger** [comment]
Just tested it also. It works sooo nice! I love slimerjs!

Update your global casperjs and install slimerjs. Add ```--engine=slimerjs``` like @sillylogger mentioned and see it running :)

**Comment by garris** [comment]
Wooyeah, that was pretty nice.  

Does anyone know how slimerjs is with web fonts?   That's a pretty big issue with phantomjs ATM.

Also, any opinions on an { "engine": "slimerjs"} switch in the backstop.json config?  Seems that and some documentation would be a nice feature.  Yes?

**Comment by axe312ger** [comment]
Casperjs falls back to phantomjs when slimerjs is not available. So you might just add the parameter and tell the user in the readme that it is his decision which one to use.

I had a lot of troubles with flexbox. Slimerjs was a relief. Since slimerjs uses a more up to date gecko engine, there should be no problems with webfonts :)

**Comment by garris** [comment]
Slimerjs support is added in version 0.6.2 now in master along with updated documentation.   

Could someone please verify that this is working?  

Much appreciated!

**Comment by sillylogger** [comment]
Working just fine.. would be nice to get a test suite running for this project... maybe sometime this weekend.

**Comment by garris** [comment]
@sillylogger  Thanks for the confirmation!
