### ISSUE TITLE
Travis build passes even if unit tests fail

### ISSUE THREAD

**Issue by KenCoder** [garris/BackstopJS#750]
There are currently two unit tests in tests/cli, and one of them (usage_spec.js) is failing. But the travis build is succeeding. I investigated this, and for some reason mocha is return a 0 exit code even though a test is failing. If I test with only usage_spec.js, mocha correctly returns 1. 

I tried a few versions of mocha but couldn't find any that fixed it. 

Maybe I could try a switch to jest? We use it a lot and haven't had this kind of problem.

**Comment by garris** [comment]
Hi @kencoder,  thank you for the suggestion — I didn’t implement those particular tests, but I’ve worked with mocha a long time and would rather not switch at this time.  You can skip the test if that makes it easier. Potentially we are not even using that code anymore (the project is moving very very fast and things go out-of-date very quickly).  

That’s why I am more focused on e2e testing — the stuff you’re working on is much more important than unit tests.

So, yes, feel free to skip that failing one.

Thanks!

**Comment by gabegorelick** [comment]
This is still an issue, albeit different tests fail now (https://github.com/garris/BackstopJS/pull/872). 

The issue is the following code that causes the process to exit with code 0:
https://github.com/garris/BackstopJS/blob/master/cli/index.js#L37-L48
