### ISSUE TITLE
puppeteer:hideSelectors , few issues

### ISSUE THREAD

**Issue by vivekbwaj** [garris/BackstopJS#752]
Couple of issues here:
 "hideSelectors":["button[title='Greyhound']","div.cb-carousel"],
throws an error:
Puppeteer encountered an error while running scenario "My Homepage"
Error: Evaluation failed: SyntaxError: Unexpected identifier
+++
      "hideSelectors":["div.cb-carousel"],
works perfectly fine
++++++
      "hideSelectors":["div.cb-carousel","#logo"],
just hides the second selector

Definitely something wrong here, these work fine with casperjs/phantomjs

**Comment by vivekbwaj** [comment]
Sure,I will give it a go.But any insight on the second part
"hideSelectors":["div.cb-carousel","#logo"],
just hides the second selector
Multiple selectors not getting hidden.From the array, just the last one gets hidden

**Comment by garris** [comment]
Hmmm.  That may be an implementation bug in `runPuppet.js` -- might want to check here...
https://github.com/garris/BackstopJS/blob/master/core/util/runPuppet.js#L179-L197

**Comment by garris** [comment]
Ok, yes.  I just looked at this.   It’s a bug.   The assignment of the selector to window._backstopSelector Is out of sync with the operation.  This should be refactored.   Maybe added to backstop tools and run synchronous on the client (which would be faster) — or just sequenced correctly in this block.

Very good catch!  Thank you!

**Comment by garris** [comment]
Also this case should be added to backstop_feature tests.

**Comment by vivekbwaj** [comment]
Thanks @garris 
waiting for an update ;)

**Comment by vivekbwaj** [comment]
I am sure you wouldn't need but these might help
https://stackoverflow.com/questions/15368072/why-is-last-element-of-an-array-only-being-populated-for-onclick-in-javascript
https://stackoverflow.com/questions/7004619/javascript-only-sets-attribute-for-last-item-in-array

**Comment by vivekbwaj** [comment]
maybe try this way?
"hideSelectors":["button[title=\"Greyhound\"]","div.cb-carousel"],
it works but I think it should be in sync with the syntax when casperjs/phantomjs is used.For me it works fine without the \
