### ISSUE TITLE
How to capture element with generated ID like popover or tooltip

### ISSUE THREAD

**Issue by patriciamarchand** [garris/BackstopJS#757]
I'm trying to figure out how to capture a dynamic element with genereted ID. Like popover or tooltip.
I'm using Headless Chrome. I dont know how to target the selector

```
"hoverSelector": "#monTooltipLink",
  "postInteractionWait": 500,
  "selectors": [
    ".popover.tooltips" \\or #tooltip9811xx (never same number)
  ],
```

<a href="https://ibb.co/jWLgM7"><img src="https://preview.ibb.co/mCdCTn/SNAG_0016.png" alt="SNAG_0016" border="0"></a>

Thanks!

**Comment by garris** [comment]
Looks like there is a sibling which triggers DOM to be generated directly below.   
So you could probably do...
```
selectors: ["#monTooltipLink + .popover.tooltips"]
```
see here... https://developer.mozilla.org/en-US/docs/Web/CSS/Adjacent_sibling_selectors

**Comment by patriciamarchand** [comment]
I can access other selector with that technique but not this tooltip. maybe It's because it doesn't exist in the dom before hover?

**Comment by patriciamarchand** [comment]
I try  my test in a very light template with just Jquery and Bootstrap. [https://codepen.io/simplementpatricia/pen/NMvZyW](url) 
I add in my test `wait('SELECTORNAME')`. I reach the timeout. 

Thanks for your input. I will just postphone this test.

```
if (clickSelector) {
    chromy
      .wait(clickSelector)
      .click(clickSelector)
      .wait('#monTooltipLink + .tooltip');
  }
```
