### ISSUE TITLE
When can I expect the latest changes in the npm module?

### ISSUE THREAD

**Issue by vivekbwaj** [garris/BackstopJS#758]
There have been few fixes lately, one of them being [752](https://github.com/garris/BackstopJS/issues/752)
The npm package doesn't reflect the changes

**Comment by garris** [comment]
Many apologies.   I will publish this batch to NPM on (or before) 5/18.

**Comment by vivekbwaj** [comment]
Hi @garris just wondering if this can be done sooner. Many of our test fail due to this one

**Comment by garris** [comment]
Garris Shipon
Garris Shipon
 8:27 PM
Vivek, I have just pushed a new build to NPM. backstopjs@3.2.16

Please pull that and validate that it is working.

Cheers.

**Comment by vivekbwaj** [comment]
Thanks @garris .Works fine on update
