### ISSUE TITLE
BackstopJS git workflow

### ISSUE THREAD

**Issue by Skoks** [garris/BackstopJS#76]
Hello guys, 

Super cool and useful project :+1:

Can you share the most efficient way for adding `bitmaps_reference` folder in version control.

**Comment by garris** [comment]
There have been a few requests to make the location of `bitmaps_reference` configurable -- however it is only hardwired at the moment.   In this case you could copy that directory somewhere it would be picked up by your versioning system after running `gulp reference`.

**Comment by Skoks** [comment]
Gotcha, thanks
