### ISSUE TITLE
Need way to scroll container

### ISSUE THREAD

**Issue by aliu145** [garris/BackstopJS#765]
I am trying to use BackstopJS to do visual regression testing on a website which has a fixed divs on top and bottom of page, and a scroll-able container in the middle which contains the things I want to take screenshots of. I have tried chromy.scroll, chromy.scrollTo and chromy.screenshotSelector but I think these do not work because it just scrolls the whole window, rather than the container within. Does anyone have a suggestion for how to address this issue? The problem is that because the container is not scrolled, the capture of the image is partially blocked by the divs above/below the middle container.

**Comment by garris** [comment]
this works for me using the puppeteer engine.
```
// onReady script vvv
module.exports = async (page, scenario, vp) => {
    console.log("SCENARIO > " + scenario.label);
    await require("./clickAndHoverHelper")(page, scenario);

    const selector = "#someScrollabble";
    await page.waitFor(selector);
    await page.evaluate(selector => {
        document.querySelector(selector).scrollIntoView();
    }, selector);
};

```

**Comment by garris** [comment]
Oh -- it's pretty similar -- the main bit is 
```
document.querySelector("#someElementInAScrollableDiv").scrollIntoView();
```
so just do that in an evaluate.

**Comment by garris** [comment]
You can also add a waitFor also to ensure the element is there before you attempt the scroll.

**Comment by aliu145** [comment]
Thank you, that worked! :)

**Comment by aliu145** [comment]
@garris is there a way to integrate this into the backstop framework so that it will always scroll to element before taking screenshot, without having to use onReady script?

**Comment by garris** [comment]
Oh, sure. That might be nice.  You could build it into the helper that ships by default. 

Are you familiar with this file...
https://github.com/garris/BackstopJS/blob/master/capture/engine_scripts/chromy/clickAndHoverHelper.js

You could add a new prop called `scrollToSelector`  and then add the wait and scroll bit before the hover and click blocks.

We would want that for puppeteer as well.

And you could add the new prop to the docs.

Would be great if you can get to it.  Cheers

**Comment by garris** [comment]
Yes.

**Comment by aliu145** [comment]
Is there any way to do it so that it doesn't require defining a separate selector at all, but that it will always scroll to the selector it's taking screenshot of before taking screenshot (i.e. using that same defined selector for screenshot as the one for scrolling to). Or would it not be preferable to do that way?

**Comment by garris** [comment]
Can you share your config file and some screenshots of what you are running into?   I would need to understand your use case better to give you a good answer.

**Comment by aliu145** [comment]
Well, I guess that would require modifying Backstop framework, can't just implement in my own config/framework, so let me know what you think. If you think it's better to just implement in clickAndHoverHelper, I could do that too! Thanks

**Comment by garris** [comment]
For this scenario, what is your `selectors` value?

**Comment by aliu145** [comment]
In this case, the `selectors` value is a div that's "below the line" i.e. that needs to be scrolled into view

**Comment by garris** [comment]
What happens if you don’t scroll in this case?  Do you get a completely blank screenshot?  An error?  An all white screenshot?

**Comment by aliu145** [comment]
So, for a selector which is partially visible it looks like this (the black part is from the "frozen" bottom div):

![image](https://user-images.githubusercontent.com/11867181/39949843-621c2504-5532-11e8-8c0e-8483a3a78767.png)

For a selector which is even lower down the page it just shows all white screenshot:

![image](https://user-images.githubusercontent.com/11867181/39949857-6fe9d6d6-5532-11e8-90de-0bff220f9d47.png)

**Comment by garris** [comment]
Ok.  Thank you for testing that.   

I do see that it makes sense to auto-scroll in your case — but,  I don’t think this makes sense in all cases.  So, I don’t think we should “auto-scroll” child elements.  However, adding a convienience method for this behavior makes it very easy for anyone who needs it.   If you can do it I am sure it would create developer happiness— so I hope you will consider adding the feature.

**Comment by aliu145** [comment]
@garris, that makes sense! I cloned this backstopjs repo, created a local branch and made the changes, but running into issues when trying to push... should I be doing something differently? this is my first time trying to make changes on a github repo

![image](https://user-images.githubusercontent.com/11867181/40026092-c6fbff5a-5788-11e8-989b-b5b695f642db.png)

**Comment by garris** [comment]
That’s great — thanks for implementing!   So, please make a pull request.  Go to the “code” tab on your github repository for your backstop fork.

Just above the repo contents list on the left you’ll ring the create pull request button.   Click that and follow the instructions.  Then we’ll start the review process. Cheers. 🙂

**Comment by aliu145** [comment]
@garris No problem! Pull request has been opened here: https://github.com/garris/BackstopJS/pull/774. Closing this issue, thanks for all your help!
