### ISSUE TITLE
Failed to download Chromium r555668

### ISSUE THREAD

**Issue by tyler36** [garris/BackstopJS#767]
I went to upgrade BackstopJS from ```3.1.21``` to ```3.2.16``` but am getting errors.
```
ERROR: Failed to download Chromium r555668! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ Error: self signed certificate in certificate chain
```

At this point, it seems to be an issue with NPM & Yarn although I could be wrong. It's preventing me from using puppeteer so I thought I'd see if there is a current solution.

I've tried multiple versions of NPM (```5.7.1```, ```5.8.0```), and Yarn (```1.5.1```,  ```1.6.0```) but without success.

I've tried turning off SSL with
```
yarn config set strict-ssl false
```
 ... but that didn't work.

Is there a page that will let me manually download it? And if so, which files are needed and where? 

OS:  ```Win10 x64```
NPM: ```5.7.1```, ```5.8.0```
YARN: ```1.5.1```,  ```1.6.0```

**Comment by tyler36** [comment]
OK ... seems binaries can be manually downloaded here

```
https://storage.googleapis.com/chromium-browser-snapshots/Win_x64/%VERSION%/chrome-win32.zip
``` where %VERSION% => 555668

**Comment by tyler36** [comment]
Managed to get it upgrade with a workaround script
```
cross-env NODE_TLS_REJECT_UNAUTHORIZED=0 yarn upgrade backstopjs
```

Not really a solution but ...

**Comment by garris** [comment]
Is this an issue for all windows users?

**Comment by aliu145** [comment]
I am running into this issue too (on windows).. @tyler36 , I downloaded the file you linked and copied into node_modules folder but I'm still running into same error. was there something else you had to do?

**Comment by tyler36** [comment]
@aliu145, no. I wasn't sure what to do it with. 
I went with temporarily adding a new script command in my ```package.json```

```
    "scripts": {
...
        "bypass": "cross-env NODE_TLS_REJECT_UNAUTHORIZED=0 yarn upgrade backstopjs",
...
```

Running this command, allowed me to install it. Then I removed the command since ```NODE_TLS_REJECT_UNAUTHORIZED=0 ``` basically turns off protection.

* Note, I have ```cross-env``` installed globally, so you will need to install it if you don't have it already.

**Comment by garris** [comment]
Is this an issue with puppeteer’s install or with backstop?

**Comment by aliu145** [comment]
Hmm I am able to directly install puppeteer into a different directory:

![image](https://user-images.githubusercontent.com/11867181/40261266-78b81822-5ab4-11e8-9b7d-e3e708765159.png)

So perhaps it's an issue with backstop?

**Comment by garris** [comment]
Ok let me try.

**Comment by garris** [comment]
Ok.   I just successfully ran the backstopjs sanity test from scratch on windows 10...

From the docs...
![image](https://user-images.githubusercontent.com/447033/40262432-1bef191c-5abc-11e8-81f6-f0678578874c.png)


It installed backstop on the desktop and ran in win10 without issues...
<img width="1421" alt="screen shot 2018-05-18 at 4 51 28 pm" src="https://user-images.githubusercontent.com/447033/40262447-35d9e046-5abc-11e8-90ed-e557812d84e6.png">


QUESTION:   Are you guys on **node version 8** or above?

**Comment by tyler36** [comment]
```
node -v
v9.11.1
```

**Comment by garris** [comment]
Did you try running the backstop sanity test script from the troubleshooting section of the docs?

**Comment by tyler36** [comment]
Just ran sanity check in PowerShell (```5.1.17134.48```)
```
...
Writing location.js file
Done. Phantomjs binary available at I:\temp\backstopSanityTest\node_modules\phantomjs-prebuilt\lib\phantom\bin\phantomjs.exe

> puppeteer@1.4.0 install I:\temp\backstopSanityTest\node_modules\puppeteer
> node install.js

ERROR: Failed to download Chromium r555668! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1046:34)
    at TLSSocket.emit (events.js:180:13)
    at TLSSocket._finishInit (_tls_wrap.js:633:8) code: 'SELF_SIGNED_CERT_IN_CHAIN' }
npm WARN enoent ENOENT: no such file or directory, open 'I:\temp\backstopSanityTest\package.json'
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN backstopSanityTest No description
npm WARN backstopSanityTest No repository field.
npm WARN backstopSanityTest No README data
npm WARN backstopSanityTest No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@1.4.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@1.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\testuser\AppData\Roaming\npm-cache\_logs\2018-05-21T00_22_36_708Z-debug.log
internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module 'I:\temp\backstopSanityTest\node_modules\backstopjs\cli\index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
```

**Comment by tyler36** [comment]
In my case, I am unable install puppeteer via npm. So for me, it seems to be a _puppeteer issue_ and not a backstopjs issue.
```
λ  **npm install puppeteer**

> puppeteer@1.4.0 install I:\temp\pup\node_modules\puppeteer
> node install.js

ERROR: Failed to download Chromium r555668! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1046:34)
    at TLSSocket.emit (events.js:180:13)
    at TLSSocket._finishInit (_tls_wrap.js:633:8) code: 'SELF_SIGNED_CERT_IN_CHAIN' }
npm WARN enoent ENOENT: no such file or directory, open 'I:\temp\pup\package.json'
```

**Comment by cesar-bedoya** [comment]
Close your antivirus

**Comment by tyler36** [comment]
@cesar-bedoya
Thanks. With Kaspersky protection running, it fails. Disabled the software and it worked. 

I still think disabling security is not a solution but since the problem is with an external package ( Puppeteer) and the installed security suite, I suspect there's nothing @garris can do.

Thank you both for your time and help!
