### ISSUE TITLE
Can you pass config obj to onBeforeScript and onReadyScript from core run files?

### ISSUE THREAD

**Issue by webhamm** [garris/BackstopJS#769]
I need access to something in the `const config = args.config;` object that is used in runPuppet.js in the onBeforeScript and the onReadyScript script. Can I get access to the configs and I dont know it?

` await require(beforeScriptPath)(page, scenario, viewport, isReference, browser, config);`
https://github.com/garris/BackstopJS/blob/master/core/util/runPuppet.js#L108

If there is another way please tell me if this works for you I can submit a PR.

Thanks.

**Comment by garris** [comment]
Can you just require/import your config at this point?

**Comment by webhamm** [comment]
Looks like that will work fine 
`var config = require('../../../mini-sanity-backstop.json');`
  `if (config.setExtraHTTPHeaders) {`
     `await page.setExtraHTTPHeaders(config.setExtraHTTPHeaders); `
`}` 

Thanks..
