### ISSUE TITLE
Upgrade error

### ISSUE THREAD

**Issue by SheffBRC** [garris/BackstopJS#770]
Hello! I try update backstopjs to 3.2 version and  get next:

```
$ npm update  -g backstopjs
/usr/local/bin/backstop -> /usr/local/lib/node_modules/backstopjs/cli/index.js

> puppeteer@1.4.0 install /usr/local/lib/node_modules/backstopjs/node_modules/puppeteer
> node install.js

Downloading Chromium r555668 - 76.4 Mb [====================] 100% 0.0s 
Chromium downloaded to /usr/local/lib/node_modules/backstopjs/node_modules/puppeteer/.local-chromium/mac-555668
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.

+ backstopjs@3.2.16
added 15 packages from 12 contributors, removed 2 packages and updated 8 packages in 65.926s
Andrews-Mini:Cart Krawchuk$ backstop test
/usr/local/lib/node_modules/backstopjs/core/util/runPuppet.js:39
async function processScenarioView (scenario, variantOrScenarioLabelSafe, scenarioLabelSafe, viewport, config) {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/backstopjs/core/util/createBitmaps.js:10:17)
```

Also after updating of Canary elder version of backstopjs doesn't work.

**Comment by garris** [comment]
Upgrading to node 8+ will fix the issue.

**Comment by SheffBRC** [comment]
@garris Thank you for help! I have updated backstopjs successfully.

But I've problem with working of application. I had similar problem in past - https://github.com/garris/BackstopJS/issues/670

Adding of this parameter - "asyncCaptureLimit": 2, to json file helped me. This did not fully resolved the problem. But tests worked really more stable.

I have similar problem now. 
![image](https://user-images.githubusercontent.com/15000715/40048236-634099d2-583a-11e8-92e4-419f516191cb.png)

I try run test. Test goes to "9223 INFO >  BackstopTools have been installed." and stop his work. Nothing happens after this. And Google Chrome stays in system processes.

Maybe you can help me. I would be very grateful!

**Comment by garris** [comment]
If your tests are crashing then you may want to try using the puppeteer engine instead of Chromy.  It is much more stable.

**Comment by SheffBRC** [comment]
Thank's. I'll try

**Comment by SheffBRC** [comment]
Bug depend on hardware. Bug was at mac mini 2014 with HDD
![image](https://user-images.githubusercontent.com/15000715/40235636-8bb87968-5ab3-11e8-8a63-47723fcec650.png)

There are no problems at MacBook with I5 2.3 Ghz, 8 Gb RAM and SSD
