### ISSUE TITLE
Should the reference images be committed on the repo?

### ISSUE THREAD

**Issue by vitto** [garris/BackstopJS#78]
Hoping to write this question in the right place:

I'm trying to work with BackstopJS and understanding how it should be used at it's best without misunderstood some point of the regression testing workflow.

I've installed BacktopJS, made some test to see if it's working and it works nice.

Now I'm on a team of back-end developers which can make front-end changes and I would learn if I should commit on the repo the reference images or I need to keep tests green.

In my project I basically add 1 HTML template every day, so I'm supposed to create a reference of images every day.

My doubt is: what about old images, are them deleted and generated again?

In that case how can I ensure I don't loose old valid template image references?

I'm not sure about this point of the testing workflow and how I should handle old reference images.

**Comment by garris** [comment]
Hi @vitto, thanks for posting, and yes, this is a good place to ask questions.

There is a feature in development which will save the reference images in parallel with the backstop.json file or allow you to specify where you want the files saved.  When this is completed, you would be able to easily commit those images with the rest of your source files and not have to worry about clobbering the reference files when re-installing. 

This will be in the next release. In the meantime, after running `gulp reference`, you can manually export the files out of bitmaps_reference into some other (safe) location for your project.   Then can re-import back if you reinstall BackstopJS.

The change I mentioned above will be in the next release.

Hope that helps answer your question.

Cheers, GS

**Comment by vitto** [comment]
Thank you for the reply!
bye
