### ISSUE TITLE
Prevent "Mismatch errors" to make my Jenkins build fail

### ISSUE THREAD

**Issue by rickdroce** [garris/BackstopJS#789]
Good morning!
First of all great job with BackstopJs, I've found it really easy to use and versatile.

I liked it so much that I decided to integrate an automated process to run regression tests with Jenkins.
I've adapted the backstop docker image in order to let Jenkins run the build inside that container.
The concept is that once Jenkins finishes running the tests, the whole build is uploaded on a web server, to show the report with all the screenshots/files ecc ecc

The problem I'm facing is that when a test fails (mismatch error) the error generated turns the Jenkins build red and prevent me to do further steps (like uploading the artefact on the web server to actually see what broke down)

I wasn't able to find anything about this, but at the moment integrating backstopjs with Jenkins doesn't give us a feedback that is more than good/broke.
Is there a way to make these errors "silent"? Allowing so, we could take advantage of the full potential of BackstopJs

**Comment by garris** [comment]
@rickdroce great to hear that you've integrated backstop+docker+jenkins!   We used to have a config property for `silentOnFail` but it was removed in Version 2.  I don't know Jenkins well -- but I thought you could ignore the result of any process?  I would try to check again and make sure you cant do this in your Jenkins config (or if your running a bash script you should be able to do this).

Alternatively you could add a `--silent` flag to backstop and switch the return value here...
https://github.com/garris/BackstopJS/blob/master/cli/index.js#L46 .

**Comment by rickdroce** [comment]
I'll definitely give it a try, I also saw the Jenkins guide you were working on, that will come handy!

I'll let you know how it goes,
thanks!

**Comment by rickdroce** [comment]
As you imagined I handled everything through Jenkins.
Here's what I've done:
- I run my tests script in a `catchError` so that I can keep the build result without blocking the build
- Then I run my other steps (like the `rsync` to my web server)
- At last, I echo the build result, so that it stays red when tests fail

Here's a code sample
```        
stage('run css regression tests') {
    steps {
        catchError {
            sh 'npm run regression'
        }
    }
}
stage('after test steps') {
    steps {
        ...
    }
}
stage('build result') {
    steps {
        echo currentBuild.result
    }
}
```

Thank you for the support :)
