### ISSUE TITLE
Accept YAML configuration

### ISSUE THREAD

**Issue by oadam** [garris/BackstopJS#79]
YAML has a [couple of advantages over JSON](http://stackoverflow.com/a/1729545/436792).

The main selling point for me is the ability to comment out most of my `viewports` when I want to use backstopjs for a quick sanity-check.

I think the best would be that the app works if there is a `backstop.yaml` file in lieu of a `backstop.json`.

It doesn't look like a big change. If nobody has time to allocate to this I might be able to create a pull-request someday.

**Comment by oadam** [comment]
Hi @garris,

What is your opinion on this ?
Do you think it's worth integrating YAML parsing into backstop or should I keep the YAML -> JSON conversion as a separate step in my build process ?

Thanks,
Olivier

**Comment by garris** [comment]
Hi Oliver, sorry for the delayed response.  I appreciate the suggestion, but I would rather see effort put into some rudimentary config manager (web UI to select named config) or config editor (web UI to parse and edit config file in place) as opposed going the yaml route.  The config file is touched in a few places and adding yaml support might be more time consuming than you and I would hope.

**Comment by oadam** [comment]
Sorry I was in vacation.
Your answer makes sense. I'll close this
Cheers,
