### ISSUE TITLE
"requireSameDimensions": false config option not functioning correctly

### ISSUE THREAD

**Issue by carlvdm** [garris/BackstopJS#794]
Hello, apologies if there is a similar question or it has been answered elsewhere, but I'm struggling to find an answer.

On one of the pages that I am comparing, I've removed dynamic elements via the backstop.json config file removeSelectors option, however am noticing that the size of the image is not reduced and that the images are just shoved upwards.

While this does allow for accurate comparison of the elements on the page (such as the aligned footers), and accurately comparing the elements indicating a misMatchPercentage of 0; unfortunately tests are still marked as failing due to the dimensions of the images being different.

I believe the intended solution for this was to have the test config option requireSameDimensions set to false, however this does not appear to be resolving the issue in my case.

See the following image showing the difference in height between the image:

![mismatch-error](https://user-images.githubusercontent.com/25169028/41098275-1dfbca12-6a5b-11e8-860a-bddc957da8ad.png)

I'm currently using BackstopJS version 2.6.4 on Ubuntu 16.04.4 LTS.

Thank you for your time.

**Comment by garris** [comment]
Can you try upgrading to the latest version of backstopjs?   Is that an option?

Also please share your config.

**Comment by carlvdm** [comment]
Updating to the latest version (BackstopJS v3.8.8) and adding the `"requireSameDimensions": false` 

option where applicable resolved the issue.

Many thanks for the help.
