### ISSUE TITLE
How to expect multiple selectors within single test?

### ISSUE THREAD

**Issue by cptwonton** [garris/BackstopJS#797]
I'm trying to test that a certain table has exactly 13 columns and exactly 18 rows.
i'm using puppeteer and would like to know if:
- is there a way to assert values in a puppeteer script, and to fail a test if the assertion is false?
- is there a way to assert values in backstop (like selectors: .... expect: ) but with multiple selectors and multiple expected values, one for each selector in selectors?

**Comment by garris** [comment]
1) no -- although it would be very cool if the external script returned an error message then the corresponding scenario would fail.   Would be happy to approve that PR.

2) Why not just take a screenshot of your table.  If the number of rows and columns change the test would fail.   Right?

**Comment by cptwonton** [comment]
the table is in a modal. and although i've scoped the screenshot to just that modal's CSS selector using selectors:... since there are scrollbars to scroll thru the table, I've found one extra row won't cause backstop to pick up a diff. even if I included the scrollwheel in the screenshot (it's not included currently), i'm not sure even a 0.1% threshold will pick up on that.

**Comment by garris** [comment]
Backstop is a screenshot capturing and comparing machine.  So, you are a lil' bit barking up the wrong tree with this puppeteer-dom-selecting business.    But... thinking visually it is very easy to do -- and there are a few way to do it.  One way would be to just use the `selectors` property to scope down your screenshot like so.
```
selectors: ["tbody tr:nth-child(18)"], 
```
That would tell backstop to take a screenshot of just the 18th row.  So if your `reference` run has some content in there and your `test` run doesn't even have the selector your test will fail.

Is that workable for your use case?

**Comment by cptwonton** [comment]
aha! yes, that will do.
