### ISSUE TITLE
Is it possible to see old report comparisons or even archive them

### ISSUE THREAD

**Issue by aixellent** [garris/BackstopJS#80]
Hi i want to use backstopJS for company development use and i am interested in some tasks which are partially answered here.

At first i think i would be good if the folders for bitmap references and tests can be directed to a user customized folder in the customer-project-folder with using a "config.json" in which the directory of the backstop.json file for defining tests can be set too. I hope this will be possible soon because this would be a high benefit for the tool.

But my question now is, is it possible to see older testruns for archiving development process and track bugsources better.
I think this now is not possible because TEST always compares the newest references with the actual taken snapshots of the webpages. In normal cases this is totally okay, but for comparing old testruns there maybe an archive folder needed which snapshots the actual references and the actual taken test_pictures for comparing them in the future. Maybe with showing a list of ran tests on the index page of the tool when starting REPORT?

If i can help you here just tell me how.

Thanks and regards

**Comment by garris** [comment]
@aixellent Thank you for posting.  I will be adding the ability to change the location of the reference and test files within the next week.   Would you be interested in beta testing the new version?

**Comment by aixellent** [comment]
For sure I am, as I said I am just trying to automatically test new
implementations of our gui and verify them to different resolutions.
Tracking would be very great benefit.
Thanks for this tool

Garris <notifications@github.com> schrieb am Do., 30. Juli 2015 18:51:

**Comment by garris** [comment]
The new version: 0.6.0 Beta is available.  

[go here to install...](https://github.com/garris/BackstopJS#version-060-beta-available-now)

**Comment by aixellent** [comment]
Hi and thanks i will have a look on this, i totally missed it up to now because i had to handle a lot of CasperJS tests in our company.
Thanks in advice

**Comment by kamlesh-astech** [comment]
Sir, Now does this beta version works in archieving the references, or is still under development.
