### ISSUE TITLE
Testing invisible elements should not result in a screenshot of the whole page

### ISSUE THREAD

**Issue by axe312ger** [garris/BackstopJS#81]
One of my selectors defines an element, which is not visible for smaller viewports. BackstopJS accidentally now takes a screenshot of the whole page.

I think it should just do not create a screenshot, what do you think?

**Comment by garris** [comment]
Agree.  Are you using slimerjs?

**Comment by axe312ger** [comment]
Yes I am :)

**Comment by axe312ger** [comment]
When the element does not exist at all, backstopjs takes (correctly) no screenshot of it. But this breaks the report server, it does not run through.

Can you catch that case?
When one or more files for the comparision are not available, set test to a new "error" mode and display some kind of message: "files missing". Also a timeout would be nice, 30 sec for example. Even the possibility to run 2 or more tests parallel would help here (at least a bit) :)

**Comment by garris** [comment]
In the first post you have an issue with an existing but *display: none* DOM element. I guess in a perfect world I would want a png file with zero pixels as the output from the rendering engine.  And I would expect BackstopJS to tell me that this element exists but is not in the layout flow.

I think there is a difference between how PhantomJS and SlimerJS handle these conditions.  It would be nice to know if this is true.  Regardless, it sounds like we may need to test all elements for a `display:none` condition and correctly report this to the user.  (Perhaps we actually create an image file with zero pixels to represent this condition in all cases).

Before taking a screenshot (line 161 in genBitmaps.js) we would get the `display:none` state of the element if true write our own file which would evaluate correctly in the test.

I think the same would go for your second issue.

**Comment by garris** [comment]
More thoughts here:

For display:none cases we should write a PNG file with a no-display icon.  e.g. Glasses with diagonal line / strike through.

For missing element, maybe a droptag with a horizontal line / strike through.

This will keep output in sync with the config files and correctly report on visual state changes with No changes to our report code.

**Comment by axe312ger** [comment]
Sounds like a good plan. Also keeps the changes minimal. Everything else might end up in a (in)complete rewrite of a lot of code :+1:

**Comment by garris** [comment]
moved to #97
