### ISSUE TITLE
BackstopJS's result comparision does currently not work [with workaround]

### ISSUE THREAD

**Issue by axe312ger** [garris/BackstopJS#82]
I was just wondering why the tests do not fail, since I made major changes in the stylesheets.

It uses a copy of the references to compare them with the references. Yes, that makes no sence. We may just remove that useless copy and tell angular to compare the jpegs from within the subfolders?
I did not look into the code in detail, just doing some assumptions)

Workaround: Just go into your test folder and remove all JPEG files. You'll find a folder for every test you did, just copy the files from the most current ones in the test folder.

**Comment by garris** [comment]
What version are you running?

**Comment by axe312ger** [comment]
I am currently on 8a40bdadaf3631fc86c6d623bc0ed7c82cd42b86 but have to admit that my backstop.json is lacking the ```config.paths``` array

**Comment by garris** [comment]
Ok. Then you have found a bug.  I added a compatibility feature.  Config files without a paths node are handled differently.  Sounds like the cp function is failing.  Perhaps missing an overwrite flag.   I will take a look at this now.   Thank you for finding this!

**Comment by axe312ger** [comment]
:+1:

**Comment by garris** [comment]
fix pushed to master.  Please verify...  thanks!

**Comment by garris** [comment]
ok, found another issue.   still working on it.

**Comment by garris** [comment]
Ok.  Please verify.   Thank you.   -GS

**Comment by axe312ger** [comment]
Nope sorry, still looks like the server is not serving the correct files.

What i found also:
It looks like the slugging for the filenames does not work as expected. Selectors like “body > div.foo” do not work. The files are not slugged correctly and angular requests wrong urls.

I’d go for the slug node lib, otherwise these regex help for me at the moment: https://github.com/axe312ger/BackstopJS/commit/ecb57a5b0dc0186d3f6e9509d7253f29551271fd <https://github.com/axe312ger/BackstopJS/commit/ecb57a5b0dc0186d3f6e9509d7253f29551271fd>

**Comment by garris** [comment]
I just retested the patch and it seems to work over here -- both with and without a path node.   This is the latest 8de6847 -- could you maybe pull into a fresh repo and see if you can duplicate the issue?

**Comment by axe312ger** [comment]
Nice! Somehow I was on the wrong commit after merging yesterday night. It works. Thx!
