### ISSUE TITLE
Is it possible to use url as config path?

### ISSUE THREAD

**Issue by hugopeek** [garris/BackstopJS#823]
I'm generating my config files with a CMS, so it dynamically loads the desired scenarios.

Right now, it seems that the --config argument only accepts physical files, so I have to let the CMS generate those as well. No biggie, but it would be nice if the argument could read from the URL directly. Something like:

```
backstop test --config=url(http://project.loc/tests/backstop.json)
```

**Comment by garris** [comment]
You can’t point to a web file like that — but... you could write a simple node app that would grab and parse the file, then pass that into backstop.   See this section in the docs for some hits.  https://github.com/garris/BackstopJS/blob/master/README.md#integration-options-local-install

**Comment by hugopeek** [comment]
Thanks, that looks useful. Also the part of running it with gulp. Not so familiar yet with node, but I'll probably be able to figure this out.

Great project btw. Incredibly useful. Thanks a bunch! :)
