### ISSUE TITLE
DIFF button isn't showing in scrubber mode

### ISSUE THREAD

**Issue by swleighton** [garris/BackstopJS#824]
I've copied the same backstop.json file between two installations (both running 3.5.2) and run a test  but the DIFF scrubber button isn't shown on one installation. Only REFERENCE, TEST and SCRUBBER are shown. The diff image in the main reports are displaying correctly.

Looking at the output report code, it doesn't look like the method:
`_react2.default.createElement(
              ScrubberViewBtn,
              {
                selected: position === -1,
                onClick: function onClick() {
                  showScrubberDiffImage();
                }
              },
              'DIFF1'
            ),`

Is being output in the index_bundle.js Is there any config setting that could cause this?

Thanks!

**Comment by garris** [comment]
Are you sure hey are both rinning 3.5.2?   You can try deleting your html_report directory and rerunning the test.
