### ISSUE TITLE
Smarter image diffing

### ISSUE THREAD

**Issue by garris** [garris/BackstopJS#826]
## Background
It’s pretty common in web layouts for a content at the top of the view to grow in size and push the subsequent layout elements down (or across) in the flow direction.  This is normal and desired behavior.

## The problem
Backstop is currently testing screenshots on a pixel by pixel basis.  This results in behavior where backstop diffs are impossible to read if an element at the top of the flow changes size and pushes subsequent layout around — even just a little bit.

##  The ask
I’ve been looking for a JS-based differ that behaves more like this...
https://johnresig.com/projects/javascript-diff-algorithm/

Anyone know if this has been implemented for images in JS with an open source license?

If not,  I might have to lock myself in a basement while I figure out how to do it efficiently.

Thoughts and opinions welcome.

Thanks!

**Comment by garris** [comment]
Ok,  after googling for a while I am confident that this library doesn't exist publicly, in javascript.   That said, the sheer number of computer vision related hits in regards to this topic are stunning.   I will start with edge detection and start heading for the basement.  Cheers.

**Comment by garris** [comment]
I have emerged from the basement.  Behold the next big thing...

**Comment by mirzazeyrek** [comment]
@garris I never thought about the image comparison part but it's strange that I had a repository a bit similar to what you shared as javascript-diff-alghoritm. 

https://github.com/mirzazeyrek/php-get-string-similarities
