### ISSUE TITLE
Error: Failed to launch chrome! not fixed with "engineOptions": {     "args": ["--no-sandbox"] }

### ISSUE THREAD

**Issue by wlsf82** [garris/BackstopJS#827]
I am experimenting BackstopJS with Docker since I have already faced the issue that this meant to solve, but even configuring it as explained on step 1 [here](https://github.com/garris/BackstopJS#requirements-for-when-youre-using-docker) I still get the `Error: Failed to launch chrome!` error.

**Comment by garris** [comment]
Thank you very much for posting this.   It would be helpful to know if a vanilla config works on your machine.   Can you try creating a test directory somewhere,  `cd` into it and run `backstop init`?  Then try `backstop test`.  Then if that works try `backstop test --docker`?   If that works it may be something else in your config set up that might be causing an issue.   Please let me know if you discover anything — this feature is totally new so I am happy to help troubleshoot.   Cheers.

**Comment by wlsf82** [comment]
Well, I think the issue is on the website that I'm trying to run the tests because I tried on my website and it worked well, with and without docker. I think you can close the issue then.

**Comment by wlsf82** [comment]
The problem seems to be due to the application blocking access to itself when it identifies that the browser is headless. :/

**Comment by garris** [comment]
Working as designed! 😄

**Comment by garris** [comment]
Please feel free to reopen if anything else come up.
