### ISSUE TITLE
Blank Reference Images

### ISSUE THREAD

**Issue by yargalot** [garris/BackstopJS#83]
Yo,

Running through using the library on one of our projects, seems to be working pretty well but we are having issues with generating reference issues, it will generate images fine up until a point but then the images will be generated blank.

Screenshot is attached, any help would be greatly appreciated.

Thanks,
Steve 
<img width="1010" alt="screenshot 2015-08-24 15 20 33" src="https://cloud.githubusercontent.com/assets/790013/9433290/c23e03d4-4a73-11e5-94f8-f5e183af646a.png">

**Comment by garris** [comment]
@yargalot Are you certain that the elements exist at the time of the screen grab? Another issue could be the style properties, e.g. display:none, opacity:0?

**Comment by yargalot** [comment]
Yeh absolutely sure they exist since its getting the first few

**Comment by yargalot** [comment]
But let me double check, might be a viewport thing

**Comment by garris** [comment]
Yup, they may be set as display:none (or something like that) at certain screen sizes.  Let me know.

**Comment by yargalot** [comment]
Hah, yep your right, some Nufftie put overflow:hidden on the html element.  Thanks for the help! Much Appreciated!

**Comment by yargalot** [comment]
Oh thanks the library btw, works like a charm :+1:

**Comment by garris** [comment]
Great to hear!  Best.  -GS

**Comment by code-mattclaffey** [comment]
I am getting the same issue but I am using backstop@latest. 

![screen shot 2018-05-04 at 09 34 22](https://user-images.githubusercontent.com/10598938/39619010-1899ce4a-4f7e-11e8-9bba-2a619a34845e.png)

Here is my config:

```
{
  "id": "prod_test",
  "viewports": [
    {
      "name": "small",
      "width": 375,
      "height": 564
    },
    {
      "name": "tablet",
      "width": 768,
      "height": 1024
    },
    {
      "name": "desktop",
      "width": 1240,
      "height": 1024
    }
  ],
  "fileNameTemplate": "{selectorLabel} - {viewportLabel}",
  "scenarios": [
    {
      "label": "Hillarys Styleguide",
      "url": "https://hillarys.local.codecomputerlove.com/styleguide-new/",
      "referenceUrl": "https://www.dev.hillarys.hblonline.co.uk/styleguide-new/",
      "removeSelectors": [],
      "selectors": [
        ".gallery-grid",
        ".hero-text-strip",
        ".porthole-strip",
        ".hero-carousel",
        ".filter",
        ".cta-text-and-image-strip",
        ".multiple-article-picker",
        ".logo-strip",
        ".browse-by-colour",
        ".service-strip",
        ".product-listing",
        ".campaign-carousel",
        ".appointment-cta-strip",
        ".coloured-banner-strip",
        ".internal-page-cta-strip",
        ".sub-product-content-list",
        ".single-video"
      ],
      "delay": 6000,
      "misMatchThreshold": 6
    }
  ],
  "paths": {
    "bitmaps_reference": "backstop_data/bitmaps_reference",
    "bitmaps_test": "backstop_data/bitmaps_test",
    "casper_scripts": "backstop_data/casper_scripts",
    "html_report": "backstop_data/html_report",
    "ci_report": "backstop_data/ci_report"
  },
  "casperFlags": [
    "--ignore-ssl-errors=true",
    "--ssl-protocol=any"
  ],
  "engine": "puppeteer",
  "report": ["browser", "cli"]
}

```

I tried to set the delay to be longer but it didn't work. Is there a way to run tests when the url has fully loaded?

**Comment by code-mattclaffey** [comment]
Tested again with less selectors and some show, some don't.

![screen shot 2018-05-04 at 10 59 06](https://user-images.githubusercontent.com/10598938/39622385-ebd8fb18-4f89-11e8-9ec7-8e59e615725b.png)

**Comment by code-mattclaffey** [comment]
When I set `debugWindow: true` and then I run reference. ( get this error when the browser closes: 

`ERROR: The process with PID 15532 (child process of PID 18756) could not be terminated.
Reason: There is no running instance of the task.`

**Comment by garris** [comment]
Can you try switching to the puppeteer engine?  It runs much more consistently.

**Comment by lflpowell** [comment]
Getting a similar issue. Large number of blank references. Using puppeteer, my config is:

```
{
  "id": "Framework",
  "viewports": [
    {
      "label": "320x568",
      "width": 320,
      "height": 568
    },
    {
      "label": "768x1024",
      "width": 768,
      "height": 1024
    },
    {
      "name": "1024x768",
      "width": 1024,
      "height": 768
    },
    {
      "name": "1280x1024",
      "width": 1280,
      "height": 1024
    }
  ],

  "scenarios": [
    {
      "label": "Framework Buttons",
      "url": "https://standards.aviva.com/framework/element-library/v3/page-components/button/",
      "referenceUrl": "https://standards.aviva.com/framework/element-library/v3/page-components/button/",
      "readyEvent": "",
      "readySelector": "",
      "delay": 1000,
      "hideSelectors": [],
      "removeSelectors": ["#tab-2 .awf-example"],
      "hoverSelectors": [],
      "clickSelectors": "",
      "postInteractionWait": 5000,
      "selectors": [".awf-example"],
      "selectorExpansion": true,
      "misMatchThreshold": 0.1,
      "requireSameDimensions": true
    }
  ],
  "paths": {
    "bitmaps_reference": "backstop_data/bitmaps_reference",
    "bitmaps_test": "backstop_data/bitmaps_test",
    "engine_scripts": "backstop_data/engine_scripts",
    "html_report": "backstop_data/html_report",
    "ci_report": "backstop_data/ci_report"
  },
  "report": ["browser"],
  "engine": "puppeteer",
  "engineOptions": {
    "ignoreHTTPSErrors": true,
    "slowMo": 500,
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-gpu",
      "--force-device-scale-factor=1",
      "--disable-infobars=true",
      "--hide-scrollbars"
    ]
  },
  "asyncCaptureLimit": 5,
  "asyncCompareLimit": 50,
  "debug": false,
  "debugWindow": false
}
```

Endpoint is publicly available, so wonder if anyone else can reproduce the issue I'm getting.

**Comment by elisexu** [comment]
I can reproduce this issue, and I get many more references when I decrease asyncCompareLimit. (In terms of this specific config file, the first time with asyncCompareLimit set to 50 I was able to generate 14/56 reference images, while the second time with asyncCompareLimit set to 5 I was able to generate 46/56 reference images.) I know a team that is experiencing the same issue, and they limited their asyncCompareLimit to 2, but sometimes there are still blank references generated.

**Comment by lflpowell** [comment]
@elisexu Thanks for confirming, and thanks for the hint on the asyncCompareLimit.
