### ISSUE TITLE
When running with --docker, getting firefox is not compatible with SlimerJS

### ISSUE THREAD

**Issue by edlefebvre** [garris/BackstopJS#830]
Using backstopjs with docker and slimerjs, I get this error:

`CasperJS:  Gecko error: it seems /usr/bin/firefox is not compatible with SlimerJS`

It is supposed to use the Firefox ESR form the docker image, right?

```
COMMAND | Executing core for "test"
Delegating command to Docker... docker run --rm -it --mount type=bind,source="$(pwd)",target=/src backstopjs/backstopjs reference --moby --configPath=tests/graphical/local/backstop.json
BackstopJS v3.5.2
Loading config:  /src/tests/graphical/local/backstop.json 

COMMAND | Executing core for "reference"
  clean | tests/graphical/local/backstop_data/bitmaps_reference was cleaned.
createBitmaps | Selected 5 of 5 scenarios.

Running CasperJS with:  [ '/usr/local/lib/node_modules/backstopjs/capture/genBitmaps.js',
  '--engine=slimerjs',
  '-P AllowSSL',
  '--headless',
  '--captureConfigFileName=/tmp/capture/7a184ad32c1530ec48156478829c0f9d3536dc68.json' ]
CasperJS:  Gecko error: it seems /usr/bin/firefox is not compatible with SlimerJS.
CasperJS: See Gecko version compatibility. If version is correct, launch slimerjs
```
`

**Comment by garris** [comment]
Yes,  it should use the firefox from the container.  I personally haven't tested the docker image with slimer.  You may need to confirm that the versions are compatible.

**Comment by edlefebvre** [comment]
OK, thank you for your answer. I think it is a little bit misleading then in the readme, "Integrated Docker rendering -- to eliminate cross-platform rendering shenanigans" if it is not expected to work with every supported engines?

Anyway, the docker image seems to have an "old" version of slimerjs (0.10.3) that doesn't support headless mode I think. 

I'll try to switch to peppeteer. Thanks for the support!
