### ISSUE TITLE
Puppeteer, 'body:noclip' is not a valid selector

### ISSUE THREAD

**Issue by mhavelant** [garris/BackstopJS#832]
Hi!

When I try to run puppeteer with "body:noclip", I get the following error (accompanied by lemur butts)

> ENGINE ERROR: Evaluation failed: DOMException: Failed to execute 'querySelectorAll' on 'Document': 'body:noclip' is not a valid selector. at Object.exists (__puppeteer_evaluation_script__:93:25) at window._backstopSelectorsExpMap.window._backstopSelectorsExp.reduce (__puppeteer_evaluation_script__:12:41) at Array.reduce (<anonymous>) at __puppeteer_evaluation_script__:10:70

Env info:
- BackstopJS v3.5.2
- OS: Docker, FROM node:10.7.0
- Google Chrome 68.0.3440.84
- Puppeteer 1.6.1
- chromium_revision 575458

**Comment by mhavelant** [comment]
I tried document, but it didn't really work for me for some reason (maybe I should set more wait time, or puppeteer is a bit buggy), that's why I wanted to try "body:noclip". But if that's deprecated, then it's fine, we can close this issue.

**Comment by garris** [comment]
Bummer — ok.  FWIW: If I remember correctly, the underlying code is exactly the same.   Does your css reference `vh` units?

**Comment by mhavelant** [comment]
Yep, it does at a few places.

**Comment by mhavelant** [comment]
I tested with PhantomJS as well, the same issue when using document. Weird.

**Comment by garris** [comment]
Ah, yes.  There is another issue with the `vh` unit.   https://github.com/garris/BackstopJS/issues/820   

I would encourage you to try to work around the issue with puppeteer (and potentially file the issue there).  The Puppeteer project will continue to get better whereas he phantom will continue to get less useful.

Please post back here if you figure out a good resolution.  Good luck either way!
