### ISSUE TITLE
Docker issue with local install

### ISSUE THREAD

**Issue by brendonbarreto** [garris/BackstopJS#834]
A have a different setup for backstopjs. Basically I have a node file where I manually invoke `backstop`

```js
backstop('test', config)
```

This node file, can be executed with other parameters like `url`

`node tests_vrt/backstop.test.js localhost:8001`

How can I run with docker in this case?

**Comment by garris** [comment]
Does it work when you pass `{docker: true, ... }`  in the config?

**Comment by brendonbarreto** [comment]
No, I tried `docker: true` and `args: { docker: true }`.
And I don't know if this was supposed to work, because of this part of the `core/command/test.js`
```js
const passAlongArgs = process.argv
	                .slice(3)
	                .join(' ')
	                .replace(/--docker/, '--moby')
```

**Comment by garris** [comment]
Hmmm,  I thought the docker argument would have been passed from the config obj...   anyway, i am happy to review a PR if you want to add this.   Cheers.

**Comment by garris** [comment]
@brendonbarreto  I just looked at my notes from the docket release.  Adding `{docker: true, ... }` as part of the config is equivalent to using the `-- docker` flag on the cli.

This worked as of the last release.  Can you please try this again?

**Comment by brendonbarreto** [comment]
Yes, that worked for me. Thanks!

**Comment by garris** [comment]
Thanks for reporting! 👍
