### ISSUE TITLE
Could someone publish version 0.6.0+ to npm?

### ISSUE THREAD

**Issue by Archiolidius** [garris/BackstopJS#84]
The latest version in npm is 0.5.1, could someone publish version 0.6.0+?

**Comment by axe312ger** [comment]
I think its not enough tested yet. You can just do:

```npm install git@github.com:garris/BackstopJS.git#3c81dfdb20352483a7b7fa7f47d7b08debe245de```

**Comment by Archiolidius** [comment]
Ok, what do you think, when you will be able to publish 0.6.0 version?

**Comment by axe312ger** [comment]
Its the decision of @garris and I know that he is pretty busy with customer projects. Just use that pinned commit as your npm dependency. You can easily change that back to "~0.6.0" later on ;)

**Comment by Archiolidius** [comment]
ok, thanks!

**Comment by garris** [comment]
@axe312ger Thanks for answering that.  Was traveling today.

@Archiolidius, we will release v0.6.+ soon. Thanks for posting.
