### ISSUE TITLE
Cannot find module 'portfinder'

### ISSUE THREAD

**Issue by kyleoliveiro** [garris/BackstopJS#841]
I'm running Backstop locally via Docker. Everything was fine and dandy, until I ran `docker pull backstopjs/backstopjs` today. After downloading the latest image, running the same backstop command which was previously working now throws: `Error: Cannot find module portfinder`.

The Backstop version in the Docker image is apparently `v3.5.4`, yes, even though the latest on Docker hub right now is `v3.5.3`.

**Comment by ExelleR** [comment]
I have the same exact issue.

**Comment by zapatoche** [comment]
Hi there, 
I have the same issue. I installed portfinder globally and it's working again.

**Comment by garris** [comment]
That sounds terrible.  Sorry everyone.   Will look into it.

**Comment by garris** [comment]
Could someone please post a config which causes the issue — plus the log output.  My versions here are working.

**Comment by zapatoche** [comment]
I have the issue with the local backstop version by the way, not the docker one. I will try again in a when I'm back at work, but my issue was fixed when I installed port finder manually.

**Comment by kyleoliveiro** [comment]
Hi @garris, I've pulled the latest Docker image, but unfortunately still having the same issue. Here's the log:

![backstop-log](https://user-images.githubusercontent.com/4415224/44511207-58128680-a6e9-11e8-8b49-64e4aae5900d.png)

**Comment by ExelleR** [comment]
I have the same issue.

**Comment by ExelleR** [comment]
@kyleoliveiro @garris I have the same issue.

**Comment by garris** [comment]
Does this happen for puppeteer?  Or just Chromy?    I suspect this problem can be solved by adding portfinder to package.json as a hard dependency.   This dependency was probably included in one of the react packages that was recently moved to dev-dependency.   

Here 👉  https://github.com/garris/BackstopJS/pull/813

**Comment by thijsvdanker** [comment]
Installing [portfinder](https://www.npmjs.com/package/portfinder) globally fixed the issue for me.
```bash
npm install portfinder -g
```

(Running locally with chromy).

**Comment by kyleoliveiro** [comment]
I don't think installing portfinder globally would help in cases where Backstop is being run from the Docker container; It would need to be installed inside the container instead of the host machine for it to work.

@garris Puppeteer doesn't work for me, so I'm forced to use Chromy.

For now, I'm getting around this issue by using v3.2.17

**Comment by garris** [comment]
fixed by a82cff2

**Comment by seleckis** [comment]
Hi, I have fresh install of backstopJS 3.5.8. Worked well until I changed engine to "chromy" and configured onBefore with custom devices. Now I have the same error.

**Comment by garris** [comment]
Ok, apologies. My bad. Please validate using v3.5.9.  Thanks!

**Comment by cactusa** [comment]
I have just tested this and had no luck. Here is what I get:
```
BackstopJS v3.5.9
Loading config:  /Users/vladaltanov/Projects/itvplayer-browser/backstopJS.config.js 

COMMAND | Executing core for "test"
createBitmaps | Selected 45 of 45 scenarios.
module.js:491
    throw err;
    ^

Error: Cannot find module 'portfinder'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/vladaltanov/Projects/itvplayer-browser/node_modules/backstopjs/core/util/getFreePorts.js:1:82)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
```

**Comment by garris** [comment]
Epic fail.  🤦‍♂️   

Ok -- just republished.  Please try again!  v3.5.10

**Comment by kyleoliveiro** [comment]
Just tried v3.5.10. It works, thanks!
