### ISSUE TITLE
BackstopJS report often failed

### ISSUE THREAD

**Issue by dewjay** [garris/BackstopJS#85]
Why my BackstopJS Report often failed (not match), Though there is difference between reference and test
![screenshot from 2015-09-01 17 54 17](https://cloud.githubusercontent.com/assets/10543750/9602389/48bb2e32-50d2-11e5-9ad7-f5bc4ca57216.png)

here's the report 
```		
Report
	
failed
Threshold: 1.5
Report: {
  "isSameDimensions": true,
  "dimensionDifference": {
    "width": 0,
    "height": 0
  },
  "misMatchPercentage": "1.78",
  "analysisTime": 106
}
```

**Comment by garris** [comment]
here `"misMatchPercentage": "1.78"`  is greater than `Threshold: 1.5 `.   Increase the threshold value in your backstop.json file and the difference will be ignored.

**Comment by garris** [comment]
Sorry, closed by accident.  Please let me know if that fixes your issue.
