### ISSUE TITLE
Upgrade Node version in Dockerfile

### ISSUE THREAD

**Issue by kyleoliveiro** [garris/BackstopJS#851]
https://hub.docker.com/r/backstopjs/backstopjs/~/dockerfile/ Dockerfile currently uses Node `v8.5.0`. Can we upgrade this to maybe LTS `v8.12.0`?

I'm using the Docker image to to VRT on my CI, and tests are currently failing as a package I'm using depends on `url-loader@1.1.1`, which is not supported on Node `v8.5.0`. Here's the relevant line from my logfile:

```
error url-loader@1.1.1: The engine "node" is incompatible with this module. Expected version ">= 6.9.0 < 7.0.0 || >= 8.9.0".
```

**Comment by garris** [comment]
Sure.  Please send PR.

**Comment by kyleoliveiro** [comment]
Will do. Is it as simple as bumping the version in the Dockerfile or are there some additional steps? I've not created a Docker image before.

**Comment by garris** [comment]
Neither have I so... eh, I guess we’ll find out!

**Comment by garris** [comment]
Can you please validate this?

**Comment by kyleoliveiro** [comment]
Works like a charm. Thanks!
