### ISSUE TITLE
Engine Error when page uses the picture tag.

### ISSUE THREAD

**Issue by Yarmolaev** [garris/BackstopJS#856]
I was trying to set up a test for my project when I started to run with specific modules into "ENGINE ERROR: Navigation Timeout Exceeded: 15000ms exceeded" 
After checking my code by throwing things away I could break it down to the following issue. 
If the page contains a picture tag the tests won't run.

Is there any good solution for my test case? 
Removing the picture tags is not an alternative.

**Comment by Yarmolaev** [comment]
Update:
With the casper engine the pictures will be rendered fine, but not with puppeteer.
Is this something which is in the scope of BackstopJS?

**Comment by garris** [comment]
Please run the sanity-check test outlined in the the docs and work backwards from there.

**Comment by Yarmolaev** [comment]
First a big thank you for the quick reply. 
I ran the sanity-check. This worked like expected with 2 compare errors. I also tried to do the smoke test but I got npm ERR! missing script: smoke-test and also didn't get what you mean with work backwards from there. 

I got my problem solved by switching my render engine to casper. This has another drawbacks like I need browser prefixes for flexbox but now I can run tests in my project. If this is nothing you can do about it, maybe this should be just pointed out in the description or be caught in the runtime somehow. 

So far thank you a lot for your help and this project and keep the great work up!

**Comment by Yarmolaev** [comment]
After a while I have just tested if this works by now and yes it does.
