### ISSUE TITLE
generating gulp reference at a particular interval

### ISSUE THREAD

**Issue by kamlesh-astech** [garris/BackstopJS#86]
I'm using backstopjs for visual testing while developing my project, After adding new pages to the project i always have to generate reference image right from the first page till the last one.
I dont want this generation of reference images from the startup. I only want to generate reference of the new page that is being added to the configs.
Plz help to figure it out.

Example: 
this is my config script

{
  "viewports" : [
    {
      "name": "desktop",
      "width": 1600,
      "height": 900
    }
  ],
  "grabConfigs" : [
    {
      "testName":"testName-1"
      ,"url":"http://localhost/project/index.html"
      ,"hideSelectors": []
      ,"removeSelectors": []
      ,"selectors":[
        "body"
      ]
    },
    {
      "testName":"testName-2"
      ,"url":"http://localhost/project/about.html"
      ,"hideSelectors": []
      ,"removeSelectors": []
      ,"selectors":[
        "body"
      ]
    },
    {
      "testName":"testName-3"
      ,"url":"http://localhost/project/contact.html"
      ,"hideSelectors": []
      ,"removeSelectors": []
      ,"selectors":[
        "body"
      ]
    }
  ]
}

Now, I only want to generate reference of the ../contact.html.
But after generating reference of the contact.html page it should not delete the previous referals of about.html and index.html page.
and after running the "gulp test" it should check all the the page referals of old and newly generated referral images

**Comment by garris** [comment]
Thanks for posting -- this feature is in development for a future release.

There is a pretty simple workaround though. After running a test you can literally drag any test image from the report into the actual reference image folder.  This will replace the reference version for subsequent tests.

Let me know if that works for you.

**Comment by garris** [comment]
Apologies, I just realized I misunderstood your question.   

In the case of adding new tests or selectors the workaround is a little less elegant but is still simple and effective.  Here goes...

1.  Locate your reference files directory and copy it to a temporary location.

2. Update your config file appending any new tests or selectors **to the end** of their respective branch arrays.

3. Run `gulp reference` -- this generates all new references.

3. Move the contents of the temp directory (created in step 1) back into their original location (overwriting any existing files).

Let me know if that works for you.

**Comment by kamlesh-astech** [comment]
HI, @garris 
Temperorily this is an good solution.
But, this wont be helpful while working on bigger projects.
Hope u soon may find an automated process for this functionality also.
Thank You !!!!
