### ISSUE TITLE
1 low severity vulnerability found by npm audit

### ISSUE THREAD

**Issue by GWShark0** [garris/BackstopJS#866]
#### Using:
- BackstopJS: `v3.5.14`
- Node: `v8.12.0`
- npm: `v6.4.1`

When installing `backstopjs` in a Node project using npm 6+, I encounter the following security warning emitted from npm's [auditing tool](https://blog.npmjs.org/post/173719309445/npm-audit-identify-and-fix-insecure):

```
                       === npm audit security report ===

# Run  npm install --save-dev backstopjs@3.6.1  to resolve 1 vulnerability
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ backstopjs [dev]                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ backstopjs > junitwriter > xmlbuilder > lodash               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/577                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
```
https://nodesecurity.io/advisories/577

#### Problem:

BackstopJS relies on [`"junitwriter": "~0.3.1"`](https://github.com/garris/BackstopJS/blob/6634b13/package.json#L85) which relies on [`"xmlbuilder": "2.6.2"`](https://github.com/schorfES/node-junitwriter/blob/master/package.json#L27) which relies on [`"lodash": "~3.5.0"`](https://github.com/oozcitak/xmlbuilder-js/blob/v2.6.2/package.json#L25). The [`xmlbuilder`](https://www.npmjs.com/package/xmlbuilder) package is currently at `v10.0.0` and the last publish on [`junitwriter`](https://www.npmjs.com/package/junitwriter) was "3 years ago".

#### Recommendation:

Either the `junitwriter` package should be updated (unlikely given the maintenance history of the package) or BackstopJS should consider using a more recently maintained package for writing JUnit XML reports (possibly [`davidparsson/junit-report-builder`](https://github.com/davidparsson/junit-report-builder)?)

**Comment by garris** [comment]
Thanks for the report!  Would be great if Someone could create a test for the junit writer test and then upgrade our library.   Cheers
