### ISSUE TITLE
backstop --docker ignores options specified before command

### ISSUE THREAD

**Issue by gabegorelick** [garris/BackstopJS#867]
I would expect the following to work:
```bash
backstop --config file test --docker
```
However, due to https://github.com/garris/BackstopJS/blob/6634b13bd7b0aa9a61697d410f3aa9b3ae96c740/core/util/runDocker.js#L7-L8, what actually gets executed is `docker run ... test "file" "test" "--moby"`.

While that may seem like a convoluted way to pass arguments, it's common when using npm scripts to compose commands. E.g. I have something like the following in my package.json `scripts` sections:
```json
{
  "backstop": "backstop --config ./test/backstop.js",
  "backstop:test": "npm run backstop test --docker",
}
```

**Comment by garris** [comment]
Feel free to propose a better way.  Thanks.
