### ISSUE TITLE
UI improvements on reports

### ISSUE THREAD

**Issue by colorful-tones** [garris/BackstopJS#882]
The scrubber seems so neat upon first experience. However, as a seasoned user of Ghost Inspector I find that the scrubber is not useful. It almost seems like a gimmick.

Assumptions:
1. Diagnosing a regression is critical
2. The diff is critical to demonstrating a regression

Ghost Inspector does a great job of doing a side-by-side modal. This has been the better experience for scrolling through long pages. If you have a side-by-side of Baseline (Reference) and Test you can quickly assess where differences are when a test has failed.

Here is a gif of GI's experience: 
![ghost-inspector-comparison-ui](https://user-images.githubusercontent.com/405912/46503626-59ab9000-c7f9-11e8-9da4-9455804fd3cb.gif)

It would be great to incorporate a different (optional?) means to compare screenshots then what the current BackstopJS UI offers.

Perhaps, the development of a secondary UI, or if there exists documentation on how to create a custom theme and I'm missing it. Then please point me to it?

**Comment by colorful-tones** [comment]
Thought about this a little more. Perhaps adding a button in between "Diff" and "Scrubber" in the existing modal would be easiest approach. 

![Example of adding "Side-by-side" button](https://user-images.githubusercontent.com/405912/46540021-219e5e80-c886-11e8-8720-a76fe65475e6.png)

When the "Side-by-side" button is clicked it would open an additional modal with the "Reference" _and_ "Test" shown side by side.

With this being the ultimate result of the new modal:

![screenshot 2018-10-05 10 09 17](https://user-images.githubusercontent.com/405912/46540250-c751cd80-c886-11e8-87e0-eaebb76a1207.png)

Using the scrubber requires too much cognitive load for me. Is it just me? When I scrub left am I seeing the "Test" on the right size, or am I seeing the "Reference"? When I scrub right am I seeing the "Test"? This is why I'm proposing the side-by-side (alternative) view.

**Comment by garris** [comment]
What is deficient about the current scrolling report for this functionality?   Seems maybe we could improve that view with a justify-w option and even a justify-h option (I.e. justify-viewport-h)?

**Comment by colorful-tones** [comment]
> What is deficient about the current scrolling report for this functionality?

The ability to see _both_ "Reference" _and_ "Test" at the same time (Side by side and top aligned). So user can scroll through the screenshots and visually scan the diffs. Right now, one has to click the "Reference" or "Test" buttons to see each one (uniquely and separately). I'm just proposing a new, additional view where they're side by side.

**Comment by colorful-tones** [comment]
Honestly, all one would ever _really_ need is the "Side-by-Side" and "Diff". The "Reference", "Test" and "Scrubber" views are not useful in themselves.

**Comment by garris** [comment]
Good.

To develop on the front end you can clone the project, cd into the root and run `npm run sanity-test`.   Then after you make changes to the UI code run  ` npm run build-and-copy-report-bundle` and simply refresh the browser.   That should enable you to see your changes.

**Comment by garris** [comment]
If you move forward, please first write up some notes on how you plan to implement it — so we can work through potential issues before implementation.

It would be great to see this happen — Thanks!

**Comment by colorful-tones** [comment]
@garris I put together a prototype in Sketch of what I believe would improve overall experience of navigating and comparing Baseline, New and Diff.

https://sketch.cloud/s/3x3ow/4jWQ9A/play

Please note this is an interactive Sketch Prototype and there are some items you can click on (and even click "X" to close, etc.).

The biggest notable change is putting the "Diff" as a sticky scrolling element. Scroll down in prototype and see what I mean please. This sticky "Diff" could be toggled (Opened/Closed) from the side of screen and would only be sticky scrolled within the bounds of the test that it is associated with.

The prototype uses mobile screenshots. For desktop (wide) screenshots they would take up 50/50 of the width of the container.

One idea I also had would be to allow for passing of a few configuration options in the form of an object in `backstop.json` for items like:

```
"report_output": {
    "expandAll": true, // Expand ALL tests by default
    "collapsedPassing": true, // Collapse all 'Passing' tests by default
    "expandDiff": true, // Expand 'Diff' sticky scroller by default
}
```

Please let me know if you have any questions. Looking forward to your feedback. Thanks!

**Comment by ackmanx** [comment]
> What is deficient about the current scrolling report for this functionality? Seems maybe we could improve that view with a justify-w option and even a justify-h option (I.e. justify-viewport-h)?

I quite like the current UI, but if I understand what you mean by `justify-w` it would be filling each column to their maximum width, regardless of the vertical scrolling this causes? For the case where your images are very tall (common use case at my company), this would be great (and be sorta like how the UI operated pre-redone UI).

**Comment by garris** [comment]
@ackmanx +1   That is exactly what I am talking about.  Just need to add a toggleable option in the drop down -- maybe called "justify".  It would be nice.

**Comment by colorful-tones** [comment]
Curious, what is this mysterious `justify-w` that keeps getting mentioned?

@garris 
> Just need to add a toggleable option in the drop down -- maybe called "justify". It would be nice.

I'm having a hard time visualizing this, but would be happy to take a stab at mocking a UI change if I understood the details a bit better.

@ackmanx 
> this would be great (and be sorta like how the UI operated pre-redone UI).

This makes me think there is some arcane, historical context that is assumed, but I have not been using BackstopJS since the first commit. I'm interested to learn more though.

**Comment by ackmanx** [comment]
It's just the name he called it, describing the behavior in my previous post. I've been using backstop for little over a year, and it used look like the below screenshot. Earlier this year a completely new UI was created.

Note in the screenshot that the width of the images are maximum allowed. The heights of those images are like 1200px. In the current backstop version images with large heights are zoomed out.

![screen shot 2018-10-23 at 09 53 08](https://user-images.githubusercontent.com/7490057/47369550-8c82ce80-d6a9-11e8-94bb-70199aec9b55.png)
