### ISSUE TITLE
Is it possible to approve screenshots selectively?

### ISSUE THREAD

**Issue by Kinglet1** [garris/BackstopJS#894]
I run backstop test and get screenshots. But some of them are not appropriate (for example, the image didn't load). Is it possible to skip not appropriate screenshots and approve only correct ones?

**Comment by brendonbarreto** [comment]
https://github.com/garris/BackstopJS#approving-changes

You can use `--filter=<scenarioLabelRegex>`

**Comment by Kinglet1** [comment]
Thank you for immediate answer!
