### ISSUE TITLE
How to replace pictures on page in scenario

### ISSUE THREAD

**Issue by kvkulish** [garris/BackstopJS#895]
I need to replace pictures on page to get similar view every time i starting test. I'm using puppet, and trying to replace pics right in its onBefore.js:

```
module.exports = async (page, scenario, vp) => {
  await require('./loadCookies')(page, scenario);
  await console.log('!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!1');
  let elementList = document.querySelectorAll('.picture-class');
  elementList.forEach((pic)=>{ pic.src = 'my-pic.jpg'})
};
```

But there is an error as a result:
> ReferenceError: document is not defined

So there is a question: is there _document_ in _page_ obgect that transmitted here? Or how to replace pics any another way while test is running?

**Comment by garris** [comment]
Use `onReadyScript` instead.

The DOM does not yet exist when `onBeforeScript` runs.

**Comment by kvkulish** [comment]
> 
> 
> Use `onReadyScript` instead.
> 
> The DOM does not yet exist when `onBeforeScript` runs.

same error, added sleep before console.log but it didn't help

**Comment by garris** [comment]
this needs to run in a `page.evaluate()`

```
  let elementList = document.querySelectorAll('.picture-class');
  elementList.forEach((pic)=>{ pic.src = 'my-pic.jpg'})
```

**Comment by kvkulish** [comment]
> 
> 
> this needs to run in a `page.evaluate()`
> 
> ```
>   let elementList = document.querySelectorAll('.picture-class');
>   elementList.forEach((pic)=>{ pic.src = 'my-pic.jpg'})
> ```

yep. it works. thank you for help!
