### ISSUE TITLE
Are backstopjs release versions the same as the docker image release versions?

### ISSUE THREAD

**Issue by ackmanx** [garris/BackstopJS#899]
I see the current release for backstop is 3.7.0, found in GitHub's Releases tab for this project. I noticed that the docker image is at 3.8.2 (https://hub.docker.com/r/backstopjs/backstopjs/tags) but just before that also has 3.7.0.

Are these tied together in some way? Like, backstopjs 3.7.0 should use the 3.7.0 docker image?

**Comment by garris** [comment]
Yes -- they are tied.  Backstop calls the docker image that matches the currently running version when you use the docker flag.

Also, If you run `npm view backstopjs ` you will see that 3.8.2 is the current beta version.

**Comment by ackmanx** [comment]
Thanks for the `npm view backstopjs` tip! I've been wondering about this for a while.
