### ISSUE TITLE
Add an explicit gulp task to compare images

### ISSUE THREAD

**Issue by klausbayrhammer** [garris/BackstopJS#90]
We are currently trying to integrate backstop tests into our CI/CD pipeline but the problem is that I currently don't see a way to pass the results of a backstop test to the gulp task (or the caller).

Is it correct that the comparison of reference and test images in done on the fly in `compare.js#compareTestPair`? What we'd require is a gulp task (or some kind of CLI) to explicitly trigger the image comparison and retrieve the result as a return value. Our overall goal is to run the backstop tests on our build servers and stop our build when errors occured.

Probably this is related to #32 and maybe we could use [node-resemble-js](https://www.npmjs.com/package/node-resemble-js) to compare the images.

**Comment by klausbayrhammer** [comment]
The following snippet could probably solve the problem. @garris if you think this is going in the right direction I'd clean the things up and provide a PR.

```javascript
const gulp = require('gulp');
const resemble = require('node-resemble-js');
const _ = require('underscore');

gulp.task('compare_backstop_images', function () {
    var compareData = getCorrectRelativePath(require('./backstop.json').paths.compare_data);
    var testPairs = require(compareData).testPairs;

    _.each(testPairs, function (pair) {
        console.log('testing', pair.fileName);
        var referencePath = getCorrectRelativePath(pair.reference);
        var testPath = getCorrectRelativePath(pair.test);

        resemble(referencePath).compareTo(testPath).onComplete(function(data) {
            if (data.misMatchPercentage > pair.misMatchThreshold) {
                console.log(data);
                console.log('Mismatch exceeded threshold for image', pair.fileName);
                process.exit(1);
            }
        });
    });
...
```

**Comment by garris** [comment]
@klausbayrhammer this looks like a great solution/feature.  Would this behavior be compatible with the SlimerJS engine option?  Would this be an option that runs in addition to / independent of the in-browser reporting process?

**Comment by klausbayrhammer** [comment]
I'm not sure if this works in all environments but we are running the backstop tests/image comparisons in a centos container with slimer installed and it works for us.

For now I'd rather provide this task as an independent addition, so we don't have any trouble when it comes to backwards compability.

Another idea came across my mind lately. With this feature we don't have to rely on any canvas/binaries in place so we could consider reworking the workflow when it comes to comparing test results. Currently the test images are created, stored and compared on the fly when the report is shown. What could probably be useful is, when the image comparison is done right after the test screenshots are made. The result of the test/comparison could be stored in a json file next to the test screenshots. So if you would like to know the results of a test you would only have to check the json instead of running the whole comparsion again.

**Comment by garris** [comment]
Yes, that would open the entire project up to devs needing a server centric solution.  I think it's all a great idea.  It doesn't seem all that hard to implement at this point either.

I completely support it -- let me know how I can help!

**Comment by garris** [comment]
Merged to master.

**Comment by klausbayrhammer** [comment]
Thanks for merging the PR. As of yet the gulp task doesn't fail when comparing the images fail. Since we execute our tests on a CI server we'd really appreciate if the gulp task would fail as a default. @garris what do you think about it?

**Comment by garris** [comment]
Yes -- was thinking the same thing.

Maybe this line would do what you need...
https://github.com/garris/BackstopJS/blob/master/gulp/tasks/compare.js#L28

You could try uncommenting that and see if it fails in the right way.  If it does, I propose we add a switch to the config to enable/disable fail passing back up to Gulp. 

Let me know what you think.

**Comment by klausbayrhammer** [comment]
Yes that's exactly what I was looking for! Probably we could add a `--dry-run` flag which supports the current (non failing) behaviour? If that's ok for you I'd send you a PR.

**Comment by garris** [comment]
Great -- glad that works! 

I am inclined to adding that flag to the config file as opposed to passing on the command line.  (Although I would be totally fine with a command-line override) Does that pose any problems for your use-case?

Also I am a inclined to cast the feature as an opt-in (not default behavior).  E.g. Flag name: `cliExitOnFail` or `cliThrowOnFail` or `cliHardFail`

The reason for both of these is to reduce complexity for users who are new to the app.

But again -- I would really want to know if this approach would work ok for you.  I would not want this to create unnecessary work to integrate.  Please let me know.

**Comment by klausbayrhammer** [comment]
I really like specifying a `cliExitOnFail` in the config file. That's the best approach by far and would work perfect for me!

**Comment by garris** [comment]
Awesome.  I am trying to get the next release out this week so I can take care of this at the same time -- it's a pretty easy one.

**Comment by garris** [comment]
Ok.  This is on master.  Please give this a test when you get a chance.   Thanks!

**Comment by klausbayrhammer** [comment]
Awesome, I'll look into it tomorrow!

**Comment by klausbayrhammer** [comment]
Probably I'm missing something, but how can you set the `cliExitOnFail` flag? It is called on the `path` module - shouldn't it be called on the `paths` object which encapsulates the config? Although the `cliExitOnFail` isn't set in `paths.js`.

**Comment by garris** [comment]
You are not missing anything.  I was switching branches a lot yesterday and merged the wrong one.
All fixed now.  Many apologies for this!

**Comment by klausbayrhammer** [comment]
I've tried it with the  `"cliExitOnFail": true` and `"report": "CLI"` and everything works like a charm! Thanks @garris a lot for your support!

As a sidenote: probably we could remove the `setTimeout` when using the CLI-compare?

**Comment by garris** [comment]
Super!  

And yes you're right, those timeouts can probably be tuned or removed entirely.
