### ISSUE TITLE
Viewports in separate files

### ISSUE THREAD

**Issue by movie4** [garris/BackstopJS#905]
Hello!

I have 12+ config files with scenarios and in each config file i use equal `viewports` options

Can BackstopJS use separate config file for `viewports` like `--config`?

It would be cool use this like:

```
backstop test --config='./path_to_config' --viewports='./path_to_viewports'
```

**Comment by brendonbarreto** [comment]
You could use `.js` config file instead of `json`. Then create a file `viewports.js`

```js
module.exports = [
    {
      label: 'phone',
      width: 320,
      height: 480
    },
    {
      label: 'tablet',
      width: 1024,
      height: 768
    }
  ]
```

And then, in your `config.js` files:

```js
const viewports = require('./viewports');

module.exports = {
   id: 'config_id',
   viewports: viewports
   ...
}
```

**Comment by steveycee** [comment]
> You could use `.js` config file instead of `json`. Then create a file `viewports.js`
> 
> ```js
> module.exports = [
>     {
>       label: 'phone',
>       width: 320,
>       height: 480
>     },
>     {
>       label: 'tablet',
>       width: 1024,
>       height: 768
>     }
>   ]
> ```
> 
> And then, in your `config.js` files:
> 
> ```js
> const viewports = require('./viewports');
> 
> module.exports = {
>    id: 'config_id',
>    viewports: viewports
>    ...
> }
> ```

This method solved the problem for me.
