### ISSUE TITLE
Browser Console Log 0: JSHandle:BackstopTools have been installed.

### ISSUE THREAD

**Issue by kud** [garris/BackstopJS#906]
Hello,

I'd just like to know if this message is normal and needs to be displayed?

I didn't find any idea in this issues or docs here about that.

Thank you :)

**Comment by garris** [comment]
It means that backstop listeners have been installed in your web app.

**Comment by kud** [comment]
Okay. It seems weird at first because it's not directly said by backstop. But I'll ignore it them. :) Thank you.
