### ISSUE TITLE
Issue with fixed headers and puppeteer

### ISSUE THREAD

**Issue by deap82** [garris/BackstopJS#914]
After reading about the large performance and stability improvements reached for the puppeteer engine I've now refactored my current test config to use this engine instead. And indeed running all my tests now takes a lot less time.

However, I've run into an issue. The app I'm testing has a fixed header, very similar to this bootstrap test page;

https://getbootstrap.com/docs/3.3/examples/navbar-fixed-top

The fixed header has its own test so for my other scenarios I'm using a selector to only capture the "`<main>`" part of the page.

So to recreate my issue I set up an example scenario for this page (sample only includes properties changed compared to what you get with `backstop init`);

```json
{
      "label": "Fixed toolbar",
      "url": "https://getbootstrap.com/docs/3.3/examples/navbar-fixed-top/",
      "selectors": ["body > .container"],
}
```

using the following viewport to force page scroll;

```json
  "viewports": [
    {
      "label": "phone-landscape",
      "width": 812,
      "height": 375
    }
  ]
```

Creating the reference with *chromy* and then running a test with *puppeteer* I get this result:

![image](https://user-images.githubusercontent.com/1295067/48329613-d1b37400-e649-11e8-9671-d3775b561e68.png)

So even though my selector is `body > .container`, with puppeteer the fixed top bar is captured but not with chromy.

I've tried to circumvent this by adding a hideSelector for the top bar - `nav.navbar` - and that works for this bootstrap example. But in the actual app I'm testing this works unreliably, probably due to some quirks in my specific setup. 

Before adressing that issue I'd just like to know if there is something that could be done to get the same capturing behaviour with puppeteer as I had with chromy. On the other hand I can totally understand that chromys way is rather magic as it somehow must hide away the topbar on its own before the screenshot is taken - or it can actually capture exactly the `body > .container` element, and not just whatever is in its "area". I'm not even really sure whether the issue belongs to backstop, puppeteer (or chromy) or whatever code you're using to take the screenshots.

Also, I thought it might be interesting for you to know that this difference exists between the use of chromy and puppeteer.

**Comment by garris** [comment]
Hi @deap82.   Yes. I have seen this kind of behavior before.  There are some differences in how capture is done between engines so, while this is an edge case, it's not that unusual.    I would recommend waiting for that fixed header dom to exist and then set to `display: none` or maybe even set horizontal offset (eg using opacity or transform: translate())  such that it's totally off the page regardless of vertical state -- just watch for triggered re-renders blowing away your overrides etc 😉.

Cheers!
