### ISSUE TITLE
Add Phantom/Slimer CLI arguments to backstop.json config

### ISSUE THREAD

**Issue by klausbayrhammer** [garris/BackstopJS#92]
We currently use backstop (with slimer) behind a proxy. There are CLI arguments in casper to control the proxy config but I haven't found a way to pass these parameters from backstop to casper and slimer. A sample casperjs call would be:
`casperjs --engine=slimerjs --proxy-type=http --proxy=proxyIp:port --proxy-auth=user:pass casperScript.js`

Is there a way to specify these proxy parameters (or even all casper parameters) in backstop?

**Comment by garris** [comment]
@klausbayrhammer short answer is no.  To add this I would add the flags as an arbitrary set of properties on a new node in the config, e.g. `casperFlags: {engine: "slimerjs", proxyType: "http", ... }`

These can be pushed onto the argument stack in the same way that the `engine` property is currently implemented.  The existing engine property would need to be deprecated (or perhaps just be overridden if a `casperFlags` is specified).

It would be pretty simple to add here...
https://github.com/garris/BackstopJS/blob/master/gulp/tasks/test.js#L46-L51

**Comment by klausbayrhammer** [comment]
If you like I'd prepare a PR this week

**Comment by garris** [comment]
@klausbayrhammer, @paweltin 
I just looked at this.   It looks like the approach, which I suggested originally, may be un-necessarily over-built.

Asking the user to split the property and value out is probably unnecessary.   All we are doing is reassembling the data (adding unnecessary complexity) -- unless we are going to actually use this data internally we are probably better off simply asking the user to add a simple array of string-formatted properties.  e.g.   `casperFlags: ["--engine=slimerjs", "proxy-type=http", ...]`

I think this updated approach is maybe better.  It gives the user more control and reduces our code complexity.  We then simply do `if (paths.casperFlags) {args = paths.casperFlags}` on [line 52](https://github.com/garris/BackstopJS/blob/master/gulp/tasks/test.js#L52).   This would also conveniently over-ride the `paths.engine` line that comes before.   Additionally, we could merge the `paths.engine` values (with the `casperFlags` array taking precedence for better compatibility/predictability.)


Please send some feedback, what do you guys think?  Is there any benefit to the original suggestion over this one?   

Thanks.

**Comment by paweltin** [comment]
If it's the only place these props are used, it's unnecesarily complicated indeed. I've fixed my mind on config consistency and I missed it. Simplicity over consistency is justified here. I can commit a fix tomorrow.

**Comment by garris** [comment]
@paweltin  Thank you for taking a second look and thank you for contributing!   Cheers,  Garris

**Comment by garris** [comment]
@klausbayrhammer @paweltin  This feature has been pushed to master.   There is no documentation yet -- but any help validating that this works with both Phantom and Slimer would be greatly appreciated.   Thanks!

**Comment by garris** [comment]
Merged and documented.
