### ISSUE TITLE
Allow BackstopJS Keypress for Selectors

### ISSUE THREAD

**Issue by marcdacz** [garris/BackstopJS#921]
It would be awesome if BackstopJS allows keypress events. I've implemented such behaviour currently in our global onReady.js but was thinking if we could integrate it in the helper files like below:

_clickAndHoverHelper.js_
```javascript
var keypressSelector = scenario.keypressSelectors || scenario.keypressSelector;

if (keypressSelector) {
        for (const keypressSelectorItem of [].concat(keypressSelector)) {
            await page.waitFor(keypressSelectorItem.selector);
            await page.type(keypressSelectorItem.selector, keypressSelectorItem.keyPress);
        }
}
```

_usage_
```javascript
"keyPressSelectors": [
          {
            "selector": ".primary-search__searchInput",
            "keyPress": "BackstopJS"
          }
 ],
```

thoughts?

**Comment by garris** [comment]
Hi Marc, sure, looks good and to me.   I'm happy to pull that in if you create a PR.  Please just include a test & document it.

Cheers!

**Comment by marcdacz** [comment]
Ok cool. On it!
