### ISSUE TITLE
data stub how-to

### ISSUE THREAD

**Issue by Fandekasp** [garris/BackstopJS#935]
Loosely related to #934 

I couldn't find documentation related to techniques for stubbing dynamic contents.
Are you aware of a blog post on the topic ? Else do you have tips to share ?

I'm currently thinking of adding fixtures for my pages in yaml format, then use the onReadyScript to run a `replaceContent` function that would read the yaml file and replace content in the page via selector keys.

Ideally, I'd like to have `backstop reference` auto-generate content fixtures from my staging or production application, and replace content from local/dev pages before taking the screenshot. If this is doable, then please consider this issue as a feature request.

**Comment by Fandekasp** [comment]
@garris I use a reference from production and am testing against a local environment to make sure it matches the production reference.

I could use fake data on staging and ask the team not to touch the data related to backstop and use the same one locally, but that wouldn't be very robust (too easy for data to change locally or on staging, creating an error).

**Comment by Fandekasp** [comment]
I explained how I dealt with backstop fixtures in [this article](https://medium.com/@Fandekasp/overview-of-backstopjs-a-tool-to-test-a-web-applications-ui-99234dc6c4f2).

Another trick is to duplicate data on the fly with an onReadyScript, eg if you have a list of 1 element and want to test the layout with 6 elements, your script would look like:
```js
/* eslint-disable */

module.exports = async (page, scenario, vp) => {
  await require("./onReady")(page, scenario, vp);

  const readySelector = "#my-list-id";
  await page.evaluate(readySelector => {
    const container = document.querySelector(readySelector);
    const user = container.firstChild;
    for (i = 0; i < 5; i++) {
      container.append(user.cloneNode(true));
    }
  }, readySelector);
};
```

**Comment by pgburrack** [comment]
Hi ✋ 

is there a way to just mock API responses?
