### ISSUE TITLE
Question: approve a single viewport

### ISSUE THREAD

**Issue by Fandekasp** [garris/BackstopJS#937]
After testing a scenario on 3 viewports, I've noticed that all tests failed when compared to their reference.
2 of them contain unexpected errors so need to be fixed, but the mobile viewport modifications are as expected. I would therefore like to only approve the mobile viewport scenario, and leave the other 2 viewports in a failed state.

The doc only suggest to filter by scenario. Can we also filter by viewport ?

**Comment by Fandekasp** [comment]
I suppose I'll need to use `--config=<custom config with single viewport>`

**Comment by brendonbarreto** [comment]
If you use git, you can approve all, and then discard the wrong ones.

**Comment by Fandekasp** [comment]
Shared the tip in [this article](https://medium.com/@Fandekasp/overview-of-backstopjs-a-tool-to-test-a-web-applications-ui-99234dc6c4f2), closing

**Comment by Fandekasp** [comment]
Thanks @garris for rectifying me on this in #946! 
There's no need to discard unwanted references with git, since backstop approve has the `--filter` option. No idea how I could miss this one :laughing:
