### ISSUE TITLE
hideSelector randomly not working

### ISSUE THREAD

**Issue by Fandekasp** [garris/BackstopJS#941]
Reference: https://www.gounite.com/
We have 4 feeds of cards with classes `.card-wrap`
The scenario looks like this:
```yaml
scenarios:
- label: "home"
  url: "https://gounite.local/"
  referenceUrl: "https://www.gounite.com/"
  removeSelectors: ["#djDebug"]
  hideSelectors: [".card-wrap"]
  delay: 5000
```

We just wanted to take a screenshot without the cards, which content is dynamic, but the screenshots very often change, and increasing delay doesn't appear to solve the issue.

Example 1: one feed sometimes has margin, sometimes not.
![](https://i.imgur.com/w76lLC5.png)

Example 2: 2 feeds will show the .card-wrap content, completely bypassing the hideSelectors (but on the same screenshot, 2 other feeds will behave as expected)
![](https://i.imgur.com/XDRHz5m.png)

We need a stable behavior from backstopJS. All 4 feeds behave the same way with the same height, therefore all screenshots should be identical to:
![](https://i.imgur.com/XCOHgvr.png)

Using version backstopjs 3.8.5
<details>
<summary>backstop.json</summary>

```json
{
  "id": "backstop_default",
  "viewports": [
    {
      "label": "iPhone 6",
      "width": 375,
      "height": 667
    },
    {
      "label": "iPad",
      "width": 768,
      "height": 1024
    },
    {
      "label": "Samsung Galaxy Tab 10",
      "width": 800,
      "height": 1280
    },
    {
      "label": "MacBook Pro 15",
      "width": 1440,
      "height": 900
    }
  ],
  "onBeforeScript": "puppet/onBefore.js",
  "onReadyScript": "puppet/onReady.js",
  "scenarios": [
    {
      "label": "dialog: SignUpForm",
      "url": "https://gounite.local/host/backstopjs",
      "referenceUrl": "https://staging.gounite.com/host/backstopjs",
      "clickSelector": [
        ".signup-btn"
      ],
      "delay": 500,
      "postInteractionWait": 100,
      "removeSelectors": [
        "#djDebug"
      ],
      "hideSelectors": [
        "#host"
      ]
    },
    {
      "label": "dialog: LoginForm",
      "url": "https://gounite.local/",
      "referenceUrl": "https://staging.gounite.com/",
      "clickSelector": [
        ".login-btn"
      ],
      "postInteractionWait": 100,
      "removeSelectors": [
        "#djDebug"
      ],
      "selectors": [
        "#anonymous-dialog"
      ]
    },
    {
      "label": "home",
      "url": "https://gounite.local/",
      "referenceUrl": "https://staging.gounite.com/",
      "removeSelectors": [
        "#djDebug"
      ],
      "hideSelectors": [
        ".card-wrap"
      ],
      "delay": 5000
    },
    {
      "label": "host",
      "url": "https://gounite.local/host/backstopjs",
      "referenceUrl": "https://staging.gounite.com/host/backstopjs",
      "removeSelectors": [
        "#djDebug"
      ],
      "delay": 500
    }
  ],
  "paths": {
    "bitmaps_reference": "backstop_data/bitmaps_reference",
    "bitmaps_test": "backstop_data/bitmaps_test",
    "engine_scripts": "backstop_data/engine_scripts",
    "html_report": "backstop_data/html_report",
    "ci_report": "backstop_data/ci_report"
  },
  "report": [
    "browser"
  ],
  "engine": "puppeteer",
  "engineOptions": {
    "args": [
      "--no-sandbox"
    ]
  },
  "asyncCaptureLimit": 5,
  "asyncCompareLimit": 50,
  "debug": false,
  "debugWindow": false
}
```
</details>

Do you have any idea how to solve this issue ?

**Comment by Fandekasp** [comment]
After investigation, the unreliable behavior might or might not be related to using react-lazyload elements

```
  <Link to={to} className={className}>
    <Card className="card-wrap">
      <LazyLoad height={200} once offset={300}>
        <CardMedia className="card-image" image={image}>
          …
        </CardMedia>
      </LazyLoad>
      <CardHeader
        className={`card-header${subtitle ? "" : " more-margin"}`}
        title={title}
        subheader={subtitle}
      />
    </Card>
  </Link>
```

* material-ui 3.6.0
* react-lazyload 2.3.0
* react 16.6.3

[react-lazyload](https://github.com/jasonslyvia/react-lazyload) uses the offset property to take action depending on the position from the viewport. 

Therefore, I tried to remove the `.card-wrap` selectors instead of just hiding them, but I still experience unreliable screenshots with differing page height

**Comment by Fandekasp** [comment]
Even removeSelector will sometimes be ignored and cards be displayed on the screenshot...
![](https://i.imgur.com/qTXZJRk.png)

**Comment by garris** [comment]
This is probably a timing issue.   You may need to look into ensuring your app's state is and display cycle is locked down before manipulation.

**Comment by Fandekasp** [comment]
timing is really delicate and takes us a lot of time to fine-tune until we get stable screenshots.
Hopefully something can be done in the future to improve this and reduce the time spent writing and verifying scenarios
