### ISSUE TITLE
Optimizing reference images with optipng

### ISSUE THREAD

**Issue by ahmadalfy** [garris/BackstopJS#942]
I just want to start by saying that I am terribly sorry for the time I spent in my career without using a visual regression testing tool like BackstopJS. Seriously thank you, it took me less than 15 minutes to get it up and running and to get it integrated in our workflow.

Now to my concern, the generated images that are added to the reference directory could really use some optimization (since these are the images we commit). This is a screenshot taken from Mac tool ImageOptim which uses optipng under the hood. I think the numbers speak for what I want to say.

![image](https://user-images.githubusercontent.com/87611/49832596-cade6500-fd9f-11e8-8646-6170460de512.png)

Are you welcoming the addition of a step of optimization before the `approve` process? It can be configured for sure. I can really work on that, if not guess I will stick to an npm script that does both steps for me.

Thanks

**Comment by mirzazeyrek** [comment]
There could be an additional parameter for optimization and image quality. Back then we were using jpg output format for smaller images.

**Comment by ahmadalfy** [comment]
@mirzazeyrek definitely not by default as it takes significant amount of time to optimize the images. I am currently using a precommit hook that only optimize the added files. If there is plans to add that feature I can work on it.

**Comment by garris** [comment]
This is a nice feature -- however, since this kind of feature can be fairly easily added to a precommit script I think it is not necessary to add this complexity to the code base.
