### ISSUE TITLE
Usage of sessionStorage

### ISSUE THREAD

**Issue by andrepm06** [garris/BackstopJS#954]
Hello,

I'm looking for a way to successfully set a item in the session storage before every test.

I tried this:

 `` "onBeforeScript": "puppet/custom/set-language-ptBr.js",``

This script is using the native `setItem()` function. 

Unfortunately I got this:

![captura de tela 2019-01-10 as 11 10 30](https://user-images.githubusercontent.com/6975975/50970421-71657500-14c8-11e9-8e79-db6d94b41d42.png)

**Comment by brendonbarreto** [comment]
Try something like this:

```javascript
page.evaluate((valueToBeStoraged) => {
    localStorage.setItem("xd", valueToBeStoraged);
}, "foo");
```

I don't know if setting `sessionStorage` is possible in `onBeforeScript`. In this moment your DOM is not loaded yet, so maybe you got an exception like this: 

`Evaluation failed: DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document`

If that is your case, you can try to put this code on `onReadyScript`

**Comment by andrepm06** [comment]
I actually did this yesterday. Forgot to post the solution here.

Instead of using `evaulate` I used `evaluateOnNewDocument` and it worked fine :-)

**Comment by ackmanx** [comment]
@andrepm06 If your solution above solved this, I suggest closing the issue.
