### ISSUE TITLE
How do I login via oauth service from backstopjs

### ISSUE THREAD

**Issue by Fandekasp** [garris/BackstopJS#957]
**Use case:** Login with a facebook account that doesn't have an email → Application will show a modal window asking the user for his email.
⇒ We would like to write a regression test for this modal window since the design broken without us noticing it.

**How to:**
1. link script to scenario via onReadyScript key
2. in script, after `await require("./onReady")(page, scenario, vp);`, click the login button then facebook button
3. fill the information in the facebook popup window  `???`
4. wait a bit for firebase & backend server to process the request and for the frontend to create the dialog window.
5. take screenshot

**Question:** For step 3, how can I select the facebook popup window (step 3) from the onReadyScript to fill in a facebook account credentials ?

I'm afraid this isn't possible, in which case I'm wondering how could the regression test be written otherwise.
If I had access to the react-tools chrome extension from puppeteer, I could have bypassed the request and directly modify my React component's state to show the modal window, but that's not the case.

**Comment by Fandekasp** [comment]
@garris I asked facebook for an alternative solution, but they closed the issue answering that the integration testing framework should handle the job.

https://github.com/facebook/react-devtools/issues/1274

How would you go about interacting with popup windows from a scenario ?

**Comment by garris** [comment]
Hi @Fandekasp Thanks for posting!

If I needed to authenticate before running a scenario I would use some offline process to get the required token, store that token in a JSON file and restore that state with a cookie in an onBefore script.

If I needed to test a pop up then I would restore whatever state I needed and then hit the pop up url and test what that returned.

**Comment by Fandekasp** [comment]
Alright, we'll try to figure this out, thanks for the advice.
