### ISSUE TITLE
failed diff has grid overlay?

### ISSUE THREAD

**Issue by aw-davidson** [garris/BackstopJS#959]
Just upgraded from backstop v3.0.32 to v3.8.5. I also just switched the engine to puppeteer. Now my diffs all have a grid overlaid on them.  Is this intentional? It's very hard for me to asses the diff with this change. Is there some configuration to turn off the grid? I've looked at resemble documentation and didn't find anything. Maybe the README can be updated with this option? 

![screen shot 2019-01-15 at 3 31 34 pm](https://user-images.githubusercontent.com/32170938/51208451-b3812300-18db-11e9-804d-d31fb800efbe.png)

**Comment by aw-davidson** [comment]
@garris Haha, this is weird. I don't think its coming from my app because neither the reference or the test image have these grids. All the other screenshots look normal -- just the diffs have grids. This has been happening ever since I made the changes I mentioned above. Was using chromy before and just switched to puppeteer.

**Comment by kbo4sho** [comment]
Whats your environment?

**Comment by aw-davidson** [comment]
@kbo4sho I've observed this while running tests locally on my mac and in docker.

**Comment by garris** [comment]
It's only in the diff?   Please post a screenshot of the report and please post your config.

**Comment by aw-davidson** [comment]
<img width="381" alt="screen shot 2019-01-16 at 1 05 09 pm" src="https://user-images.githubusercontent.com/32170938/51269075-88580b80-198f-11e9-8711-272b09b4553e.png">
<img width="1542" alt="screen shot 2019-01-16 at 1 12 33 pm" src="https://user-images.githubusercontent.com/32170938/51269430-804c9b80-1990-11e9-9dd2-36892904e1a6.png">


```
var config = {
  id: 'myId',
  viewports: [
    {
      label: 'desktop',
      width: env_config.viewport.width,
      height: env_config.viewport.height
    }
  ],
  onBeforeScript: 'puppet/onBefore.js',
  onReadyScript: 'puppet/onReady.js',
  scenarios: [...myScenarios],
  paths: {
    bitmaps_reference: 'src/bitmaps_reference',
    bitmaps_test: 'report/bitmaps_test',
    engine_scripts: 'src/engine_scripts',
    html_report: 'report/html_report',
    ci_report: 'report/ci_report'
  },
  report: ['browser', 'CI'],
  engine: 'puppeteer',
  engineOptions: {
    waitTimeout: 90000,
    gotoTimeout: 300000,
    headless: true,
    args: ['--no-check-certificate', '--disable-dev-shm-usage', '--no-sandbox']
  },
  resembleOutputOptions: {
    ignoreAntialiasing: true
  },
  asyncCaptureLimit: env_config.baseURL.includes('http:') ? 1 : 3,
  asyncCompareLimit: 50
};
```

Example scenario:
```
{
        "label": "Typography",
        "cookiePath": "src/engine_scripts/cookies.json",
        "url": "myUrl",
        "referenceUrl": "",
        "readyEvent": "",
        "readySelector": "mySelector",
        "delay": 5000,
        "hideSelectors": [],
        "removeSelectors": [],
        "hoverSelector": "",
        "clickSelector": "",
        "postInteractionWait": "",
        "selectors": [
          "mySelector"
        ],
        "selectorExpansion": false,
        "misMatchThreshold": 0.05,
        "requireSameDimensions": true
}
```

**Comment by aw-davidson** [comment]
Figured out the issue. Apparently, resemble skips pixels if the height or width of an image is above 1200 pixels. Setting `largeImageThresh: 0` in resembleOutputOptions fixed this. See: https://github.com/rsmbl/Resemble.js/issues/52
