### ISSUE TITLE
Inconsistent hover action being performed when not defined

### ISSUE THREAD

**Issue by elizabethsjudd** [garris/BackstopJS#961]
We have scenarios where there is no hoverSelector defined but we are getting screen shots where the hover state of an element is displayed.  This is inconsistent in which scenarios this applied to and at which breakpoint. We are running 5 tests in parallel and this is in a Travis CI environment.

The image on the left is correct and the image on the right the first button is "hovered" but there is no hover selector.  We have 4 different breakpoints an it was only on 1 breakpoint that this occurred. The other 3 were as expected.
<img width="890" alt="screen shot 2019-01-18 at 11 16 21 am" src="https://user-images.githubusercontent.com/1275779/51398822-8e2a2a00-1b12-11e9-838e-a75290299ac3.png">

**Comment by elizabethsjudd** [comment]
@garris when there isnt' a hover selector I move it to the bottom right corner of the viewport.  This seems to be doing the trick.  Thanks!

**Comment by jonathanherdt** [comment]
This worked like a charm! Thank you so much! I am using BackstopJS together with Storybook. Storybook's canvas by default places everything in the upper left corner so I repeatedly had this problem. From your instructions, I just did not know how to move the cursor. I'm now doing it like this, in my `onReady.js`:

```
module.exports = async (page, scenario) => {
  // Move mouse out of the way so that we can circumvent hover problems.
  page.mouse.move(1000, 1000);
};
```
