### ISSUE TITLE
Puppeteer: hideSelectors doesn't hide the selectors

### ISSUE THREAD

**Issue by eschb002** [garris/BackstopJS#965]
`    {
{
  "id": "backstop_default",
  "viewports": [
    {
      "label": "desktop",
      "width": 1680,
      "height": 2000
    }
  ],
  "onBeforeScript": "puppet/onBefore.js",
  "onReadyScript": "puppet/onReady.js",
  "scenarios": [
    {
      "label": "Home",
      "cookie_path": "",
      "url": "http://www.petfinder.com",
      "reference_url": "http://dev-www.petfinder.com",
      "ready_event": "",
      "ready_selector": "",
      "delay": 3000,
      "hide_selectors": [
        "#Home1",
        "#Home2",
        "#Home3",
        "#Home4"
      ],
      "remove_selectors": [],
      "hover_selector": "",
      "click_Selector": "",
      "post_interaction_wait": 0,
      "selectors": [],
      "selector_expansion": true,
      "expect": 0,
      "mis_match_threshold": 1,
      "require_same_dimensions": true
    }
  ],
  "paths": {
    "bitmaps_reference": "backstop_data/bitmaps_reference",
    "bitmaps_test": "backstop_data/bitmaps_test",
    "engine_scripts": "backstop_data/engine_scripts",
    "html_report": "backstop_data/html_report",
    "ci_report": "backstop_data/ci_report"
  },
  "report": [
    "browser"
  ],
  "engine": "puppeteer",
  "engineOptions": {
    "args": [
      "--no-sandbox"
    ]
  },
  "asyncCaptureLimit": 5,
  "asyncCompareLimit": 50,
  "debug": false,
  "debugWindow": false
}
  }`

The selectors are for the ad spaces on the page.

I have this config, and when I run backstop reference and backstop test, everything runs normally. No errors. The selectors specified are still being compared.

**Comment by brendonbarreto** [comment]
Try changing `hide_selectors` to `hideSelectors`

https://github.com/garris/BackstopJS#hiding-selectors
