### ISSUE TITLE
missing selectors should be explicitly handled

### ISSUE THREAD

**Issue by garris** [garris/BackstopJS#97]
Reported by @axe312ger.  

Fix would be to add a selector check here https://github.com/garris/BackstopJS/blob/master/capture/genBitmaps.js#L142.

For display:none cases we should reference a no-display icon. e.g. Glasses with diagonal line / strike through.   display:none cases to be addressed in separate issue.

For missing element, we should reference a droptag icon with a horizontal line / strike through icon.

This will keep output in sync with the config files and correctly report on visual state changes with No changes to our report code.

**Comment by garris** [comment]
Selector check and reference substitutions can be made here... https://github.com/garris/BackstopJS/blob/master/capture/genBitmaps.js#L142

**Comment by axe312ger** [comment]
Also added a check to remove - on the first position of the filename

https://github.com/axe312ger/BackstopJS/blob/master/capture/genBitmaps.js#L178
