### ISSUE TITLE
Backstop is cutting images references when using Puppeteer or Chromy

### ISSUE THREAD

**Issue by stephenbe** [garris/BackstopJS#973]
Hi Garris,

We are having a small problem when using the new engine.

![image](https://user-images.githubusercontent.com/3018441/51920645-bdc41680-23dd-11e9-8a76-7b53d0bbb3ee.png)

We are using bootstrap and you can see here the badge is cut.

We made a repo you can see here (I added you as a collaborator so you should see it even though it's private)
https://github.com/stephenbe/backstop-error

when you do backstop test you should see the same error.

Tested on Windows 7, Windows 10 and Mac...all three have this problem.

Thanks!

**Comment by patriciamarchand** [comment]
Hello, 
just an update on this one. I try the basic Bootstrap outline button and I think it's related with the width of the element. These elements have width with decimal. Ex : 79.65px 

I dont know how to resolve this. I try different value for Chrome flag '--force-device-scale-factor=1' 

element in browser
![snag-0009](https://user-images.githubusercontent.com/6225238/53270974-1922b500-36bb-11e9-88d1-29750a75aafc.png)

Capture element with Backstop
![snag-0010](https://user-images.githubusercontent.com/6225238/53270973-1922b500-36bb-11e9-9868-d2fd30365071.png)

**Comment by patriciamarchand** [comment]
I found the problem. This was related to puppeter version. In my package.json lock I had the version 1.11.0 of puppeteer. I remove the package.json.lock and the most recent version of puppeteer (v.1.13) is now install.
