### ISSUE TITLE
Advanced Scenarios configuration

### ISSUE THREAD

**Issue by beto-aveiga** [garris/BackstopJS#975]
Reading `util/runChromy.js` and `util/runPuppet.js` code I don't see some configuration params which are documented, which makes sense because I had been trying to use `clickSelector` on `chromy` without any success.
So what I'm willing to understand is if these selectors and configurations are really implemented or not, and where, because if not, I would love to contribute to this awesome project... or maybe I'm getting something wrong, however selectors present in code like `hideSelectors` or `readySelector` did work as expected.
Also, regarding the mentioned selectors, the documentation says that **processed sequentially in the following order...** but this is not happening for all cases.

**Comment by garris** [comment]
@beto-aveiga Thank you for posting!   These features are part of a plug-in architecture.  These are intended to enable you to customize for your own project.  After running `backstop init` you will find these here... `backstop_data/engine_scripts/puppet/`  (for puppeteer)

I hope this answers your question.

**Comment by beto-aveiga** [comment]
Thanks for answering so quick @garris, but I still think something is not right. Parameters listed on documentation are not working as expected, only a few of them. As I said, `clickSelector` for `chromy` is not working. Also, those params are not processed sequentially as the docs state, for example, `removeSelector` is processed before `hideSelector`... Or there is something that I'm not getting yet, sorry if so.

**Comment by garris** [comment]
At this point we are softly deprecating chromy.   If possible -- please try this in puppeteer.   But in either engine -- if the documentation is off or `clickSelector` is not working it is a bug.   Please verify using a clean install and start here for troubleshooting... https://github.com/garris/BackstopJS#troubleshooting

**Comment by beto-aveiga** [comment]
Thanks @garris. I'm pretty sure this is happening on Puppeteer. I will check this twice and PR if I found something :+1:
