### ISSUE TITLE
Smoke tests failing without changing anything

### ISSUE THREAD

**Issue by beto-aveiga** [garris/BackstopJS#976]
I was about making a PR so I was following the recommendations like linting and running the smoke test. My code passes the linting, but the smoke test throws 68 failed tests. I don't know what is happening. I erased my code and did the smoke test again, but the same number of errors are appearing.
Here is the log in case you could help me:
[2019-01-30T22_01_01_352Z-debug.log](https://github.com/garris/BackstopJS/files/2814888/2019-01-30T22_01_01_352Z-debug.log)
Thanks.

**Comment by garris** [comment]
The tests render differently on different machines.  Can you just "print" to a pdf and attach the file here.  I can take a look and validate that the differences are "safe".   (At some point we will move to a docker version which will not have this issue)

**Comment by AnithaDharanee** [comment]
Is there any update on this issue, did you manage to resolve it @beto-aveiga ? I am facing the same problem . Thanks

**Comment by beto-aveiga** [comment]
Sorry, @AnithaDharanee, I don't even remember this issue.
Closing this issue as I can't give any details.
