### ISSUE TITLE
Issues with dependency versioning

### ISSUE THREAD

**Issue by aw-davidson** [garris/BackstopJS#983]
I'm trying to use a specific version of chrome with backstop, but am unable to do so because of the `^` in front of puppeteer. I see @brendonbarreto made a fix for this in #960 but then it was reverted. Are there plans to include this fix in the future? I think it would be a good idea to bump backstop every time puppeteer is bumped.

**Comment by garris** [comment]
I had to back that change out because that commit broke the scrubber feature.  I'm happy to reapply you want to pull that diff and troubleshoot/fix the issue.

**Comment by aw-davidson** [comment]
@garris sounds good. How do I check the scrubber feature?

**Comment by garris** [comment]
Sure,  Just run a test on something that will produce a diff -- then click on the diff in the web report.   If the scrubber is grabbable/useable then everything is good.  If it doesn't work -- then you'll need to figure out which dependency caused the issue.

Cheers.
