### ISSUE TITLE
BackstopJS halts execution when one of the scenario fails to identify locator

### ISSUE THREAD

**Issue by Bhav1907** [garris/BackstopJS#992]
I have 242 scenarios running and in 32nd scenario locator not found. then it stopped execution for rest e=scenarios. Do we have any solution for this so i can run all the scenarios even some of the locator /scenarios fails.

BELOW are my logs. It fails on one of the locator into one of the scenario.
**TypeError: Cannot read property 'click' of null**

===========================
  }
]
Browser Console Log 0: JSHandle:them is =>
Browser Console Log 1: JSHandle@object
Browser Console Log 0: JSHandle:`setOptions(options)` is deprecated. Please use the `withOptions(options)` decorator globally.
Puppeteer encountered an error while running scenario "AutoCompleteWithMultipleSelection-SelectMultiRecords"
**TypeError: Cannot read property 'click' of null**
Browser Console Log 0: JSHandle:them is =>
Browser Console Log 1: JSHandle@object
Browser Console Log 0: JSHandle:`setOptions(options)` is deprecated. Please use the `withOptions(options)` decorator globally.
Browser Console Log 0: JSHandle:this is the content of ts
Browser Console Log 1: JSHandle:import { Component } from '@angular/core';
import { ColorsSwatchesModel } from './model/colors-swatches.model';
import { Message } from 'primeng/api';

@Component({
  selector: 'app-colors-swatches',
  templateUrl: './colors-swatches.component.html',
  styleUrls: ['./colors-swatches.component.scss']
})
export class ColorsSwatchesComponent {
  public overviewContentPath = './assets/content/features/style/colors/colors-swatches/overview.md';
  public colorsSwatchesModel: ColorsSwatchesModel;
  public msgs: Message[] = [];

  constructor() {
    this.colorsSwatchesModel = new ColorsSwatchesModel();
  }

  /**
   * [copySuccess - To display success message after copying to the clipboard]
   * @param {string}  value  [value copied to the clipboard]
   */
  copySuccess(value: string): void {
    this.msgs = [{
      severity: 'info',
      summary: 'Copied to Clipboard',
      detail: `Color variable (${value}) copied to Clipboard`
    }];
  }

  /**
   * [copyError - To display error message while copying to the clipboard]
   * @param {Error}  error  [error while copying to the clipboard]
   */
  copyError(error: Error): void {
    this.msgs = [{
      severity: 'error',
      summary: 'Error',
      detail: error.message
    }];
  }
}

Browser Console Log 0: JSHandle:this is the content of ts
Browser Console Log 1: JSHandle:import { Component } from '@angular/core';
import { ColorsSwatchesModel } from './model/colors-swatches.model';
import { Message } from 'primeng/api';

@Component({
  selector: 'app-colors-swatches',
  templateUrl: './colors-swatches.component.html',
  styleUrls: ['./colors-swatches.component.scss']
})
export class ColorsSwatchesComponent {
  public overviewContentPath = './assets/content/features/style/colors/colors-swatches/overview.md';
  public colorsSwatchesModel: ColorsSwatchesModel;
  public msgs: Message[] = [];

  constructor() {
    this.colorsSwatchesModel = new ColorsSwatchesModel();
  }

  /**
   * [copySuccess - To display success message after copying to the clipboard]
   * @param {string}  value  [value copied to the clipboard]
   */
  copySuccess(value: string): void {
    this.msgs = [{
      severity: 'info',
      summary: 'Copied to Clipboard',
      detail: `Color variable (${value}) copied to Clipboard`
    }];
  }

  /**
   * [copyError - To display error message while copying to the clipboard]
   * @param {Error}  error  [error while copying to the clipboard]
   */
  copyError(error: Error): void {
    this.msgs = [{
      severity: 'error',
      summary: 'Error',
      detail: error.message
    }];
  }
}

Browser Console Log 0: JSHandle:%cDownload the React DevTools for a better development experience: https://fb.me/react-devtools
Browser Console Log 1: JSHandle:font-weight:bold
Browser Console Log 0: JSHandle:BackstopTools have been installed.
Browser Console Log 0: JSHandle:BackstopTools have been installed.
Browser Console Log 0: JSHandle:them is =>
Browser Console Log 1: JSHandle@object
Browser Console Log 0: JSHandle:`setOptions(options)` is deprecated. Please use the `withOptions(options)` decorator globally.
Browser Console Log 0: JSHandle:this is the content of ts
Browser Console Log 1: JSHandle:import { Component } from '@angular/core';
import { ColorsSwatchesModel } from './model/colors-swatches.model';
import { Message } from 'primeng/api';

@Component({
  selector: 'app-colors-swatches',
  templateUrl: './colors-swatches.component.html',
  styleUrls: ['./colors-swatches.component.scss']
})
export class ColorsSwatchesComponent {
  public overviewContentPath = './assets/content/features/style/colors/colors-swatches/overview.md';
  public colorsSwatchesModel: ColorsSwatchesModel;
  public msgs: Message[] = [];

  constructor() {
    this.colorsSwatchesModel = new ColorsSwatchesModel();
  }

  /**
   * [copySuccess - To display success message after copying to the clipboard]
   * @param {string}  value  [value copied to the clipboard]
   */
  copySuccess(value: string): void {
    this.msgs = [{
      severity: 'info',
      summary: 'Copied to Clipboard',
      detail: `Color variable (${value}) copied to Clipboard`
    }];
  }

  /**
   * [copyError - To display error message while copying to the clipboard]
   * @param {Error}  error  [error while copying to the clipboard]
   */
  copyError(error: Error): void {
    this.msgs = [{
      severity: 'error',
      summary: 'Error',
      detail: error.message
    }];
  }
}

SCENARIO > AutoCompleteWithMultipleSelection-Disabled
SCENARIO > AutoCompleteWithMultipleSelection-ForceSelection
x Close Browser
ERROR: The process with PID 15720 (child process of PID 24848) could not be terminated.
Reason: There is no running instance of the task.
Browser Console Log 0: JSHandle:[HMR] connected
Browser Console Log 0: JSHandle:[HMR] connected
      COMMAND | Command "test" ended with an error after [142.714s]
      COMMAND | TypeError: scenario.selectors.join is not a function

**Comment by Bhav1907** [comment]
@garris  Need your help on this. I am running 242 scenarios and on 32nd scenario i m getting some locator not found error ( i try to click on it where locator is not present). So that particular scenario should fail. My execution is getting halted and doesn't run for remaining scenarios. Any solution to this will be really appreciated.

**Comment by Bhav1907** [comment]
Is anyone can help me with this ?

**Comment by garris** [comment]
Is it just one scenario out of 232 that fails?

**Comment by Bhav1907** [comment]
I mean this is 32nd scenario..first 31 are getting passed/executes properly..on 32nd locator not found issue due so it dint executed rest of the scenarios and it stopped.

ERROR: The process with PID 15720 (child process of PID 24848) could not be terminated.
Reason: There is no running instance of the task.
Browser Console Log 0: JSHandle:[HMR] connected
Browser Console Log 0: JSHandle:[HMR] connected
COMMAND | Command "test" ended with an error after [142.714s]
COMMAND | TypeError: scenario.selectors.join is not a function



**Sample JSON file for scenarios :** 

   {
        "label": "DataPaginator-LinkSize",
        "referenceUrl": "http://localhost:6007/?selectedKind=Data%7CPaginator&selectedStory=Link%20Size&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs&knob-No%20of%20rows=5&knob-Total%20records=300&knob-Append%20panel%20to=&knob-Rows%20Per%20Page%5B0%5D=5&knob-Rows%20Per%20Page%5B1%5D=10&knob-Rows%20Per%20Page%5B2%5D=15&knob-Rows%20Per%20Page%5B3%5D=20&knob-Rows%20Per%20Page%5B4%5D=25&knob-Page%20Link%20Size=5&knob-Page%20link%20size=3",
        "testUrl": "http://localhost:6007/?selectedKind=Data%7CPaginator&selectedStory=Link%20Size&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs&knob-No%20of%20rows=5&knob-Total%20records=300&knob-Append%20panel%20to=&knob-Rows%20Per%20Page%5B0%5D=5&knob-Rows%20Per%20Page%5B1%5D=10&knob-Rows%20Per%20Page%5B2%5D=15&knob-Rows%20Per%20Page%5B3%5D=20&knob-Rows%20Per%20Page%5B4%5D=25&knob-Page%20Link%20Size=5&knob-Page%20link%20size=3"
    },
    {
        "label": "AutoCompleteDefault-SendKey",
        "referenceUrl": "http://localhost:6007/?selectedKind=Components%7CAutocomplete&selectedStory=Default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs&knob-Placeholder=Automobile&knob-Field%20Size=30&knob-Append%20panel%20to=&knob-Disabled=&knob-Required=true&knob-Force%20Selection=",
        "testUrl": "http://localhost:6007/?selectedKind=Components%7CAutocomplete&selectedStory=Default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs&knob-Placeholder=Automobile&knob-Field%20Size=30&knob-Append%20panel%20to=&knob-Disabled=&knob-Required=true&knob-Force%20Selection=",
        "actionsWorkflow": [
            "type#**.ui-autocomplete-input**#a" **//consider this locator not found then all further are not executing.** 
        ],
        "actionDelay": 2000
    },
    {
        "label": "AutoCompleteDefault-Hover",
        "referenceUrl": "http://localhost:6007/?selectedKind=Components%7CAutocomplete&selectedStory=Default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs&knob-Placeholder=Automobile&knob-Field%20Size=30&knob-Append%20panel%20to=&knob-Disabled=&knob-Required=true&knob-Force%20Selection=",
        "testUrl": "http://localhost:6007/?selectedKind=Components%7CAutocomplete&selectedStory=Default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs&knob-Placeholder=Automobile&knob-Field%20Size=30&knob-Append%20panel%20to=&knob-Disabled=&knob-Required=true&knob-Force%20Selection=",
        "actionsWorkflow": [
            "hover#.ui-autocomplete-input"
        ]
    },
=================================
JS file  : 

   "onBeforeScript": "puppet/onBefore.js",
    "onReadyScript": "puppet/onReady.js",
    "scenarios":
      scenarios,  /// Array of scenarios comes from JSON file
    "paths":
      saveDirectories,
    "engine": "puppeteer", 
    "report": ["browser"],
    "debug": false,
    "engineOptions": {
      "args": ["--no-sandbox"],
        },
    "asyncCaptureLimit": 5,
    "asyncCompareLimit": 50,
    "debugWindow": false
  };


**Helper JS file :** 

 if (actionsWorkflow) {
    const frames = await page.frames();
    const tryItFrame = frames.find(f => f.name() === 'storybook-preview-iframe');
    for (var i = 0; i < actionsWorkflow.length; i++) {
      var action = actionsWorkflow[i].split("#")[0];
      var locatorID = actionsWorkflow[i].split("#")[1];
      var parameters = actionsWorkflow[i].split("#")[2];
      const locator = await tryItFrame.$(locatorID);
................................
................................
..............................
}

**Comment by Bhav1907** [comment]
Anyone has any solution for me ?

**Comment by Bhav1907** [comment]
@garris  I think i made this complicated. My question is simple-

If i have hover and click selectors in my scenario. First is click and then hover. I have added in that sequence . It clicked on element but the hover element dint come up (application issue) then its throwing error and no further scenarios are running.execution stops and no report generated.
Is there any thing i can put to handle hovering on null /clicking on null a fail and continue further.

"clickSelector": ".ui-dropdown",
"hoverSelector": ".ui-dropdown .ui-dropdown-item:nth-child(1)", // due to issue in application this locator dint come up/present.

**Comment by Bhav1907** [comment]
Added visibility check for hidden elements  , and x- y bounding solved the issue.
