### ISSUE TITLE
blank screenshots on the build server

### ISSUE THREAD

**Issue by x1c0** [garris/BackstopJS#999]
Hi! :)

BackstopJS work great locally, the project is very recent so is using the latest versions of everything.

when I try to run the same command on the build server it fails because all the images are blank. 

![image](https://user-images.githubusercontent.com/2421483/53866569-23657d00-3ff2-11e9-9581-e6f50c1b11e7.png)

![image](https://user-images.githubusercontent.com/2421483/53866721-80f9c980-3ff2-11e9-8180-4a31f0890f0d.png)

This is my config file, I use local html files to test my scenarios:

![image](https://user-images.githubusercontent.com/2421483/53866640-4bed7700-3ff2-11e9-94f9-0d4640201b7a.png)

Any ideas?

**Comment by x1c0** [comment]
This was happening because I had an issue on the build server, causing BackstopJS to run a not proper build that caused a white page.. so no related with  BackstopJS. Sorry for the issue!

**Comment by garris** [comment]
Glad it worked or you.  Thanks for following up.
